// Domain 3 — Part 2: Security models (BLP, Biba, Clark-Wilson, Brewer-Nash,
// Graham-Denning, Take-Grant, Sutherland, non-interference), TCB / reference
// monitor / security kernel, Common Criteria / EAL, architecture vulnerabilities
// (databases/ACID, ICS/SCADA, IoT, embedded, microservices/API).
module.exports = [
  // ---- TCB / reference monitor / security kernel ----
  {
    t: 'Security Models', s: 'Trusted Computing Base', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Understanding Security Models',
    q: 'The Trusted Computing Base (TCB) is BEST defined as:',
    o: [
      'The combination of hardware, software, and controls that work together to enforce a security policy',
      'A single firewall at the network perimeter',
      'The list of all users authorized to access a system',
      'A precomputed table of password hashes',
    ],
    a: 'A',
    wc: 'The TCB is the totality of protection mechanisms (hardware, software, firmware, and controls) that together enforce the system\'s security policy.',
    ww: {
      B: 'A firewall is one control, not the entire trusted computing base.',
      C: 'A user list is not the TCB.',
      D: 'A rainbow table is an attack artifact, unrelated to the TCB.',
    },
    er: 'Recall of the TCB definition.',
  },
  {
    t: 'Security Models', s: 'Reference monitor', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Reference Monitor',
    q: 'The reference monitor concept describes a component that:',
    o: [
      'Verifies and enforces access requests between subjects and objects',
      'Stores backup copies of all system data',
      'Generates cryptographic key pairs in hardware',
      'Physically restricts entry to the server room',
    ],
    a: 'A',
    wc: 'The reference monitor mediates (verifies and enforces) all access requests between subjects and objects.',
    ww: {
      B: 'Backups are a recovery function, not the reference monitor.',
      C: 'Key generation is a TPM/HSM function.',
      D: 'Physical entry restriction is a facility control.',
    },
    er: 'Recall of the reference monitor\'s mediation role.',
  },
  {
    t: 'Security Models', s: 'Security kernel', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Security Kernel',
    q: 'How does the security kernel relate to the reference monitor concept?',
    o: [
      'The security kernel is the hardware/software implementation that enforces the reference monitor concept',
      'The security kernel is an abstract idea while the reference monitor is physical hardware only',
      'They are unrelated; the kernel handles only memory paging',
      'The security kernel replaces the need for any access control',
    ],
    a: 'A',
    wc: 'The security kernel is the actual implementation (hardware, firmware, software) that realizes and enforces the reference monitor concept, handling access requests and maintaining security integrity.',
    ww: {
      B: 'The reference monitor is the abstract concept; the kernel is its implementation—this option reverses them.',
      C: 'They are directly related, not unrelated.',
      D: 'The kernel enforces access control; it does not eliminate it.',
    },
    er: 'Tests the concept (reference monitor) vs implementation (security kernel) relationship.',
  },
  {
    t: 'Security Models', s: 'Trusted path', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Trusted Path',
    q: 'A "trusted path" provides:',
    o: [
      'A protected communication channel between the user and the security functions of a system',
      'A precomputed lookup of password hashes',
      'A magnetic method to destroy data',
      'A list of all open network ports',
    ],
    a: 'A',
    wc: 'A trusted path is a protected channel that assures users they are communicating directly with the TCB/security functions, free from interference.',
    ww: {
      B: 'That describes a rainbow table.',
      C: 'That describes degaussing.',
      D: 'That describes a port scan result.',
    },
    er: 'Recall of trusted path as a protected user-to-TCB channel.',
  },
  {
    t: 'Security Models', s: 'Lattice model', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Security Perimeter',
    q: 'A lattice-based access control model assigns security based on:',
    o: [
      'Levels (and compartments) where each subject/object sits at a defined position with upper and lower bounds',
      'The order in which users logged in',
      'The physical color of the device chassis',
      'The number of CPU cores in the system',
    ],
    a: 'A',
    wc: 'Lattice models place subjects and objects at defined security levels with least-upper-bound/greatest-lower-bound relationships, underpinning models like Biba and Bell-LaPadula.',
    ww: {
      B: 'Login order does not define lattice positions.',
      C: 'Chassis color is irrelevant.',
      D: 'CPU core count is irrelevant to a lattice.',
    },
    er: 'Tests the level/bounds nature of lattice models.',
  },
  // ---- Bell-LaPadula ----
  {
    t: 'Security Models', s: 'Bell-LaPadula', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Bell-LaPadula Model',
    q: 'The Bell-LaPadula model is designed primarily to protect which security property?',
    o: ['Confidentiality', 'Integrity', 'Availability', 'Non-repudiation'],
    a: 'A',
    wc: 'Bell-LaPadula is a confidentiality model, especially used in military/government environments.',
    ww: {
      B: 'Integrity is the focus of Biba and Clark-Wilson.',
      C: 'Availability is not the focus of BLP.',
      D: 'Non-repudiation is a cryptographic property, not BLP\'s focus.',
    },
    er: 'Recall that BLP = confidentiality.',
  },
  {
    t: 'Security Models', s: 'Bell-LaPadula', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Bell-LaPadula Model',
    q: 'Bell-LaPadula\'s Simple Security Rule states "no read up." What does its Star (*) Property state?',
    o: ['No write down', 'No read down', 'No write up', 'No read up'],
    a: 'A',
    wc: 'The BLP Star Property is "no write down"—subjects cannot write to a lower classification, preventing leakage of sensitive data to lower levels.',
    ww: {
      B: '"No read down" is the Biba Simple Integrity Axiom.',
      C: '"No write up" is the Biba Star Integrity Axiom.',
      D: '"No read up" is the BLP Simple Security Rule, not the Star Property.',
    },
    er: 'Tests the BLP star property (no write down).',
  },
  {
    t: 'Security Models', s: 'Bell-LaPadula', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Bell-LaPadula Model',
    q: 'A military system must ensure a user cleared only to "Secret" cannot read "Top Secret" documents. Which model rule directly enforces this, and from which model?',
    o: [
      'Simple Security Rule (no read up) — Bell-LaPadula',
      'Simple Integrity Axiom (no read down) — Biba',
      'Star Integrity Axiom (no write up) — Biba',
      'Well-formed transactions — Clark-Wilson',
    ],
    a: 'A',
    wc: 'Preventing a lower-cleared subject from reading higher-classified data is the Bell-LaPadula Simple Security Rule ("no read up"), a confidentiality protection.',
    ww: {
      B: 'Biba\'s simple integrity axiom (no read down) protects integrity, not confidentiality of higher data.',
      C: 'Biba\'s star integrity axiom (no write up) is an integrity rule.',
      D: 'Clark-Wilson well-formed transactions protect integrity in business apps.',
    },
    er: 'Maps a confidentiality "no read up" requirement to BLP.',
  },
  // ---- Biba ----
  {
    t: 'Security Models', s: 'Biba', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Biba Model',
    q: 'The Biba model is designed primarily to protect:',
    o: ['Integrity', 'Confidentiality', 'Availability', 'Anonymity'],
    a: 'A',
    wc: 'Biba prioritizes integrity, ensuring the accuracy and consistency of data, and is based on the lattice model.',
    ww: {
      B: 'Confidentiality is the focus of Bell-LaPadula.',
      C: 'Availability is not Biba\'s focus.',
      D: 'Anonymity is not an addressed property.',
    },
    er: 'Recall that Biba = integrity.',
  },
  {
    t: 'Security Models', s: 'Biba', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Biba Model',
    q: 'Biba\'s Simple Integrity Axiom is "no read down." What is its Star Integrity Axiom?',
    o: ['No write up', 'No write down', 'No read up', 'No read down'],
    a: 'A',
    wc: 'Biba\'s Star Integrity Axiom is "no write up"—lower-integrity subjects cannot write to higher-integrity objects, protecting data integrity.',
    ww: {
      B: '"No write down" is the Bell-LaPadula star property.',
      C: '"No read up" is the Bell-LaPadula simple security rule.',
      D: '"No read down" is Biba\'s Simple Integrity Axiom, not the star axiom.',
    },
    er: 'Tests the Biba star integrity axiom (no write up).',
  },
  {
    t: 'Security Models', s: 'BLP vs Biba', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Biba Model',
    q: 'A financial system must ensure low-integrity data entered by untrusted processes cannot corrupt high-integrity records. Which rule applies?',
    o: [
      'Biba Star Integrity Axiom (no write up)',
      'Bell-LaPadula Star Property (no write down)',
      'Bell-LaPadula Simple Security Rule (no read up)',
      'Brewer-Nash conflict-of-interest rule',
    ],
    a: 'A',
    wc: 'Preventing low-integrity subjects from writing to high-integrity objects is Biba\'s Star Integrity Axiom ("no write up"), protecting record integrity.',
    ww: {
      B: 'BLP no-write-down protects confidentiality, not integrity of high records.',
      C: 'BLP no-read-up is a confidentiality rule.',
      D: 'Brewer-Nash prevents conflicts of interest, not integrity corruption.',
    },
    er: 'Maps integrity protection to Biba\'s no-write-up rule.',
  },
  {
    t: 'Security Models', s: 'Model focus mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 3 > Secure Design Principles > Security Models - Part 2',
    p: ['Bell-LaPadula', 'Biba', 'Clark-Wilson', 'Brewer-Nash'],
    q: 'Match each security model (1-4) to its primary focus (A-D).',
    o: [
      'Integrity via well-formed transactions and an access triple',
      'Confidentiality (no read up / no write down)',
      'Preventing conflicts of interest (Chinese Wall)',
      'Integrity using a lattice (no read down / no write up)',
    ],
    a: '1-B,2-D,3-A,4-C',
    wc: 'Bell-LaPadula → confidentiality (B); Biba → integrity via lattice (D); Clark-Wilson → integrity via well-formed transactions/access triple (A); Brewer-Nash → conflict-of-interest prevention (C).',
    ww: {},
    er: 'Tests mapping of the major security models to their focus.',
  },
  // ---- Clark-Wilson ----
  {
    t: 'Security Models', s: 'Clark-Wilson', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Clark-Wilson Model',
    q: 'The Clark-Wilson model enforces integrity by requiring subjects to access data only through:',
    o: [
      'Well-formed transactions via an access triple (subject, program, object)',
      'Direct, unrestricted read/write to all objects',
      'A no-read-up confidentiality rule',
      'Conflict-of-interest class separation',
    ],
    a: 'A',
    wc: 'Clark-Wilson restricts subjects from directly manipulating data; access occurs through programs (the subject-program-object access triple) using well-formed transactions.',
    ww: {
      B: 'Clark-Wilson specifically restricts direct manipulation of data.',
      C: 'No-read-up is a Bell-LaPadula confidentiality rule.',
      D: 'Conflict-of-interest separation is Brewer-Nash.',
    },
    er: 'Tests the Clark-Wilson access triple and well-formed transactions.',
  },
  {
    t: 'Security Models', s: 'Clark-Wilson terms', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Key Terms',
    q: 'In Clark-Wilson, which element verifies that a Constrained Data Item (CDI) remains in a valid, consistent state after modification?',
    o: [
      'Integrity Verification Procedure (IVP)',
      'Transformation Procedure (TP)',
      'Unconstrained Data Item (UDI)',
      'Access Control Matrix (ACM)',
    ],
    a: 'A',
    wc: 'The Integrity Verification Procedure (IVP) verifies that the integrity of a CDI is maintained after modification.',
    ww: {
      B: 'A Transformation Procedure (TP) is the authorized method that modifies a CDI.',
      C: 'A UDI is data that does not require protection.',
      D: 'An ACM maps subjects to object permissions; it is not the Clark-Wilson IVP.',
    },
    er: 'Distinguishes IVP (verify) from TP (modify) in Clark-Wilson.',
  },
  // ---- Brewer-Nash / Graham-Denning / others ----
  {
    t: 'Security Models', s: 'Brewer-Nash', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Brewer-Nash Model (Chinese Wall Model)',
    q: 'A consulting firm must ensure an analyst who accessed Company A\'s confidential data cannot then access data from Company A\'s direct competitor. Which model addresses this?',
    o: ['Brewer-Nash (Chinese Wall) Model', 'Bell-LaPadula Model', 'Biba Model', 'Graham-Denning Model'],
    a: 'A',
    wc: 'The Brewer-Nash (Chinese Wall) model dynamically prevents access that would create a conflict of interest, such as accessing competing companies\' data.',
    ww: {
      B: 'Bell-LaPadula addresses confidentiality classification levels, not conflicts of interest.',
      C: 'Biba addresses integrity.',
      D: 'Graham-Denning defines subject/object creation and access-rights actions.',
    },
    er: 'Maps conflict-of-interest prevention to Brewer-Nash.',
  },
  {
    t: 'Security Models', s: 'Graham-Denning', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Graham-Denning Model',
    q: 'The Graham-Denning model focuses on:',
    o: [
      'Securely creating/deleting subjects and objects and managing access rights via an access control matrix',
      'Preventing low-integrity writes to high-integrity data',
      'Enforcing no read up for confidentiality',
      'Suppressing fires in a data center',
    ],
    a: 'A',
    wc: 'Graham-Denning defines eight primary actions for securely creating/deleting subjects and objects and granting/transferring/revoking access rights, using an access control matrix.',
    ww: {
      B: 'That describes Biba\'s star integrity axiom.',
      C: 'That describes Bell-LaPadula\'s simple security rule.',
      D: 'Fire suppression is a physical security control, not a model.',
    },
    er: 'Recall of Graham-Denning\'s focus on subject/object/rights operations.',
  },
  {
    t: 'Security Models', s: 'Take-Grant', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Biba Model',
    q: 'The Take-Grant model uses rules such as take, grant, create, and remove primarily to:',
    o: [
      'Manage how access rights are transferred or revoked between subjects and objects',
      'Detect hash collisions in weak algorithms',
      'Suppress electrical fires in server rooms',
      'Define classification levels for military data',
    ],
    a: 'A',
    wc: 'Take-Grant uses take, grant, create, and remove rules to model how rights are assigned, inherited, or removed based on trust relationships.',
    ww: {
      B: 'Hash collisions relate to birthday attacks, not Take-Grant.',
      C: 'Fire suppression is a physical control.',
      D: 'Classification levels relate to data classification/Bell-LaPadula context, not Take-Grant rules.',
    },
    er: 'Tests the Take-Grant rights-transfer rules.',
  },
  {
    t: 'Security Models', s: 'Sutherland / non-interference', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Sutherland Model',
    q: 'The Sutherland (Non-Deducibility) model aims to prevent which type of security problem?',
    o: [
      'Information leaks through covert channels and unauthorized inferences about data',
      'Physical theft of backup tapes',
      'Brute-force cracking of password hashes',
      'Excessive humidity in a server room',
    ],
    a: 'A',
    wc: 'The Sutherland (Non-Deducibility) model controls information flow to prevent leaks via covert channels and prevent unauthorized inferences about protected data.',
    ww: {
      B: 'Tape theft is a physical security issue.',
      C: 'Hash cracking is a cryptanalytic attack.',
      D: 'Humidity is an environmental control concern.',
    },
    er: 'Maps covert-channel/inference prevention to Sutherland/non-deducibility.',
  },
  {
    t: 'Security Models', s: 'Access control matrix', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Access Control Matrix',
    q: 'In an access control matrix, the permissions a specific subject has on a specific object are found:',
    o: [
      'At the cell where the subject\'s row intersects the object\'s column',
      'Only in the matrix header',
      'In a separate rainbow table',
      'In the TPM\'s endorsement key',
    ],
    a: 'A',
    wc: 'An access control matrix lists subjects as rows and objects as columns; the cell at their intersection holds the granted permissions.',
    ww: {
      B: 'Headers label rows/columns; permissions live in the cells.',
      C: 'A rainbow table is an attack artifact, not an ACM.',
      D: 'The EK is a TPM key, unrelated to an ACM.',
    },
    er: 'Tests the row/column/cell structure of an access control matrix.',
  },
  // ---- Common Criteria / EAL ----
  {
    t: 'Common Criteria', s: 'EAL', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Evaluation Assurance Levels (EALs)',
    q: 'Within Common Criteria, an Evaluation Assurance Level (EAL) expresses:',
    o: [
      'The depth and rigor of the evaluation/assurance applied to a product (e.g., EAL1 lowest to EAL7 highest)',
      'The market price of the product',
      'The number of users licensed to use the product',
      'The physical weight of the appliance',
    ],
    a: 'A',
    wc: 'EALs (EAL1 through EAL7) express the rigor and depth of the security evaluation, with higher levels indicating more thorough assurance.',
    ww: {
      B: 'EAL is about assurance rigor, not price.',
      C: 'EAL does not denote user count.',
      D: 'EAL has nothing to do with physical weight.',
    },
    er: 'Tests the meaning of EAL as evaluation rigor.',
  },
  // ---- Architecture vulnerabilities ----
  {
    t: 'Architecture Vulnerabilities', s: 'ACID', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > ACID Framework for Database Transactions',
    q: 'The ACID properties that ensure reliable database transactions stand for:',
    o: [
      'Atomicity, Consistency, Isolation, Durability',
      'Authentication, Confidentiality, Integrity, Defense',
      'Access, Control, Identity, Directory',
      'Availability, Capacity, Interoperability, Density',
    ],
    a: 'A',
    wc: 'ACID = Atomicity, Consistency, Isolation, Durability—the properties ensuring reliable database transactions.',
    ww: {
      B: 'These are mixed security terms, not the ACID properties.',
      C: 'These are not the ACID properties.',
      D: 'These are not the ACID properties.',
    },
    er: 'Recall of the ACID transaction properties.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'ICS/SCADA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Industrial Control Systems',
    q: 'Industrial Control Systems (ICS) and SCADA environments are especially security-sensitive primarily because:',
    o: [
      'They manage physical processes (e.g., power, water) where a compromise can cause real-world physical impact',
      'They are never connected to any network',
      'They store only public marketing data',
      'They automatically patch themselves continuously',
    ],
    a: 'A',
    wc: 'ICS/SCADA control physical processes, so attacks can have real-world physical and safety impacts; they often run legacy, hard-to-patch components.',
    ww: {
      B: 'Many ICS are networked, increasing exposure.',
      C: 'They handle operational/process data, not just public marketing data.',
      D: 'ICS are often difficult to patch, not continuously self-patching.',
    },
    er: 'Tests why ICS/SCADA compromise carries physical-impact risk.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'IoT', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Internet of Things',
    q: 'A company is deploying hundreds of inexpensive IoT sensors. Which is the MOST appropriate security consideration for this rollout?',
    o: [
      'Segment IoT devices on isolated networks and change default credentials, since many lack strong built-in security',
      'Place all IoT devices directly on the main corporate LAN for convenience',
      'Assume the devices are secure because they are new',
      'Disable all monitoring to reduce alert volume',
    ],
    a: 'A',
    wc: 'IoT devices often have weak built-in security; segmenting them and removing default credentials reduces the risk they pose to the broader network.',
    ww: {
      B: 'Placing weak IoT devices on the main LAN exposes critical systems.',
      C: 'New does not mean secure; many IoT devices ship with weak defaults.',
      D: 'Disabling monitoring reduces visibility into a high-risk device class.',
    },
    er: 'Tests IoT segmentation and credential hygiene.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'Embedded systems', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Embedded Systems',
    q: 'A common security challenge specific to embedded systems is that they:',
    o: [
      'Often have limited resources and infrequent updates, making patching difficult',
      'Always run a full modern OS with automatic updates',
      'Cannot be attacked because they have no software',
      'Are immune to supply-chain risks',
    ],
    a: 'A',
    wc: 'Embedded systems frequently have constrained resources and are rarely/never updated, making vulnerabilities persistent and patching difficult.',
    ww: {
      B: 'Embedded systems typically run minimal firmware, not full auto-updating OSes.',
      C: 'Embedded systems run software/firmware and can be attacked.',
      D: 'Embedded components are subject to supply-chain risks (e.g., counterfeits, malcode).',
    },
    er: 'Tests the patching/resource constraints of embedded systems.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'API gateway / microservices', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Secure Design Principles > API Gateway and Service Mesh Architecture',
    q: 'Which TWO security functions does an API gateway centralize for calls into a microservices architecture? (Select TWO.)',
    o: [
      'Authentication of incoming requests',
      'Authorization and rate limiting of traffic',
      'Generating TPM endorsement keys',
      'Physically locking the server room door',
    ],
    a: ['A', 'B'],
    wc: 'An API gateway provides a central point to enforce authentication, authorization, and rate limiting/traffic control for microservice calls.',
    ww: {
      C: 'EK generation is a TPM hardware function, not an API gateway role.',
      D: 'Door locks are physical controls, unrelated to API gateways.',
    },
    er: 'Identifies the centralized security functions of an API gateway.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'Database inference/aggregation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Database Vulnerabilities',
    q: 'A user without access to classified salary data is able to deduce an executive\'s salary by combining several unclassified query results. This database vulnerability is BEST described as:',
    o: ['Inference', 'Aggregation of patches', 'Atomicity failure', 'A wet-pipe leak'],
    a: 'A',
    wc: 'Inference occurs when a user derives sensitive information from combinations of data they are authorized to see—a classic database confidentiality vulnerability.',
    ww: {
      B: '"Aggregation of patches" is not a database vulnerability term.',
      C: 'Atomicity failure concerns transaction integrity, not deducing secrets.',
      D: 'A wet-pipe leak is a physical/fire-suppression issue.',
    },
    er: 'Tests recognizing the inference problem in databases.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'SASE', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Access Service Edge',
    q: 'Secure Access Service Edge (SASE) primarily combines:',
    o: [
      'Networking and security functions delivered together as a cloud-based service',
      'Only on-premises firewalls with no cloud component',
      'Fire suppression and HVAC controls',
      'Hardware key generation and physical badges',
    ],
    a: 'A',
    wc: 'SASE converges network and security capabilities (e.g., SD-WAN, secure web gateway, ZTNA) delivered as a cloud-based service.',
    ww: {
      B: 'SASE is cloud-delivered, not purely on-prem firewalls.',
      C: 'Those are facility/environmental controls.',
      D: 'Those are unrelated hardware/physical controls.',
    },
    er: 'Recall of SASE as converged cloud networking + security.',
  },
  {
    t: 'Architecture Vulnerabilities', s: 'Architecture concepts', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Secure Design Principles > Objective 3.5',
    q: 'Which TWO are recognized strategies for mitigating vulnerabilities in modern system architectures? (Select TWO.)',
    o: [
      'Traffic isolation and network segmentation',
      'Securing APIs and inter-service communications with encryption',
      'Granting every microservice full administrative rights',
      'Disabling all logging to improve performance',
    ],
    a: ['A', 'B'],
    wc: 'Segmentation/isolation and securing APIs/inter-service communication with encryption are sound mitigations for modern architecture risks.',
    ww: {
      C: 'Granting full admin rights to every service violates least privilege and expands blast radius.',
      D: 'Disabling logging removes detection and forensic capability.',
    },
    er: 'Separates real mitigations from harmful anti-patterns.',
  },
  {
    t: 'Security Models', s: 'State machine model', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Security Perimeter',
    q: 'A finite state machine model considers a system secure if:',
    o: [
      'It begins in a secure state and every permitted transition leads to another secure state',
      'It uses the fastest possible CPU',
      'It encrypts all data with symmetric keys',
      'It has the most network ports open',
    ],
    a: 'A',
    wc: 'In a state machine model, a system is secure if it starts in a secure state and all transitions keep it in secure states.',
    ww: {
      B: 'CPU speed is irrelevant to the model.',
      C: 'Encryption choice is not what defines a secure state machine.',
      D: 'Open ports do not define security in a state machine model.',
    },
    er: 'Tests the secure-state-transition concept.',
  },
  {
    t: 'Security Models', s: 'Non-interference', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Security Models - Part 1',
    q: 'The Non-Interference (Goguen-Meseguer) model ensures that:',
    o: [
      'Actions of higher-security subjects do not affect or become visible to lower-security subjects',
      'All users can read all data regardless of level',
      'Data is destroyed when no longer needed',
      'Fires are suppressed before damaging equipment',
    ],
    a: 'A',
    wc: 'Non-interference ensures that the actions of high-level subjects do not interfere with or leak to low-level subjects, preventing covert information flow.',
    ww: {
      B: 'Unrestricted reads contradict the model\'s purpose.',
      C: 'Data destruction is a lifecycle/retention concern.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Tests the non-interference principle.',
  },
];
