// Domain 3 — Part 1: Secure design concepts & principles (Saltzer-Schroeder),
// Zero Trust (NIST SP 800-207), shared responsibility, Privacy by Design,
// system security capabilities, TPM/HSM.
module.exports = [
  // ---- Secure design concepts ----
  {
    t: 'Secure Design Concepts', s: 'Confinement (sandboxing)', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Concepts',
    q: 'Running software in an isolated environment that restricts its access to system resources to avoid unintended interactions is known as:',
    o: ['Confinement (sandboxing)', 'Transitive trust', 'Open design', 'Psychological acceptability'],
    a: 'A',
    wc: 'Confinement (sandboxing) runs software in an isolated environment, restricting its access to system resources to prevent unintended interactions.',
    ww: {
      B: 'Transitive trust is when trust is passed along a chain of relationships.',
      C: 'Open design means the design can be openly reviewed; security rests on secret keys.',
      D: 'Psychological acceptability concerns making security usable.',
    },
    er: 'Recall of confinement/sandboxing.',
  },
  {
    t: 'Secure Design Concepts', s: 'Bounds', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Concepts',
    q: 'A control that limits the memory resources available to a process so it cannot affect other areas of the system is referred to as:',
    o: ['Bounds', 'Assurance', 'Complete mediation', 'Work factor'],
    a: 'A',
    wc: 'Bounds limit the memory/resources available to a process, ensuring it operates within assigned limits and cannot impact other system areas.',
    ww: {
      B: 'Assurance is the degree of confidence that security controls work as intended.',
      C: 'Complete mediation requires authorization on every access.',
      D: 'Work factor measures the effort required to break a control or cipher.',
    },
    er: 'Distinguishes bounds (resource limits) from related concepts.',
  },
  {
    t: 'Secure Design Concepts', s: 'Transitive trust', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Trust and Secure Design',
    q: 'System A trusts System B, and System B trusts System C. Because of this chain, System A effectively trusts System C even though it was never directly evaluated. This relationship is an example of:',
    o: ['Transitive trust', 'Complete mediation', 'Separation of duties', 'Fail-safe defaults'],
    a: 'A',
    wc: 'Transitive trust is when trust flows along a chain (A→B→C), causing A to implicitly trust C; least common mechanism warns against such transitive trust.',
    ww: {
      B: 'Complete mediation checks authorization on every access, not chained trust.',
      C: 'Separation of duties splits critical functions among people.',
      D: 'Fail-safe defaults deny by default; unrelated to trust chaining.',
    },
    er: 'Tests recognizing transitive trust and its inherent risk.',
  },
  {
    t: 'Secure Design Concepts', s: 'Assurance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Trust and Secure Design',
    q: 'In secure design, "assurance" refers to:',
    o: [
      'The degree of confidence that a system\'s security controls function as intended',
      'The act of isolating a process in memory',
      'A precomputed table of password hashes',
      'A magnetic method of destroying data',
    ],
    a: 'A',
    wc: 'Assurance is the level of confidence that security measures/controls work correctly and as intended.',
    ww: {
      B: 'That describes memory protection/isolation.',
      C: 'That describes a rainbow table.',
      D: 'That describes degaussing.',
    },
    er: 'Recall of the assurance concept.',
  },
  // ---- Saltzer & Schroeder principles ----
  {
    t: 'Secure Design Principles', s: 'Fail-safe defaults', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'A design principle stating that default settings should DENY access and that components should fail closed rather than open is:',
    o: ['Fail-safe defaults', 'Open design', 'Psychological acceptability', 'Economy of mechanism'],
    a: 'A',
    wc: 'Fail-safe defaults require that default settings deny access and that components fail securely (closed) rather than open.',
    ww: {
      B: 'Open design means the design itself is open to review.',
      C: 'Psychological acceptability concerns usability of security.',
      D: 'Economy of mechanism favors simple, small designs.',
    },
    er: 'Maps deny-by-default/fail-closed to fail-safe defaults.',
  },
  {
    t: 'Secure Design Principles', s: 'Complete mediation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Which principle requires that authorization be checked EVERY time a subject requests access to an object, rather than once and cached indefinitely?',
    o: ['Complete mediation', 'Least common mechanism', 'Economy of mechanism', 'Open design'],
    a: 'A',
    wc: 'Complete mediation requires authorization to be verified on each access request, preventing unauthorized access that could arise from stale permissions.',
    ww: {
      B: 'Least common mechanism limits shared components/transitive trust.',
      C: 'Economy of mechanism favors simplicity.',
      D: 'Open design concerns openness of the design to review.',
    },
    er: 'Recall of complete mediation.',
  },
  {
    t: 'Secure Design Principles', s: 'Open design', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'The "open design" principle holds that the security of a system should depend on:',
    o: [
      'Keeping cryptographic keys and passwords secret, not on hiding the design itself',
      'Keeping the entire system design secret from everyone',
      'Using only proprietary, undisclosed algorithms',
      'Avoiding any external review of the system',
    ],
    a: 'A',
    wc: 'Open design states the design should be open to external review; security should rest on secret keys/passwords, not obscurity of the design (the opposite of security through obscurity).',
    ww: {
      B: 'Hiding the design is security through obscurity, which open design rejects.',
      C: 'Proprietary undisclosed algorithms contradict open design.',
      D: 'Open design encourages external review.',
    },
    er: 'Tests open design vs. security through obscurity.',
  },
  {
    t: 'Secure Design Principles', s: 'Economy of mechanism', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Which secure design principle favors keeping a design as simple and small as possible to reduce complexity and potential errors?',
    o: ['Economy of mechanism', 'Least privilege', 'Complete mediation', 'Separation of privilege'],
    a: 'A',
    wc: 'Economy of mechanism calls for simple, small designs to reduce complexity and the likelihood of errors/flaws.',
    ww: {
      B: 'Least privilege grants minimum necessary access.',
      C: 'Complete mediation checks every access.',
      D: 'Separation of privilege requires multiple subjects for critical functions.',
    },
    er: 'Recall of economy of mechanism.',
  },
  {
    t: 'Secure Design Principles', s: 'Least common mechanism', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'A principle that advises LIMITING shared components and avoiding transitive trust between processes to minimize cross-system vulnerabilities is:',
    o: ['Least common mechanism', 'Psychological acceptability', 'Fail-safe defaults', 'Complete mediation'],
    a: 'A',
    wc: 'Least common mechanism minimizes shared mechanisms/components and avoids transitive trust, reducing pathways for cross-system compromise.',
    ww: {
      B: 'Psychological acceptability concerns usable security.',
      C: 'Fail-safe defaults deny by default.',
      D: 'Complete mediation checks authorization on each access.',
    },
    er: 'Distinguishes least common mechanism from other principles.',
  },
  {
    t: 'Secure Design Principles', s: 'Psychological acceptability', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Designing security features so users find them simple and are not tempted to bypass them embodies which principle?',
    o: ['Psychological acceptability', 'Economy of mechanism', 'Open design', 'Separation of privilege'],
    a: 'A',
    wc: 'Psychological acceptability holds that security should be user-friendly so users do not circumvent it through error or frustration.',
    ww: {
      B: 'Economy of mechanism is about design simplicity, not user experience.',
      C: 'Open design concerns openness of design to review.',
      D: 'Separation of privilege requires multiple parties for critical actions.',
    },
    er: 'Maps usable security to psychological acceptability.',
  },
  {
    t: 'Secure Design Principles', s: 'Separation of privilege', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Requiring two or more subjects to execute a critical function, minimizing risk from any single user, is the principle of:',
    o: ['Separation of privilege', 'Least privilege', 'Least common mechanism', 'Complete mediation'],
    a: 'A',
    wc: 'Separation of privilege (separation of duties) requires two or more subjects to perform critical functions, reducing single-user risk.',
    ww: {
      B: 'Least privilege limits each subject to minimum access, but does not require multiple subjects for one function.',
      C: 'Least common mechanism limits shared components.',
      D: 'Complete mediation checks every access.',
    },
    er: 'Distinguishes separation of privilege from least privilege.',
  },
  {
    t: 'Secure Design Principles', s: 'Saltzer and Schroeder', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Which TWO of the following are among Saltzer and Schroeder\'s secure design principles? (Select TWO.)',
    o: ['Least privilege', 'Complete mediation', 'No write down', 'Birthday attack resistance'],
    a: ['A', 'B'],
    wc: 'Least privilege and complete mediation are Saltzer & Schroeder design principles.',
    ww: {
      C: '"No write down" is the Bell-LaPadula star property, not a Saltzer-Schroeder design principle.',
      D: '"Birthday attack resistance" is a cryptographic property, not a design principle.',
    },
    er: 'Separates Saltzer-Schroeder principles from model rules and crypto concepts.',
  },
  // ---- Zero Trust ----
  {
    t: 'Zero Trust Architecture', s: 'Core concept', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Zero Trust Architecture',
    q: 'The central premise of Zero Trust Architecture is:',
    o: [
      'Never automatically trust any user or device; verify every access on a per-session basis',
      'Trust all devices on the internal/private network by default',
      'Trust is granted permanently after the first successful login',
      'Only perimeter firewalls are needed for security',
    ],
    a: 'A',
    wc: 'Zero Trust assumes no implicit trust—every access is authenticated/authorized per session regardless of network location.',
    ww: {
      B: 'Zero Trust explicitly rejects implicit trust of private networks.',
      C: 'Access is evaluated continuously per session, not granted permanently.',
      D: 'Zero Trust goes beyond perimeter defenses to per-resource verification.',
    },
    er: 'Tests the no-implicit-trust premise of ZT.',
  },
  {
    t: 'Zero Trust Architecture', s: 'NIST SP 800-207', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > NIST SP 800-207 Zero Trust Principles',
    q: 'Which document defines the Zero Trust Architecture principles referenced in the guide?',
    o: ['NIST SP 800-207', 'NIST SP 800-53', 'ISO 11889', 'NIST SP 800-88'],
    a: 'A',
    wc: 'NIST SP 800-207 defines Zero Trust Architecture principles.',
    ww: {
      B: 'NIST SP 800-53 is the security/privacy control catalog.',
      C: 'ISO 11889 is the TPM standard.',
      D: 'NIST SP 800-88 covers media sanitization.',
    },
    er: 'Maps Zero Trust to NIST SP 800-207.',
  },
  {
    t: 'Zero Trust Architecture', s: 'ZT components', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Zero Trust Architecture Components',
    q: 'In a Zero Trust Architecture, which component actually ENFORCES the access decision by acting as a gateway between a subject and a resource?',
    o: ['Policy Enforcement Point (PEP)', 'Policy Engine (PE)', 'Policy Administrator (PA)', 'Trusted Platform Module (TPM)'],
    a: 'A',
    wc: 'The Policy Enforcement Point (PEP) enforces access control by acting as the gateway/intermediary between subjects and resources.',
    ww: {
      B: 'The Policy Engine decides whether to grant access (the decision), but does not enforce at the gateway.',
      C: 'The Policy Administrator manages communication and token creation between the PE and PEP.',
      D: 'A TPM is a cryptographic hardware chip, not a ZT policy component.',
    },
    er: 'Distinguishes PEP (enforce) from PE (decide) and PA (manage).',
  },
  {
    t: 'Zero Trust Architecture', s: 'ZT components', d: 'hard', qt: 'matching',
    sec: 'Domain 3 > Secure Design Principles > Zero Trust Architecture Components',
    p: ['Policy Engine (PE)', 'Policy Administrator (PA)', 'Policy Enforcement Point (PEP)'],
    q: 'Match each Zero Trust component (1-3) to its role (A-C).',
    o: [
      'Manages subject-resource communication and creates access tokens',
      'Decides whether to authorize a subject\'s access to a resource and logs decisions',
      'Enforces access as a gateway/intermediary between subject and resource',
    ],
    a: '1-B,2-A,3-C',
    wc: 'Policy Engine → decides/logs (B); Policy Administrator → manages communication/tokens (A); Policy Enforcement Point → enforces at the gateway (C).',
    ww: {},
    er: 'Tests the decide/manage/enforce split of ZT components.',
  },
  {
    t: 'Zero Trust Architecture', s: 'Trust but verify vs ZT', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Zero Trust Architecture',
    q: 'An organization currently grants broad network access once a device connects to the corporate LAN. To move toward Zero Trust, it should:',
    o: [
      'Treat the internal network as untrusted and authenticate/authorize each resource request',
      'Continue trusting all LAN-connected devices to reduce friction',
      'Rely solely on a stronger perimeter firewall',
      'Grant permanent access tokens that never expire',
    ],
    a: 'A',
    wc: 'Zero Trust removes implicit trust of private networks—each resource request is authenticated/authorized regardless of network location.',
    ww: {
      B: 'Trusting LAN devices by default is exactly what Zero Trust eliminates.',
      C: 'A stronger perimeter still leaves implicit internal trust intact.',
      D: 'Non-expiring tokens contradict per-session, continuous verification.',
    },
    er: 'Tests applying Zero Trust to remove implicit internal trust.',
  },
  // ---- Shared responsibility ----
  {
    t: 'Shared Responsibility Model', s: 'Inherited controls', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Shared Responsibility Model',
    q: 'Under the shared responsibility model, an organization that uses a cloud provider typically INHERITS which type of control from the provider?',
    o: ['Physical security of the data center', 'Classification of its own data', 'Its own user access reviews', 'Its application-layer input validation'],
    a: 'A',
    wc: 'Customers inherit controls like physical security of the provider\'s data centers, while retaining responsibility for their own data and access.',
    ww: {
      B: 'Data classification remains the customer\'s responsibility.',
      C: 'Access reviews of the customer\'s users remain the customer\'s job.',
      D: 'Application input validation is the customer\'s responsibility (especially in IaaS/PaaS).',
    },
    er: 'Identifies physical security as a commonly inherited control.',
  },
  // ---- Privacy by Design ----
  {
    t: 'Privacy by Design', s: 'Proactive principle', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Privacy By Design',
    q: 'The Privacy by Design principle "Proactive, not Reactive" means an organization should:',
    o: [
      'Anticipate and prevent privacy risks before they occur rather than responding after the fact',
      'Wait for a breach before adding any privacy controls',
      'Collect as much data as possible by default',
      'Disclose user data publicly for transparency',
    ],
    a: 'A',
    wc: 'Proactive, not reactive focuses on anticipating and preventing privacy risks before they materialize, aiming beyond mere compliance.',
    ww: {
      B: 'Waiting for a breach is reactive—the opposite of this principle.',
      C: 'Collecting maximal data violates privacy by default/data minimization.',
      D: 'Transparency means clear policies, not exposing user data publicly.',
    },
    er: 'Tests the proactive, preventative stance of Privacy by Design.',
  },
  {
    t: 'Privacy by Design', s: 'Privacy by default', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > Privacy By Design',
    q: 'A new app is configured so that, out of the box, it shares the minimum data necessary and keeps the strictest privacy settings unless a user opts in to more sharing. This best reflects which Privacy by Design principle?',
    o: ['Privacy by Default', 'Visibility and Transparency', 'Full Functionality (Positive-Sum)', 'End-to-End Security'],
    a: 'A',
    wc: 'Privacy by Default sets the strictest privacy protections as the default, collecting only necessary data and limiting purpose, scope, and retention.',
    ww: {
      B: 'Visibility and Transparency concerns publishing accessible privacy policies.',
      C: 'Full Functionality (Positive-Sum) balances privacy with functionality without trade-offs.',
      D: 'End-to-End Security protects data across its full lifecycle.',
    },
    er: 'Maps default-minimal-sharing to Privacy by Default.',
  },
  {
    t: 'Privacy by Design', s: 'Positive-sum', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Full Functionality – Positive-Sum, Not Zero-Sum',
    q: 'The "Full Functionality – Positive-Sum, Not Zero-Sum" principle asserts that privacy measures should:',
    o: [
      'Coexist with business objectives and usability rather than forcing an either/or trade-off',
      'Always be sacrificed to maximize functionality',
      'Replace all business functionality with privacy controls',
      'Be applied only after the product is decommissioned',
    ],
    a: 'A',
    wc: 'Positive-sum means privacy protections support business processes and user experience without unnecessary trade-offs—not an either/or choice.',
    ww: {
      B: 'Sacrificing privacy for functionality is the zero-sum view this principle rejects.',
      C: 'Privacy does not replace functionality; the two coexist.',
      D: 'Privacy is integrated throughout, not only at decommission.',
    },
    er: 'Tests the positive-sum (no trade-off) principle.',
  },
  // ---- System security capabilities ----
  {
    t: 'System Security Capabilities', s: 'Memory protection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > System Security Capabilities',
    q: 'The PRIMARY goal of memory protection as a system security capability is to:',
    o: [
      'Prevent processes in memory from interacting with each other to avoid data leaks',
      'Increase the clock speed of the CPU',
      'Encrypt all network traffic in transit',
      'Provide physical access control to the data center',
    ],
    a: 'A',
    wc: 'Memory protection prevents processes in memory from interacting, allowing multiple processes (even at different security levels) to run independently without data leakage.',
    ww: {
      B: 'Memory protection is about isolation, not CPU performance.',
      C: 'Encrypting network traffic is a transport-layer control, not memory protection.',
      D: 'Physical access control is a facility control, not memory protection.',
    },
    er: 'Maps process isolation in memory to memory protection.',
  },
  {
    t: 'System Security Capabilities', s: 'Constrained interface', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > User Interfaces (Restricted or Constrained Interfaces)',
    q: 'An application hides admin-only menu items from standard users, exposing only the functions appropriate to each role. This capability is a:',
    o: ['Restricted/constrained interface', 'Trusted Platform Module', 'Reference monitor', 'Covert channel'],
    a: 'A',
    wc: 'A restricted/constrained interface limits the objects and functions a user can access based on privilege level, implementing least privilege at the UI.',
    ww: {
      B: 'A TPM is a cryptographic hardware chip.',
      C: 'A reference monitor mediates all access between subjects and objects at a system level.',
      D: 'A covert channel is an unauthorized communication path, not a UI control.',
    },
    er: 'Maps role-based UI hiding to constrained interfaces.',
  },
  {
    t: 'System Security Capabilities', s: 'TPM', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Trusted Platform Module (TPM)',
    q: 'A Trusted Platform Module (TPM) is BEST described as:',
    o: [
      'A specialized motherboard chip that provides cryptographic services such as key generation and encryption',
      'A cloud service that stores virtual machines',
      'A network appliance that filters egress traffic',
      'A software sandbox for running untrusted code',
    ],
    a: 'A',
    wc: 'A TPM is a specialized motherboard chip (ISO 11889) providing cryptographic services such as creating key pairs, signing data, and encryption.',
    ww: {
      B: 'A TPM is local hardware, not a cloud VM service.',
      C: 'Egress filtering is a network DLP/firewall function.',
      D: 'A sandbox isolates code in software, not a cryptographic chip.',
    },
    er: 'Recall of the TPM as a cryptographic hardware chip.',
  },
  {
    t: 'System Security Capabilities', s: 'TPM endorsement key', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Trusted Platform Module (TPM)',
    q: 'Which TPM component is a private key embedded by the hardware manufacturer that is unique and cannot be altered?',
    o: ['Endorsement Key (EK)', 'Storage Root Key (SRK)', 'Platform Configuration Register (PCR)', 'Attestation Identity Key (AIK)'],
    a: 'A',
    wc: 'The Endorsement Key (EK) is a private key embedded by the hardware manufacturer that is unalterable and unique to the TPM.',
    ww: {
      B: 'The Storage Root Key (SRK) secures keys stored in the TPM.',
      C: 'PCRs track the current software/configuration state.',
      D: 'The AIK is used for attestation of platform identity.',
    },
    er: 'Distinguishes the manufacturer-embedded EK from other TPM components.',
  },
  {
    t: 'System Security Capabilities', s: 'HSM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Trusted Platform Module (TPM)',
    q: 'A standalone cryptographic device used to perform encryption/decryption and securely manage cryptographic keys for high-security applications is a:',
    o: ['Hardware Security Module (HSM)', 'Policy Enforcement Point (PEP)', 'Constrained interface', 'Sandbox'],
    a: 'A',
    wc: 'An HSM is a standalone cryptographic device providing encryption/decryption and high-security key management.',
    ww: {
      B: 'A PEP enforces Zero Trust access decisions.',
      C: 'A constrained interface limits UI functions by privilege.',
      D: 'A sandbox isolates running code.',
    },
    er: 'Distinguishes HSM (standalone crypto device) from a TPM (motherboard chip).',
  },
  {
    t: 'System Security Capabilities', s: 'Virtualization benefits', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > System Security Capabilities',
    q: 'As a system security capability, virtualization is useful for malware analysis primarily because it:',
    o: [
      'Provides isolated, sandboxed environments where malware can run without affecting the host',
      'Permanently prevents all malware from executing',
      'Encrypts all data on the network',
      'Eliminates the need for any access controls',
    ],
    a: 'A',
    wc: 'Virtualization enables isolated, sandboxed environments useful for safely analyzing malware, along with centralized control, scalability, and easy recovery.',
    ww: {
      B: 'Virtualization isolates malware but does not prevent its execution within the sandbox.',
      C: 'Virtualization is about emulating systems, not encrypting network traffic.',
      D: 'Access controls are still required in virtualized environments.',
    },
    er: 'Connects virtualization isolation to safe malware analysis.',
  },
  {
    t: 'Secure Design Principles', s: 'Least privilege', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Secure Design Principles',
    q: 'Granting a subject only the minimum access required to perform its job functions is the principle of:',
    o: ['Least privilege', 'Open design', 'Economy of mechanism', 'Complete mediation'],
    a: 'A',
    wc: 'Least privilege grants subjects only the minimum access necessary for their functions.',
    ww: {
      B: 'Open design concerns openness of the design to review.',
      C: 'Economy of mechanism favors simple design.',
      D: 'Complete mediation checks authorization on each access.',
    },
    er: 'Recall of least privilege as a design principle.',
  },
  {
    t: 'Zero Trust Architecture', s: 'NIST 800-207 principles', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Secure Design Principles > NIST SP 800-207 Zero Trust Principles',
    q: 'Which TWO statements reflect NIST SP 800-207 Zero Trust principles? (Select TWO.)',
    o: [
      'Access to resources is granted on a per-session basis',
      'Authentication and authorization are strictly enforced before access is allowed',
      'Devices on the private network are implicitly trusted',
      'Once authenticated, a session is trusted indefinitely',
    ],
    a: ['A', 'B'],
    wc: 'Per-session access and strict, real-time authentication/authorization are core NIST SP 800-207 principles.',
    ww: {
      C: 'Zero Trust grants no implicit trust to private-network devices.',
      D: 'Trust is continuously evaluated, not granted indefinitely.',
    },
    er: 'Separates genuine Zero Trust principles from implicit-trust distractors.',
  },
  {
    t: 'Privacy by Design', s: 'End-to-end security', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > End-to-End Security – Full Lifecycle Protection',
    q: 'The Privacy by Design principle of "End-to-End Security – Full Lifecycle Protection" requires protecting data:',
    o: [
      'Throughout its entire lifecycle—creation, processing, storage, and destruction',
      'Only while it is displayed on screen',
      'Only after a regulator requests it',
      'Only during the initial collection step',
    ],
    a: 'A',
    wc: 'End-to-end security protects data across its full lifecycle: creation, processing, storage, and destruction, with secure handling and transmission.',
    ww: {
      B: 'Protection must extend beyond on-screen display to all lifecycle stages.',
      C: 'Protection is proactive, not triggered by a regulator request.',
      D: 'Protection spans the whole lifecycle, not only collection.',
    },
    er: 'Ties end-to-end security to full-lifecycle data protection.',
  },
];
