// Domain 3 — Part 4: Cryptanalytic attacks (3.7), physical/site & facility
// security (3.8/3.9), and the information system lifecycle (3.10).
module.exports = [
  // ---- Cryptanalytic attacks ----
  {
    t: 'Cryptanalytic Attacks', s: 'Brute force', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Summary of Key Attacks',
    q: 'A brute-force attack against a cipher works by:',
    o: [
      'Trying all possible key combinations until the correct one is found',
      'Analyzing the power consumption of the device',
      'Reusing a captured authentication token',
      'Tricking a user into revealing their password',
    ],
    a: 'A',
    wc: 'Brute force tries every possible key; given enough time and resources it is guaranteed to succeed, which is why sufficient key length matters.',
    ww: {
      B: 'Analyzing power consumption is a side-channel attack.',
      C: 'Reusing a captured token is a replay attack.',
      D: 'Tricking a user is social engineering.',
    },
    er: 'Recall of brute force as exhaustive key search.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Known plaintext', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Cryptanalytic Attacks - Part 1',
    q: 'In a known-plaintext attack, the attacker attempts to recover the key by analyzing:',
    o: [
      'Known plaintext together with its corresponding ciphertext',
      'Only ciphertext, with no plaintext available',
      'The device\'s electromagnetic emissions',
      'A precomputed table of password hashes',
    ],
    a: 'A',
    wc: 'A known-plaintext attack uses pairs of known plaintext and its resulting ciphertext to deduce the key.',
    ww: {
      B: 'Having only ciphertext describes a ciphertext-only attack.',
      C: 'Electromagnetic emissions are exploited by side-channel attacks.',
      D: 'Precomputed hash tables describe a rainbow table attack.',
    },
    er: 'Distinguishes known-plaintext from ciphertext-only attacks.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Chosen plaintext', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Chosen Plaintext Attack',
    q: 'A chosen-plaintext attack is characterized by the attacker\'s ability to:',
    o: [
      'Select specific plaintext, have it encrypted, and analyze the resulting ciphertext',
      'Only observe ciphertext that happens to be transmitted',
      'Physically destroy the encryption hardware',
      'Reuse intercepted session tokens',
    ],
    a: 'A',
    wc: 'In a chosen-plaintext attack, the attacker chooses plaintext, obtains its ciphertext, and analyzes the pair to narrow down the key.',
    ww: {
      B: 'Passive observation of ciphertext is a ciphertext-only attack.',
      C: 'Destroying hardware is not a cryptanalytic chosen-plaintext attack.',
      D: 'Reusing tokens is a replay attack.',
    },
    er: 'Tests the chosen-plaintext capability.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Ciphertext-only', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Cryptanalytic Attacks - Part 2',
    q: 'Which attack attempts to discover the key by analyzing ONLY ciphertext, with no access to matching plaintext?',
    o: ['Ciphertext-only attack', 'Known-plaintext attack', 'Chosen-plaintext attack', 'Replay attack'],
    a: 'A',
    wc: 'A ciphertext-only attack works from ciphertext alone, often aided by techniques like frequency analysis.',
    ww: {
      B: 'Known-plaintext requires matching plaintext-ciphertext pairs.',
      C: 'Chosen-plaintext requires the attacker to encrypt chosen plaintext.',
      D: 'A replay attack reuses captured messages, not pure ciphertext analysis.',
    },
    er: 'Tests the ciphertext-only definition.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Differential cryptanalysis', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Chosen Plaintext Attack',
    q: 'Differential cryptanalysis attempts to recover key information by:',
    o: [
      'Analyzing how small differences in plaintext (or key) affect the resulting ciphertext',
      'Trying every possible key exhaustively',
      'Measuring the time each operation takes',
      'Capturing and replaying a valid message',
    ],
    a: 'A',
    wc: 'Differential cryptanalysis studies how slight changes (differences) in plaintext or key propagate to ciphertext to infer key information.',
    ww: {
      B: 'Exhaustive key search is brute force.',
      C: 'Measuring operation time is a timing/side-channel attack.',
      D: 'Capturing and replaying is a replay attack.',
    },
    er: 'Tests the differential-analysis concept.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Meet in the middle', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Meet in the Middle Attack',
    q: 'A meet-in-the-middle attack is particularly effective against ciphers that:',
    o: [
      'Use multiple rounds/stages of encryption (e.g., double encryption)',
      'Use only a single short key with no rounds',
      'Are physically air-gapped',
      'Have no key at all',
    ],
    a: 'A',
    wc: 'Meet-in-the-middle encrypts from one end and decrypts from the other to find matching intermediate values, making it effective against multi-stage (e.g., double) encryption.',
    ww: {
      B: 'Single-stage short-key ciphers are attacked by brute force, not meet-in-the-middle.',
      C: 'Air-gapping is a physical control unrelated to this cryptanalytic method.',
      D: 'Encryption inherently involves a key.',
    },
    er: 'Tests the multi-stage target of meet-in-the-middle.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Birthday attack', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Cryptanalytic Attacks > Hash-Based Attacks',
    q: 'An attacker finds two different inputs that produce the SAME hash value to bypass an integrity check on a weak hashing algorithm. This exploits which attack?',
    o: ['Birthday attack (hash collision)', 'Replay attack', 'Side-channel attack', 'Brute force of a symmetric key'],
    a: 'A',
    wc: 'A birthday attack exploits the birthday paradox to find hash collisions (two inputs with the same hash), undermining integrity controls on weaker hash algorithms.',
    ww: {
      B: 'A replay attack reuses captured messages.',
      C: 'A side-channel attack measures physical characteristics.',
      D: 'Brute-forcing a symmetric key is not about hash collisions.',
    },
    er: 'Maps hash collisions to the birthday attack.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Rainbow table', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Hash-Based Attacks',
    q: 'A rainbow table attack recovers passwords by:',
    o: [
      'Matching a captured password hash against precomputed hash-to-plaintext tables',
      'Encrypting chosen plaintext and analyzing the output',
      'Measuring CPU timing during decryption',
      'Reusing an intercepted session cookie',
    ],
    a: 'A',
    wc: 'A rainbow table uses precomputed tables of hashes for common passwords; a captured hash matching an entry reveals the plaintext password (salting defends against this).',
    ww: {
      B: 'That describes a chosen-plaintext attack.',
      C: 'That describes a timing/side-channel attack.',
      D: 'That describes session replay.',
    },
    er: 'Tests the precomputed-hash nature of rainbow tables.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Pass the hash', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Cryptanalytic Attacks > Hash-Based Attacks',
    q: 'An attacker steals NTLM password hashes from a Windows host and uses them directly to authenticate to other systems without ever cracking the plaintext password. This is:',
    o: ['Pass the hash', 'Kerberoasting', 'A birthday attack', 'A timing attack'],
    a: 'A',
    wc: 'Pass the hash uses stolen password hashes directly for authentication, commonly targeting Windows LM/NTLM, without needing the plaintext password.',
    ww: {
      B: 'Kerberoasting targets Kerberos tickets, not NTLM hash reuse.',
      C: 'A birthday attack finds hash collisions, not credential reuse.',
      D: 'A timing attack measures operation duration.',
    },
    er: 'Tests recognition of pass-the-hash.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Kerberoasting', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Hash-Based Attacks',
    q: 'Kerberoasting specifically targets:',
    o: [
      'Kerberos authentication by harvesting and cracking service ticket hashes',
      'The power consumption of a smart card',
      'TLS certificate revocation lists',
      'Physical badge readers at a facility',
    ],
    a: 'A',
    wc: 'Kerberoasting targets Kerberos by requesting and harvesting service-ticket hashes and attempting to crack them offline to obtain credentials.',
    ww: {
      B: 'Power consumption is a side-channel target.',
      C: 'CRLs relate to PKI certificate validation, not Kerberoasting.',
      D: 'Badge readers are physical controls.',
    },
    er: 'Maps Kerberos ticket cracking to Kerberoasting.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Replay attack', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Cryptanalytic Attacks > Replay Attack',
    q: 'An attacker intercepts an encrypted authentication message and resends it later to gain access. Which countermeasure BEST defends against this replay attack?',
    o: [
      'Timestamps, expiration periods, or nonces/timeouts on messages',
      'Longer office fences',
      'A wet-pipe fire suppression system',
      'Increasing the CPU clock speed',
    ],
    a: 'A',
    wc: 'Replay attacks reuse captured valid messages; timestamps, expiration windows, and nonces/timeouts ensure a captured message cannot be reused later.',
    ww: {
      B: 'Fences are physical perimeter controls, irrelevant to message replay.',
      C: 'Fire suppression is a facility control.',
      D: 'CPU speed has no effect on replay defense.',
    },
    er: 'Maps anti-replay measures (timestamps/nonces) to replay attacks.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Side-channel / timing', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Cryptanalytic Attacks > Side Channel Attack',
    q: 'An attacker measures the exact time and power a smart card uses during cryptographic operations to infer the secret key, without attacking the algorithm mathematically. This is a:',
    o: ['Side-channel attack (including timing analysis)', 'Chosen-ciphertext attack', 'Brute-force attack', 'Man-in-the-middle attack'],
    a: 'A',
    wc: 'Side-channel attacks exploit physical operational characteristics (timing, power consumption, emissions) rather than the math of the algorithm; timing analysis is one variant.',
    ww: {
      B: 'A chosen-ciphertext attack analyzes selected ciphertext and its decryption, not physical characteristics.',
      C: 'Brute force tries all keys mathematically.',
      D: 'A man-in-the-middle intercepts communications between parties.',
    },
    er: 'Tests recognition of side-channel/timing attacks.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Work factor', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Cryptanalytic Attacks > Cryptanalytic Attacks - Part 3',
    q: 'In cryptanalysis, "work factor" refers to:',
    o: [
      'The time, effort, and resources required to break a cryptosystem',
      'The number of employees who manage the system',
      'The physical weight of the cryptographic hardware',
      'The humidity level in the server room',
    ],
    a: 'A',
    wc: 'Work factor measures the effort/time/resources needed to defeat a cryptosystem, helping assess whether an attack is feasible.',
    ww: {
      B: 'Staff count is unrelated to work factor.',
      C: 'Physical weight is irrelevant.',
      D: 'Humidity is an environmental control concern.',
    },
    er: 'Recall of the work-factor concept.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Attack-to-description mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 3 > Cryptanalytic Attacks > Summary of Attacks',
    p: ['Brute force', 'Birthday attack', 'Side-channel attack', 'Replay attack'],
    q: 'Match each cryptanalytic attack (1-4) to its description (A-D).',
    o: [
      'Finds two inputs producing the same hash (collision)',
      'Tries all possible keys until one works',
      'Reuses a captured valid message to gain access',
      'Exploits physical characteristics such as timing or power use',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Brute force → tries all keys (B); Birthday → hash collision (A); Side-channel → physical characteristics (D); Replay → reuses captured message (C).',
    ww: {},
    er: 'Tests mapping of cryptanalytic attacks to their mechanisms.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Hash-based attacks', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Cryptanalytic Attacks > Hash-Based Attacks',
    q: 'Which TWO attacks specifically target password HASHES? (Select TWO.)',
    o: ['Rainbow table attack', 'Pass the hash', 'CPTED bypass', 'Brownout exploitation'],
    a: ['A', 'B'],
    wc: 'Rainbow table attacks and pass-the-hash both target password hashes (matching precomputed hashes, and reusing stolen hashes respectively).',
    ww: {
      C: 'CPTED is a physical site-design strategy, not a hash attack.',
      D: 'A brownout is a power anomaly, not a hash attack.',
    },
    er: 'Identifies hash-targeting attacks.',
  },
  {
    t: 'Cryptanalytic Attacks', s: 'Ciphertext attacks', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Cryptanalytic Attacks > Cryptanalytic Attacks - Part 2',
    q: 'Which TWO techniques are associated with analyzing ciphertext to break encryption? (Select TWO.)',
    o: ['Frequency analysis', 'Related-key attack', 'Mantrap installation', 'Generator maintenance'],
    a: ['A', 'B'],
    wc: 'Frequency analysis (identifying repeating patterns) and related-key attacks (comparing ciphertexts under related keys) are ciphertext-focused cryptanalytic techniques.',
    ww: {
      C: 'A mantrap is a physical access control.',
      D: 'Generator maintenance is a power-availability practice.',
    },
    er: 'Separates ciphertext cryptanalysis from physical controls.',
  },
  // ---- Physical / site & facility security ----
  {
    t: 'Physical Security', s: 'First line of defense', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Physical Security',
    q: 'Physical security is often described as the ________ in protecting sensitive data, systems, and personnel.',
    o: ['First line of defense', 'Last resort only', 'Least important control', 'Same thing as encryption'],
    a: 'A',
    wc: 'Physical security is the first line of defense, protecting facilities, systems, and people before logical controls are even reached.',
    ww: {
      B: 'It is a primary, front-line defense, not merely a last resort.',
      C: 'It is foundational, not least important.',
      D: 'Encryption is a logical control; physical security is distinct.',
    },
    er: 'Recall of physical security as the first line of defense.',
  },
  {
    t: 'Physical Security', s: 'CPTED', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Crime Prevention Through Environmental Design (CPTED)',
    q: 'Crime Prevention Through Environmental Design (CPTED) focuses on:',
    o: [
      'Designing the physical environment to influence behavior and deter crime',
      'Encrypting data at rest on servers',
      'Generating cryptographic key pairs',
      'Defining cloud shared-responsibility boundaries',
    ],
    a: 'A',
    wc: 'CPTED uses environmental design (natural access control, surveillance, and territorial reinforcement) to influence behavior and deter crime.',
    ww: {
      B: 'Encryption is a logical control, not CPTED.',
      C: 'Key generation is a cryptographic function.',
      D: 'Shared responsibility is a cloud concept.',
    },
    er: 'Recall of CPTED\'s purpose.',
  },
  {
    t: 'Physical Security', s: 'CPTED elements', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Physical Security > Crime Prevention Through Environmental Design (CPTED)',
    q: 'Which TWO are key elements of CPTED? (Select TWO.)',
    o: ['Natural surveillance', 'Natural access control', 'Pre-action sprinkler systems', 'Rainbow tables'],
    a: ['A', 'B'],
    wc: 'CPTED elements are natural access control, natural surveillance, and natural territorial reinforcement.',
    ww: {
      C: 'Pre-action sprinklers are a fire suppression system, not a CPTED element.',
      D: 'Rainbow tables are a cryptanalytic attack technique.',
    },
    er: 'Identifies genuine CPTED elements.',
  },
  {
    t: 'Physical Security', s: 'Natural surveillance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Crime Prevention Through Environmental Design (CPTED)',
    q: 'Designing a parking lot with clear sightlines and good lighting so that activity is easily observed is an example of which CPTED element?',
    o: ['Natural surveillance', 'Natural access control', 'Natural territorial reinforcement', 'Mantrap deployment'],
    a: 'A',
    wc: 'Natural surveillance designs spaces (lighting, sightlines) so legitimate users can readily observe activity, deterring crime.',
    ww: {
      B: 'Natural access control guides movement via design (paths, entrances).',
      C: 'Natural territorial reinforcement uses design to express ownership of space.',
      D: 'A mantrap is a specific physical access control device, not a CPTED element.',
    },
    er: 'Maps sightlines/lighting to natural surveillance.',
  },
  {
    t: 'Physical Security', s: 'Fencing heights', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Types of Physical Security Controls',
    q: 'To deter a DETERMINED intruder, the guide recommends fencing of approximately:',
    o: ['8+ feet topped with barbed wire', '3-4 feet', '1 foot decorative edging', 'No fence at all'],
    a: 'A',
    wc: 'Fencing of 8+ feet with barbed wire is intended to deter determined intruders; 3-4 feet only deters casual trespassers.',
    ww: {
      B: '3-4 feet deters only casual intruders.',
      C: '1 foot edging provides no meaningful deterrence.',
      D: 'No fence provides no perimeter deterrence.',
    },
    er: 'Tests fence-height deterrence guidance.',
  },
  {
    t: 'Physical Security', s: 'Mantrap', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Physical Security > Types of Physical Security Controls',
    q: 'A data center wants to prevent an unauthorized person from slipping in behind an authorized employee (tailgating). Which control DIRECTLY addresses this?',
    o: ['A mantrap (double-door interlock allowing one person at a time)', 'A taller perimeter fence', 'A wet-pipe sprinkler', 'A backup generator'],
    a: 'A',
    wc: 'A mantrap uses interlocking doors that admit one person at a time, directly preventing tailgating/piggybacking into secure areas.',
    ww: {
      B: 'A fence addresses perimeter intrusion, not tailgating at a door.',
      C: 'A sprinkler is fire suppression.',
      D: 'A generator provides backup power.',
    },
    er: 'Maps anti-tailgating at entry to a mantrap.',
  },
  {
    t: 'Physical Security', s: 'Bollards', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Detection',
    q: 'Sturdy posts installed in front of a building entrance to stop a vehicle from ramming into it are called:',
    o: ['Bollards', 'Turnstiles', 'Mantraps', 'PTZ cameras'],
    a: 'A',
    wc: 'Bollards are posts/barriers that prevent vehicles from ramming into a structure or pedestrian area.',
    ww: {
      B: 'Turnstiles control pedestrian flow, not vehicle ramming.',
      C: 'A mantrap prevents tailgating at a door.',
      D: 'PTZ cameras are surveillance devices.',
    },
    er: 'Recall of bollards as anti-vehicle barriers.',
  },
  {
    t: 'Physical Security', s: 'Facility control categories', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Physical Security > Types of Facility Security Controls',
    q: 'Which TWO are categories of facility security controls described in the guide\'s layered (defense-in-depth) approach? (Select TWO.)',
    o: ['Deterrence', 'Delay', 'Kerberoasting', 'Brute force'],
    a: ['A', 'B'],
    wc: 'Facility controls follow a layered model of deterrence, denial, detection, delay, and response; deterrence and delay are two of these categories.',
    ww: {
      C: 'Kerberoasting is a cryptanalytic credential attack.',
      D: 'Brute force is a cryptanalytic attack.',
    },
    er: 'Identifies genuine facility control categories.',
  },
  {
    t: 'Physical Security', s: 'Detection sensors', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Detection',
    q: 'A Passive Infrared (PIR) sensor detects intruders by sensing:',
    o: ['Changes in infrared (heat) energy from a moving body', 'Radio frequency interference from lights', 'Power voltage fluctuations', 'Hash collisions'],
    a: 'A',
    wc: 'A PIR sensor detects the infrared (heat) energy changes caused by a moving person, a common motion-detection method.',
    ww: {
      B: 'RFI relates to electrical noise, not PIR motion detection.',
      C: 'Voltage fluctuations are power anomalies, not PIR triggers.',
      D: 'Hash collisions are a cryptographic concept.',
    },
    er: 'Recall of PIR (heat-based) detection.',
  },
  {
    t: 'Physical Security', s: 'Data center tiers', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Facility Power Considerations',
    q: 'Among the four data center tiers, which provides the HIGHEST uptime and redundancy?',
    o: ['Tier 4', 'Tier 1', 'Tier 2', 'Tier 0'],
    a: 'A',
    wc: 'Data center Tier 4 provides the highest level of uptime and redundancy; Tier 1 is the lowest.',
    ww: {
      B: 'Tier 1 has the lowest uptime/redundancy.',
      C: 'Tier 2 is below Tier 3 and Tier 4.',
      D: '"Tier 0" is not a data center tier.',
    },
    er: 'Recall of Tier 4 as highest availability.',
  },
  {
    t: 'Physical Security', s: 'Environmental humidity', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > HVAC Considerations',
    q: 'Server room humidity is generally kept around 50% because excessively LOW humidity can cause:',
    o: ['Static electricity (electrostatic discharge)', 'Metal corrosion', 'Power surges', 'Hash collisions'],
    a: 'A',
    wc: 'Low humidity increases static electricity (ESD risk), while high humidity causes condensation and metal corrosion—so ~50% is targeted.',
    ww: {
      B: 'Corrosion results from HIGH humidity, not low.',
      C: 'Power surges are an electrical anomaly, not a humidity effect.',
      D: 'Hash collisions are a cryptographic concept.',
    },
    er: 'Tests low-humidity (static) vs high-humidity (corrosion) effects.',
  },
  {
    t: 'Physical Security', s: 'Power anomalies', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Power Issues',
    q: 'An EXTENDED period of low voltage (not a complete outage) is called a:',
    o: ['Brownout', 'Sag', 'Blackout', 'Spike'],
    a: 'A',
    wc: 'A brownout is an extended period of low voltage; a sag is a temporary (brief) low voltage.',
    ww: {
      B: 'A sag is a temporary (short) low voltage, not extended.',
      C: 'A blackout is a complete power loss.',
      D: 'A spike is a temporary high voltage.',
    },
    er: 'Distinguishes brownout (extended low) from sag (temporary low).',
  },
  {
    t: 'Physical Security', s: 'Power anomalies', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Power Issues',
    q: 'A momentary (very brief) increase in voltage is a spike, whereas an EXTENDED period of high voltage is a:',
    o: ['Surge', 'Sag', 'Brownout', 'Fault'],
    a: 'A',
    wc: 'A surge is an extended period of high voltage; a spike is a temporary (momentary) high voltage.',
    ww: {
      B: 'A sag is a temporary low voltage.',
      C: 'A brownout is an extended low voltage.',
      D: 'A fault is a temporary power loss.',
    },
    er: 'Distinguishes surge (extended high) from spike (temporary high).',
  },
  {
    t: 'Physical Security', s: 'Power anomalies', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Physical Security > Power Issues',
    q: 'Which TWO terms describe a COMPLETE or temporary LOSS of power (rather than a voltage level change)? (Select TWO.)',
    o: ['Blackout (complete loss)', 'Fault (temporary loss)', 'Surge (extended high voltage)', 'Brownout (extended low voltage)'],
    a: ['A', 'B'],
    wc: 'A blackout is a complete power loss and a fault is a temporary power loss; surge and brownout are voltage-level anomalies, not losses.',
    ww: {
      C: 'A surge is extended HIGH voltage, not a loss.',
      D: 'A brownout is extended LOW voltage, not a complete loss.',
    },
    er: 'Separates power-loss terms from voltage-level anomalies.',
  },
  {
    t: 'Physical Security', s: 'Fire triangle', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Fire Triangle Components',
    q: 'The fire triangle consists of heat, fuel, and:',
    o: ['Oxygen', 'Water', 'Humidity', 'Voltage'],
    a: 'A',
    wc: 'The fire triangle is oxygen, heat, and fuel; removing any one component disrupts the fire.',
    ww: {
      B: 'Water is a suppression agent, not a fire-triangle component.',
      C: 'Humidity is an environmental factor, not a triangle component.',
      D: 'Voltage is a power concept, not part of the fire triangle.',
    },
    er: 'Recall of the fire triangle components.',
  },
  {
    t: 'Physical Security', s: 'Fire class C', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Fire Extinguisher Classes and Materials',
    q: 'A fire breaks out in energized electrical equipment (Class C). Which suppression agent is appropriate, and which must be AVOIDED?',
    o: [
      'Use carbon dioxide or a halon substitute; avoid water',
      'Use water; avoid carbon dioxide',
      'Use dry powder only; avoid all gases',
      'Use soda acid; avoid halon substitutes',
    ],
    a: 'A',
    wc: 'Class C (electrical) fires require non-conductive agents like carbon dioxide or a halon substitute; water is conductive and dangerous on energized equipment.',
    ww: {
      B: 'Water is conductive and hazardous on electrical fires—this is reversed.',
      C: 'Dry powder is for Class D (metal) fires, not the recommended Class C agent.',
      D: 'Soda acid (water-based) is for Class A, not energized electrical fires.',
    },
    er: 'Tests correct agent selection for electrical (Class C) fires.',
  },
  {
    t: 'Physical Security', s: 'Fire class D', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Fire Extinguisher Classes and Materials',
    q: 'Which extinguishing agent is appropriate for a Class D (combustible metals such as magnesium or lithium) fire?',
    o: ['Dry powder', 'Water', 'Carbon dioxide', 'Soda acid'],
    a: 'A',
    wc: 'Class D combustible-metal fires require dry powder agents; water and common agents can react dangerously with burning metals.',
    ww: {
      B: 'Water can react violently with burning metals.',
      C: 'CO2 is for Class B/C, not Class D metals.',
      D: 'Soda acid is a water-based Class A agent.',
    },
    er: 'Maps metal fires to dry powder.',
  },
  {
    t: 'Physical Security', s: 'Pre-action suppression', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Physical Security > Facility-Level Fire Suppression Systems',
    q: 'A data center wants a sprinkler system that minimizes the risk of accidental water discharge onto equipment by requiring two separate triggers before water is released. Which system fits BEST?',
    o: ['Pre-action system', 'Deluge system', 'Wet pipe system', 'Open-head system'],
    a: 'A',
    wc: 'A pre-action system combines dry and wet pipe behavior and requires two activation conditions (e.g., heat/smoke detection plus sprinkler activation), reducing accidental discharge—suited to computer rooms/data centers.',
    ww: {
      B: 'A deluge system releases large volumes quickly and is not recommended for electronics.',
      C: 'A wet-pipe system is always water-filled, raising accidental-discharge risk.',
      D: 'An open-head (wet) system does not provide the dual-trigger protection.',
    },
    er: 'Maps dual-trigger, low-accidental-discharge needs to pre-action systems.',
  },
  {
    t: 'Physical Security', s: 'Wet vs dry pipe', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Facility-Level Fire Suppression Systems',
    q: 'A dry-pipe fire suppression system differs from a wet-pipe system in that the dry-pipe system:',
    o: [
      'Holds compressed air in the pipes and fills with water only upon activation',
      'Is always filled with water ready to discharge immediately',
      'Uses only carbon dioxide gas',
      'Requires no water source at all',
    ],
    a: 'A',
    wc: 'A dry-pipe system keeps compressed air in the pipes and admits water only when activated, reducing the risk of leaks/freezing compared to an always-charged wet-pipe system.',
    ww: {
      B: 'Being always water-filled describes a wet-pipe (closed-head) system.',
      C: 'Dry-pipe systems still use water, not only CO2.',
      D: 'A water source is still required; it just fills on activation.',
    },
    er: 'Distinguishes dry-pipe (air, fills on activation) from wet-pipe.',
  },
  {
    t: 'Physical Security', s: 'Fire detection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Fire Detection Methods',
    q: 'A photoelectric smoke detector triggers based on:',
    o: [
      'Disruption of a light source/beam by smoke particles',
      'Disruption of an electrical plate by ionized particles from radioactive material',
      'A rapid rate of temperature increase',
      'A fixed temperature threshold being reached',
    ],
    a: 'A',
    wc: 'A photoelectric smoke detector triggers when smoke disrupts a light source/beam; ionization detectors instead use radioactive material affecting an electrical plate.',
    ww: {
      B: 'That describes an ionization smoke detector.',
      C: 'That describes a rate-of-rise heat detector.',
      D: 'That describes a fixed-temperature detector.',
    },
    er: 'Distinguishes photoelectric from ionization smoke detection.',
  },
  {
    t: 'Physical Security', s: 'Fire safety priority', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Physical Security > Fire Prevention, Detection, and Suppression',
    q: 'In fire safety planning, the TOP priority is always to:',
    o: [
      'Protect human life by enabling safe exit from the facility',
      'Protect system assets and equipment above all else',
      'Preserve the building\'s aesthetic appearance',
      'Avoid triggering any alarms to prevent panic',
    ],
    a: 'A',
    wc: 'Protecting human life (safe egress) is the top fire-safety priority; protecting assets is secondary.',
    ww: {
      B: 'Asset protection is secondary to life safety.',
      C: 'Aesthetics are irrelevant to fire safety priorities.',
      D: 'Alarms are essential for safe evacuation, not to be suppressed.',
    },
    er: 'Reinforces life safety as the top fire priority.',
  },
  // ---- Information system lifecycle (3.10) ----
  {
    t: 'Information System Lifecycle', s: 'Security integration', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > System Security Capabilities',
    q: 'Managing the information system lifecycle securely means that security should be:',
    o: [
      'Integrated from initiation through disposal, at every phase',
      'Considered only after the system goes live',
      'Added only when an auditor requests it',
      'Limited to the disposal phase',
    ],
    a: 'A',
    wc: 'Secure lifecycle management integrates security at every phase—from initiation/requirements through development, operations, and secure disposal.',
    ww: {
      B: 'Bolting on security after go-live is reactive and leaves gaps.',
      C: 'Security is proactive, not auditor-triggered.',
      D: 'Security spans the whole lifecycle, not only disposal.',
    },
    er: 'Reinforces full-lifecycle security integration.',
  },
  {
    t: 'Information System Lifecycle', s: 'Secure disposal', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 3 > Secure Design Principles > System Security Capabilities',
    q: 'A server holding sensitive data is being retired at the end of the system lifecycle. Which action is MOST important during this disposal phase?',
    o: [
      'Securely sanitize/destroy the data so it cannot be recovered before disposing of the hardware',
      'Leave the data intact in case it is needed later',
      'Donate the drives immediately without any wiping',
      'Publish the data publicly to clear the storage',
    ],
    a: 'A',
    wc: 'Secure disposal requires sanitizing or destroying data so it cannot be recovered, then disposing of hardware appropriately.',
    ww: {
      B: 'Leaving sensitive data intact on retired hardware risks disclosure.',
      C: 'Donating un-wiped drives exposes sensitive data (remanence).',
      D: 'Publishing the data is a severe confidentiality breach.',
    },
    er: 'Maps end-of-life data sanitization to secure disposal.',
  },
  {
    t: 'Information System Lifecycle', s: 'Verification and validation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Secure Design Principles > Objective 3.5',
    q: 'During the verification and validation stage of the system lifecycle, the goal is to:',
    o: [
      'Confirm through testing/assessment that the system meets its technical, security, and user requirements',
      'Securely destroy all of the system\'s data',
      'Identify and engage stakeholders for the first time',
      'Negotiate the hardware procurement contract',
    ],
    a: 'A',
    wc: 'Verification and validation use testing, code reviews, and security assessments to confirm the system meets all requirements before full-scale implementation.',
    ww: {
      B: 'Data destruction occurs at disposal/retirement.',
      C: 'Stakeholder engagement is part of initiation.',
      D: 'Procurement negotiation is part of acquisition.',
    },
    er: 'Maps requirement-confirmation testing to verification and validation.',
  },
];
