// Domain 3 — Part 3: Virtualization & hypervisors, containerization, cloud
// deployment & service models, shared responsibility, VPC, serverless,
// cryptographic solutions & key management (objective 3.6).
module.exports = [
  // ---- Virtualization ----
  {
    t: 'Virtualization', s: 'Type 1 vs Type 2 hypervisor', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Types of Hypervisors',
    q: 'A Type 1 hypervisor differs from a Type 2 hypervisor in that a Type 1:',
    o: [
      'Runs directly on the bare-metal hardware without an underlying host OS',
      'Always runs as an application on top of a host operating system',
      'Cannot host more than one virtual machine',
      'Is only used on mobile phones',
    ],
    a: 'A',
    wc: 'A Type 1 (bare-metal) hypervisor runs directly on hardware, typically used for production; a Type 2 (hosted) hypervisor runs as software on a host OS.',
    ww: {
      B: 'Running on a host OS describes a Type 2 hypervisor.',
      C: 'Type 1 hypervisors host many VMs.',
      D: 'Type 1 hypervisors run on servers, not specifically phones.',
    },
    er: 'Distinguishes bare-metal (Type 1) from hosted (Type 2) hypervisors.',
  },
  {
    t: 'Virtualization', s: 'Hypervisor use cases', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Use Cases for Hypervisor Types',
    q: 'A developer wants to run a few test VMs on their Windows laptop using VMware Workstation. Which hypervisor type is this?',
    o: ['Type 2 (hosted)', 'Type 1 (bare-metal)', 'A container engine', 'A serverless function'],
    a: 'A',
    wc: 'VMware Workstation/VirtualBox run on top of a host OS, making them Type 2 (hosted) hypervisors—suited to desktop/testing use.',
    ww: {
      B: 'Type 1 runs directly on hardware (e.g., ESXi), typically for production servers.',
      C: 'A container engine shares the host kernel rather than virtualizing full machines.',
      D: 'Serverless runs functions in a managed cloud environment, not a desktop VM.',
    },
    er: 'Maps a desktop hosted VM tool to Type 2.',
  },
  {
    t: 'Virtualization', s: 'VM escape', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Drawbacks and Risks',
    q: 'An attacker exploits a hypervisor vulnerability to break out of a guest virtual machine and gain control of the underlying host and other VMs. This attack is known as:',
    o: ['VM escape', 'Pass the hash', 'Tailgating', 'A birthday attack'],
    a: 'A',
    wc: 'VM escape is breaking out of a guest VM to reach the hypervisor/host, potentially compromising other VMs—a key virtualization risk.',
    ww: {
      B: 'Pass the hash reuses stolen password hashes for authentication.',
      C: 'Tailgating is a physical access tactic.',
      D: 'A birthday attack exploits hash collisions.',
    },
    er: 'Tests recognition of the VM escape risk.',
  },
  // ---- Containers ----
  {
    t: 'Containerization', s: 'Containers vs VMs', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Containers vs. Virtual Machines',
    q: 'A key security-relevant difference between containers and virtual machines is that containers:',
    o: [
      'Share the host operating system kernel, whereas each VM runs its own full OS',
      'Each require a separate hypervisor per container',
      'Cannot run application code',
      'Are always more isolated than virtual machines',
    ],
    a: 'A',
    wc: 'Containers share the host OS kernel (lightweight), while VMs each run a full guest OS via a hypervisor; the shared kernel is a notable container risk consideration.',
    ww: {
      B: 'Containers use a container engine and share the kernel, not a hypervisor each.',
      C: 'Containers run application code.',
      D: 'Containers are generally LESS isolated than VMs due to the shared kernel.',
    },
    er: 'Tests the shared-kernel distinction and its security implication.',
  },
  {
    t: 'Containerization', s: 'Container risks', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Containerization Risks',
    q: 'Which TWO are recognized container security risks? (Select TWO.)',
    o: [
      'Vulnerabilities inherited from the host OS or container engine',
      'Weak isolation/authentication between inter-container communications',
      'The impossibility of ever updating a container image',
      'Containers eliminating the need for any access control',
    ],
    a: ['A', 'B'],
    wc: 'Containers can inherit host/engine vulnerabilities and face risks from inter-container communication and identification/authentication weaknesses.',
    ww: {
      C: 'Container images can and should be rebuilt/updated; the risk is unpatched images, not inability to update.',
      D: 'Containers still require access control.',
    },
    er: 'Identifies genuine container risks.',
  },
  {
    t: 'Containerization', s: 'Orchestration', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Containerization',
    q: 'Which tool is primarily used for container ORCHESTRATION (managing many containers across hosts)?',
    o: ['Kubernetes', 'Degausser', 'TPM', 'CPTED'],
    a: 'A',
    wc: 'Kubernetes is a container orchestration platform for deploying and managing containers at scale (Docker is the container platform).',
    ww: {
      B: 'A degausser destroys data on magnetic media.',
      C: 'A TPM is a cryptographic hardware chip.',
      D: 'CPTED is a physical site-design strategy.',
    },
    er: 'Recall of Kubernetes as orchestration.',
  },
  // ---- Cloud deployment models ----
  {
    t: 'Cloud Deployment Models', s: 'Community cloud', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cloud Deployment Models',
    q: 'Several hospitals jointly use a shared cloud environment built for their common compliance and security needs. This is an example of a:',
    o: ['Community cloud', 'Public cloud', 'Private cloud', 'Hybrid cloud'],
    a: 'A',
    wc: 'A community cloud is shared by several organizations with common concerns (e.g., compliance), pooling a tailored environment.',
    ww: {
      B: 'A public cloud is open to the general public/many unrelated tenants.',
      C: 'A private cloud is dedicated to a single organization.',
      D: 'A hybrid cloud combines two or more deployment models.',
    },
    er: 'Maps a shared-industry environment to community cloud.',
  },
  {
    t: 'Cloud Deployment Models', s: 'Hybrid cloud', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cloud Deployment Models',
    q: 'A hybrid cloud is BEST described as:',
    o: [
      'A combination of two or more distinct cloud models (e.g., private and public) that remain unique but work together',
      'A cloud used by only one organization with no external connectivity',
      'A cloud open to any member of the public',
      'An on-premises data center with no cloud at all',
    ],
    a: 'A',
    wc: 'A hybrid cloud combines two or more deployment models (e.g., private + public) that remain distinct but are bound together.',
    ww: {
      B: 'That describes a private cloud.',
      C: 'That describes a public cloud.',
      D: 'That describes purely on-premises infrastructure.',
    },
    er: 'Recall of the hybrid cloud definition.',
  },
  // ---- Cloud service models + shared responsibility ----
  {
    t: 'Cloud Service Models', s: 'IaaS responsibility', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Service Models in Cloud Computing',
    q: 'A company uses Infrastructure as a Service (IaaS). Under the shared responsibility model, the company is MOST responsible for:',
    o: [
      'The operating system, applications, and data it runs on the provided virtual infrastructure',
      'The physical security of the provider\'s data center',
      'The hypervisor that virtualizes the hardware',
      'The provider\'s underlying network cabling',
    ],
    a: 'A',
    wc: 'In IaaS, the provider supplies the virtualized infrastructure (and secures the physical/hypervisor layers), while the customer manages the OS, applications, and data.',
    ww: {
      B: 'Physical data center security is the provider\'s responsibility.',
      C: 'The hypervisor/virtualization layer is managed by the provider.',
      D: 'Provider network cabling is the provider\'s responsibility.',
    },
    er: 'Tests the IaaS customer-vs-provider responsibility split.',
  },
  {
    t: 'Cloud Service Models', s: 'SaaS responsibility', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Shared Responsibility Model',
    q: 'An organization adopts a SaaS email platform. Even though the provider manages the application and infrastructure, the customer ALWAYS retains responsibility for:',
    o: [
      'Its own data and managing user access/identities',
      'Patching the provider\'s application servers',
      'Maintaining the provider\'s physical facilities',
      'Configuring the provider\'s hypervisors',
    ],
    a: 'A',
    wc: 'Across all cloud service models, the customer remains responsible for its own data and for managing user access/identities; SaaS shifts most other responsibilities to the provider.',
    ww: {
      B: 'Patching the SaaS application servers is the provider\'s responsibility.',
      C: 'Physical facilities are the provider\'s responsibility.',
      D: 'Hypervisor configuration is the provider\'s responsibility.',
    },
    er: 'Tests that data and access management stay with the customer in SaaS.',
  },
  {
    t: 'Cloud Service Models', s: 'Service model mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Service Models in Cloud Computing',
    p: ['IaaS', 'PaaS', 'SaaS', 'SECaaS'],
    q: 'Match each cloud service model (1-4) to its description (A-D).',
    o: [
      'Provider delivers a development/runtime platform; customer manages apps and data',
      'Provider delivers virtualized infrastructure; customer manages OS, apps, and data',
      'Provider delivers security services directly from the cloud',
      'Provider delivers complete applications; customer manages mainly data and access',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'IaaS → virtualized infrastructure (B); PaaS → platform/runtime (A); SaaS → complete applications (D); SECaaS → cloud-delivered security services (C).',
    ww: {},
    er: 'Tests mapping of cloud service models to their responsibility scopes.',
  },
  {
    t: 'Cloud Service Models', s: 'SECaaS', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Service Models in Cloud Computing',
    q: 'Security as a Service (SECaaS) refers to:',
    o: [
      'Providing security services (e.g., anti-malware, IAM, monitoring) directly from the cloud',
      'A bare-metal hypervisor for production VMs',
      'A magnetic data-destruction method',
      'A physical mantrap at a building entrance',
    ],
    a: 'A',
    wc: 'SECaaS delivers security capabilities directly from the cloud as a service.',
    ww: {
      B: 'That describes a Type 1 hypervisor.',
      C: 'That describes degaussing.',
      D: 'That describes a physical access control.',
    },
    er: 'Recall of SECaaS.',
  },
  {
    t: 'Cloud Service Models', s: 'CASB in cloud', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cloud Access Security Broker (CASB)',
    q: 'In a cloud architecture, a Cloud Access Security Broker (CASB) primarily acts as:',
    o: [
      'A proxy/policy enforcement point between users and cloud services',
      'A bare-metal hypervisor',
      'A backup generator for the data center',
      'A fire suppression system',
    ],
    a: 'A',
    wc: 'A CASB functions as a proxy between users and cloud services, enforcing security policies such as DLP and threat protection.',
    ww: {
      B: 'A hypervisor virtualizes hardware; it is not a CASB.',
      C: 'A generator provides backup power.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Recall of CASB as a cloud policy enforcement proxy.',
  },
  // ---- VPC / serverless ----
  {
    t: 'Cloud Networking', s: 'Serverless risk', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Risks and Vulnerabilities in Serverless Computing',
    q: 'A team is moving many small functions to a serverless (FaaS) platform. Which security concern is MOST characteristic of serverless architectures?',
    o: [
      'An expanded attack surface with reduced control over the underlying environment',
      'The need to physically rack and patch their own servers',
      'Complete elimination of all application vulnerabilities',
      'Guaranteed immunity to misconfiguration',
    ],
    a: 'A',
    wc: 'Serverless expands the attack surface (many small functions/triggers) and reduces customer control over the environment, complicating traditional security approaches.',
    ww: {
      B: 'Serverless removes server management; there is no physical racking for the customer.',
      C: 'Application code can still contain vulnerabilities.',
      D: 'Misconfiguration remains a major serverless risk.',
    },
    er: 'Tests the characteristic serverless attack-surface/control trade-off.',
  },
  {
    t: 'Cloud Networking', s: 'Serverless mitigation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Mitigations for Serverless Computing Security',
    q: 'Which is a recommended mitigation for serverless security risk?',
    o: [
      'Minimize code/microservices and limit the use of sensitive data in functions',
      'Grant each function unlimited permissions for convenience',
      'Disable all monitoring and logging',
      'Store all secrets in plaintext within the function code',
    ],
    a: 'A',
    wc: 'Mitigations include clarifying responsibility, minimizing code/microservices, limiting sensitive data use, and designing architecture for CIA.',
    ww: {
      B: 'Unlimited permissions violate least privilege and expand impact.',
      C: 'Disabling monitoring removes detection capability.',
      D: 'Plaintext secrets in code is a severe vulnerability.',
    },
    er: 'Identifies sound serverless mitigations.',
  },
  // ---- Cryptography (3.6) ----
  {
    t: 'Cryptographic Solutions', s: 'Symmetric vs asymmetric', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Symmetric Encryption',
    q: 'A primary WEAKNESS of symmetric encryption compared to asymmetric encryption is:',
    o: [
      'Secure key distribution and scalability of keys among many parties',
      'It is far too slow for bulk data encryption',
      'It cannot encrypt data at all',
      'It requires no keys whatsoever',
    ],
    a: 'A',
    wc: 'Symmetric encryption is fast but struggles with secure key distribution and scalability (the number of keys grows rapidly as parties increase).',
    ww: {
      B: 'Symmetric encryption is fast and well suited to bulk data—asymmetric is the slower one.',
      C: 'Symmetric encryption does encrypt data.',
      D: 'It requires a shared secret key.',
    },
    er: 'Tests the key-distribution/scalability weakness of symmetric crypto.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Confidentiality with asymmetric', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Asymmetric Encryption',
    q: 'Alice wants to send a confidential message to Bob using asymmetric encryption so that only Bob can read it. Alice should encrypt the message with:',
    o: [
      'Bob\'s public key (so only Bob\'s private key can decrypt it)',
      'Bob\'s private key',
      'Alice\'s private key',
      'A shared symmetric key sent in the clear',
    ],
    a: 'A',
    wc: 'For confidentiality, the sender encrypts with the recipient\'s public key; only the recipient\'s matching private key can decrypt it.',
    ww: {
      B: 'Only Bob holds his private key; Alice cannot encrypt with it, and it is not used for inbound confidentiality.',
      C: 'Encrypting with Alice\'s private key provides a signature, not confidentiality (anyone can decrypt with her public key).',
      D: 'Sending a symmetric key in the clear exposes it to interception.',
    },
    er: 'Tests using the recipient\'s public key for confidentiality.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Digital signature', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Digital Signatures',
    q: 'To create a digital signature that provides integrity, authentication, and non-repudiation, the sender signs a hash of the message with:',
    o: [
      'The sender\'s private key',
      'The recipient\'s public key',
      'A shared symmetric session key',
      'The sender\'s public key',
    ],
    a: 'A',
    wc: 'A digital signature is created by hashing the message and encrypting the hash with the sender\'s private key; anyone can verify with the sender\'s public key, providing integrity, authentication, and non-repudiation.',
    ww: {
      B: 'The recipient\'s public key is used for confidentiality, not signing.',
      C: 'A symmetric key cannot provide non-repudiation (both parties share it).',
      D: 'The sender\'s public key is used to verify, not create, the signature.',
    },
    er: 'Tests signing with the sender\'s private key.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Hashing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Hashing',
    q: 'A cryptographic hash function is primarily used to provide:',
    o: ['Integrity (detecting unauthorized changes to data)', 'Confidentiality of stored files', 'High-speed bulk encryption', 'Physical access control'],
    a: 'A',
    wc: 'A hash function produces a fixed-length one-way digest used to verify integrity—any change to the input changes the hash.',
    ww: {
      B: 'Hashing is one-way and does not provide confidentiality (it is not reversible encryption).',
      C: 'Hashing is not bulk encryption.',
      D: 'Physical access control is unrelated to hashing.',
    },
    er: 'Maps hashing to integrity.',
  },
  {
    t: 'Cryptographic Solutions', s: 'HMAC', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Hashed Message Authentication Code (HMAC)',
    q: 'A Hashed Message Authentication Code (HMAC) combines a hash with a secret key to provide:',
    o: [
      'Integrity and authenticity of a message',
      'Non-repudiation through a public/private key pair',
      'Confidentiality of the entire message body',
      'Physical destruction of media',
    ],
    a: 'A',
    wc: 'HMAC uses a shared secret key with a hash to provide message integrity and authenticity; because the key is shared, it does not provide non-repudiation.',
    ww: {
      B: 'Non-repudiation requires asymmetric keys (a digital signature), not a shared HMAC key.',
      C: 'HMAC authenticates/verifies integrity but does not encrypt the message for confidentiality.',
      D: 'Media destruction is unrelated to HMAC.',
    },
    er: 'Distinguishes HMAC (integrity+authenticity) from digital signatures (add non-repudiation).',
  },
  {
    t: 'Key Management', s: 'Key escrow', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cryptographic Key Management',
    q: 'Storing a copy of cryptographic keys with a trusted third party so they can be recovered if needed is called:',
    o: ['Key escrow', 'Key rotation', 'Split knowledge', 'Key revocation'],
    a: 'A',
    wc: 'Key escrow places a copy of keys with a trusted third party for recovery (e.g., for lawful access or business continuity).',
    ww: {
      B: 'Key rotation periodically replaces keys with new ones.',
      C: 'Split knowledge divides key components among multiple people.',
      D: 'Key revocation invalidates a key that should no longer be used.',
    },
    er: 'Recall of key escrow.',
  },
  {
    t: 'Key Management', s: 'Split knowledge', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cryptographic Key Management',
    q: 'A bank requires that no single administrator can reconstruct the master key alone; two of three custodians must combine their key parts. This control is:',
    o: ['Split knowledge (with dual control)', 'Key escrow', 'Key rotation', 'Open design'],
    a: 'A',
    wc: 'Split knowledge divides the key (or its components) among multiple parties so a threshold must cooperate to use/reconstruct it, enforcing dual control.',
    ww: {
      B: 'Key escrow stores a recoverable copy with a third party, not a split-component scheme.',
      C: 'Key rotation replaces keys periodically.',
      D: 'Open design is a secure-design principle, not a key-management control.',
    },
    er: 'Maps M-of-N key reconstruction to split knowledge/dual control.',
  },
  {
    t: 'Key Management', s: 'Key rotation', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cryptographic Key Management',
    q: 'Periodically replacing cryptographic keys with new ones to limit the impact of a compromised key is:',
    o: ['Key rotation', 'Key escrow', 'Split knowledge', 'Frequency analysis'],
    a: 'A',
    wc: 'Key rotation periodically replaces keys, reducing the window and data exposed if a key is compromised.',
    ww: {
      B: 'Key escrow stores recoverable copies of keys.',
      C: 'Split knowledge divides key components among parties.',
      D: 'Frequency analysis is a cryptanalytic technique.',
    },
    er: 'Recall of key rotation.',
  },
  {
    t: 'Cryptographic Solutions', s: 'PKI', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Public Key Infrastructure (PKI)',
    q: 'In Public Key Infrastructure (PKI), which entity issues and digitally signs digital certificates that bind a public key to an identity?',
    o: ['Certificate Authority (CA)', 'Policy Enforcement Point (PEP)', 'Hardware Security Module owner', 'Data steward'],
    a: 'A',
    wc: 'A Certificate Authority (CA) issues and signs digital certificates binding a public key to a verified identity.',
    ww: {
      B: 'A PEP is a Zero Trust enforcement component.',
      C: 'An HSM stores/protects keys but is not the certificate-issuing authority.',
      D: 'A data steward is a data SME role, not a PKI authority.',
    },
    er: 'Recall of the CA\'s role in PKI.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Cryptographic life cycle', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Cryptographic Life Cycle Steps',
    q: 'Order the following stages of the cryptographic key life cycle from first to last. (Provide the option labels in order.)',
    o: ['Key generation', 'Key distribution/storage', 'Key use (rotation)', 'Key revocation/destruction'],
    a: 'A,B,C,D',
    wc: 'Keys are generated, then distributed/stored securely, used (and rotated) during their validity, and finally revoked/destroyed at end of life.',
    ww: {},
    er: 'Tests the ordering of the cryptographic key life cycle.',
  },
  {
    t: 'Cryptographic Solutions', s: 'PKI certificate process', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 3 > Virtualization and Cloud Computing > PKI Certificate Creation Process',
    q: 'Order the steps by which a subject obtains and uses a PKI certificate. (Provide the option labels in order.)',
    o: [
      'Subject generates a key pair and submits a certificate signing request',
      'Registration Authority verifies the subject\'s identity',
      'Certificate Authority issues and signs the digital certificate',
      'Relying parties validate the certificate (e.g., via CRL/OCSP) before trusting it',
    ],
    a: 'A,B,C,D',
    wc: 'The subject generates keys and submits a CSR, the RA verifies identity, the CA issues/signs the certificate, and relying parties validate it (checking revocation) before trusting it.',
    ww: {},
    er: 'Tests the ordered PKI certificate issuance/validation flow.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Quantum impact', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Quantum Cryptography',
    q: 'The PRIMARY concern about large-scale quantum computers for current cryptography is that they could:',
    o: [
      'Break widely used asymmetric algorithms (e.g., RSA) by efficiently solving their underlying math problems',
      'Make all hashing instantly reversible with no effort',
      'Eliminate the need for any encryption keys',
      'Physically degauss storage media remotely',
    ],
    a: 'A',
    wc: 'Quantum computers threaten current asymmetric algorithms (such as RSA/ECC) by efficiently solving the hard math problems they rely on, motivating post-quantum cryptography.',
    ww: {
      B: 'Quantum computing weakens some symmetric/hash strength but does not make hashing trivially reversible.',
      C: 'Encryption still requires keys; quantum changes which algorithms are safe.',
      D: 'Quantum computing does not remotely degauss media.',
    },
    er: 'Tests the quantum threat to asymmetric cryptography.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Symmetric algorithms', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Symmetric Encryption',
    q: 'Which TWO of the following are SYMMETRIC encryption algorithms/standards? (Select TWO.)',
    o: ['AES', '3DES', 'RSA', 'ECC'],
    a: ['A', 'B'],
    wc: 'AES and 3DES are symmetric ciphers that use the same key to encrypt and decrypt.',
    ww: {
      C: 'RSA is an asymmetric algorithm.',
      D: 'ECC (Elliptic Curve Cryptography) is asymmetric.',
    },
    er: 'Distinguishes symmetric ciphers from asymmetric algorithms.',
  },
  {
    t: 'Key Management', s: 'Key management risks', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 3 > Cryptanalytic Attacks > Key Management Risks',
    q: 'Which TWO are genuine key-management risks that weaken a cryptosystem? (Select TWO.)',
    o: [
      'Weak key strength (e.g., short keys)',
      'Insecure key storage or usage',
      'Rotating keys on a defined schedule',
      'Revoking keys that are known to be compromised',
    ],
    a: ['A', 'B'],
    wc: 'Weak/short keys and insecure key storage/usage are key-management risks; rotation and revocation of compromised keys are good practices, not risks.',
    ww: {
      C: 'Scheduled key rotation is a protective practice, not a risk.',
      D: 'Revoking compromised keys is a protective practice, not a risk.',
    },
    er: 'Separates key-management weaknesses from sound practices.',
  },
  {
    t: 'Cryptographic Solutions', s: 'Non-repudiation limitation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 3 > Virtualization and Cloud Computing > Symmetric Encryption',
    q: 'Why does symmetric encryption alone NOT provide non-repudiation?',
    o: [
      'Both parties share the same secret key, so neither can prove the other was the sole originator',
      'Symmetric keys are too long to manage',
      'Symmetric encryption cannot protect confidentiality',
      'Symmetric algorithms are always broken by quantum computers',
    ],
    a: 'A',
    wc: 'Because the same secret key is shared, either party could have produced a message, so symmetric encryption cannot prove sole origin (no non-repudiation); digital signatures (asymmetric) are needed.',
    ww: {
      B: 'Key length is not the reason non-repudiation fails.',
      C: 'Symmetric encryption does protect confidentiality.',
      D: 'Quantum impact is separate from the non-repudiation limitation.',
    },
    er: 'Explains why shared keys preclude non-repudiation.',
  },
];
