// Domain 2 — Part 3: Data lifecycle, data states (rest/transit/use),
// information system lifecycle (3.10), data/asset retention (2.5),
// EOL/EOS, chain of custody.
module.exports = [
  // ---- Data states ----
  {
    t: 'Data States', s: 'Three states', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Understanding Data States',
    q: 'The guide describes data as existing in three states. Which set correctly lists them?',
    o: ['In use, in transit, and at rest', 'Hot, warm, and cold', 'Public, internal, and secret', 'Create, read, and delete'],
    a: 'A',
    wc: 'Data exists in three states—in use, in transit, and at rest—each requiring appropriate protection.',
    ww: {
      B: 'Hot/warm/cold describe site recovery strategies, not data states.',
      C: 'Public/internal/secret are classification levels, not data states.',
      D: 'Create/read/delete are operations, not data states.',
    },
    er: 'Recall of the three data states.',
  },
  {
    t: 'Data States', s: 'Data at rest', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data at Rest',
    q: 'Which protection mechanisms are MOST associated with securing data at rest?',
    o: [
      'Full-disk encryption, Trusted Platform Modules (TPM), and secure storage',
      'TLS certificates and secure routing',
      'Memory-only authentication during active processing',
      'Network egress monitoring on the perimeter',
    ],
    a: 'A',
    wc: 'Data at rest is protected with full-disk encryption, TPMs, and secure storage environments because it is a static target.',
    ww: {
      B: 'TLS and secure routing protect data in transit.',
      C: 'In-memory protections apply to data in use.',
      D: 'Egress monitoring targets data leaving the network (in transit/exfiltration), not data at rest.',
    },
    er: 'Maps at-rest protections to encryption/TPM/secure storage.',
  },
  {
    t: 'Data States', s: 'Data in transit', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Understanding Data States',
    q: 'Data is considered MOST at risk in which state, because it is exposed to the network?',
    o: ['In transit', 'At rest', 'In use', 'Archived'],
    a: 'A',
    wc: 'Data in transit is most at risk because it is exposed to the network (wired or wireless); it is protected with encryption, secure routing, and certificates (SSL/TLS).',
    ww: {
      B: 'Data at rest is a static target but is not described as the most-at-risk state.',
      C: 'Data in use is the most volatile but is being processed locally, not exposed across the network.',
      D: 'Archived data is a form of data at rest.',
    },
    er: 'Identifies in-transit as the most network-exposed state.',
  },
  {
    t: 'Data States', s: 'Data in use', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Understanding Data States',
    q: 'Which statement best characterizes data in use?',
    o: [
      'It is the most volatile state, residing in memory or being processed, and needs authentication, authorization, and monitoring',
      'It is always encrypted and never at risk',
      'It only exists on backup tapes',
      'It is data that has been permanently destroyed',
    ],
    a: 'A',
    wc: 'Data in use is actively processed (often in memory), is the most volatile state, and requires authentication, authorization, and monitoring to protect integrity.',
    ww: {
      B: 'Data in use can be at risk during processing and is not inherently always encrypted.',
      C: 'Backup tapes hold data at rest, not data in use.',
      D: 'Destroyed data is not a live state.',
    },
    er: 'Tests the volatility and controls for data in use.',
  },
  {
    t: 'Data States', s: 'Protection by state', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Security Considerations',
    q: 'A company sends application logs from a web server to a remote analysis platform over the internet. Which protection is MOST appropriate for this data while it travels?',
    o: [
      'Encryption with mutual authentication (e.g., TLS) to protect data in motion',
      'Full-disk encryption on the destination server only',
      'A Trusted Platform Module on the source server',
      'Degaussing the source storage media',
    ],
    a: 'A',
    wc: 'Data in transit is best protected with encryption and mutual authentication (e.g., TLS) to defend confidentiality and integrity while it moves.',
    ww: {
      B: 'Disk encryption at the destination protects data at rest, not while it traverses the network.',
      C: 'A TPM protects keys/data at rest on a device, not data crossing the network.',
      D: 'Degaussing destroys data on magnetic media; it does not protect data in transit.',
    },
    er: 'Tests selecting in-transit protection for a network transfer scenario.',
  },
  // ---- Data lifecycle ----
  {
    t: 'Data Lifecycle', s: 'Lifecycle phases', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 2 > Asset Security > Managing the Data Lifecycle',
    q: 'Place the data lifecycle phases in their typical order from cradle to grave. (Provide the option labels in order.)',
    o: ['Creation', 'Storage', 'Use', 'Archiving', 'Destruction'],
    a: 'A,B,C,D,E',
    wc: 'The data lifecycle runs creation → storage → use → archiving → destruction (cradle to grave).',
    ww: {},
    er: 'Tests the order of the data lifecycle phases.',
  },
  {
    t: 'Data Lifecycle', s: 'Creation/classification', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Managing the Data Lifecycle',
    q: 'Immediately after data is created, what should occur to ensure it receives the right level of protection?',
    o: [
      'It should be classified or categorized according to its sensitivity',
      'It should be permanently destroyed',
      'It should be made public by default',
      'It should be moved straight to archive storage',
    ],
    a: 'A',
    wc: 'After creation, data must be classified/categorized by sensitivity so that appropriate protection is applied throughout its life.',
    ww: {
      B: 'Destruction is the final phase, not the step right after creation.',
      C: 'Defaulting to public would expose sensitive data.',
      D: 'Archiving applies to data no longer needed regularly, not freshly created data.',
    },
    er: 'Ties classification to the create phase of the lifecycle.',
  },
  {
    t: 'Data Lifecycle', s: 'Archiving', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Managing the Data Lifecycle',
    q: 'When data that is no longer needed regularly is moved to archive storage, the guide states that archives must still have:',
    o: [
      'Access controls and encryption applied',
      'All security controls removed to save space',
      'Public read access for convenience',
      'No retention limits whatsoever',
    ],
    a: 'A',
    wc: 'Archived data must have access controls and encryption applied; archiving can be driven by regulatory or organizational requirements.',
    ww: {
      B: 'Removing controls would expose archived sensitive data.',
      C: 'Public access to archives risks unauthorized disclosure.',
      D: 'Retention limits and policies still apply to archived data.',
    },
    er: 'Reinforces that archives remain protected.',
  },
  {
    t: 'Data Lifecycle', s: 'Data value over time', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Asset Security > Key Considerations',
    q: 'A dataset that was highly sensitive at launch becomes far less sensitive years later as the information becomes obsolete. According to the guide\'s "data value over time" consideration, the organization should:',
    o: [
      'Re-evaluate the data\'s classification and adjust protection needs as its value changes',
      'Keep the original classification permanently regardless of changes',
      'Immediately make the data public without review',
      'Delete the classification policy entirely',
    ],
    a: 'A',
    wc: 'Data value can change over time, affecting classification and protection needs; classification should be re-evaluated accordingly.',
    ww: {
      B: 'Static classification ignores legitimate changes in data value.',
      C: 'Reclassification requires review, not automatic public release.',
      D: 'The policy remains necessary to govern reclassification decisions.',
    },
    er: 'Tests reclassification as data value changes over time.',
  },
  {
    t: 'Data Lifecycle', s: 'Secure destruction', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Managing the Data Lifecycle',
    q: 'In the destruction phase of the data lifecycle, secure destruction methods are required primarily to:',
    o: [
      'Ensure no sensitive data can be recovered by unauthorized parties',
      'Increase the amount of stored data',
      'Make data publicly searchable',
      'Avoid the need to follow any regulations',
    ],
    a: 'A',
    wc: 'Secure destruction follows policy and legal/regulatory requirements and ensures that no sensitive data can be recovered by unauthorized parties.',
    ww: {
      B: 'Destruction removes data; it does not increase storage.',
      C: 'Destruction prevents access, not public searchability.',
      D: 'Destruction must comply with—not bypass—regulations.',
    },
    er: 'Connects secure destruction to preventing recovery of sensitive data.',
  },
  // ---- Information system lifecycle (3.10) ----
  {
    t: 'Information System Lifecycle', s: 'Initiation phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > The Information System Lifecycle - Part 1',
    q: 'During the initiation phase of the information system lifecycle, the PRIMARY focus is to:',
    o: [
      'Identify and engage stakeholders and understand requirements and the system\'s purpose',
      'Securely erase all data and dispose of hardware',
      'Run the system in full production',
      'Conduct the final retirement of the system',
    ],
    a: 'A',
    wc: 'Initiation focuses on identifying/engaging stakeholders (users, managers, customers, auditors, leadership) and understanding requirements and the system\'s purpose.',
    ww: {
      B: 'Erasure/disposal occurs at the disposal/retirement phase.',
      C: 'Full production occurs in operations and maintenance.',
      D: 'Retirement is the final phase, not initiation.',
    },
    er: 'Maps stakeholder/requirement understanding to the initiation phase.',
  },
  {
    t: 'Information System Lifecycle', s: 'Development vs acquisition', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > The Information System Lifecycle - Part 1',
    q: 'The "development and acquisition" phase centers on which key decision?',
    o: [
      'Whether to build the system in-house or buy/acquire a third-party solution, based on capability and security needs',
      'How to degauss backup tapes',
      'Which classification color to use on labels',
      'How many press releases to issue',
    ],
    a: 'A',
    wc: 'Development and acquisition addresses the build-vs-buy decision, applying secure development practices internally or vetting third-party solutions for security.',
    ww: {
      B: 'Degaussing is a destruction method, not a build/buy decision.',
      C: 'Label color is a handling cosmetic, not a lifecycle decision.',
      D: 'Press releases are unrelated to the system lifecycle.',
    },
    er: 'Tests the build-vs-buy focus of the development/acquisition phase.',
  },
  {
    t: 'Information System Lifecycle', s: 'Disposal phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Disposal',
    q: 'The disposal (retirement) phase of the information system lifecycle requires that:',
    o: [
      'All data is securely erased and hardware is disposed of so data cannot be recovered',
      'The system is moved into full production use',
      'Stakeholder requirements are first gathered',
      'The build-vs-buy decision is made',
    ],
    a: 'A',
    wc: 'Disposal involves secure decommissioning—ensuring all data is securely erased and hardware is disposed of to prevent data recovery.',
    ww: {
      B: 'Production use is operations/maintenance, not disposal.',
      C: 'Requirement gathering is part of initiation.',
      D: 'Build-vs-buy is the development/acquisition phase.',
    },
    er: 'Maps secure data erasure/hardware disposal to the disposal phase.',
  },
  {
    t: 'Information System Lifecycle', s: 'NIST SP 800-64', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Disposal',
    q: 'Which (now retired but still referenced) NIST publication provides a structured approach to embedding security into the information system lifecycle?',
    o: ['NIST SP 800-64', 'NIST SP 800-60', 'NIST SP 800-88', 'NIST SP 800-137'],
    a: 'A',
    wc: 'NIST SP 800-64 Rev. 2, though retired, is still referenced for embedding security into the system development lifecycle.',
    ww: {
      B: 'NIST SP 800-60 covers data types and classification.',
      C: 'NIST SP 800-88 covers media sanitization.',
      D: 'NIST SP 800-137 covers information security continuous monitoring.',
    },
    er: 'Distinguishes lifecycle-security guidance (800-64) from related publications.',
  },
  {
    t: 'Information System Lifecycle', s: 'Security integration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > The Information System Lifecycle - Part 2',
    q: 'A core principle emphasized across the information system lifecycle is that security should be:',
    o: [
      'Integrated from the initial phases through disposal, at every step',
      'Added only after a breach occurs',
      'Considered only during the disposal phase',
      'Left entirely to the end users',
    ],
    a: 'A',
    wc: 'Security must be integrated from the initial phases through disposal—built in at every step rather than bolted on.',
    ww: {
      B: 'Waiting for a breach is reactive and leaves the system exposed.',
      C: 'Security must apply throughout, not only at disposal.',
      D: 'Security is a shared responsibility led by management, not solely end users.',
    },
    er: 'Reinforces security integration throughout the lifecycle.',
  },
  // ---- Retention (2.5) ----
  {
    t: 'Data Retention', s: 'Retention principle', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data Retention Requirements',
    q: 'A sound data retention policy holds that data should be retained:',
    o: [
      'Only as long as necessary or legally required, then securely destroyed',
      'Forever, regardless of need or regulation',
      'For exactly 24 hours in all cases',
      'Only if it is public data',
    ],
    a: 'A',
    wc: 'Data should be retained securely and only for as long as necessary per organizational policy and legal/regulatory requirements, then destroyed.',
    ww: {
      B: 'Indefinite retention increases liability and breach exposure.',
      C: 'There is no universal 24-hour rule; retention depends on policy/regulation.',
      D: 'Retention applies to many data types, not only public data.',
    },
    er: 'Tests the retain-only-as-long-as-needed principle.',
  },
  {
    t: 'Data Retention', s: 'EOL vs EOS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Retention Best Practices',
    q: 'A vendor announces it will no longer release patches or provide support for a server operating system, although the OS still technically runs. This status is called:',
    o: ['End-of-Support (EOS)', 'End-of-Life (EOL)', 'Data remanence', 'Tailoring out'],
    a: 'A',
    wc: 'End-of-Support (EOS) is when the vendor no longer maintains or supports the hardware/software, even if it still runs.',
    ww: {
      B: 'End-of-Life (EOL) is when the asset can no longer be used or the license expires.',
      C: 'Data remanence is leftover data after deletion attempts.',
      D: 'Tailoring out is removing controls from a baseline.',
    },
    er: 'Distinguishes EOS (no support) from EOL (no longer usable).',
  },
  {
    t: 'Data Retention', s: 'EOL vs EOS', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Asset Retention',
    q: 'A critical application server has reached end-of-support, so it no longer receives security patches. From an asset-retention standpoint, the BEST action is to:',
    o: [
      'Replace or remove the unsupported asset to avoid security vulnerabilities',
      'Keep running it indefinitely since it still functions',
      'Expose it directly to the internet to extend its usefulness',
      'Remove all monitoring to reduce noise',
    ],
    a: 'A',
    wc: 'When assets are no longer supported, they should be replaced or removed because unpatched systems introduce security vulnerabilities.',
    ww: {
      B: 'Running unsupported systems indefinitely leaves unpatched vulnerabilities exposed.',
      C: 'Internet exposure of an unpatched server dramatically increases risk.',
      D: 'Removing monitoring reduces visibility into an already-risky asset.',
    },
    er: 'Tests responding to end-of-support assets.',
  },
  {
    t: 'Data Retention', s: 'Retention regulations', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Data Security Controls > Regulations Governing Data Retention',
    q: 'Which TWO regulations/standards are cited as governing data retention requirements? (Select TWO.)',
    o: ['HIPAA', 'PCI DSS', 'Wassenaar Arrangement', 'STRIDE'],
    a: ['A', 'B'],
    wc: 'HIPAA (healthcare) and PCI DSS (payment data) are among the regulations/standards governing data retention.',
    ww: {
      C: 'The Wassenaar Arrangement governs export controls, not data retention.',
      D: 'STRIDE is a threat-modeling methodology, not a retention regulation.',
    },
    er: 'Identifies retention-governing regulations among distractors.',
  },
  {
    t: 'Data Retention', s: 'Retention guidance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Guidance on Data Retention',
    q: 'Which standard focuses specifically on records management, including the concepts and principles of data retention?',
    o: ['ISO 15489', 'ISO 27040', 'NIST SP 800-88', 'PCI DSS'],
    a: 'A',
    wc: 'ISO 15489 focuses on records management, including data-retention concepts and principles.',
    ww: {
      B: 'ISO 27040 addresses storage security.',
      C: 'NIST SP 800-88 covers media sanitization.',
      D: 'PCI DSS is a payment-card security standard.',
    },
    er: 'Maps records-management retention guidance to ISO 15489.',
  },
  {
    t: 'Data Retention', s: 'Chain of custody', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Retention and Legal Proceedings',
    q: 'When data is involved in a legal or security investigation, what must be maintained to ensure its integrity is defensible?',
    o: ['Chain of custody', 'A marketing plan', 'A public changelog', 'An end-user license agreement'],
    a: 'A',
    wc: 'Chain of custody is a documented process tracking who accessed data, ensuring its integrity in legal proceedings; such data must be retained until the case concludes.',
    ww: {
      B: 'A marketing plan is irrelevant to evidentiary integrity.',
      C: 'A public changelog does not establish evidentiary control.',
      D: 'A EULA is a licensing agreement, not an evidence-integrity process.',
    },
    er: 'Connects evidentiary integrity to chain of custody.',
  },
  {
    t: 'Data Retention', s: 'Legal hold', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Retention and Legal Proceedings',
    q: 'An organization\'s policy says to destroy a category of records after 18 months, but those exact records are now the subject of active litigation. The organization should:',
    o: [
      'Retain the records until the legal matter concludes, overriding the routine destruction schedule',
      'Destroy them on schedule because policy takes precedence over litigation',
      'Make the records public to resolve the dispute faster',
      'Move the records off-site and stop tracking who accesses them',
    ],
    a: 'A',
    wc: 'Data involved in legal proceedings must be retained until the case concludes, and chain of custody maintained—this overrides routine destruction.',
    ww: {
      B: 'Destroying records under litigation can constitute spoliation and legal liability.',
      C: 'Public disclosure could violate confidentiality and harm the case.',
      D: 'Ceasing access tracking breaks chain of custody and undermines integrity.',
    },
    er: 'Tests legal hold overriding scheduled destruction.',
  },
  {
    t: 'Data Retention', s: 'Retention policy contents', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Data Security Controls > Organizational Data Retention Policy',
    q: 'Which TWO elements should a well-formed data retention policy define? (Select TWO.)',
    o: [
      'Retention periods or timelines for the data',
      'End-of-life and end-of-support requirements for assets',
      'The personal opinions of individual employees',
      'A list of competitor product prices',
    ],
    a: ['A', 'B'],
    wc: 'A retention policy should define retention periods/timelines and EOL/EOS requirements (along with purpose/scope and data covered), aligned with legal/regulatory needs.',
    ww: {
      C: 'Personal opinions are not policy elements.',
      D: 'Competitor pricing is irrelevant to a retention policy.',
    },
    er: 'Identifies required contents of a retention policy.',
  },
];
