// Domain 2 — Part 4: Determining/selecting security controls (baseline,
// scoping, tailoring), control frameworks (COBIT/COSO/ISO 27002/NIST 800-53/
// RMF/HITRUST), control types, Deming cycle, data protection methods
// (DRM/DLP/CASB), and data remanence/destruction.
module.exports = [
  // ---- Control selection ----
  {
    t: 'Determining Security Controls', s: 'Baseline', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Baseline and Tailoring',
    q: 'In control selection, a "baseline" is BEST described as:',
    o: [
      'The minimum set of controls that serves as a starting point for protection',
      'The maximum number of controls a system can hold',
      'A control that is never modified',
      'A method for destroying magnetic media',
    ],
    a: 'A',
    wc: 'A baseline is the minimum set of controls for safeguarding security/privacy (often from NIST SP 800-53 or ISO/IEC 27002) and acts as an adaptable starting point.',
    ww: {
      B: 'A baseline is a minimum starting point, not a maximum.',
      C: 'Baselines are adaptable through scoping and tailoring.',
      D: 'Destroying magnetic media is degaussing, unrelated to a control baseline.',
    },
    er: 'Recall of the baseline as a minimum control starting point.',
  },
  {
    t: 'Determining Security Controls', s: 'Scoping', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Baseline and Tailoring',
    q: 'Selecting which controls from a baseline actually apply to a specific system or environment is called:',
    o: ['Scoping', 'Tailoring in', 'Degaussing', 'Provisioning'],
    a: 'A',
    wc: 'Scoping determines which baseline controls are applicable to an organization\'s system or environment.',
    ww: {
      B: 'Tailoring in is adding controls beyond the baseline for new risks.',
      C: 'Degaussing is a data-destruction method.',
      D: 'Provisioning is creating/managing/destroying assets over their lifecycle.',
    },
    er: 'Distinguishes scoping (applicability) from tailoring.',
  },
  {
    t: 'Determining Security Controls', s: 'Tailoring', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Baseline and Tailoring',
    q: 'Modifying a baseline by ADDING controls to address new risks or heightened data sensitivity is referred to as:',
    o: ['Tailoring in', 'Tailoring out', 'Scoping', 'Sanitization'],
    a: 'A',
    wc: 'Tailoring in is adding additional controls based on new risks or data sensitivity; tailoring out is removing controls that are not relevant.',
    ww: {
      B: 'Tailoring out removes controls that do not apply.',
      C: 'Scoping selects which baseline controls apply at all.',
      D: 'Sanitization is a data-destruction concept.',
    },
    er: 'Distinguishes tailoring in (add) from tailoring out (remove).',
  },
  {
    t: 'Determining Security Controls', s: 'Tailoring out', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Control Baseline and Tailoring',
    q: 'A baseline includes a control requiring secure handling of wireless transmissions, but the target system is fully air-gapped with no wireless capability. The MOST appropriate action is to:',
    o: [
      'Tailor out the wireless control because it does not apply to this system',
      'Tailor in additional wireless controls to be safe',
      'Apply the high-watermark principle to add more controls',
      'Leave the control and force the system to add wireless hardware',
    ],
    a: 'A',
    wc: 'Tailoring out removes baseline controls that are not relevant or applicable—an air-gapped system with no wireless does not need the wireless control.',
    ww: {
      B: 'Adding wireless controls to a system with no wireless wastes effort and is irrelevant.',
      C: 'High watermark addresses co-mingled sensitivity, not inapplicable controls.',
      D: 'Forcing wireless hardware to justify a control is backwards and increases risk.',
    },
    er: 'Tests tailoring out an inapplicable control.',
  },
  {
    t: 'Selecting Security Controls', s: 'Risk-based selection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Selection Process',
    q: 'According to the control selection process, controls should be selected based primarily on:',
    o: [
      'The level of risk and the protection needs of the information',
      'The personal preference of the newest administrator',
      'Whichever controls are cheapest, regardless of risk',
      'The alphabetical order of control names',
    ],
    a: 'A',
    wc: 'Controls are selected based on the level of risk and protection needs; over-securing public systems is avoided while sensitive systems receive appropriate controls.',
    ww: {
      B: 'Personal preference is not a valid selection basis.',
      C: 'Cost alone, ignoring risk, leads to under- or over-protection.',
      D: 'Alphabetical order is irrelevant to control selection.',
    },
    er: 'Ties control selection to risk and protection needs.',
  },
  {
    t: 'Selecting Security Controls', s: 'Avoiding over-securing', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Control Selection Process',
    q: 'A public-facing website serves only non-sensitive marketing content. Applying the control selection principles, the team should:',
    o: [
      'Apply controls proportionate to the low sensitivity and avoid over-securing the public system',
      'Apply the same controls used for the most sensitive internal database',
      'Remove all controls because the data is public',
      'Classify the marketing content as Top Secret to be safe',
    ],
    a: 'A',
    wc: 'Control selection avoids over-securing public systems; controls should be proportionate to the data\'s low sensitivity and risk.',
    ww: {
      B: 'Applying maximum internal controls to a public site wastes resources.',
      C: 'Even public systems need baseline protections (e.g., integrity, availability).',
      D: 'Over-classifying non-sensitive content misallocates protection effort.',
    },
    er: 'Tests proportionate control selection to avoid over-securing.',
  },
  // ---- Frameworks ----
  {
    t: 'Security Control Frameworks', s: 'COBIT', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Security Control Frameworks',
    q: 'Which framework, managed by ISACA, is designed for IT governance and aligning IT with business objectives?',
    o: ['COBIT', 'NIST SP 800-88', 'ISO 15489', 'Deming Cycle'],
    a: 'A',
    wc: 'COBIT (Control Objectives for Information and Related Technologies), managed by ISACA, focuses on IT governance and aligning IT with business needs.',
    ww: {
      B: 'NIST SP 800-88 covers media sanitization.',
      C: 'ISO 15489 covers records management.',
      D: 'The Deming Cycle (PDCA) is a continuous-improvement model, not a governance framework.',
    },
    er: 'Maps IT-governance framework to COBIT/ISACA.',
  },
  {
    t: 'Security Control Frameworks', s: 'COSO and SOX', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Security Control Frameworks',
    q: 'COBIT is derived from which framework, which is used to comply with Sarbanes-Oxley (SOX) 404 and focuses on preventing fraudulent financial reporting?',
    o: ['COSO', 'ISO/IEC 27002', 'HITRUST', 'NIST SP 800-53'],
    a: 'A',
    wc: 'COBIT is derived from COSO; COSO is used for SOX 404 compliance and focuses on preventing fraudulent financial reporting.',
    ww: {
      B: 'ISO/IEC 27002 is an international code of practice for security controls.',
      C: 'HITRUST is a common security framework for health information.',
      D: 'NIST SP 800-53 is the U.S. federal control catalog required by FISMA.',
    },
    er: 'Connects COSO to SOX 404 and its relationship to COBIT.',
  },
  {
    t: 'Security Control Frameworks', s: 'NIST SP 800-53', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Common Security Control Standards',
    q: 'Which control framework is widely used by U.S. government organizations, is required by FISMA, and is organized into control families?',
    o: ['NIST SP 800-53', 'ISO 15489', 'COBIT', 'AACS'],
    a: 'A',
    wc: 'NIST SP 800-53 provides security and privacy controls, is required by FISMA, and is organized into control families (e.g., access control, audit and accountability).',
    ww: {
      B: 'ISO 15489 is a records-management standard.',
      C: 'COBIT is an IT-governance framework, not the FISMA control catalog.',
      D: 'AACS is a DRM scheme for optical media.',
    },
    er: 'Maps FISMA-required control families to NIST SP 800-53.',
  },
  {
    t: 'Security Control Frameworks', s: 'ISO/IEC 27002', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Security Control Frameworks',
    q: 'Which international standard, originating from British Standard 7799, provides a widely adopted code of practice broken into control objectives (policies, HR security, cryptography, etc.)?',
    o: ['ISO/IEC 27002', 'NIST SP 800-37', 'COSO', 'PCI DSS'],
    a: 'A',
    wc: 'ISO/IEC 27002 originated from BS 7799 (via 17799) and is an international standard of control objectives, widely adopted across industries.',
    ww: {
      B: 'NIST SP 800-37 is the Risk Management Framework process.',
      C: 'COSO is a financial-reporting/governance framework used for SOX.',
      D: 'PCI DSS is a payment-card security standard.',
    },
    er: 'Identifies ISO/IEC 27002 by its BS 7799 lineage and control-objective structure.',
  },
  {
    t: 'Security Control Frameworks', s: 'HITRUST', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Selecting Security Controls',
    q: 'Which common security framework is specifically associated with protecting health information?',
    o: ['HITRUST', 'COBIT', 'ISO 15489', 'AACS'],
    a: 'A',
    wc: 'HITRUST (Health Information Trust Alliance) is a common security framework for health information.',
    ww: {
      B: 'COBIT is a general IT-governance framework.',
      C: 'ISO 15489 is a records-management standard.',
      D: 'AACS is a DRM scheme.',
    },
    er: 'Maps health-information framework to HITRUST.',
  },
  {
    t: 'Security Control Frameworks', s: 'Framework-to-purpose mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 2 > Data Security Controls > Important Terms',
    p: ['COBIT', 'COSO', 'ISO/IEC 27002', 'NIST SP 800-53'],
    q: 'Match each framework (1-4) to its primary description (A-D).',
    o: [
      'Financial-reporting framework that drives SOX 404 compliance',
      'IT governance framework managed by ISACA',
      'U.S. federal security control catalog with control families (required by FISMA)',
      'International code of practice with security control objectives',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'COBIT → IT governance/ISACA (B); COSO → financial reporting/SOX 404 (A); ISO/IEC 27002 → international control objectives (D); NIST SP 800-53 → U.S. federal control families/FISMA (C).',
    ww: {},
    er: 'Tests precise mapping of control frameworks to their purposes.',
  },
  {
    t: 'Control Types', s: 'Detective control', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Types within Defense in Depth Strategy',
    q: 'Log monitoring and an intrusion detection system are examples of which control type?',
    o: ['Detective', 'Preventative', 'Recovery', 'Deterrent'],
    a: 'A',
    wc: 'Detective controls identify incidents after they happen, e.g., log monitoring and intrusion detection systems.',
    ww: {
      B: 'Preventative controls stop incidents from happening (e.g., firewalls, authentication).',
      C: 'Recovery controls return systems to normal after an incident (e.g., DR plans).',
      D: 'Deterrent controls discourage incidents (e.g., warning banners).',
    },
    er: 'Maps log monitoring/IDS to detective controls.',
  },
  {
    t: 'Control Types', s: 'Corrective control', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Control Types within Defense in Depth Strategy',
    q: 'Backup recovery and patch management, used to remedy an incident after detection, are examples of which control type?',
    o: ['Corrective', 'Deterrent', 'Directive', 'Preventative'],
    a: 'A',
    wc: 'Corrective controls remedy an incident after detection, e.g., backup recovery and patch management.',
    ww: {
      B: 'Deterrent controls discourage incidents before they occur.',
      C: 'Directive controls mandate behaviors (e.g., policies).',
      D: 'Preventative controls stop incidents from happening in the first place.',
    },
    er: 'Maps remediation-after-detection to corrective controls.',
  },
  {
    t: 'Deming Cycle', s: 'PDCA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > The Deming Cycle (PDCA)',
    q: 'In the Deming Cycle (PDCA) applied to security controls, which step assesses whether implemented controls are effective and meet security goals?',
    o: ['Check', 'Plan', 'Do', 'Act'],
    a: 'A',
    wc: 'In PDCA, "Check" assesses the effectiveness of controls and whether they meet security goals.',
    ww: {
      B: '"Plan" identifies objectives and determines appropriate controls.',
      C: '"Do" implements the selected controls.',
      D: '"Act" addresses gaps in effectiveness, especially after incidents or changes.',
    },
    er: 'Tests the assessment step of PDCA.',
  },
  // ---- Data protection methods ----
  {
    t: 'Data Protection Methods', s: 'DLP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data Loss Prevention (DLP)',
    q: 'Which technology blocks unauthorized data exfiltration by performing egress monitoring and pattern matching against classifications like PII and PHI?',
    o: ['Data Loss Prevention (DLP)', 'Digital Rights Management (DRM)', 'Trusted Platform Module (TPM)', 'Degaussing'],
    a: 'A',
    wc: 'DLP blocks unauthorized data exfiltration (egress monitoring) and uses pattern matching to act on classified data such as PII or PHI.',
    ww: {
      B: 'DRM enforces copyright protection on digital media via encryption.',
      C: 'A TPM secures cryptographic keys/data at rest on a device.',
      D: 'Degaussing is a magnetic data-destruction method.',
    },
    er: 'Maps exfiltration prevention/egress monitoring to DLP.',
  },
  {
    t: 'Data Protection Methods', s: 'DLP types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Types of DLP',
    q: 'A DLP deployment that scans local file systems and monitors data leaving individual laptops is which type of DLP?',
    o: ['Endpoint DLP', 'Network DLP', 'Cloud DLP gateway', 'Perimeter firewall'],
    a: 'A',
    wc: 'Endpoint DLP scans local file systems and monitors data leaving individual endpoints to detect and block exfiltration.',
    ww: {
      B: 'Network DLP scans outgoing data on the network rather than on the endpoint.',
      C: '"Cloud DLP gateway" is not the term used; CASB provides cloud DLP functions.',
      D: 'A firewall filters traffic but is not specifically endpoint DLP.',
    },
    er: 'Distinguishes endpoint DLP from network DLP.',
  },
  {
    t: 'Data Protection Methods', s: 'DLP prerequisite', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Types of DLP',
    q: 'For DLP software to reliably detect and act on sensitive data, that data must FIRST be:',
    o: [
      'Labeled or classified so the DLP policies can recognize it',
      'Encrypted with a key the DLP cannot access',
      'Deleted from all endpoints',
      'Made publicly available',
    ],
    a: 'A',
    wc: 'DLP relies on data being labeled or classified so its policies can detect and act on it; regular updates are also needed for performance.',
    ww: {
      B: 'If DLP cannot inspect the data, it cannot enforce policy on it; this defeats detection.',
      C: 'Deleting data removes the very thing DLP is meant to protect.',
      D: 'Making data public is the opposite of protecting it from exfiltration.',
    },
    er: 'Tests the classification prerequisite for effective DLP.',
  },
  {
    t: 'Data Protection Methods', s: 'CASB', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Cloud Access Security Broker (CASB)',
    q: 'A Cloud Access Security Broker (CASB) primarily functions as:',
    o: [
      'A security policy enforcement point (proxy) between users and cloud services',
      'A magnetic device for destroying backup tapes',
      'A records-management retention standard',
      'A hardware root of trust embedded in a CPU',
    ],
    a: 'A',
    wc: 'A CASB is a policy enforcement point that acts as a proxy between users and cloud services, applying data security, DLP, threat protection, and URL filtering.',
    ww: {
      B: 'That describes a degausser.',
      C: 'That describes a standard like ISO 15489.',
      D: 'That describes a TPM.',
    },
    er: 'Maps cloud policy enforcement to CASB.',
  },
  {
    t: 'Data Protection Methods', s: 'DRM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data Protection Methods',
    q: 'Digital Rights Management (DRM) primarily uses encryption to:',
    o: [
      'Enforce copyright protection and prevent unauthorized copying/sharing of digital media',
      'Monitor outbound network traffic for PII',
      'Sanitize magnetic media before reuse',
      'Track which employees badge into a facility',
    ],
    a: 'A',
    wc: 'DRM uses encryption to enforce copyright protection for digital media and prevent copying, piracy, and unauthorized sharing.',
    ww: {
      B: 'Monitoring outbound traffic for PII is DLP\'s role.',
      C: 'Media sanitization is a destruction activity, not DRM.',
      D: 'Badge tracking is a physical access control, not DRM.',
    },
    er: 'Maps copyright/anti-piracy enforcement to DRM.',
  },
  {
    t: 'Data Protection Methods', s: 'Protection method selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Data Protection Methods',
    q: 'A company is most worried that employees might email spreadsheets full of customer PII to personal accounts. Which protection method MOST directly addresses this exfiltration risk?',
    o: [
      'Data Loss Prevention (DLP) with egress monitoring',
      'Digital Rights Management (DRM) for media files',
      'Degaussing of backup tapes',
      'A Trusted Platform Module on each laptop',
    ],
    a: 'A',
    wc: 'DLP with egress monitoring detects and blocks unauthorized transfer of classified data such as PII leaving the organization.',
    ww: {
      B: 'DRM protects copyrighted media from copying, not general PII exfiltration via email.',
      C: 'Degaussing destroys data on tapes; it does not stop email exfiltration.',
      D: 'A TPM protects keys/data at rest on a device, not data being emailed out.',
    },
    er: 'Tests selecting DLP for an exfiltration scenario.',
  },
  {
    t: 'Data Protection Methods', s: 'Protection methods', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Data Security Controls > Important Terms',
    q: 'Which TWO of the following are data protection methods described in the guide? (Select TWO.)',
    o: ['Data Loss Prevention (DLP)', 'Cloud Access Security Broker (CASB)', 'Tier 0 (Essential)', 'Unclassified'],
    a: ['A', 'B'],
    wc: 'DLP and CASB are data protection methods; the others are an asset tier and a classification level.',
    ww: {
      C: 'Tier 0 (Essential) is an asset classification tier, not a protection method.',
      D: 'Unclassified is a data classification level, not a protection method.',
    },
    er: 'Separates protection methods from classification constructs.',
  },
  // ---- Data remanence & destruction ----
  {
    t: 'Data Remanence', s: 'Definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Managing Data Remanence',
    q: 'Data remanence refers to:',
    o: [
      'Leftover data that remains after an attempt to delete or remove it',
      'Data that has been classified as Top Secret',
      'Data currently being processed in memory',
      'A type of cloud access broker',
    ],
    a: 'A',
    wc: 'Data remanence is leftover data that remains after deletion attempts; simple deletion often just moves data (e.g., to a recycle bin) rather than destroying it.',
    ww: {
      B: 'Classification level is unrelated to remanence.',
      C: 'Data in memory is data in use, not remanence.',
      D: 'A CASB is a cloud security proxy, not remanence.',
    },
    er: 'Recall of the data-remanence definition.',
  },
  {
    t: 'Data Destruction', s: 'Destruction techniques', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data Destruction Techniques',
    q: 'Which destruction technique involves REPEATED clearing (overwriting) to ensure data is completely unrecoverable, often used in highly sensitive government or medical environments?',
    o: ['Purging', 'Erasing', 'Clearing', 'Labeling'],
    a: 'A',
    wc: 'Purging is repeated clearing to ensure data is completely unrecoverable, common in highly sensitive environments.',
    ww: {
      B: 'Erasing only deletes from the file system and is not effective against remnants.',
      C: 'Clearing overwrites once; purging repeats clearing for stronger assurance.',
      D: 'Labeling is a handling identification activity, not destruction.',
    },
    er: 'Distinguishes purging (repeated clearing) from erasing and clearing.',
  },
  {
    t: 'Data Destruction', s: 'Erasing limitation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Data Destruction Techniques',
    q: 'An administrator "deletes" sensitive files and empties the recycle bin before donating the hard drive. Why is this insufficient to prevent data disclosure?',
    o: [
      'Erasing removes file-system references but leaves recoverable data remnants on the disk',
      'Erasing physically shreds the platters, which is unnecessary',
      'Erasing encrypts the data so strongly it cannot be read',
      'Erasing automatically degausses the drive',
    ],
    a: 'A',
    wc: 'Erasing deletes the file-system reference but does not remove the data from the disk, leaving recoverable remnants; clearing/purging/sanitization is required.',
    ww: {
      B: 'Erasing does not physically destroy platters; that would be a separate method.',
      C: 'Erasing does not encrypt data.',
      D: 'Erasing does not perform degaussing.',
    },
    er: 'Tests why simple deletion fails to prevent data remanence.',
  },
  {
    t: 'Data Destruction', s: 'Sanitization methods', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Data Sanitization Methods',
    q: 'Which sanitization method uses strong magnetic fields to scramble data and is effective for magnetic media such as backup tapes?',
    o: ['Degaussing', 'Zeroing', 'Tokenization', 'Pseudonymization'],
    a: 'A',
    wc: 'Degaussing uses strong magnetic fields to scramble data on magnetic media (e.g., backup tapes), making it unrecoverable.',
    ww: {
      B: 'Zeroing overwrites the medium with zeros and is not magnetic destruction.',
      C: 'Tokenization substitutes data with non-sensitive tokens (a protection method).',
      D: 'Pseudonymization replaces data with aliases (a declassification technique).',
    },
    er: 'Maps magnetic-media destruction to degaussing.',
  },
  {
    t: 'Data Destruction', s: 'Method by media', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Best Practices for Data Remnant Management',
    q: 'A best practice is to choose the sanitization method based on the storage medium. Which pairing follows this guidance?',
    o: [
      'Degaussing for magnetic tapes; overwriting for hard drives',
      'Degaussing for solid-state drives; tokenizing for tapes',
      'Pseudonymization for hard drives; labeling for tapes',
      'Zeroing for paper documents; marking for SSDs',
    ],
    a: 'A',
    wc: 'The guide recommends matching method to medium—e.g., degaussing for tapes and overwriting for hard drives.',
    ww: {
      B: 'Degaussing is for magnetic media (not SSDs), and tokenization is a protection method, not sanitization for tapes.',
      C: 'Pseudonymization and labeling are not media-sanitization methods.',
      D: 'Zeroing applies to digital media, not paper; marking is handling, not SSD sanitization.',
    },
    er: 'Tests matching sanitization methods to the appropriate media.',
  },
  {
    t: 'Data Declassification', s: 'Tokenization vs pseudonymization', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Declassification Techniques',
    q: 'Which declassification technique substitutes sensitive data with non-sensitive tokens that have no intrinsic value, requiring a separate mapping to recover the original data?',
    o: ['Tokenization', 'Pseudonymization', 'Obfuscation', 'De-identification'],
    a: 'A',
    wc: 'Tokenization substitutes sensitive data with meaningless tokens; the tokens must be mapped back to the original for internal use but appear valueless to unauthorized users.',
    ww: {
      B: 'Pseudonymization replaces data with aliases that can still be linked back through separate records, but is not specifically the non-intrinsic-value token mechanism described.',
      C: 'Obfuscation conceals/masks data (e.g., a black box over text).',
      D: 'De-identification removes personal identifiers to anonymize data.',
    },
    er: 'Distinguishes tokenization from other declassification techniques.',
  },
  {
    t: 'Data Declassification', s: 'De-identification', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Declassification Techniques',
    q: 'Removing personal identifiers (such as account numbers) from medical records so the data can no longer be linked to a specific person is called:',
    o: ['De-identification', 'Tokenization', 'Degaussing', 'Scoping'],
    a: 'A',
    wc: 'De-identification removes personal identifiers to prevent linking data to a specific subject, anonymizing it.',
    ww: {
      B: 'Tokenization substitutes data with mapped tokens, not identifier removal for anonymization.',
      C: 'Degaussing is magnetic media destruction.',
      D: 'Scoping selects which controls apply to a system.',
    },
    er: 'Maps identifier removal/anonymization to de-identification.',
  },
  {
    t: 'Data Destruction', s: 'NIST SP 800-88', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Data Security Controls > Regulations and Guidelines',
    q: 'Which NIST Special Publication provides guidelines for media sanitization?',
    o: ['NIST SP 800-88', 'NIST SP 800-60', 'NIST SP 800-37', 'NIST SP 800-53'],
    a: 'A',
    wc: 'NIST SP 800-88 provides guidelines for media sanitization.',
    ww: {
      B: 'NIST SP 800-60 covers data types and classification.',
      C: 'NIST SP 800-37 is the Risk Management Framework.',
      D: 'NIST SP 800-53 is the security/privacy control catalog.',
    },
    er: 'Maps media-sanitization guidance to NIST SP 800-88.',
  },
];
