// Domain 2 — Part 1: Information & asset classification and categorization,
// classification levels, asset tiers, sensitive data types (PII/PHI/proprietary).
module.exports = [
  {
    t: 'Asset Classification', s: 'Purpose of classification', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Classifying Data and Assets',
    q: 'What is the PRIMARY purpose of classifying information and assets?',
    o: [
      'To determine how data should be handled and secured based on its criticality, sensitivity, and value',
      'To increase the total number of assets an organization owns',
      'To eliminate the need for any security controls',
      'To make all data publicly accessible by default',
    ],
    a: 'A',
    wc: 'Classification identifies and ranks information/assets by criticality, sensitivity, and value so the right handling and protection are applied.',
    ww: {
      B: 'Classification organizes and protects existing assets; it does not increase asset count.',
      C: 'Classification drives appropriate controls; it does not remove the need for them.',
      D: 'Classification restricts sensitive data; it does not make everything public.',
    },
    er: 'Tests the core reason for classification: aligning protection to data value/sensitivity.',
  },
  {
    t: 'Asset Classification', s: 'Classification criteria', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Classifying Data and Assets',
    q: 'When assigning a classification level, an organization should evaluate data primarily on the basis of its:',
    o: [
      'Criticality, sensitivity, and value to the organization',
      'File size and storage format',
      'Age of the storage hardware',
      'Number of employees who created it',
    ],
    a: 'A',
    wc: 'Data is classified based on its criticality, sensitivity, and value to the organization, which determine the required protection.',
    ww: {
      B: 'File size/format does not determine sensitivity or required protection.',
      C: 'Hardware age is an asset-lifecycle concern, not a classification criterion.',
      D: 'The number of creators is irrelevant to data sensitivity.',
    },
    er: 'Reinforces the criteria that drive classification decisions.',
  },
  {
    t: 'Asset Classification', s: 'Government classification levels', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Classification Levels',
    q: 'In the government classification scheme described in the guide, which level applies to information whose disclosure would cause EXTREMELY high impact and the most significant damage?',
    o: ['Top Secret', 'Secret', 'Confidential', 'Unclassified'],
    a: 'A',
    wc: 'Top Secret denotes extremely high impact on disclosure with significant damage potential—the highest level.',
    ww: {
      B: 'Secret causes serious (high) damage, but less than Top Secret.',
      C: 'Confidential causes moderate/noticeable damage.',
      D: 'Unclassified has low or no impact.',
    },
    er: 'Tests ordering of government classification levels by impact.',
  },
  {
    t: 'Asset Classification', s: 'Government classification levels', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Classification Levels',
    q: 'Which government classification level corresponds to information that would cause MODERATE impact (noticeable damage) if disclosed?',
    o: ['Confidential', 'Top Secret', 'Secret', 'Unclassified'],
    a: 'A',
    wc: 'Confidential corresponds to moderate impact—noticeable damage if disclosed.',
    ww: {
      B: 'Top Secret is extremely high impact.',
      C: 'Secret is high impact with serious damage.',
      D: 'Unclassified is low or no impact.',
    },
    er: 'Distinguishes Confidential (moderate) from higher and lower levels.',
  },
  {
    t: 'Asset Classification', s: 'Classification levels mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 2 > Asset Security > Classification Levels',
    p: ['Top Secret', 'Secret', 'Confidential', 'Unclassified'],
    q: 'Match each government classification level (1-4) to the impact of its disclosure (A-D).',
    o: [
      'Low or no impact; minimal value information',
      'Extremely high impact; significant damage potential',
      'High impact; serious damage if disclosed',
      'Moderate impact; noticeable damage',
    ],
    a: '1-B,2-C,3-D,4-A',
    wc: 'Top Secret → extremely high impact (B); Secret → high/serious damage (C); Confidential → moderate/noticeable (D); Unclassified → low/no impact (A).',
    ww: {},
    er: 'Tests precise mapping of classification levels to disclosure impact.',
  },
  {
    t: 'Asset Classification', s: 'Commercial vs government labels', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Asset Security > Classifying Data and Assets',
    q: 'A private retail company wants a classification scheme that fits its business rather than military labels. Which set of levels is MOST appropriate for a commercial organization?',
    o: [
      'Public, Internal, Sensitive (commercial tiers aligned to business needs)',
      'Top Secret, Secret, Confidential (military-only labels)',
      'Tier 0, Tier 1, Tier 2 hardware tiers used for data sensitivity',
      'No classification, since commercial data is never sensitive',
    ],
    a: 'A',
    wc: 'Commercial organizations typically use business-aligned levels such as public, internal, and sensitive; classification should align with business needs.',
    ww: {
      B: 'Top Secret/Secret/Confidential are government/military labels, not the natural commercial fit.',
      C: 'Tier 0/1/2 are asset (system) tiers, not data sensitivity labels.',
      D: 'Commercial data (e.g., PII, proprietary data) is frequently sensitive and must be classified.',
    },
    er: 'Tests choosing business-aligned commercial classification over military labels.',
  },
  {
    t: 'Asset Classification', s: 'Asset classification tiers', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Asset Classification Tiers',
    q: 'Using the asset classification tiers in the guide, critical servers, databases, and network devices belong to which tier?',
    o: ['Tier 0 (Essential)', 'Tier 1 (Important)', 'Tier 2 (Non-Essential)', 'Tier 3 (Disposable)'],
    a: 'A',
    wc: 'Tier 0 (Essential) covers critical servers, databases, and network devices.',
    ww: {
      B: 'Tier 1 (Important) covers development environments and backup systems.',
      C: 'Tier 2 (Non-Essential) covers workstations, mobile devices, and printers.',
      D: '"Tier 3 (Disposable)" is not a tier defined in the guide.',
    },
    er: 'Tests recall of the most critical asset tier.',
  },
  {
    t: 'Asset Classification', s: 'Asset classification tiers', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Asset Classification Tiers',
    q: 'Workstations, mobile devices, and printers are categorized in which asset tier?',
    o: ['Tier 2 (Non-Essential)', 'Tier 0 (Essential)', 'Tier 1 (Important)', 'Tier 0 (Critical-Plus)'],
    a: 'A',
    wc: 'Tier 2 (Non-Essential) includes workstations, mobile devices, and printers.',
    ww: {
      B: 'Tier 0 is essential infrastructure such as critical servers and databases.',
      C: 'Tier 1 is important systems like development environments and backups.',
      D: '"Tier 0 (Critical-Plus)" is not a defined tier.',
    },
    er: 'Distinguishes non-essential assets from essential and important tiers.',
  },
  {
    t: 'Asset Classification', s: 'Asset classification tiers', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Asset Classification Tiers',
    q: 'Development environments and backup systems are classified under which asset tier?',
    o: ['Tier 1 (Important)', 'Tier 0 (Essential)', 'Tier 2 (Non-Essential)', 'Unclassified'],
    a: 'A',
    wc: 'Tier 1 (Important) includes development environments and backup systems.',
    ww: {
      B: 'Tier 0 is essential infrastructure (critical servers, databases, network devices).',
      C: 'Tier 2 is non-essential (workstations, mobile devices, printers).',
      D: 'Unclassified is a data classification level, not an asset tier.',
    },
    er: 'Recall of the middle asset tier.',
  },
  {
    t: 'Sensitive Data Types', s: 'PII', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Types of Sensitive Data',
    q: 'Data that can uniquely identify an individual and is subject to strict regulatory standards is known as:',
    o: ['Personally Identifiable Information (PII)', 'Protected Health Information (PHI)', 'Proprietary data', 'Public data'],
    a: 'A',
    wc: 'PII is data that can uniquely identify an individual and is subject to strict regulatory standards.',
    ww: {
      B: 'PHI is specifically health-related information protected under laws like HIPAA.',
      C: 'Proprietary data gives a business competitive advantage.',
      D: 'Public data has minimal sensitivity.',
    },
    er: 'Recall of the PII definition.',
  },
  {
    t: 'Sensitive Data Types', s: 'PHI', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Types of Sensitive Data',
    q: 'Health-related information that requires protection under laws such as HIPAA is categorized as:',
    o: ['Protected Health Information (PHI)', 'Personally Identifiable Information (PII)', 'Proprietary data', 'Tier 0 asset'],
    a: 'A',
    wc: 'PHI is health-related information requiring protection under laws like HIPAA.',
    ww: {
      B: 'PII identifies individuals generally but is not specifically health data.',
      C: 'Proprietary data provides competitive advantage, unrelated to health.',
      D: 'Tier 0 is an asset tier, not a data type.',
    },
    er: 'Distinguishes PHI from PII and proprietary data.',
  },
  {
    t: 'Sensitive Data Types', s: 'Proprietary data', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Types of Sensitive Data',
    q: 'Information that gives a business a competitive advantage and therefore requires high-level security is BEST described as:',
    o: ['Proprietary data', 'Public data', 'Unclassified data', 'Personally Identifiable Information (PII)'],
    a: 'A',
    wc: 'Proprietary data gives a business competitive advantage and requires high-level security.',
    ww: {
      B: 'Public data carries minimal sensitivity.',
      C: 'Unclassified data has low or no impact.',
      D: 'PII identifies individuals; it is not defined by competitive advantage.',
    },
    er: 'Maps competitive-advantage information to proprietary data.',
  },
  {
    t: 'Sensitive Data Types', s: 'Identifying sensitive data', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Asset Security > Types of Sensitive Data',
    q: 'Which TWO of the following are categories of sensitive data that warrant heightened protection? (Select TWO.)',
    o: [
      'Personally Identifiable Information (PII)',
      'Protected Health Information (PHI)',
      'Public marketing brochures posted on the company website',
      'Press releases already distributed to the media',
    ],
    a: ['A', 'B'],
    wc: 'PII and PHI are sensitive data types subject to regulatory protection; public materials are not sensitive.',
    ww: {
      C: 'Public marketing brochures are intentionally public and not sensitive.',
      D: 'Distributed press releases are public information, not sensitive data.',
    },
    er: 'Separates regulated sensitive data from intentionally public information.',
  },
  {
    t: 'Data Classification', s: 'NIST SP 800-60', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Important Reference',
    q: 'Which NIST Special Publication is referenced as essential for understanding data types and classification standards?',
    o: ['NIST SP 800-60', 'NIST SP 800-88', 'NIST SP 800-37', 'NIST SP 1800-5'],
    a: 'A',
    wc: 'NIST SP 800-60 provides guidance on mapping information and information system types to security categories (data types and classification).',
    ww: {
      B: 'NIST SP 800-88 covers media sanitization.',
      C: 'NIST SP 800-37 is the Risk Management Framework.',
      D: 'NIST SP 1800-5 relates to IT asset management.',
    },
    er: 'Maps data-type/classification guidance to NIST SP 800-60.',
  },
  {
    t: 'Data Classification', s: 'Sensitivity assessment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Classification',
    q: 'A sensitivity assessment evaluates a data set\'s need for protection based primarily on its:',
    o: [
      'Confidentiality, integrity, and availability requirements',
      'Color and font formatting',
      'Number of backup copies that exist',
      'The vendor that supplied the storage device',
    ],
    a: 'A',
    wc: 'Sensitivity assessment evaluates the data\'s need for protection based on its confidentiality, integrity, and availability.',
    ww: {
      B: 'Formatting does not determine protection requirements.',
      C: 'Backup count is a resilience detail, not a sensitivity measure.',
      D: 'Storage vendor is unrelated to data sensitivity.',
    },
    er: 'Ties sensitivity assessment to CIA-based protection needs.',
  },
  {
    t: 'Data Classification', s: 'Data inventory', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Classification',
    q: 'Why is maintaining a comprehensive inventory of all data and assets important to classification?',
    o: [
      'It helps assess each item\'s criticality and impact on business operations',
      'It guarantees data can never be breached',
      'It removes the need to classify data at all',
      'It automatically encrypts all data',
    ],
    a: 'A',
    wc: 'A comprehensive inventory helps assess the criticality and business impact of data and assets, which underpins classification and protection.',
    ww: {
      B: 'An inventory supports protection but does not guarantee breach immunity.',
      C: 'Inventory enables classification; it does not replace it.',
      D: 'Inventory is a listing activity; it does not perform encryption.',
    },
    er: 'Connects asset inventory to criticality/impact assessment.',
  },
  {
    t: 'Data Classification', s: 'Classification scope', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Classification',
    q: 'When identifying data types for classification, an organization should account for data in:',
    o: [
      'Both physical and digital formats',
      'Digital formats only, since paper is never sensitive',
      'Physical formats only, since digital data is automatically secure',
      'Neither format, because classification applies only to hardware',
    ],
    a: 'A',
    wc: 'Data classification must consider both physical and digital formats of information.',
    ww: {
      B: 'Paper records can be highly sensitive and must be classified.',
      C: 'Digital data is not automatically secure and must be classified.',
      D: 'Classification applies to data/information, including but not limited to hardware.',
    },
    er: 'Reinforces that classification covers physical and digital data.',
  },
  {
    t: 'Asset Classification', s: 'Benefits of classification', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Asset Security > Asset Classification Tiers',
    q: 'Which TWO are stated benefits of properly classifying assets? (Select TWO.)',
    o: [
      'Improved security awareness',
      'Compliance assurance',
      'Guaranteed elimination of all cyber risk',
      'Permanent exemption from all audits',
    ],
    a: ['A', 'B'],
    wc: 'Benefits of proper classification include improved security awareness, compliance assurance, and enhanced planning.',
    ww: {
      C: 'Classification reduces and manages risk but cannot eliminate it entirely.',
      D: 'Classification supports compliance; it does not exempt an organization from audits.',
    },
    er: 'Recall of classification benefits.',
  },
  {
    t: 'Asset Classification', s: 'Flow of data', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Asset Security > Asset Classification',
    q: 'During asset classification, a team maps exactly how sensitive data moves into, within, and out of the organization. The PRIMARY security value of tracking this data flow is to:',
    o: [
      'Ensure appropriate security measures are applied wherever the data travels, including in transit',
      'Increase the volume of data the organization stores',
      'Replace the need to classify the data itself',
      'Guarantee the data never needs encryption',
    ],
    a: 'A',
    wc: 'Tracking the flow of data ensures appropriate controls are applied as data moves within and outside the organization, protecting it in all states including transit.',
    ww: {
      B: 'Mapping flow does not increase stored volume.',
      C: 'Flow analysis complements—not replaces—classification.',
      D: 'Data in transit often specifically requires encryption.',
    },
    er: 'Connects data-flow mapping to applying controls across data states.',
  },
  {
    t: 'Data Classification', s: 'Governance and compliance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Classification',
    q: 'Policies governing data creation, collection, management, and disposal primarily help ensure:',
    o: [
      'Data quality, authenticity, and reliability, and regulatory compliance',
      'That data is never classified',
      'That all data is deleted immediately upon creation',
      'That security controls are unnecessary',
    ],
    a: 'A',
    wc: 'Governance, regulation, and compliance policies over the data lifecycle help ensure data quality, authenticity, and reliability while meeting regulations.',
    ww: {
      B: 'Such governance supports classification rather than preventing it.',
      C: 'Immediate deletion would destroy needed data and ignore retention requirements.',
      D: 'Governance reinforces—not removes—the need for controls.',
    },
    er: 'Links data governance policies to quality and compliance outcomes.',
  },
  {
    t: 'Asset Classification', s: 'High watermark', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Data Security Controls > Control Baseline and Tailoring',
    q: 'A single system stores both public data and highly sensitive PII together (co-mingled). According to the high-watermark principle, the system should be protected at the level of:',
    o: [
      'The most sensitive data it contains (the PII)',
      'The least sensitive data it contains (the public data)',
      'The average sensitivity of all data on the system',
      'Whatever level is cheapest to implement',
    ],
    a: 'A',
    wc: 'The high-watermark principle applies the highest level of protection required by the most sensitive data type present on a system.',
    ww: {
      B: 'Protecting to the lowest level would leave the sensitive PII exposed.',
      C: 'Averaging sensitivity under-protects the most sensitive data.',
      D: 'Cost cannot override the protection needs of the most sensitive data.',
    },
    er: 'Tests the high-watermark concept for co-mingled data.',
  },
  {
    t: 'Sensitive Data Types', s: 'Regulated data', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Types of Sensitive Data',
    q: 'Which of the following is an example of "regulated information" that must be handled according to legal requirements?',
    o: [
      'Cardholder data subject to PCI DSS',
      'A blank spreadsheet template',
      'The company lunch menu',
      'A public blog post',
    ],
    a: 'A',
    wc: 'Regulated information includes data governed by laws/standards such as cardholder data under PCI DSS, which mandates specific handling.',
    ww: {
      B: 'A blank template contains no sensitive or regulated content.',
      C: 'A lunch menu is non-sensitive public information.',
      D: 'A public blog post is intentionally public, not regulated sensitive data.',
    },
    er: 'Identifies regulated data via a concrete PCI DSS example.',
  },
  {
    t: 'Asset Classification', s: 'Aligning classification to business', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Classifying Data and Assets',
    q: 'Aligning a classification scheme with business needs primarily helps to:',
    o: [
      'Minimize risk while strengthening security in a way that supports operations',
      'Force every asset into the Top Secret level',
      'Avoid documenting any data at all',
      'Guarantee the organization never needs encryption',
    ],
    a: 'A',
    wc: 'Aligning classification with business needs minimizes risks and strengthens security while supporting business operations.',
    ww: {
      B: 'Over-classifying all assets as Top Secret wastes resources and is not business-aligned.',
      C: 'Classification requires documenting/inventorying data, not avoiding it.',
      D: 'Alignment does not eliminate the need for controls such as encryption.',
    },
    er: 'Connects business-aligned classification to balanced risk reduction.',
  },
  {
    t: 'Asset Classification', s: 'Government classification levels', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Asset Security > Classification Levels',
    q: 'Which TWO of the following are government data classification levels described in the guide? (Select TWO.)',
    o: ['Top Secret', 'Confidential', 'Tier 0 (Essential)', 'Proprietary'],
    a: ['A', 'B'],
    wc: 'Top Secret and Confidential are government classification levels (along with Secret and Unclassified).',
    ww: {
      C: 'Tier 0 (Essential) is an asset tier, not a data classification level.',
      D: 'Proprietary describes a sensitive data type, not a government classification level.',
    },
    er: 'Separates government classification levels from asset tiers and data types.',
  },
];
