// Domain 2 — Part 2: Data roles & responsibilities, handling requirements
// (marking vs labeling), asset management/provisioning/inventory.
module.exports = [
  {
    t: 'Data Roles and Responsibilities', s: 'Data Owner', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    q: 'Which data role holds ultimate responsibility for a data set and typically delegates protection tasks to a custodian?',
    o: ['Data Owner', 'Data Custodian', 'Data Steward', 'Data Subject'],
    a: 'A',
    wc: 'The data owner is responsible for the data (often specialized by type, e.g., financial or medical) and delegates implementation to data custodians.',
    ww: {
      B: 'The custodian implements controls on the owner\'s behalf.',
      C: 'The steward is a subject-matter expert who assists with classification.',
      D: 'The data subject is the individual the data is about / who uses it.',
    },
    er: 'Recall of the owner\'s accountability and delegation to the custodian.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Data Custodian', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    q: 'Who implements the physical, administrative, and logical controls that protect data, working on behalf of the data owner?',
    o: ['Data Custodian', 'Data Owner', 'Data Steward', 'Data Processor'],
    a: 'A',
    wc: 'The data custodian implements physical, administrative, and logical controls on behalf of the owner and manages the technical protection of data.',
    ww: {
      B: 'The owner sets requirements and delegates; it does not necessarily implement controls.',
      C: 'The steward provides subject-matter expertise and assists with classification.',
      D: 'The processor (GDPR) acts on the controller\'s behalf to process data, a distinct role.',
    },
    er: 'Distinguishes the custodian\'s implementation role from the owner and steward.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Data Steward', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    q: 'Which role acts as a subject-matter expert for specific data types and assists in classifying and categorizing the data?',
    o: ['Data Steward', 'Data Custodian', 'Data Subject', 'Senior Management'],
    a: 'A',
    wc: 'The data steward is a subject-matter expert for specific data types who assists with classification and works with both owner and custodian.',
    ww: {
      B: 'The custodian implements technical protection, not SME classification guidance.',
      C: 'The data subject is the individual whose data is processed or a system user.',
      D: 'Senior management is accountable for overall asset management, not data SME work.',
    },
    er: 'Maps SME classification assistance to the steward.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Data Subject', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    q: 'In the guide\'s role model, "data subjects" include which of the following?',
    o: [
      'Human users and non-human entities (applications, scripts) that consume or interact with data',
      'Only senior executives who approve budgets',
      'Only external regulators auditing the system',
      'Only the physical storage hardware',
    ],
    a: 'A',
    wc: 'Data subjects are individuals who consume/interact with data (often "users") and can also include non-human entities such as applications, scripts, or automated processes.',
    ww: {
      B: 'Executives are not the definition of data subjects.',
      C: 'Regulators are external oversight, not data subjects in this model.',
      D: 'Hardware is an asset, not a data subject.',
    },
    er: 'Tests that data subjects/users include automated non-human processes.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Controller vs Processor', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Controllers and Processors (GDPR Focused)',
    q: 'Under the GDPR-focused roles, who determines the purpose and means of processing personal data and bears ultimate responsibility?',
    o: ['Data Controller', 'Data Processor', 'Data Custodian', 'Data Steward'],
    a: 'A',
    wc: 'The data controller determines the purpose and means of processing personal data and holds ultimate responsibility.',
    ww: {
      B: 'The processor acts on the controller\'s behalf to collect, process, and store data.',
      C: 'The custodian is an internal protection-implementation role, not the GDPR controller.',
      D: 'The steward provides data expertise, not processing-purpose decisions.',
    },
    er: 'Distinguishes controller (decides) from processor (acts).',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Controller vs Processor', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Data Controllers and Processors (GDPR Focused)',
    q: 'A cloud analytics vendor collects and processes customer data strictly according to its client\'s instructions. Under GDPR roles, the vendor is the:',
    o: ['Data Processor', 'Data Controller', 'Data Owner', 'Data Steward'],
    a: 'A',
    wc: 'A party that processes personal data on behalf of, and per the instructions of, the controller is the data processor and is liable for breaches during processing.',
    ww: {
      B: 'The controller decides purpose/means; here the vendor follows the client\'s instructions.',
      C: 'Data owner is an internal accountability role, not the GDPR term for this vendor.',
      D: 'A steward provides data expertise, not bulk processing on instruction.',
    },
    er: 'Applies the processor definition to a vendor acting on instructions.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Roles in a network', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Asset Security > Practical Example of Roles in a Network',
    q: 'On a storage server, an analyst decides which encryption and access requirements apply to a financial dataset, while an administrator actually configures the encryption and monitors access. Which roles do they hold, respectively?',
    o: [
      'Data Owner and Data Custodian',
      'Data Custodian and Data Owner',
      'Data Steward and Data Subject',
      'Data Processor and Data Controller',
    ],
    a: 'A',
    wc: 'Setting the security/access requirements is the data owner\'s responsibility; configuring encryption and monitoring access is the custodian\'s implementation role.',
    ww: {
      B: 'This reverses the roles—the decision-maker is the owner, the implementer is the custodian.',
      C: 'A steward is an SME and a subject is a user; neither matches setting requirements vs implementing them.',
      D: 'Controller/processor are GDPR processing roles, not the owner/custodian split described.',
    },
    er: 'Tests applying owner vs custodian in an operational scenario.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Role mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    p: ['Data Owner', 'Data Custodian', 'Data Steward', 'Data Processor'],
    q: 'Match each data role (1-4) to its primary responsibility (A-D).',
    o: [
      'Implements physical, administrative, and logical controls on the owner\'s behalf',
      'Holds ultimate responsibility for the data and sets protection requirements',
      'Processes personal data on behalf of the controller',
      'Serves as subject-matter expert and assists with classification',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Data Owner → ultimate responsibility/sets requirements (B); Data Custodian → implements controls (A); Data Steward → SME/classification help (D); Data Processor → processes data for the controller (C).',
    ww: {},
    er: 'Tests precise mapping of data roles to responsibilities.',
  },
  {
    t: 'Data Roles and Responsibilities', s: 'Distinguishing roles', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Asset Security > Data Roles and Responsibilities',
    q: 'Which TWO statements about data roles are correct? (Select TWO.)',
    o: [
      'The data owner can delegate implementation tasks to a data custodian',
      'The data steward assists with classifying and categorizing data',
      'The data subject sets the organization\'s data classification policy',
      'The data custodian decides the business purpose for collecting personal data',
    ],
    a: ['A', 'B'],
    wc: 'Owners delegate to custodians, and stewards assist with classification/categorization—both correct.',
    ww: {
      C: 'Data subjects are users/individuals; they do not set classification policy.',
      D: 'Deciding the purpose of processing is the controller/owner role, not the custodian.',
    },
    er: 'Reinforces correct responsibilities across the role model.',
  },
  {
    t: 'Handling Requirements', s: 'Marking', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Information and Asset Handling Requirements',
    q: 'Physically identifying an asset with its sensitivity or classification level (for example, a stamped "CONFIDENTIAL" label on a folder) is referred to as:',
    o: ['Marking', 'Labeling', 'Scoping', 'Tailoring'],
    a: 'A',
    wc: 'Marking is the physical identification of an asset with its appropriate sensitivity or classification level.',
    ww: {
      B: 'Labeling is the digital/logical identification (e.g., metadata or watermarks).',
      C: 'Scoping selects which controls apply to a system.',
      D: 'Tailoring modifies baseline controls.',
    },
    er: 'Distinguishes physical marking from logical labeling.',
  },
  {
    t: 'Handling Requirements', s: 'Labeling', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Information and Asset Handling Requirements',
    q: 'Embedding a classification level in a file\'s metadata or as a digital watermark is an example of:',
    o: ['Labeling', 'Marking', 'Degaussing', 'Tokenization'],
    a: 'A',
    wc: 'Labeling is the digital or logical identification of an asset with its sensitivity/classification, implemented through metadata or digital watermarks.',
    ww: {
      B: 'Marking is the physical identification of an asset.',
      C: 'Degaussing is a magnetic data-destruction method.',
      D: 'Tokenization substitutes sensitive data with non-sensitive tokens.',
    },
    er: 'Maps metadata/watermark identification to logical labeling.',
  },
  {
    t: 'Handling Requirements', s: 'Marking vs labeling', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 2 > Asset Security > Information and Asset Handling Requirements',
    q: 'An organization stamps "SECRET" on printed reports and embeds a "SECRET" tag in the metadata of the corresponding electronic files. The printed stamp and the metadata tag represent, respectively:',
    o: [
      'Marking (physical) and labeling (logical)',
      'Labeling (physical) and marking (logical)',
      'Scoping and tailoring',
      'Clearing and purging',
    ],
    a: 'A',
    wc: 'The physical stamp is marking; the electronic metadata tag is labeling (logical identification).',
    ww: {
      B: 'This reverses the definitions—physical is marking, logical is labeling.',
      C: 'Scoping/tailoring are control-selection activities, not handling identification.',
      D: 'Clearing/purging are data-destruction techniques.',
    },
    er: 'Tests the physical-vs-logical distinction in a concrete handling example.',
  },
  {
    t: 'Handling Requirements', s: 'Consistent processes', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Organizational Policies',
    q: 'Why should an organization define a consistent process for marking and labeling assets?',
    o: [
      'To ensure all personnel handle data correctly and support compliance, reducing breach and misuse risk',
      'To make every asset Top Secret regardless of sensitivity',
      'To avoid having to classify data at all',
      'To guarantee assets never need to be inventoried',
    ],
    a: 'A',
    wc: 'A consistent marking/labeling process ensures correct, repeatable handling, supports compliance, and minimizes the risk of breaches or asset misuse.',
    ww: {
      B: 'Consistency is about correct handling, not over-classifying everything.',
      C: 'Consistent handling depends on classification, not its absence.',
      D: 'Inventory remains essential to asset management.',
    },
    er: 'Connects consistent handling processes to compliance and risk reduction.',
  },
  {
    t: 'Handling Requirements', s: 'Backups and copies', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Handling Sensitive Data and Assets',
    q: 'When sensitive data is copied or backed up, those copies should be:',
    o: [
      'Handled and stored according to the same sensitivity/classification as the original',
      'Treated as public since they are duplicates',
      'Stored without any access controls to ease recovery',
      'Exempt from the data retention policy',
    ],
    a: 'A',
    wc: 'Copies and backups must be handled and stored according to the data\'s sensitivity, just like the original.',
    ww: {
      B: 'Copies retain the original\'s sensitivity and are not public.',
      C: 'Backups of sensitive data still require access controls.',
      D: 'Retention policy applies to copies/backups as well.',
    },
    er: 'Reinforces that backups inherit the original data\'s classification and handling.',
  },
  {
    t: 'Asset Management', s: 'Provisioning', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Managing System Assets',
    q: 'In secure asset management, "provisioning" refers to:',
    o: [
      'Creating, managing, and destroying assets throughout their lifecycle',
      'Permanently deleting all backups',
      'Marking assets as public',
      'Auditing financial statements for SOX',
    ],
    a: 'A',
    wc: 'Provisioning involves creating, managing, and destroying assets throughout their lifecycle.',
    ww: {
      B: 'Provisioning covers the full lifecycle, not only deletion of backups.',
      C: 'Marking is a handling activity, not provisioning.',
      D: 'SOX auditing is a compliance activity unrelated to provisioning definition.',
    },
    er: 'Recall of provisioning across the asset lifecycle.',
  },
  {
    t: 'Asset Management', s: 'Asset inventory', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Asset Management Components',
    q: 'An accurate asset inventory is described as crucial primarily because it:',
    o: [
      'Enables effective change control and configuration management by accounting for all assets',
      'Eliminates the need for any security controls',
      'Automatically patches all systems',
      'Replaces the need for data classification',
    ],
    a: 'A',
    wc: 'An accurate inventory is crucial for implementing change control and configuration management and ensures all assets are accounted for throughout their lifecycle.',
    ww: {
      B: 'Inventory supports, but does not replace, security controls.',
      C: 'Inventory tracks assets; it does not perform patching itself.',
      D: 'Inventory and classification are complementary activities.',
    },
    er: 'Links inventory to change/configuration management.',
  },
  {
    t: 'Asset Management', s: 'Responsibilities', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Responsibilities',
    q: 'Who is described as accountable for overall asset management, including IT assets, hardware procurement, and asset disposal?',
    o: ['Senior Management', 'Data Subjects', 'External auditors', 'End users'],
    a: 'A',
    wc: 'Senior management is accountable for overall asset management, including IT assets, hardware, procurement, and disposal.',
    ww: {
      B: 'Data subjects are users/individuals interacting with data.',
      C: 'External auditors verify compliance; they are not accountable for asset management.',
      D: 'End users operate systems but are not accountable for overall asset management.',
    },
    er: 'Assigns overall asset-management accountability to senior management.',
  },
  {
    t: 'Asset Management', s: 'What to track', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 2 > Asset Security > What to Track',
    q: 'Which TWO of the following are HARDWARE assets that should be tracked in an inventory? (Select TWO.)',
    o: ['A firewall appliance', 'A network switch', 'An operating system license key', 'A security awareness policy'],
    a: ['A', 'B'],
    wc: 'Hardware to track includes servers, switches, firewalls, gateways, proxies, and IDS/IPS systems—both a firewall appliance and a network switch qualify.',
    ww: {
      C: 'A license key relates to software, not a hardware asset.',
      D: 'A policy is an administrative document, not a hardware asset.',
    },
    er: 'Distinguishes hardware assets from software and administrative items.',
  },
  {
    t: 'Asset Management', s: 'Automated discovery', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Tools and Techniques for Asset Tracking',
    q: 'Which approach uses tools such as Nmap or OpenVAS to discover hosts and identify operating systems for an asset inventory?',
    o: ['Automated discovery', 'Manual spreadsheet tracking', 'Degaussing', 'Tokenization'],
    a: 'A',
    wc: 'Automated discovery uses tools like Nessus, Nmap, and OpenVAS for host discovery and OS identification.',
    ww: {
      B: 'Manual tracking uses spreadsheets/databases, not automated scanning tools.',
      C: 'Degaussing is a data-destruction method.',
      D: 'Tokenization is a data-protection/declassification technique.',
    },
    er: 'Maps host-discovery tooling to automated asset discovery.',
  },
  {
    t: 'Asset Management', s: 'Inventory integrity', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Organizational Policy and Management',
    q: 'To protect the asset inventory itself, an organization should ensure that:',
    o: [
      'Access to view and modify the inventory is restricted to authorized personnel and changes follow change control',
      'The inventory is publicly editable to encourage updates',
      'The inventory is never updated once created',
      'Anyone may delete entries to keep the list short',
    ],
    a: 'A',
    wc: 'Inventory security and integrity require restricting access/modifications to authorized personnel and managing updates through configuration management and change control.',
    ww: {
      B: 'Public editability destroys integrity and enables tampering.',
      C: 'The inventory must be updated as assets change, via change control.',
      D: 'Uncontrolled deletion undermines accuracy and integrity.',
    },
    er: 'Tests protecting the integrity of the asset inventory.',
  },
  {
    t: 'Asset Management', s: 'Asset lifecycle', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Key Concepts',
    q: 'The asset lifecycle (per NIST SP 1800-5) includes strategy, planning, design, procurement, operation, maintenance, modification, and:',
    o: ['Disposal', 'Marketing', 'Tokenization', 'Phishing'],
    a: 'A',
    wc: 'The asset lifecycle culminates in disposal, completing the cradle-to-grave management of assets.',
    ww: {
      B: 'Marketing is not part of the asset lifecycle.',
      C: 'Tokenization is a data-protection technique, not an asset-lifecycle phase.',
      D: 'Phishing is an attack technique, not a lifecycle phase.',
    },
    er: 'Recall of disposal as the final asset-lifecycle phase.',
  },
  {
    t: 'Handling Requirements', s: 'Regulatory influence', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > Information and Asset Handling Requirements',
    q: 'Regulations such as GDPR and HIPAA most directly influence which aspect of asset security?',
    o: [
      'How data is stored, accessed, transmitted, and destroyed (data handling)',
      'The brand of laptop employees may purchase',
      'The office floor plan layout',
      'The color of classification labels',
    ],
    a: 'A',
    wc: 'Regulations like GDPR and HIPAA shape data-handling practices—storage, access control, transmission, and destruction.',
    ww: {
      B: 'Laptop brand selection is procurement, not regulatory data handling.',
      C: 'Floor plans are facilities matters, not data-handling regulation.',
      D: 'Label color is a cosmetic detail, not the substance of handling rules.',
    },
    er: 'Connects regulations to data-handling requirements.',
  },
  {
    t: 'Asset Management', s: 'Asset details tracked', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 2 > Asset Security > What to Track',
    q: 'Which of the following operational details is appropriate to record for a tracked asset?',
    o: [
      'Purchase/installation date, licensing, location, and baseline configuration',
      'The personal hobbies of the employee who uses it',
      'The asset\'s favorite color',
      'Unrelated marketing slogans',
    ],
    a: 'A',
    wc: 'Operational details to track include purchase/installation dates, licensing, dependencies, location, IP addresses, and baseline configurations.',
    ww: {
      B: 'Personal hobbies are irrelevant to asset tracking.',
      C: 'Assets do not have a "favorite color"; this is not a tracked detail.',
      D: 'Marketing slogans are unrelated to asset records.',
    },
    er: 'Identifies legitimate operational tracking details.',
  },
];
