// Domain 8 — Part 3: Programming languages (compiled/interpreted, generations),
// code libraries/SDK/IDE/runtime, application security testing (SAST/DAST/IAST,
// fuzzing, test types), and software assurance (OWASP ASVS).
module.exports = [
  {
    t: 'Programming Languages', s: 'Compiled vs interpreted', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Compiled vs. Interpreted Languages',
    q: 'A KEY difference between compiled and interpreted languages is that compiled languages:',
    o: [
      'Are translated to machine code before execution, so the source is not distributed to run it',
      'Are always executed line-by-line from source at runtime',
      'Cannot be used to build secure software',
      'Require no translation to run',
    ],
    a: 'A',
    wc: 'Compiled languages are translated to machine code ahead of execution (the distributed artifact is the binary), while interpreted languages are translated/executed at runtime from source.',
    ww: {
      B: 'Line-by-line runtime execution describes interpreted languages.',
      C: 'Both compiled and interpreted languages can build secure software.',
      D: 'Compiled languages require compilation; interpreted require an interpreter.',
    },
    er: 'Distinguishes compiled (pre-translated) from interpreted (runtime) languages.',
  },
  {
    t: 'Programming Languages', s: 'Interpreted security note', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Compiled vs. Interpreted Languages',
    q: 'An interpreted application is distributed as human-readable source. From a security standpoint, what is a notable consideration?',
    o: [
      'The source code (and any embedded secrets) is readable by anyone who obtains it',
      'It is impossible to reverse engineer in any way',
      'It automatically hides all logic from users',
      'It cannot contain vulnerabilities',
    ],
    a: 'A',
    wc: 'Interpreted code is distributed as source, so its logic—and any embedded secrets or vulnerabilities—are directly visible to anyone with the files; secrets must not be hardcoded.',
    ww: {
      B: 'Even compiled binaries can be reverse engineered; interpreted source is trivially readable.',
      C: 'Distributing source exposes, rather than hides, the logic.',
      D: 'Any code can contain vulnerabilities.',
    },
    er: 'Tests the exposure risk of distributing interpreted source.',
  },
  {
    t: 'Programming Languages', s: 'Generations', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Programming Language Generations',
    q: 'In the programming language generations, which generation corresponds to machine language (binary)?',
    o: ['First generation (1GL)', 'Third generation (3GL)', 'Fourth generation (4GL)', 'Fifth generation (5GL)'],
    a: 'A',
    wc: 'First-generation languages (1GL) are machine language (binary) executed directly by hardware; higher generations are progressively more abstract/human-readable.',
    ww: {
      B: '3GLs are high-level languages (e.g., C, Java), not binary.',
      C: '4GLs are higher-level, often domain-specific languages.',
      D: '5GLs are associated with AI/constraint-based programming.',
    },
    er: 'Maps machine language to 1GL.',
  },
  {
    t: 'Programming Languages', s: 'Code libraries', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Code Libraries',
    q: 'Reusable code libraries enhance efficiency and consistency, but from a security perspective they must be:',
    o: [
      'Properly managed and kept updated, since vulnerable libraries introduce supply chain risk',
      'Never updated once included',
      'Trusted blindly regardless of source',
      'Avoided entirely in all software',
    ],
    a: 'A',
    wc: 'Libraries speed development but can carry vulnerabilities; they must be vetted, kept updated, and tracked (supply chain risk management) to remain secure.',
    ww: {
      B: 'Outdated libraries accumulate known vulnerabilities.',
      C: 'Blind trust ignores supply chain risk (e.g., malicious or vulnerable components).',
      D: 'Libraries are valuable; the goal is secure management, not avoidance.',
    },
    er: 'Tests secure management of code libraries.',
  },
  {
    t: 'Programming Languages', s: 'SDK/IDE', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Software Development Kit (SDK)',
    q: 'A Software Development Kit (SDK) typically provides:',
    o: [
      'Tools, libraries, and resources to build applications for a platform (sometimes including third-party resources)',
      'Backup power for build servers',
      'Physical access control to the office',
      'A wireless encryption key',
    ],
    a: 'A',
    wc: 'An SDK bundles tools, libraries, documentation, and sometimes third-party resources to develop for a given platform; an IDE is the integrated coding environment.',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'Physical access control is a facility control.',
      D: 'A wireless key is a network secret.',
    },
    er: 'Recall of the SDK\'s purpose.',
  },
  {
    t: 'Programming Languages', s: 'SDK supply chain', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Software Development Kit (SDK)',
    q: 'A security risk specific to SDKs that include third-party resources is that:',
    o: [
      'Bundled third-party components can introduce vulnerabilities or malicious code (supply chain risk)',
      'They make all code automatically secure',
      'They cannot be scanned for vulnerabilities',
      'They eliminate the need for testing',
    ],
    a: 'A',
    wc: 'SDKs may include third-party libraries/components that carry their own vulnerabilities or malicious code, so they must be vetted and tracked (supply chain risk management).',
    ww: {
      B: 'Including an SDK does not guarantee security.',
      C: 'SDK components can and should be scanned.',
      D: 'Testing is still required when using SDKs.',
    },
    er: 'Tests the third-party supply chain risk of SDKs.',
  },
  // ---- Application security testing ----
  {
    t: 'Application Security Testing', s: 'SAST', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Testing Approaches',
    q: 'Static Application Security Testing (SAST) analyzes:',
    o: [
      'Source code or binaries WITHOUT executing the application',
      'A running application by sending it inputs',
      'Only the network perimeter',
      'Only physical access logs',
    ],
    a: 'A',
    wc: 'SAST (white-box) examines source code/binaries without running the application, finding issues early in development.',
    ww: {
      B: 'Analyzing a running app via inputs is DAST.',
      C: 'Network-perimeter testing is not SAST.',
      D: 'Physical access logs are unrelated to SAST.',
    },
    er: 'Maps non-executing code analysis to SAST.',
  },
  {
    t: 'Application Security Testing', s: 'DAST', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Testing Approaches',
    q: 'Dynamic Application Security Testing (DAST) is BEST described as:',
    o: [
      'Testing a running application from the outside (black-box) by sending inputs and observing behavior',
      'Reading source code statically without running it',
      'A formal code inspection meeting',
      'A disaster recovery drill',
    ],
    a: 'A',
    wc: 'DAST (black-box) tests a running application by sending inputs and observing responses, finding runtime/exploitable issues.',
    ww: {
      B: 'Static source reading is SAST.',
      C: 'A formal inspection is a manual code review (e.g., Fagan).',
      D: 'A DR drill is a continuity exercise.',
    },
    er: 'Maps running-app external testing to DAST.',
  },
  {
    t: 'Application Security Testing', s: 'IAST', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Types of Fuzz Testing',
    q: 'Interactive Application Security Testing (IAST) combines aspects of SAST and DAST by:',
    o: [
      'Instrumenting the running application to observe code behavior during execution/testing',
      'Only reading static source code',
      'Only scanning the network perimeter',
      'Replacing the need for all other testing',
    ],
    a: 'A',
    wc: 'IAST instruments the application (agents inside the running app) to observe code execution during testing, combining static insight with dynamic context.',
    ww: {
      B: 'Static-source-only analysis is SAST.',
      C: 'Perimeter scanning is not IAST.',
      D: 'IAST complements, not replaces, other testing.',
    },
    er: 'Tests the instrumented-runtime nature of IAST.',
  },
  {
    t: 'Application Security Testing', s: 'White box vs black box', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Testing Approaches',
    q: 'A tester is given full access to the application\'s source code and internal design to perform the assessment. This testing approach is:',
    o: ['White box testing', 'Black box testing', 'A reciprocal agreement', 'A tabletop exercise'],
    a: 'A',
    wc: 'White box testing gives the tester full knowledge of internals (source, design); black box provides no internal knowledge.',
    ww: {
      B: 'Black box testing provides no internal knowledge.',
      C: 'A reciprocal agreement is a DR site arrangement.',
      D: 'A tabletop exercise is a DR test.',
    },
    er: 'Maps full-internal-knowledge testing to white box.',
  },
  {
    t: 'Application Security Testing', s: 'Fuzz testing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Additional Types of Software Tests',
    q: 'Fuzz testing assesses software by:',
    o: [
      'Sending invalid, unexpected, or random inputs to find flaws or crashes',
      'Only validating documented happy-path inputs',
      'Reviewing the marketing plan',
      'Encrypting the database',
    ],
    a: 'A',
    wc: 'Fuzz testing injects invalid/unexpected/random inputs to discover vulnerabilities, crashes, or unexpected behavior.',
    ww: {
      B: 'Only happy-path validation misses edge cases fuzzing targets.',
      C: 'Marketing plans are unrelated.',
      D: 'Database encryption is a separate control.',
    },
    er: 'Maps invalid-input testing to fuzzing.',
  },
  {
    t: 'Application Security Testing', s: 'Mutational fuzzing', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Types of Fuzz Testing',
    q: 'Mutational fuzzing generates test inputs by:',
    o: [
      'Mutating existing valid data samples into malformed variants',
      'Building inputs from a formal model of the expected format',
      'Reading the source code only',
      'Encrypting the inputs',
    ],
    a: 'A',
    wc: 'Mutational fuzzing alters existing valid inputs to create malformed test cases (vs. generational/smart fuzzing, which builds inputs from a model).',
    ww: {
      B: 'Building from a model describes generational (smart) fuzzing.',
      C: 'Reading source only is static analysis (SAST).',
      D: 'Fuzzing malforms inputs; it does not encrypt them.',
    },
    er: 'Distinguishes mutational fuzzing (alter valid data).',
  },
  {
    t: 'Application Security Testing', s: 'Testing-type mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 8 > Application Security > Testing Approaches',
    p: ['SAST', 'DAST', 'IAST', 'Fuzz testing'],
    q: 'Match each application security testing technique (1-4) to its description (A-D).',
    o: [
      'Tests a running application from the outside (black-box)',
      'Analyzes code without executing it (white-box)',
      'Sends invalid/random inputs to find flaws',
      'Instruments the running app to observe code during execution',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'SAST → static code analysis (B); DAST → running-app black-box testing (A); IAST → instrumented runtime (D); Fuzz testing → invalid/random inputs (C).',
    ww: {},
    er: 'Tests mapping of application security testing techniques.',
  },
  // ---- Software assurance / ASVS ----
  {
    t: 'Software Assurance', s: 'ASVS Level 3', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > ASVS Assurance Levels',
    q: 'A critical application must defend against advanced persistent threats (APTs) with the most extensive controls. Which OWASP ASVS level applies?',
    o: ['Level 3 (High)', 'Level 1 (Low)', 'Level 2 (Moderate)', 'There is no such standard'],
    a: 'A',
    wc: 'ASVS Level 3 (High) is for applications critical to operations, protecting against advanced threats including APTs, with the most extensive controls.',
    ww: {
      B: 'Level 1 (Low) is the most basic assurance level.',
      C: 'Level 2 (Moderate) defends against most risks but is below the APT-focused Level 3.',
      D: 'OWASP ASVS is a recognized standard.',
    },
    er: 'Maps APT-grade critical apps to ASVS Level 3.',
  },
  {
    t: 'Software Assurance', s: 'ASVS Level 2', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > ASVS Assurance Levels',
    q: 'OWASP ASVS Level 2 (Moderate) is intended to:',
    o: [
      'Defend against most application security risks, including skilled/motivated attackers',
      'Provide only the most basic assurance',
      'Defend only against advanced persistent threats',
      'Eliminate the need for any testing',
    ],
    a: 'A',
    wc: 'ASVS Level 2 is sufficient for most applications, defending against most risks and skilled, motivated attackers (e.g., standard pen-test resistance).',
    ww: {
      B: 'Basic assurance is Level 1.',
      C: 'APT-grade defense is Level 3.',
      D: 'ASVS guides testing requirements; it does not remove testing.',
    },
    er: 'Tests the scope of ASVS Level 2.',
  },
  {
    t: 'Software Assurance', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Software Assurance',
    q: 'Software assurance aims to ensure that software:',
    o: [
      'Functions as intended while protecting against threats and vulnerabilities',
      'Is the cheapest possible to produce',
      'Has the most marketing features',
      'Never needs to be tested',
    ],
    a: 'A',
    wc: 'Software assurance provides confidence that software functions as intended and is protected against threats/vulnerabilities.',
    ww: {
      B: 'Lowest cost is not the goal of assurance.',
      C: 'Marketing features are not software assurance.',
      D: 'Assurance relies on testing, not its absence.',
    },
    er: 'Tests the function-as-intended-and-secure goal of software assurance.',
  },
  {
    t: 'Software Assurance', s: 'Determining ASVS level', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Determining Assurance Levels',
    q: 'The appropriate ASVS assurance level for an application is determined primarily by:',
    o: [
      'The application\'s criticality and risk (informed by the SDLC)',
      'The color of the application\'s logo',
      'The number of developers on the team',
      'The brand of the developers\' laptops',
    ],
    a: 'A',
    wc: 'The required assurance level is chosen based on the application\'s criticality and risk profile, informed by the SDLC—higher risk warrants higher assurance.',
    ww: {
      B: 'Logo color is irrelevant to assurance level.',
      C: 'Team size does not determine the assurance level.',
      D: 'Laptop brand is irrelevant.',
    },
    er: 'Connects ASVS level selection to criticality/risk.',
  },
  {
    t: 'Application Security Testing', s: 'Unit vs integration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Additional Types of Software Tests',
    q: 'Which test verifies that two or more components work correctly TOGETHER?',
    o: ['Integration test', 'Unit test', 'Smoke test', 'Sanity test'],
    a: 'A',
    wc: 'Integration testing verifies that combined components/modules interact correctly; unit testing checks a single component in isolation.',
    ww: {
      B: 'Unit testing checks one component in isolation.',
      C: 'Smoke testing is a quick post-build basic-functionality check.',
      D: 'A sanity test quickly validates a specific feature\'s viability.',
    },
    er: 'Distinguishes integration testing from unit/smoke/sanity.',
  },
  {
    t: 'Programming Languages', s: 'Runtime environment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Runtime Environment',
    q: 'A runtime environment provides:',
    o: [
      'The platform/services in which a program executes (e.g., interpreters, libraries, memory management)',
      'Physical security for the data center',
      'A backup generator',
      'A wireless access point',
    ],
    a: 'A',
    wc: 'A runtime environment supplies the execution platform and services (interpreters/VMs, libraries, memory management) a program relies on at run time.',
    ww: {
      B: 'Physical security is a facility control.',
      C: 'A generator is power equipment.',
      D: 'A WAP is a wireless network device.',
    },
    er: 'Recall of the runtime environment.',
  },
  {
    t: 'Application Security Testing', s: 'Testing approaches', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Application Security > Testing Approaches',
    q: 'Which TWO are recognized application security testing techniques? (Select TWO.)',
    o: ['SAST (static)', 'DAST (dynamic)', 'Degaussing', 'War driving'],
    a: ['A', 'B'],
    wc: 'SAST and DAST (along with IAST and fuzzing) are application security testing techniques.',
    ww: {
      C: 'Degaussing is a media-destruction method.',
      D: 'War driving is a wireless reconnaissance technique.',
    },
    er: 'Identifies application security testing techniques.',
  },
  {
    t: 'Programming Languages', s: 'IDE', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Software Development Kit (SDK)',
    q: 'An Integrated Development Environment (IDE) primarily provides developers with:',
    o: [
      'A unified application combining editor, build tools, and debugger',
      'A backup power supply',
      'A physical door lock',
      'A fire suppression system',
    ],
    a: 'A',
    wc: 'An IDE bundles a code editor, build/compile tools, and a debugger into one application to streamline development.',
    ww: {
      B: 'A backup power supply is a UPS/generator.',
      C: 'A door lock is a physical control.',
      D: 'Fire suppression is a physical safety control.',
    },
    er: 'Recall of the IDE.',
  },
  {
    t: 'Software Assurance', s: 'ASVS Level 1', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > ASVS Assurance Levels',
    q: 'OWASP ASVS Level 1 represents:',
    o: [
      'The lowest/basic security assurance level',
      'The highest assurance level for APT defense',
      'A moderate assurance level',
      'A networking protocol',
    ],
    a: 'A',
    wc: 'ASVS Level 1 is the lowest, basic assurance level; Level 2 is moderate and Level 3 is high (APT-grade).',
    ww: {
      B: 'APT-grade high assurance is Level 3.',
      C: 'Moderate assurance is Level 2.',
      D: 'ASVS is an assurance standard, not a networking protocol.',
    },
    er: 'Recall of ASVS Level 1 as basic assurance.',
  },
  {
    t: 'Application Security Testing', s: 'Approach selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Application Security Testing',
    q: 'A team wants to catch insecure coding patterns as early as possible during development, before the app even runs. Which testing technique fits BEST?',
    o: [
      'SAST (static analysis of source code)',
      'DAST (testing the running application)',
      'A full interruption DR test',
      'War driving',
    ],
    a: 'A',
    wc: 'SAST examines source code without execution, enabling early detection of insecure patterns during development (shift-left).',
    ww: {
      B: 'DAST requires a running application, so it is later than SAST.',
      C: 'A full interruption test is a DR exercise.',
      D: 'War driving is wireless reconnaissance, unrelated to code testing.',
    },
    er: 'Maps earliest pre-runtime code analysis to SAST.',
  },
];
