// Domain 8 — Part 2: DevOps/DevSecOps, CI/CD pipeline security, software
// maturity models (CMM/CMMI/IDEAL/SAMM), O&M & patch management, regression,
// IPT, and code repositories.
module.exports = [
  {
    t: 'DevSecOps', s: 'Concept', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > DevSecOps Overview',
    q: 'DevSecOps differs from DevOps in that DevSecOps:',
    o: [
      'Integrates security into the DevOps pipeline ("security as code"), shifting security left',
      'Removes security entirely to speed delivery',
      'Applies only to hardware manufacturing',
      'Replaces developers with operations staff',
    ],
    a: 'A',
    wc: 'DevSecOps embeds security throughout the DevOps pipeline ("security as code"), automating security testing and shifting security earlier ("shift left").',
    ww: {
      B: 'DevSecOps adds security; it does not remove it.',
      C: 'It applies to software pipelines, not hardware manufacturing.',
      D: 'DevSecOps integrates dev, sec, and ops collaboration—not staff replacement.',
    },
    er: 'Tests the security-integrated nature of DevSecOps.',
  },
  {
    t: 'DevOps', s: 'Access controls', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Security and Access Controls in DevOps',
    q: 'In a DevOps environment, developers gradually accumulate pipeline permissions from past projects. Which controls BEST address this?',
    o: [
      'Enforce least privilege and separation of duties with role-based access to avoid authorization creep',
      'Grant everyone administrator access for convenience',
      'Disable all access controls in the pipeline',
      'Share one privileged account across the team',
    ],
    a: 'A',
    wc: 'Least privilege, separation of duties, and clear role-based access controls prevent authorization (privilege) creep in DevOps pipelines.',
    ww: {
      B: 'Universal admin access violates least privilege and expands risk.',
      C: 'Disabling access controls is dangerous.',
      D: 'A shared privileged account destroys accountability.',
    },
    er: 'Maps authorization-creep mitigation to least privilege/SoD/RBAC.',
  },
  {
    t: 'CI/CD', s: 'Continuous integration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > CI/CD Pipeline and Security Integration',
    q: 'Continuous Integration (CI) primarily involves:',
    o: [
      'Frequently merging code changes into a shared repository with automated build/test',
      'Manually deploying once per year',
      'Avoiding any automated testing',
      'Writing code without version control',
    ],
    a: 'A',
    wc: 'CI frequently integrates code into a shared repo, triggering automated builds and tests to catch issues early.',
    ww: {
      B: 'Annual manual deployment is the opposite of continuous practices.',
      C: 'CI relies on automated testing.',
      D: 'CI depends on version control.',
    },
    er: 'Tests the frequent-merge/automated-test nature of CI.',
  },
  {
    t: 'CI/CD', s: 'Continuous deployment', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > CI/CD Pipeline and Security Integration',
    q: 'How does Continuous Deployment differ from Continuous Delivery?',
    o: [
      'Continuous Deployment automatically releases passing changes to production; Continuous Delivery stops at a deployable artifact awaiting approval',
      'They are identical in every way',
      'Continuous Delivery automatically deploys to production with no gate',
      'Continuous Deployment never tests code',
    ],
    a: 'A',
    wc: 'Continuous Delivery produces a release-ready artifact that requires a manual approval to deploy; Continuous Deployment automatically pushes passing changes all the way to production.',
    ww: {
      B: 'They differ at the final release gate.',
      C: 'Continuous Delivery typically includes an approval gate before production.',
      D: 'Continuous Deployment relies on automated testing to gate releases.',
    },
    er: 'Distinguishes Continuous Deployment (auto-to-prod) from Continuous Delivery (gated).',
  },
  {
    t: 'CI/CD', s: 'Pipeline security', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Security in CI/CD Pipelines',
    q: 'Embedding security into a CI/CD pipeline (DevSecOps) is BEST achieved by:',
    o: [
      'Involving security at each pipeline stage with automated security testing',
      'Running a single manual security review only after release',
      'Removing automated tests to speed the pipeline',
      'Letting only one person see the pipeline',
    ],
    a: 'A',
    wc: 'Security should be involved at every pipeline stage with automated security testing (e.g., SAST/DAST, dependency scanning) so issues are caught continuously.',
    ww: {
      B: 'A single post-release review misses issues introduced earlier.',
      C: 'Removing tests increases the risk of shipping vulnerabilities.',
      D: 'Restricting visibility to one person harms collaboration and review.',
    },
    er: 'Tests integrating automated security throughout CI/CD.',
  },
  {
    t: 'DevOps', s: 'Infrastructure as Code', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > DevOps and DevSecOps',
    q: 'Infrastructure as Code (IaC) improves security and consistency by:',
    o: [
      'Defining infrastructure in version-controlled code so it is repeatable and auditable',
      'Configuring every server manually by hand',
      'Preventing any infrastructure changes',
      'Eliminating the need for access controls',
    ],
    a: 'A',
    wc: 'IaC declares infrastructure in code (version-controlled), enabling consistent, repeatable, auditable, and reviewable provisioning—reducing configuration drift and manual error.',
    ww: {
      B: 'Manual configuration is error-prone and inconsistent—the problem IaC solves.',
      C: 'IaC manages changes; it does not prevent them.',
      D: 'Access controls still apply to IaC pipelines and infrastructure.',
    },
    er: 'Tests the repeatable/auditable benefit of IaC.',
  },
  // ---- Maturity models ----
  {
    t: 'Maturity Models', s: 'CMMI levels', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Capability Maturity Model Integration (CMMI)',
    q: 'The Capability Maturity Model Integration (CMMI) defines how many maturity levels?',
    o: ['Five', 'Three', 'Seven', 'Ten'],
    a: 'A',
    wc: 'CMMI defines five maturity levels (typically Initial, Managed, Defined, Quantitatively Managed, and Optimizing), used to assess and improve process maturity.',
    ww: {
      B: 'CMMI has five, not three, levels.',
      C: 'CMMI has five, not seven, levels.',
      D: 'CMMI has five, not ten, levels.',
    },
    er: 'Recall of CMMI\'s five maturity levels.',
  },
  {
    t: 'Maturity Models', s: 'IDEAL model', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Maturity Models',
    q: 'The IDEAL model\'s five phases stand for:',
    o: [
      'Initiating, Diagnosing, Establishing, Acting, Learning',
      'Identify, Detect, Eradicate, Analyze, Log',
      'Initiate, Develop, Encrypt, Audit, Launch',
      'Inspect, Design, Execute, Approve, List',
    ],
    a: 'A',
    wc: 'IDEAL stands for Initiating, Diagnosing, Establishing, Acting, and Learning—a model for guiding process improvement.',
    ww: {
      B: 'These are not the IDEAL phases.',
      C: 'These are not the IDEAL phases.',
      D: 'These are not the IDEAL phases.',
    },
    er: 'Recall of the IDEAL phases.',
  },
  {
    t: 'Maturity Models', s: 'SAMM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Assurance Maturity Model (SAM)',
    q: 'The OWASP Software Assurance Maturity Model (SAMM) is used to:',
    o: [
      'Analyze and improve an organization\'s software security posture across the SDLC',
      'Encrypt data at rest on servers',
      'Provide backup power to build servers',
      'Route packets between subnets',
    ],
    a: 'A',
    wc: 'OWASP SAMM helps organizations assess and improve their software security posture and integrate security strategy throughout the SDLC.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Packet routing is a network function.',
    },
    er: 'Maps software-security maturity assessment to OWASP SAMM.',
  },
  {
    t: 'Maturity Models', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Maturity Models',
    q: 'Software maturity models are used to:',
    o: [
      'Assess and improve the effectiveness/consistency of an organization\'s software development processes',
      'Encrypt source code automatically',
      'Replace the need for any testing',
      'Provide physical security for data centers',
    ],
    a: 'A',
    wc: 'Maturity models evaluate how effective and consistent development processes are and provide a path to improve them.',
    ww: {
      B: 'They assess processes; they do not encrypt code.',
      C: 'Testing remains necessary regardless of maturity level.',
      D: 'Physical security is unrelated to software maturity models.',
    },
    er: 'Tests the process-improvement purpose of maturity models.',
  },
  // ---- O&M / patch ----
  {
    t: 'Operations and Maintenance', s: 'Patch process order', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 8 > Software Development Security > Patch Management Process',
    q: 'Order the patch management process steps as described in the guide. (Provide the option labels in order.)',
    o: ['Evaluation', 'Testing', 'Approval', 'Rollout', 'Verification'],
    a: 'A,B,C,D,E',
    wc: 'Patch management proceeds: Evaluation, Testing, Approval, Rollout, and Verification.',
    ww: {},
    er: 'Tests the ordered patch management process.',
  },
  {
    t: 'Operations and Maintenance', s: 'Regression testing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Regression and Regression Testing',
    q: 'Regression testing during O&M ensures that:',
    o: [
      'New patches or changes have not broken previously working functionality',
      'The software has the most marketing appeal',
      'No documentation is ever produced',
      'The build server has redundant power',
    ],
    a: 'A',
    wc: 'Regression testing verifies that applied changes/patches have not adversely affected existing functionality.',
    ww: {
      B: 'Marketing appeal is unrelated to regression testing.',
      C: 'Documentation is still valuable; regression testing does not preclude it.',
      D: 'Build-server power is unrelated to regression testing.',
    },
    er: 'Tests the purpose of regression testing.',
  },
  {
    t: 'Operations and Maintenance', s: 'Continuous monitoring', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Continuous Monitoring in O&M',
    q: 'During O&M, continuous monitoring helps identify:',
    o: [
      'Unauthorized patches or backdoors and other emerging security issues',
      'The office holiday schedule',
      'The marketing conversion rate',
      'The cafeteria menu',
    ],
    a: 'A',
    wc: 'Continuous monitoring during O&M can detect unauthorized changes (e.g., rogue patches or backdoors) and emerging vulnerabilities.',
    ww: {
      B: 'Holiday schedules are unrelated.',
      C: 'Marketing metrics are unrelated to O&M monitoring.',
      D: 'The cafeteria menu is irrelevant.',
    },
    er: 'Tests the security value of continuous monitoring in O&M.',
  },
  {
    t: 'Operations and Maintenance', s: 'Patch test before rollout', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Patch Management Process',
    q: 'A vendor releases an urgent security patch for a production application. Before broad rollout, the team should:',
    o: [
      'Test the patch in a non-production environment and obtain approval via change control',
      'Deploy it to production immediately with no testing',
      'Ignore it indefinitely',
      'Apply it only to the developer\'s laptop and consider it done',
    ],
    a: 'A',
    wc: 'Patches should be evaluated, tested in non-production, and approved through change control before rollout and verification—balancing security with stability.',
    ww: {
      B: 'Untested production deployment risks outages from a faulty patch.',
      C: 'Ignoring an urgent security patch leaves a known vulnerability exposed.',
      D: 'Patching one laptop does not protect production systems.',
    },
    er: 'Tests test-then-approve-then-rollout patch practice.',
  },
  // ---- IPT / code repos ----
  {
    t: 'Integrated Product Teams', s: 'Purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Integrated Product Teams',
    q: 'An Integrated Product Team (IPT) brings together which kind of membership to improve outcomes?',
    o: [
      'Cross-functional stakeholders (e.g., development, security, operations, business) collaborating on the product',
      'Only the most senior executive, working alone',
      'Exclusively external contractors with no internal staff',
      'Only the marketing department',
    ],
    a: 'A',
    wc: 'An IPT is a cross-functional team (development, security, operations, business, etc.) that collaborates throughout the product lifecycle to improve quality and alignment.',
    ww: {
      B: 'A lone executive is not a cross-functional team.',
      C: 'IPTs integrate internal stakeholders, not only external contractors.',
      D: 'IPTs span multiple functions, not marketing alone.',
    },
    er: 'Tests the cross-functional nature of IPTs.',
  },
  {
    t: 'Code Repositories', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Code Repositories',
    q: 'A code repository (e.g., using Git) primarily provides:',
    o: [
      'Version control, change tracking, and collaboration for source code',
      'Backup power for build servers',
      'Physical access control to the office',
      'Wireless encryption',
    ],
    a: 'A',
    wc: 'Code repositories manage code versions, track changes, and enable team collaboration (e.g., Git with GitHub/GitLab/Bitbucket).',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'Physical access control is a facility control.',
      D: 'Wireless encryption is WPA2/WPA3.',
    },
    er: 'Tests the version-control/collaboration purpose of code repos.',
  },
  {
    t: 'Code Repositories', s: 'Secrets in repos', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Security Considerations for Code Repositories',
    q: 'A developer is about to commit a file containing API keys and database passwords to a PUBLIC code repository. What is the security concern and best practice?',
    o: [
      'Secrets must not be stored in (especially public) repos; use secret managers and remove/rotate exposed secrets',
      'Public repos automatically encrypt secrets, so it is safe',
      'Hardcoding secrets is fine if the repo is popular',
      'Secrets should always be committed for convenience',
    ],
    a: 'A',
    wc: 'Storing secrets in repositories—especially public ones—exposes them to anyone; secrets should be kept in secret managers, and any exposed secrets must be removed and rotated.',
    ww: {
      B: 'Public repos do not encrypt content; anyone can read committed secrets.',
      C: 'Repo popularity increases, not decreases, exposure risk.',
      D: 'Committing secrets is a serious security mistake.',
    },
    er: 'Tests the no-secrets-in-repos best practice.',
  },
  {
    t: 'Code Repositories', s: 'Git operations', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Basic Git Operations (Example)',
    q: 'In Git, which operation uploads local commits to a remote repository?',
    o: ['git push', 'git init', 'git clone', 'git ignore'],
    a: 'A',
    wc: 'git push uploads local commits to the remote repository; git init creates a new repo and git clone copies a remote repo locally.',
    ww: {
      B: 'git init initializes a new local repository.',
      C: 'git clone copies a remote repository to the local machine.',
      D: '".gitignore" excludes files; "git ignore" is not the push command.',
    },
    er: 'Recall of git push (upload to remote).',
  },
  {
    t: 'DevSecOps', s: 'Shift left', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > DevSecOps Overview',
    q: '"Shifting security left" in DevSecOps means:',
    o: [
      'Addressing security earlier in the development lifecycle rather than only at the end',
      'Moving servers physically to the left side of the room',
      'Deferring security to post-release',
      'Removing security testing entirely',
    ],
    a: 'A',
    wc: 'Shifting left moves security activities earlier (design, coding, build) so issues are found and fixed sooner and more cheaply.',
    ww: {
      B: 'It is a metaphor about timing, not physical placement.',
      C: 'Shifting left is the opposite of deferring security.',
      D: 'It adds earlier security testing, not removes it.',
    },
    er: 'Tests the meaning of shifting security left.',
  },
  {
    t: 'Maturity Models', s: 'CMM purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Maturity Models',
    q: 'The Capability Maturity Model (CMM/SW-CMM) helps an organization to:',
    o: [
      'Assess the maturity of its software process and chart improvements toward higher levels',
      'Encrypt all production traffic',
      'Replace developers with automation entirely',
      'Provide fire suppression in server rooms',
    ],
    a: 'A',
    wc: 'CMM evaluates software-process maturity and provides a staged path to improve process capability over time.',
    ww: {
      B: 'Traffic encryption is a separate control.',
      C: 'CMM improves processes; it does not replace developers.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Tests the maturity-assessment purpose of CMM.',
  },
  {
    t: 'CI/CD', s: 'Pipeline benefits', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Software Development Security > Security in CI/CD Pipelines',
    q: 'Which TWO are benefits of a well-designed CI/CD pipeline with integrated security? (Select TWO.)',
    o: [
      'Faster, more consistent and repeatable releases',
      'Earlier detection of vulnerabilities through automated security testing',
      'Elimination of the need for any version control',
      'Removal of all human oversight from releases',
    ],
    a: ['A', 'B'],
    wc: 'CI/CD with integrated security yields faster, repeatable releases and earlier vulnerability detection via automated testing.',
    ww: {
      C: 'CI/CD depends on version control, not its elimination.',
      D: 'Human oversight/approval gates remain important, especially for production.',
    },
    er: 'Identifies CI/CD-with-security benefits.',
  },
  {
    t: 'DevOps', s: 'DevOps definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > DevOps and DevSecOps',
    q: 'DevOps primarily aims to:',
    o: [
      'Unify software development and IT operations to deliver software faster and more reliably',
      'Separate developers and operations into isolated silos',
      'Eliminate the need for testing',
      'Replace all software with hardware',
    ],
    a: 'A',
    wc: 'DevOps integrates development and operations (culture, practices, automation) to accelerate and stabilize software delivery.',
    ww: {
      B: 'DevOps breaks down silos rather than reinforcing them.',
      C: 'DevOps emphasizes automated testing, not its removal.',
      D: 'DevOps is about software delivery practices, not replacing software with hardware.',
    },
    er: 'Tests the dev+ops unification goal of DevOps.',
  },
  {
    t: 'Operations and Maintenance', s: 'CM in patching', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Operations And Maintenance',
    q: 'Why is configuration management important to patch management during O&M?',
    o: [
      'It ensures patches are tracked and applied consistently against known baselines, preventing drift',
      'It eliminates the need to ever test patches',
      'It allows untracked ad-hoc changes',
      'It encrypts the office Wi-Fi',
    ],
    a: 'A',
    wc: 'Configuration management tracks system baselines and changes, ensuring patches are applied consistently and that configuration drift/unauthorized changes are detected.',
    ww: {
      B: 'Patches still require testing.',
      C: 'CM exists to control changes, not permit untracked ones.',
      D: 'Wi-Fi encryption is unrelated to CM in patching.',
    },
    er: 'Connects configuration management to consistent patching.',
  },
];
