// Domain 8 — Part 1: SDLC phases, development methodologies (Waterfall, Spiral,
// Incremental, Cleanroom, JAD, RAD), and Agile (values, principles, Scrum).
module.exports = [
  {
    t: 'SDLC', s: 'Security integration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Development Lifecycle',
    q: 'A core principle for secure software development is that security and privacy should be:',
    o: [
      'Integrated at every phase of the SDLC, not bolted on at the end',
      'Added only after the software is in production',
      'Considered only during the disposal phase',
      'Left entirely to the end users',
    ],
    a: 'A',
    wc: 'Security and privacy must be built in at every SDLC phase (requirements through disposal); change control is especially critical during O&M.',
    ww: {
      B: 'Bolting on security post-production is costly and leaves gaps.',
      C: 'Security must apply throughout, not only at disposal.',
      D: 'Security is a shared responsibility led by the development organization.',
    },
    er: 'Tests the build-security-in-at-every-phase principle.',
  },
  {
    t: 'SDLC', s: 'Phases order', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 8 > Software Development Security > Key Phases of SDLC',
    q: 'Order the following SDLC phases from earliest to latest. (Provide the option labels in order.)',
    o: ['Requirements/Initiation', 'Design', 'Development', 'Testing', 'Deployment', 'Operations and Maintenance', 'Disposal'],
    a: 'A,B,C,D,E,F,G',
    wc: 'The SDLC proceeds from requirements/initiation, to design, development, testing, deployment, operations & maintenance, and finally disposal.',
    ww: {},
    er: 'Tests the ordered SDLC phases.',
  },
  {
    t: 'SDLC', s: 'O&M change control', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Important Considerations',
    q: 'During the Operations and Maintenance (O&M) phase, which control is described as especially critical?',
    o: ['Change control', 'Marketing analysis', 'Office space planning', 'Recruitment'],
    a: 'A',
    wc: 'Change control is critical during O&M to ensure updates/patches do not introduce security weaknesses or instability.',
    ww: {
      B: 'Marketing analysis is unrelated to O&M security.',
      C: 'Office planning is a facilities task.',
      D: 'Recruitment is an HR function.',
    },
    er: 'Maps O&M-phase rigor to change control.',
  },
  {
    t: 'Methodologies', s: 'Waterfall', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Development Methodologies Part 1',
    q: 'The Waterfall model is characterized by:',
    o: [
      'A sequential approach where each phase is completed before the next begins (with limited feedback loops)',
      'Continuous, overlapping iterations with no defined phases',
      'Delivering working software every two weeks by default',
      'No documentation at any stage',
    ],
    a: 'A',
    wc: 'Waterfall is a sequential model: one phase must finish before the next starts, with only limited feedback (e.g., testing back to a prior step). Its rigidity is a noted drawback.',
    ww: {
      B: 'Continuous overlapping iteration describes Agile, not Waterfall.',
      C: 'Two-week deliveries describe Agile sprints.',
      D: 'Waterfall is documentation-heavy, not documentation-free.',
    },
    er: 'Tests the sequential nature of Waterfall.',
  },
  {
    t: 'Methodologies', s: 'Spiral model', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Increment Build Model',
    q: 'The Spiral model is BEST known for:',
    o: [
      'Emphasizing iterative development with repeated risk analysis in each cycle',
      'Forbidding any iteration or feedback',
      'Eliminating the need for requirements',
      'Being identical to Waterfall',
    ],
    a: 'A',
    wc: 'The Spiral model combines iterative development with explicit, repeated risk analysis at each loop/cycle, making it well-suited to high-risk projects.',
    ww: {
      B: 'The Spiral model is inherently iterative.',
      C: 'Requirements are still essential in the Spiral model.',
      D: 'It differs from Waterfall by adding iteration and risk focus.',
    },
    er: 'Maps repeated risk analysis to the Spiral model.',
  },
  {
    t: 'Methodologies', s: 'Cleanroom', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Development Methodologies Part 2',
    q: 'The Cleanroom development model focuses primarily on:',
    o: [
      'Preventing defects through rigorous design/verification rather than relying on after-the-fact testing',
      'Rapidly prototyping with end users in JAD sessions',
      'Skipping design to start coding immediately',
      'Outsourcing all development overseas',
    ],
    a: 'A',
    wc: 'Cleanroom emphasizes defect prevention and correctness via formal methods and rigorous review, aiming to avoid introducing defects rather than finding them later.',
    ww: {
      B: 'Rapid prototyping with users describes RAD/JAD.',
      C: 'Cleanroom is design-rigorous, not design-skipping.',
      D: 'Outsourcing is unrelated to the Cleanroom approach.',
    },
    er: 'Maps defect prevention/correctness to the Cleanroom model.',
  },
  {
    t: 'Methodologies', s: 'JAD', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Joint Application Development (JAD) Model',
    q: 'The Joint Application Development (JAD) model is characterized by:',
    o: [
      'Structured collaborative workshops/sessions involving stakeholders to define requirements',
      'A purely solo developer working in isolation',
      'Never involving the customer',
      'Eliminating all requirements gathering',
    ],
    a: 'A',
    wc: 'JAD uses facilitated, collaborative sessions ("JAD sessions") with stakeholders to rapidly define and refine requirements together.',
    ww: {
      B: 'JAD is collaborative, not solo.',
      C: 'JAD specifically involves stakeholders/customers.',
      D: 'JAD is a requirements-gathering technique, not its elimination.',
    },
    er: 'Maps collaborative requirement workshops to JAD.',
  },
  {
    t: 'Methodologies', s: 'RAD', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Rapid Application Development (RAD) Model',
    q: 'A team needs to quickly produce a working prototype to validate an idea with users, iterating fast. Which methodology is MOST suited?',
    o: [
      'Rapid Application Development (RAD)',
      'Strict sequential Waterfall',
      'Cleanroom with formal verification only',
      'No methodology at all',
    ],
    a: 'A',
    wc: 'RAD emphasizes rapid prototyping and iteration (often with JAD and CASE tools), ideal for quickly building and validating prototypes.',
    ww: {
      B: 'Waterfall\'s rigidity is poorly suited to rapid prototyping.',
      C: 'Cleanroom prioritizes formal correctness over rapid prototyping.',
      D: 'Skipping methodology invites disorganized, risky development.',
    },
    er: 'Maps rapid prototyping needs to RAD.',
  },
  {
    t: 'Methodologies', s: 'Incremental build', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Increment Build Model',
    q: 'The Incremental Build model develops software by:',
    o: [
      'Building it in smaller, manageable increments, learning from each to improve the next',
      'Delivering the entire system only once at the very end',
      'Avoiding any system engineering',
      'Prohibiting changes between increments',
    ],
    a: 'A',
    wc: 'The Incremental Build model constructs software in increments, allowing learning from prior increments to improve later ones (it resembles Agile but predates it).',
    ww: {
      B: 'A single end delivery describes Waterfall, not incremental build.',
      C: 'It enables system engineering during analysis/design.',
      D: 'Incremental development specifically adapts based on prior increments.',
    },
    er: 'Maps incremental, learn-as-you-go development to the Incremental Build model.',
  },
  {
    t: 'Agile', s: 'Core values', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Agile Development',
    q: 'Which statement reflects a core value of the Agile Manifesto?',
    o: [
      'Responding to change over following a rigid plan',
      'Comprehensive documentation over working software',
      'Contract negotiation over customer collaboration',
      'Processes and tools over individuals and interactions',
    ],
    a: 'A',
    wc: 'Agile values responding to change over following a plan (and individuals/interactions, working software, and customer collaboration over their counterparts).',
    ww: {
      B: 'Agile values working software over comprehensive documentation.',
      C: 'Agile values customer collaboration over contract negotiation.',
      D: 'Agile values individuals and interactions over processes and tools.',
    },
    er: 'Tests an Agile core value.',
  },
  {
    t: 'Agile', s: 'Security in Agile', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Security in Agile',
    q: 'A team is adopting Agile and wants to ensure security keeps pace with rapid iterations. The BEST approach is to:',
    o: [
      'Define security controls upfront and integrate them (and configuration management) into the Agile process',
      'Defer all security work until a final security phase after release',
      'Skip security because Agile moves too fast for it',
      'Let each developer decide security individually with no standards',
    ],
    a: 'A',
    wc: 'Security should be defined upfront and integrated into each iteration (along with configuration management), rather than deferred—keeping security continuous in Agile.',
    ww: {
      B: 'Deferring security to a final phase contradicts Agile\'s iterative delivery and leaves risk.',
      C: 'Agile and security are compatible; security must be integrated, not skipped.',
      D: 'Ad-hoc per-developer security yields inconsistent, weak controls.',
    },
    er: 'Tests integrating security into Agile iterations.',
  },
  {
    t: 'Agile', s: 'Scrum roles', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Scrum Methodology in Agile',
    q: 'In Scrum, which role is primarily responsible for facilitating the process and removing impediments for the team?',
    o: ['Scrum Master', 'Product Owner', 'Database Administrator', 'Chief Financial Officer'],
    a: 'A',
    wc: 'The Scrum Master facilitates the Scrum process and removes impediments; the Product Owner manages the backlog/priorities, and the development team builds the product.',
    ww: {
      B: 'The Product Owner owns the backlog and priorities, not impediment removal/facilitation.',
      C: 'A DBA is not a defined Scrum role.',
      D: 'A CFO is not a Scrum role.',
    },
    er: 'Maps facilitation/impediment removal to the Scrum Master.',
  },
  {
    t: 'Agile', s: 'Sprint retrospective', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Sprint Lifecycle and Process',
    q: 'The Sprint Retrospective in Scrum is used to:',
    o: [
      'Reflect on the completed sprint and identify process improvements for the next one',
      'Demonstrate the product to customers',
      'Write the initial requirements',
      'Deploy code to production automatically',
    ],
    a: 'A',
    wc: 'The retrospective is a continuous-improvement ceremony where the team reflects on what went well/poorly and adjusts for the next sprint.',
    ww: {
      B: 'Demonstrating the product is the sprint review.',
      C: 'Initial requirements precede sprints (in the backlog).',
      D: 'Automated deployment is a CI/CD activity, not the retrospective.',
    },
    er: 'Tests the improvement purpose of the retrospective.',
  },
  {
    t: 'Methodologies', s: 'Methodology selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Choosing a Development Methodology (Review)',
    q: 'A project has stable, well-understood, unchanging requirements and strict documentation needs (e.g., a regulated system). Which methodology is MOST appropriate?',
    o: [
      'Waterfall (sequential, well-documented)',
      'Pure Agile with no fixed requirements',
      'Ad-hoc development with no plan',
      'RAD with constant requirement churn',
    ],
    a: 'A',
    wc: 'Waterfall suits projects with stable, well-defined requirements and heavy documentation/regulatory needs, where sequential phases work well.',
    ww: {
      B: 'Agile shines with evolving requirements; here requirements are stable/fixed.',
      C: 'Ad-hoc development lacks the rigor regulated systems require.',
      D: 'RAD\'s rapid churn fits prototyping, not a stable, documentation-heavy effort.',
    },
    er: 'Maps stable, documentation-heavy requirements to Waterfall.',
  },
  {
    t: 'Agile', s: 'Agile principles', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Software Development Security > Agile Manifesto - 12 Principles',
    q: 'Which TWO are principles of the Agile Manifesto? (Select TWO.)',
    o: [
      'Deliver working software frequently',
      'Welcome changing requirements, even late in development',
      'Resist any requirement changes after the start',
      'Measure progress only by lines of documentation',
    ],
    a: ['A', 'B'],
    wc: 'Agile principles include delivering working software frequently and welcoming changing requirements; working software (not documentation volume) measures progress.',
    ww: {
      C: 'Agile welcomes requirement changes rather than resisting them.',
      D: 'Working software, not documentation volume, measures progress.',
    },
    er: 'Identifies Agile Manifesto principles.',
  },
  {
    t: 'Methodologies', s: 'Methodology mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 8 > Software Development Security > Choosing a Development Methodology (Review)',
    p: ['Waterfall', 'Spiral', 'RAD', 'Cleanroom'],
    q: 'Match each development methodology (1-4) to its defining characteristic (A-D).',
    o: [
      'Iterative cycles with repeated risk analysis',
      'Sequential phases completed one before the next',
      'Defect prevention through rigorous verification',
      'Rapid prototyping, often with JAD and CASE tools',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Waterfall → sequential phases (B); Spiral → iterative with risk analysis (A); RAD → rapid prototyping with JAD/CASE (D); Cleanroom → defect prevention via verification (C).',
    ww: {},
    er: 'Tests mapping of methodologies to their characteristics.',
  },
  {
    t: 'Agile', s: 'Agile core values', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Software Development Security > Agile Development',
    q: 'Which TWO are Agile core values (the preferred side of the comparison)? (Select TWO.)',
    o: [
      'Individuals and interactions (over processes and tools)',
      'Working software (over comprehensive documentation)',
      'Following a fixed plan (over responding to change)',
      'Contract negotiation (over customer collaboration)',
    ],
    a: ['A', 'B'],
    wc: 'Agile values individuals/interactions and working software (also customer collaboration and responding to change) over their counterparts.',
    ww: {
      C: 'Agile values responding to change over following a fixed plan.',
      D: 'Agile values customer collaboration over contract negotiation.',
    },
    er: 'Identifies the preferred Agile values.',
  },
  {
    t: 'Methodologies', s: 'Waterfall drawback', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Development Methodologies Part 1',
    q: 'A noted drawback of the Waterfall model is that:',
    o: [
      'It is rigid—changes are difficult and costly once later phases begin',
      'It delivers software too frequently',
      'It has no defined phases',
      'It requires no planning',
    ],
    a: 'A',
    wc: 'Waterfall\'s sequential rigidity makes accommodating changes late in the project difficult and expensive, a primary drawback.',
    ww: {
      B: 'Waterfall delivers once at the end, not frequently.',
      C: 'Waterfall has clearly defined sequential phases.',
      D: 'Waterfall is planning-heavy, not planning-free.',
    },
    er: 'Tests the rigidity drawback of Waterfall.',
  },
  {
    t: 'SDLC', s: 'Disposal phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Software Development Lifecycle',
    q: 'Security activities during the SDLC disposal phase should ensure that:',
    o: [
      'Data is securely sanitized and the system is decommissioned without leaving recoverable sensitive data',
      'New features are added before retirement',
      'The system runs indefinitely without review',
      'Source code is published publicly by default',
    ],
    a: 'A',
    wc: 'The disposal phase securely sanitizes/destroys data and decommissions the system so no sensitive data remains recoverable.',
    ww: {
      B: 'Adding features is a development/maintenance activity, not disposal.',
      C: 'Disposal ends the system\'s life rather than running it forever.',
      D: 'Publishing source by default is not a disposal security goal.',
    },
    er: 'Tests secure data handling at the disposal phase.',
  },
  {
    t: 'Agile', s: 'Other Agile methods', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > Other Agile Methodologies',
    q: 'Which of the following is an Agile methodology/variant?',
    o: ['Scrum', 'Waterfall', 'Cleanroom', 'JAD'],
    a: 'A',
    wc: 'Scrum is a widely used Agile framework; Waterfall, Cleanroom, and JAD are non-Agile (or pre-Agile) approaches.',
    ww: {
      B: 'Waterfall is a sequential, non-Agile model.',
      C: 'Cleanroom emphasizes formal defect prevention, not Agile iteration.',
      D: 'JAD is a collaborative requirements technique, not an Agile framework.',
    },
    er: 'Identifies Scrum as an Agile methodology.',
  },
  {
    t: 'SDLC', s: 'NIST SDLC guidance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Software Development Security > NIST Special Publications',
    q: 'NIST publications on the SDLC emphasize that across the lifecycle phases, organizations should:',
    o: [
      'Integrate security and privacy considerations consistently into each phase',
      'Treat security as optional after deployment',
      'Avoid documenting any phase outputs',
      'Skip testing to accelerate delivery',
    ],
    a: 'A',
    wc: 'NIST SDLC guidance stresses integrating security and privacy at every phase, with consistent processes and documented phase outputs.',
    ww: {
      B: 'Security is not optional; it must be continuous.',
      C: 'Documenting phase outputs is part of sound SDLC practice.',
      D: 'Skipping testing increases the risk of vulnerabilities.',
    },
    er: 'Reinforces consistent security integration per NIST SDLC guidance.',
  },
  {
    t: 'Agile', s: 'Welcoming change', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Software Development Security > Agile Manifesto - 12 Principles',
    q: 'Midway through development, a key customer requirement changes significantly. How does an Agile team ideally respond, per Agile principles?',
    o: [
      'Welcome the change and incorporate it in an upcoming iteration, even late in development',
      'Refuse the change because the plan is fixed',
      'Cancel the project entirely',
      'Ignore the customer and ship the original scope',
    ],
    a: 'A',
    wc: 'Agile welcomes changing requirements—even late—harnessing change for the customer\'s competitive advantage by incorporating it in an upcoming iteration.',
    ww: {
      B: 'Refusing change contradicts Agile\'s responding-to-change value.',
      C: 'Canceling overreacts; Agile adapts to change.',
      D: 'Ignoring the customer contradicts customer collaboration.',
    },
    er: 'Tests Agile\'s welcoming of late requirement changes.',
  },
];
