// Domain 8 — Part 4: Application attacks (injection, hijacking, rootkit,
// privilege escalation, TOCTOU), OWASP Top 10, secure coding & API security,
// and acquired software security (COTS/OSS/GOTS/NDI, NIST acquisition).
module.exports = [
  // ---- Application attacks ----
  {
    t: 'Application Attacks', s: 'SQL injection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Injection Attacks',
    q: 'SQL injection occurs when:',
    o: [
      'Untrusted input is included in a database query, allowing an attacker to run unauthorized SQL',
      'A user changes the wireless encryption key',
      'A backup tape is degaussed',
      'A server loses power',
    ],
    a: 'A',
    wc: 'SQL injection sends crafted untrusted input that a web application incorporates into a database query, letting an attacker execute unauthorized SQL commands.',
    ww: {
      B: 'Changing a wireless key is unrelated to SQL injection.',
      C: 'Degaussing destroys magnetic media.',
      D: 'Power loss is unrelated to injection attacks.',
    },
    er: 'Recall of SQL injection.',
  },
  {
    t: 'Application Attacks', s: 'Injection mitigation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Mitigations for Injection Attacks',
    q: 'A web app builds SQL queries by concatenating user input. Which control MOST directly prevents SQL injection?',
    o: [
      'Input validation plus parameterized queries/approved stored procedures',
      'Disabling logging on the database',
      'Using a faster database server',
      'Increasing the office Wi-Fi range',
    ],
    a: 'A',
    wc: 'Validating input and using parameterized queries/whitelisted stored procedures (so input is treated as data, not executable SQL) directly prevent SQL injection.',
    ww: {
      B: 'Disabling logging hides activity and does not prevent injection.',
      C: 'A faster server does not address the injection vulnerability.',
      D: 'Wi-Fi range is unrelated to injection defense.',
    },
    er: 'Maps injection prevention to input validation + parameterized queries.',
  },
  {
    t: 'Application Attacks', s: 'LDAP/XML injection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Injection Attacks',
    q: 'LDAP injection differs from SQL injection in that LDAP injection targets:',
    o: [
      'A directory server (e.g., LDAP/Active Directory) rather than a SQL database',
      'A wireless access point',
      'A backup generator',
      'A fire suppression system',
    ],
    a: 'A',
    wc: 'LDAP injection submits unauthorized queries to a directory server (LDAP/Active Directory); SQL injection targets relational databases; both exploit unvalidated input.',
    ww: {
      B: 'A WAP is a wireless device, not a directory server.',
      C: 'A generator is power equipment.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Distinguishes LDAP injection (directory) from SQL injection (database).',
  },
  {
    t: 'Application Attacks', s: 'Cross-site scripting', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'Cross-Site Scripting (XSS) primarily allows an attacker to:',
    o: [
      'Inject malicious scripts that run in other users\' browsers via a vulnerable web app',
      'Physically enter a secure facility',
      'Drain a UPS battery',
      'Reformat a hard drive remotely with no access',
    ],
    a: 'A',
    wc: 'XSS injects attacker-controlled scripts that execute in victims\' browsers (e.g., to steal sessions/data); output encoding and input validation mitigate it.',
    ww: {
      B: 'XSS is a web attack, not physical entry.',
      C: 'XSS does not drain batteries.',
      D: 'XSS does not reformat drives without access.',
    },
    er: 'Recall of XSS (script injection into users\' browsers).',
  },
  {
    t: 'Application Attacks', s: 'Session hijacking', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Hijacking Attacks',
    q: 'Session hijacking takes over an active session by:',
    o: [
      'Stealing/replaying session tokens, cookies, or credentials',
      'Physically removing the server',
      'Degaussing a backup tape',
      'Disabling the air conditioning',
    ],
    a: 'A',
    wc: 'Session hijacking uses stolen session tokens/cookies/credentials (sometimes via replay) to assume a legitimate user\'s active session.',
    ww: {
      B: 'Physically removing a server is theft, not session hijacking.',
      C: 'Degaussing destroys media.',
      D: 'Disabling AC is an environmental disruption, unrelated to sessions.',
    },
    er: 'Maps stolen-token session takeover to session hijacking.',
  },
  {
    t: 'Application Attacks', s: 'TOCTOU', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Rootkit Attacks',
    q: 'An attacker alters a file AFTER an application checks its permissions but BEFORE the application uses it, exploiting the timing gap. This is a:',
    o: [
      'Time-of-Check to Time-of-Use (TOCTOU) race-condition attack',
      'SQL injection',
      'Cross-site scripting',
      'War driving',
    ],
    a: 'A',
    wc: 'A TOCTOU attack exploits a race condition by changing a resource between the moment it is checked and the moment it is used, altering the outcome.',
    ww: {
      B: 'SQL injection manipulates database queries, not check/use timing.',
      C: 'XSS injects scripts into browsers.',
      D: 'War driving is wireless reconnaissance.',
    },
    er: 'Maps a check-then-use race condition to TOCTOU.',
  },
  {
    t: 'Application Attacks', s: 'Privilege escalation', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Rootkit Attacks',
    q: 'Vertical privilege escalation occurs when an attacker:',
    o: [
      'Gains higher privileges (e.g., from a normal user to administrator)',
      'Moves laterally to another account at the same privilege level',
      'Encrypts files for ransom',
      'Sends spam over instant messaging',
    ],
    a: 'A',
    wc: 'Vertical privilege escalation raises the attacker\'s privilege level (e.g., user to admin); horizontal escalation moves laterally at the same level.',
    ww: {
      B: 'Same-level lateral movement is horizontal privilege escalation.',
      C: 'Encrypting files for ransom is ransomware.',
      D: 'Spam over IM is spim, unrelated to escalation.',
    },
    er: 'Distinguishes vertical (gain higher) from horizontal escalation.',
  },
  {
    t: 'Application Attacks', s: 'Rootkit detection', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Rootkit Attacks',
    q: 'Rootkits, which provide stealthy root/admin-level access, are BEST detected by:',
    o: [
      'Host-based intrusion detection systems (HIDS)',
      'A taller perimeter fence',
      'A backup generator',
      'A wireless access point',
    ],
    a: 'A',
    wc: 'Because rootkits embed deep in the host (OS, boot sector, firmware), host-based IDS (HIDS) is best positioned to detect their presence/changes.',
    ww: {
      B: 'A fence is a physical control, irrelevant to rootkit detection.',
      C: 'A generator provides power.',
      D: 'A WAP is a wireless network device.',
    },
    er: 'Maps rootkit detection to HIDS.',
  },
  {
    t: 'Application Attacks', s: 'Backdoor', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Hijacking Attacks',
    q: 'A backdoor in software is:',
    o: [
      'A means of bypassing normal authentication, sometimes left by developers for maintenance',
      'A standard secure login mechanism',
      'A type of fire suppression',
      'A backup power source',
    ],
    a: 'A',
    wc: 'A backdoor bypasses normal authentication to grant access; developers may leave them for maintenance, but they are a serious security risk if discovered/abused.',
    ww: {
      B: 'A backdoor circumvents, rather than provides, secure authentication.',
      C: 'Fire suppression is a physical control.',
      D: 'A backdoor is not a power source.',
    },
    er: 'Recall of a backdoor (auth bypass).',
  },
  {
    t: 'Application Attacks', s: 'Attack-to-description mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 8 > Application Security > Application Attacks',
    p: ['SQL injection', 'Cross-site scripting (XSS)', 'TOCTOU', 'Session hijacking'],
    q: 'Match each application attack (1-4) to its description (A-D).',
    o: [
      'Runs malicious scripts in other users\' browsers',
      'Runs unauthorized SQL via untrusted input',
      'Takes over an active session using stolen tokens',
      'Exploits a race condition between check and use',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'SQL injection → unauthorized SQL via input (B); XSS → scripts in users\' browsers (A); TOCTOU → check/use race condition (D); Session hijacking → stolen-token session takeover (C).',
    ww: {},
    er: 'Tests mapping of application attacks to descriptions.',
  },
  // ---- OWASP Top 10 / secure coding ----
  {
    t: 'OWASP Top 10', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'The OWASP Top 10 is BEST described as:',
    o: [
      'A list of the most critical web application security risks',
      'A wireless encryption standard',
      'A backup rotation schedule',
      'A physical access control model',
    ],
    a: 'A',
    wc: 'The OWASP Top 10 ranks the most critical web application security risks (e.g., injection, broken access control), guiding secure development.',
    ww: {
      B: 'Wireless encryption standards are WPA2/WPA3.',
      C: 'Backup rotation is an operations schedule.',
      D: 'Physical access models are unrelated to OWASP Top 10.',
    },
    er: 'Recall of the OWASP Top 10\'s purpose.',
  },
  {
    t: 'OWASP Top 10', s: 'Broken access control', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'A user changes the account ID in a URL and gains access to another user\'s data. Which OWASP category does this represent?',
    o: ['Broken access control', 'A backup failure', 'A power surge', 'A wireless jamming attack'],
    a: 'A',
    wc: 'Accessing another user\'s data by manipulating a parameter is broken access control (e.g., insecure direct object reference)—a top OWASP risk.',
    ww: {
      B: 'A backup failure is an availability/recovery issue.',
      C: 'A power surge is an electrical anomaly.',
      D: 'Wireless jamming is a network DoS.',
    },
    er: 'Maps unauthorized data access via parameter tampering to broken access control.',
  },
  {
    t: 'OWASP Top 10', s: 'SSRF', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'Server-Side Request Forgery (SSRF), added in the OWASP 2021 list, allows an attacker to:',
    o: [
      'Make the server send crafted requests to unintended internal/external resources',
      'Physically unlock a door',
      'Encrypt all backups',
      'Drain a UPS battery',
    ],
    a: 'A',
    wc: 'SSRF abuses a server\'s ability to make requests, tricking it into accessing unintended internal/external resources (e.g., internal metadata services).',
    ww: {
      B: 'SSRF is a web attack, not a physical door control.',
      C: 'SSRF does not encrypt backups.',
      D: 'SSRF does not drain batteries.',
    },
    er: 'Recall of SSRF.',
  },
  {
    t: 'OWASP Top 10', s: '2021 additions', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'Which TWO risks were notably added/elevated in the OWASP Top 10 2021 list? (Select TWO.)',
    o: ['Insecure design', 'Server-Side Request Forgery (SSRF)', 'Wet-pipe sprinkler failure', 'UPS battery aging'],
    a: ['A', 'B'],
    wc: 'The 2021 OWASP Top 10 added insecure design and SSRF (among reorganizations); the others are physical/facility issues.',
    ww: {
      C: 'Sprinkler failure is a physical fire-safety issue.',
      D: 'UPS battery aging is a power-equipment concern.',
    },
    er: 'Identifies 2021 OWASP additions.',
  },
  {
    t: 'Secure Coding', s: 'Input validation', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Secure Coding Practices',
    q: 'Which is a fundamental secure coding practice that defends against many injection attacks?',
    o: [
      'Validating and sanitizing all untrusted input',
      'Trusting all user input by default',
      'Disabling error handling entirely',
      'Hardcoding admin passwords in the source',
    ],
    a: 'A',
    wc: 'Input validation/sanitization (treating untrusted input as untrusted) is a core secure-coding practice that mitigates injection and related attacks.',
    ww: {
      B: 'Trusting all input invites injection and other attacks.',
      C: 'Proper error handling is itself a secure-coding practice.',
      D: 'Hardcoding credentials is a serious vulnerability.',
    },
    er: 'Maps injection defense to input validation.',
  },
  {
    t: 'Secure Coding', s: 'Error handling', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Secure Coding Practices',
    q: 'Proper secure error handling means an application should:',
    o: [
      'Fail gracefully without revealing sensitive details (e.g., stack traces) to users',
      'Display full database errors and stack traces to all users',
      'Crash without logging anything',
      'Email passwords on every error',
    ],
    a: 'A',
    wc: 'Secure error handling avoids leaking sensitive internal details (stack traces, queries) to users while logging enough internally for diagnosis.',
    ww: {
      B: 'Exposing detailed errors aids attackers (information disclosure).',
      C: 'Crashing without logging removes diagnostic/audit capability.',
      D: 'Emailing passwords is a severe security flaw.',
    },
    er: 'Tests secure error-handling practice.',
  },
  {
    t: 'API Security', s: 'Risks', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Software API Security',
    q: 'A common API security risk highlighted in the guide is:',
    o: [
      'Insufficient authentication and excessive data exposure',
      'Too much physical security',
      'Overuse of backup generators',
      'Excessive fire drills',
    ],
    a: 'A',
    wc: 'APIs commonly suffer from weak authentication and excessive data exposure; strong authentication, encryption, and input validation mitigate these.',
    ww: {
      B: 'Physical security is unrelated to API risk.',
      C: 'Generator usage is unrelated to API security.',
      D: 'Fire drills are a safety activity, not an API risk.',
    },
    er: 'Tests common API security risks.',
  },
  {
    t: 'API Security', s: 'Controls', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Application Security > Software API Security',
    q: 'Which TWO controls help secure an API? (Select TWO.)',
    o: [
      'Strong authentication of API callers',
      'Encryption of API traffic with TLS',
      'Open access with no authentication',
      'Returning all internal data by default',
    ],
    a: ['A', 'B'],
    wc: 'APIs should enforce strong authentication and encrypt traffic (TLS), along with input validation, to limit exposure and abuse.',
    ww: {
      C: 'Open, unauthenticated access invites abuse.',
      D: 'Returning all internal data is excessive data exposure.',
    },
    er: 'Identifies sound API security controls.',
  },
  // ---- Acquired software ----
  {
    t: 'Acquired Software', s: 'COTS', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Types of Acquired Software',
    q: 'Commercial Off-The-Shelf (COTS) software is:',
    o: [
      'Commercial software purchased and managed by the organization',
      'Free software maintained by a community',
      'Government-licensed software',
      'A custom in-house build',
    ],
    a: 'A',
    wc: 'COTS is commercially available software the organization purchases and manages (e.g., a licensed productivity suite).',
    ww: {
      B: 'Community-maintained free software is OSS/FOSS.',
      C: 'Government-licensed software is GOTS.',
      D: 'A custom in-house build is bespoke development, not COTS.',
    },
    er: 'Recall of COTS.',
  },
  {
    t: 'Acquired Software', s: 'OSS/FOSS', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Types of Acquired Software',
    q: 'Open-Source/Free Software (OSS/FOSS) is characterized by:',
    o: [
      'Being community-maintained and often hosted on platforms like GitHub',
      'Always being purchased from a single commercial vendor',
      'Being government-only software',
      'Having no source code available',
    ],
    a: 'A',
    wc: 'OSS/FOSS is typically free, community-maintained software with available source, often hosted on platforms like GitHub.',
    ww: {
      B: 'Commercial single-vendor purchase describes COTS.',
      C: 'Government-only software is GOTS.',
      D: 'OSS makes source code available by definition.',
    },
    er: 'Recall of OSS/FOSS.',
  },
  {
    t: 'Acquired Software', s: 'NDI supply chain', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Types of Acquired Software',
    q: 'A COTS product bundles several third-party libraries (NDIs). What is the PRIMARY security concern, and the BEST response?',
    o: [
      'Supply chain risk from the bundled components; vet them and apply supply chain risk management',
      'There is no risk because the vendor is commercial',
      'Bundled libraries are always more secure than custom code',
      'Third-party components never need updates',
    ],
    a: 'A',
    wc: 'Non-Developmental Items (NDIs)—third-party libraries bundled with products—introduce supply chain risk; they must be vetted, tracked, and managed (SCRM).',
    ww: {
      B: 'Commercial vendors\' bundled components can still contain vulnerabilities.',
      C: 'Bundled libraries are not inherently more secure.',
      D: 'Third-party components require updates as vulnerabilities emerge.',
    },
    er: 'Maps bundled third-party (NDI) risk to supply chain management.',
  },
  {
    t: 'Acquired Software', s: 'Software-type mapping', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Types of Acquired Software',
    q: 'Software acquired from the government, usually under a government license, is categorized as:',
    o: ['GOTS', 'COTS', 'OSS/FOSS', 'NDI'],
    a: 'A',
    wc: 'GOTS (Government Off-The-Shelf) is software acquired from the government, typically used under a government license.',
    ww: {
      B: 'COTS is commercial purchased software.',
      C: 'OSS/FOSS is community-maintained free software.',
      D: 'NDIs are third-party components bundled into other products.',
    },
    er: 'Recall of GOTS.',
  },
  {
    t: 'Acquired Software', s: 'Acquisition policy', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Security Considerations for Acquired Software',
    q: 'A security-focused software acquisition policy should ensure the organization:',
    o: [
      'Communicates security/compliance requirements to vendors and applies supply chain risk management',
      'Buys whichever software is cheapest with no security review',
      'Never tests acquired software before deployment',
      'Trusts all vendors without evaluation',
    ],
    a: 'A',
    wc: 'A sound acquisition policy communicates security/compliance requirements (e.g., GDPR, HIPAA) to vendors, uses trusted vendors, and applies SCRM—especially for bundled NDIs.',
    ww: {
      B: 'Cheapest-with-no-review ignores security risk.',
      C: 'Acquired software should be tested before production.',
      D: 'Vendors should be evaluated, not blindly trusted.',
    },
    er: 'Tests the elements of a secure acquisition policy.',
  },
  {
    t: 'Acquired Software', s: 'NIST acquisition steps', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > NIST Acquisition Controls',
    q: 'Per NIST acquisition guidance, an organization confirms a provider meets its security needs BEFORE finalizing the purchase. Which step is this?',
    o: ['Acceptance', 'Preparation', 'Selection', 'Monitoring'],
    a: 'A',
    wc: 'In the NIST acquisition approach (Preparation, Selection, Agreement Management, Monitoring, Acceptance), Acceptance confirms compliance with security needs before purchasing/licensing.',
    ww: {
      B: 'Preparation defines security needs and includes them in requests.',
      C: 'Selection evaluates vendors for trustworthiness.',
      D: 'Monitoring assesses ongoing performance/SLA adherence after acquisition.',
    },
    er: 'Maps pre-purchase compliance confirmation to the Acceptance step.',
  },
  {
    t: 'Acquired Software', s: 'Cloud lease models', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Cloud-Based Lease Software Models',
    q: 'In the SaaS model for acquired software, the customer is primarily responsible for:',
    o: [
      'Its own data and access controls (the provider manages the OS and supporting applications)',
      'Patching the provider\'s operating system',
      'Maintaining the provider\'s physical data center',
      'Writing the SaaS application\'s source code',
    ],
    a: 'A',
    wc: 'In SaaS, the provider manages the OS and supporting applications, while the customer manages its data and access controls.',
    ww: {
      B: 'OS patching is the provider\'s responsibility in SaaS.',
      C: 'Physical data-center maintenance is the provider\'s responsibility.',
      D: 'The provider develops/maintains the SaaS application.',
    },
    er: 'Tests SaaS customer responsibilities (data + access).',
  },
  {
    t: 'Acquired Software', s: 'Acquired software testing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Best Practices for Acquired Software',
    q: 'Before deploying acquired software to production, a best practice is to:',
    o: [
      'Conduct security testing (e.g., vulnerability and privacy impact assessments)',
      'Deploy it immediately with no evaluation',
      'Assume it is secure because it was purchased',
      'Disable all monitoring of it',
    ],
    a: 'A',
    wc: 'Acquired software should undergo security testing (vulnerability assessments, privacy impact assessments) before production and be monitored continuously afterward.',
    ww: {
      B: 'Immediate deployment without evaluation risks importing vulnerabilities.',
      C: 'Purchased software is not automatically secure.',
      D: 'Monitoring is needed to catch emerging issues.',
    },
    er: 'Tests pre-deployment security testing of acquired software.',
  },
  {
    t: 'Acquired Software', s: 'Acquired software types', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Application Security > Types of Acquired Software',
    q: 'Which TWO are categories of acquired software described in the guide? (Select TWO.)',
    o: ['COTS (commercial off-the-shelf)', 'OSS/FOSS (open-source/free)', 'TOCTOU', 'XSS'],
    a: ['A', 'B'],
    wc: 'COTS and OSS/FOSS are acquired-software categories (along with GOTS and NDIs); TOCTOU and XSS are attack types.',
    ww: {
      C: 'TOCTOU is a race-condition attack.',
      D: 'XSS is a web application attack.',
    },
    er: 'Separates acquired-software categories from attack types.',
  },
  {
    t: 'OWASP Top 10', s: 'Top 10 risks', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'Which TWO are risks included in the OWASP Top 10? (Select TWO.)',
    o: [
      'Injection',
      'Broken access control',
      'Backup tape aging',
      'Air-conditioning failure',
    ],
    a: ['A', 'B'],
    wc: 'Injection and broken access control are OWASP Top 10 web application security risks; the others are physical/facility issues.',
    ww: {
      C: 'Backup tape aging is a media/operations concern, not an OWASP risk.',
      D: 'Air-conditioning failure is an environmental issue, not an OWASP risk.',
    },
    er: 'Identifies OWASP Top 10 risks.',
  },
  {
    t: 'Application Attacks', s: 'Domain hijacking', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Hijacking Attacks',
    q: 'Domain hijacking involves:',
    o: [
      'Unauthorized changes to a domain\'s registration/DNS records to redirect traffic',
      'Stealing a single session cookie',
      'Injecting SQL into a database',
      'Draining a UPS battery',
    ],
    a: 'A',
    wc: 'Domain hijacking makes unauthorized changes to registered domain records (e.g., DNS) to redirect traffic to attacker-controlled destinations.',
    ww: {
      B: 'Stealing a session cookie is session hijacking.',
      C: 'SQL injection targets databases, not domain records.',
      D: 'Draining a UPS is unrelated to domain hijacking.',
    },
    er: 'Distinguishes domain hijacking from session hijacking.',
  },
  {
    t: 'Secure Coding', s: 'Defense in depth in code', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 8 > Application Security > Secure Coding Practices',
    q: 'To mitigate the OWASP Top 10 across an application, the MOST effective approach is to:',
    o: [
      'Apply secure coding practices (input validation, output encoding, parameterization, error handling) throughout development',
      'Add a single firewall rule and consider the app secure',
      'Rely solely on a post-release penetration test',
      'Hardcode credentials to simplify access',
    ],
    a: 'A',
    wc: 'Building secure coding practices into development (validation, encoding, parameterized queries, proper error handling) addresses the root causes behind the OWASP Top 10.',
    ww: {
      B: 'A single firewall rule does not address application-layer code flaws.',
      C: 'A post-release pen test alone is too late and not comprehensive.',
      D: 'Hardcoding credentials introduces a serious vulnerability.',
    },
    er: 'Maps broad OWASP mitigation to integrated secure coding.',
  },
  {
    t: 'OWASP Top 10', s: 'Broken authentication', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > OWASP Top 10 Vulnerabilities',
    q: 'Broken authentication (an OWASP Top 10 risk) typically results from:',
    o: [
      'Poorly managed credentials, sessions, or authentication logic',
      'Excessive backup power',
      'Too many fire drills',
      'Overly strict input validation',
    ],
    a: 'A',
    wc: 'Broken authentication stems from weaknesses in credential, session, or authentication management (e.g., weak passwords, exposed session IDs), enabling account compromise.',
    ww: {
      B: 'Backup power is unrelated to authentication.',
      C: 'Fire drills are a safety activity.',
      D: 'Strict input validation strengthens, not breaks, security.',
    },
    er: 'Tests the causes of broken authentication.',
  },
  {
    t: 'Acquired Software', s: 'PaaS responsibility', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 8 > Application Security > Cloud-Based Lease Software Models',
    q: 'In a PaaS model, the customer typically:',
    o: [
      'Owns the application (with some limited control over its security) while the provider manages the OS',
      'Manages the provider\'s physical facilities',
      'Has no responsibility for the application',
      'Patches the underlying operating system',
    ],
    a: 'A',
    wc: 'In PaaS, the provider manages the OS/platform while the customer owns the application (with limited control over underlying security).',
    ww: {
      B: 'Physical facilities are the provider\'s responsibility.',
      C: 'The customer owns/operates the application in PaaS.',
      D: 'OS patching is the provider\'s responsibility in PaaS.',
    },
    er: 'Tests PaaS customer responsibilities (the application).',
  },
];
