// Domain 1 — Part 2 (Q0042-Q0080): Security awareness/training/education,
// social engineering, personnel security lifecycle, personnel safety,
// due care / due diligence.
module.exports = [
  // ---- Awareness / Training / Education (1.12) ----
  {
    t: 'Security Awareness Training', s: 'Awareness vs training vs education', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Security Awareness Training and Education',
    q: 'In the awareness/training/education model, which activity is intended to CHANGE behavior by enhancing the specific skills employees need to follow security policies?',
    o: ['Training', 'Awareness', 'Education', 'Certification renewal'],
    a: 'A',
    wc: 'Training focuses on enhancing skills so personnel can adhere to security policies, often via hands-on sessions and role-specific instruction.',
    ww: {
      B: 'Awareness reinforces what to pay attention to (the "what"), not deep skill-building.',
      C: 'Education provides comprehensive knowledge beyond immediate job functions.',
      D: 'Certification renewal is an administrative credential activity, not the behavior-changing skill layer.',
    },
    er: 'Distinguishes the purpose of training (skills) from awareness (attention) and education (broad knowledge).',
  },
  {
    t: 'Security Awareness Training', s: 'Awareness', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Security Awareness Training and Education',
    q: 'Posters, emails, and periodic reminders about security protocols are common methods used to deliver which program element?',
    o: ['Security awareness', 'Security education', 'Penetration testing', 'Disaster recovery'],
    a: 'A',
    wc: 'Awareness uses methods such as emails, posters, workshops, and regular updates to keep security top-of-mind.',
    ww: {
      B: 'Education uses formal courses, certifications, and advanced programs.',
      C: 'Penetration testing is an assessment activity, not awareness delivery.',
      D: 'Disaster recovery is a continuity activity, not awareness delivery.',
    },
    er: 'Maps common low-cost reminders to the awareness layer.',
  },
  {
    t: 'Security Awareness Training', s: 'Program effectiveness', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Security Awareness Training and Education',
    q: 'A CISO wants to evaluate whether the security awareness program is actually reducing risk. Which approach best measures program effectiveness rather than mere completion?',
    o: [
      'Track click rates on simulated phishing campaigns over time and correlate with reported incidents',
      'Count how many employees opened the awareness email',
      'Measure how many posters were printed and displayed',
      'Record the total budget spent on the program',
    ],
    a: 'A',
    wc: 'Evaluating effectiveness requires outcome metrics—e.g., changes in simulated-phishing susceptibility and incident trends—rather than activity counts.',
    ww: {
      B: 'Email opens measure exposure, not behavior change or risk reduction.',
      C: 'Poster counts are an activity input, not an effectiveness outcome.',
      D: 'Spend is a cost input and says nothing about effectiveness.',
    },
    er: 'Tests evaluating awareness programs by behavioral outcomes, not vanity/activity metrics.',
  },
  {
    t: 'Security Awareness Training', s: 'Regulatory-driven training', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Practical Applications and Scenarios',
    q: 'Targeted training programs that ensure adherence to standards such as PCI DSS, FISMA, and ISO 27001 are an example of using awareness/training to achieve:',
    o: ['Regulatory compliance', 'Network segmentation', 'Cryptographic key escrow', 'Physical perimeter defense'],
    a: 'A',
    wc: 'Training can be designed to achieve regulatory compliance with standards like PCI DSS, FISMA, and ISO 27001.',
    ww: {
      B: 'Segmentation is a network control, not a training outcome.',
      C: 'Key escrow is a cryptographic process.',
      D: 'Perimeter defense is a physical control.',
    },
    er: 'Connects training programs to compliance objectives.',
  },
  {
    t: 'Security Awareness Training', s: 'Administrative controls', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Practical Applications and Scenarios',
    q: 'Security policies and procedures distributed to employees during onboarding and at regular intervals are an example of which control category?',
    o: ['Administrative controls', 'Technical controls', 'Physical controls', 'Compensating controls'],
    a: 'A',
    wc: 'Policies and procedures delivered through onboarding and recurring training are administrative (managerial) controls.',
    ww: {
      B: 'Technical controls are implemented in hardware/software.',
      C: 'Physical controls protect tangible assets and facilities.',
      D: 'Compensating controls substitute for an infeasible primary control; that is not what is described here.',
    },
    er: 'Classifies policy/procedure distribution as administrative control.',
  },
  // ---- Social Engineering ----
  {
    t: 'Social Engineering', s: 'Definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'Social engineering is best described as:',
    o: [
      'Psychological manipulation that deceives individuals into divulging confidential information',
      'A method for encrypting data in transit',
      'A technique for load-balancing network traffic',
      'A process for classifying organizational assets',
    ],
    a: 'A',
    wc: 'Social engineering uses psychological manipulation to deceive people into divulging confidential or personal information, often for fraud.',
    ww: {
      B: 'Encryption protects data, not a manipulation technique.',
      C: 'Load balancing is a networking function.',
      D: 'Asset classification is a governance/asset-security activity.',
    },
    er: 'Confirms the human-manipulation nature of social engineering.',
  },
  {
    t: 'Social Engineering', s: 'Phishing variants', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'A finance employee receives a highly customized email that references their manager by name and a real internal project, attempting to trick them into wiring funds. This is best classified as:',
    o: ['Spear phishing', 'Vishing', 'Smishing', 'Dumpster diving'],
    a: 'A',
    wc: 'Spear phishing is a targeted phishing attack customized to a specific individual or group using personalized details.',
    ww: {
      B: 'Vishing is voice phishing conducted over the phone.',
      C: 'Smishing is phishing via SMS messages.',
      D: 'Dumpster diving is sifting through trash for information, a physical tactic.',
    },
    er: 'Distinguishes targeted (spear) phishing from channel-specific variants.',
  },
  {
    t: 'Social Engineering', s: 'Whaling', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'A phishing attack that specifically targets a high-value individual such as a CEO or CFO is known as:',
    o: ['Whaling', 'Smishing', 'Spim', 'Tailgating'],
    a: 'A',
    wc: 'Whaling is phishing aimed at high-profile, high-value targets such as senior executives.',
    ww: {
      B: 'Smishing uses SMS as the delivery channel.',
      C: 'Spim is spam over instant messaging.',
      D: 'Tailgating is a physical access tactic.',
    },
    er: 'Identifies whaling as executive-targeted phishing.',
  },
  {
    t: 'Social Engineering', s: 'Vishing vs smishing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'Phishing conducted through SMS text messages is called:',
    o: ['Smishing', 'Vishing', 'Whaling', 'Pretexting'],
    a: 'A',
    wc: 'Smishing is phishing carried out through SMS messages.',
    ww: {
      B: 'Vishing is voice phishing over the phone.',
      C: 'Whaling targets high-value executives.',
      D: 'Pretexting uses a fabricated scenario to obtain information.',
    },
    er: 'Channel recall: SMS = smishing.',
  },
  {
    t: 'Social Engineering', s: 'Pretexting', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'An attacker calls the help desk pretending to be a traveling executive locked out of their account, inventing a detailed but false back-story to pressure the agent into a password reset. This technique is:',
    o: ['Pretexting', 'Quid pro quo', 'Shoulder surfing', 'Piggybacking'],
    a: 'A',
    wc: 'Pretexting uses a fabricated but believable scenario (a pretext) to manipulate a target into providing access or information.',
    ww: {
      B: 'Quid pro quo offers a benefit in exchange for information or access.',
      C: 'Shoulder surfing is visually observing someone to capture information.',
      D: 'Piggybacking is gaining physical entry by getting someone to hold a door.',
    },
    er: 'Tests recognition of the fabricated-scenario hallmark of pretexting.',
  },
  {
    t: 'Social Engineering', s: 'Quid pro quo', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    q: 'A caller posing as IT support offers to "fix a slow computer" in exchange for the employee\'s login credentials. Which technique does this represent?',
    o: ['Quid pro quo', 'Whaling', 'Smishing', 'Dumpster diving'],
    a: 'A',
    wc: 'Quid pro quo offers something of value (help/fix) in exchange for information or access.',
    ww: {
      B: 'Whaling targets executives specifically.',
      C: 'Smishing uses SMS.',
      D: 'Dumpster diving searches trash for information.',
    },
    er: 'Identifies the "something for something" exchange as quid pro quo.',
  },
  {
    t: 'Social Engineering', s: 'Physical tactics', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Physical Social Engineering Tactics',
    q: 'An unauthorized person follows an employee through a secured door WITHOUT the employee\'s knowledge. This is best described as:',
    o: ['Tailgating', 'Piggybacking', 'Shoulder surfing', 'Vishing'],
    a: 'A',
    wc: 'Tailgating is following someone through a secure door without their knowledge or consent.',
    ww: {
      B: 'Piggybacking involves the employee knowingly holding the door (often via an empathy ploy).',
      C: 'Shoulder surfing is observing to capture information such as passwords.',
      D: 'Vishing is voice phishing.',
    },
    er: 'Distinguishes tailgating (without knowledge) from piggybacking (with consent).',
  },
  {
    t: 'Social Engineering', s: 'Physical tactics', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Physical Social Engineering Tactics',
    q: 'The KEY difference between piggybacking and tailgating, as taught in the guide, is that piggybacking:',
    o: [
      'Involves the authorized person knowingly granting entry, often after being asked to hold the door',
      'Always requires cloning an access badge',
      'Only occurs in fully unmanned facilities',
      'Is a purely digital, network-based attack',
    ],
    a: 'A',
    wc: 'Piggybacking is gaining access by getting someone to hold the door—i.e., with the authorized person\'s knowledge/consent—whereas tailgating happens without their knowledge.',
    ww: {
      B: 'Badge cloning is a separate technique and not what defines piggybacking.',
      C: 'It typically occurs precisely where people are present to be manipulated.',
      D: 'Both are physical entry tactics, not network attacks.',
    },
    er: 'Tests the consent/knowledge distinction between the two physical tactics.',
  },
  {
    t: 'Social Engineering', s: 'Defense', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Management Concepts > Defense Against Social Engineering',
    q: 'A receptionist is unsure whether a visitor claiming to be a vendor is legitimate. Which TWO actions align with social-engineering defenses? (Select TWO.)',
    o: [
      'Require valid identification from the visitor before granting access',
      'Verify the visitor by contacting their associated company or team',
      'Grant access immediately to avoid appearing rude to the vendor',
      'Ask the visitor to hold the door for the next person entering',
    ],
    a: ['A', 'B'],
    wc: 'Defenses require valid identification for all personnel and visitors and verification of unknown individuals (e.g., by contacting their associated company or team) before granting access.',
    ww: {
      C: 'Politeness must not override verification; granting access immediately enables impersonation.',
      D: 'Encouraging door-holding facilitates piggybacking and defeats access control.',
    },
    er: 'Tests identification and verification as the front-line defenses against in-person social engineering.',
  },
  {
    t: 'Social Engineering', s: 'Defense', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Defense Against Social Engineering',
    q: 'Which control is the MOST effective broad defense against social engineering, given that it targets the human element?',
    o: [
      'Ongoing security awareness training that teaches staff to recognize and respond to manipulation',
      'A faster internet connection',
      'Disabling all email attachments permanently',
      'Increasing the office temperature',
    ],
    a: 'A',
    wc: 'Because social engineering exploits people, security awareness training that helps personnel recognize and respond to attempts is the primary defense.',
    ww: {
      B: 'Bandwidth has no bearing on human manipulation.',
      C: 'Blanket attachment blocking is impractical and does not address phone, in-person, or SMS vectors.',
      D: 'Office temperature is irrelevant to social engineering.',
    },
    er: 'Reinforces that the human-focused control (training) best counters human-focused attacks.',
  },
  {
    t: 'Social Engineering', s: 'Technique-to-definition mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 1 > Security Management Concepts > Social Engineering',
    p: ['Vishing', 'Smishing', 'Shoulder surfing', 'Dumpster diving'],
    q: 'Match each social-engineering technique (1-4) to its description (A-D).',
    o: [
      'Sifting through discarded trash to find sensitive information',
      'Voice phishing conducted over the phone',
      'Phishing carried out through SMS messages',
      'Observing a person to capture information such as passwords',
    ],
    a: '1-B,2-C,3-D,4-A',
    wc: 'Vishing → phone voice phishing (B); Smishing → SMS phishing (C); Shoulder surfing → visually observing to capture info (D); Dumpster diving → trash sifting (A).',
    ww: {},
    er: 'Tests precise mapping of social-engineering techniques to their channels/methods.',
  },
  // ---- Personnel security lifecycle ----
  {
    t: 'Personnel Security', s: 'Separation of duties', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Key Security Controls for Personnel Management',
    q: 'Which personnel control prevents any single individual from having excessive control over a critical business function?',
    o: ['Separation of duties', 'Least privilege', 'Need to know', 'Job rotation'],
    a: 'A',
    wc: 'Separation of duties divides critical functions so no single person can complete a sensitive process alone, reducing fraud and error.',
    ww: {
      B: 'Least privilege limits access to the minimum needed, but does not by itself split a single function across people.',
      C: 'Need to know restricts information access, not control over a whole function.',
      D: 'Job rotation moves staff between roles; it is a related but distinct control.',
    },
    er: 'Separates SoD (split a function) from least privilege and need-to-know.',
  },
  {
    t: 'Personnel Security', s: 'Least privilege vs need to know', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Key Security Controls for Personnel Management',
    q: 'An employee has the system rights to open a folder (their role allows it) but should not view a specific file inside it because it is unrelated to their current task. Restricting that specific file most directly enforces:',
    o: ['Need to know', 'Least privilege', 'Separation of duties', 'Mandatory vacation'],
    a: 'A',
    wc: 'Need to know restricts access to specific information to only those who require it for their duties, even when broader privileges technically permit access.',
    ww: {
      B: 'Least privilege limits the rights/permissions granted; here the rights exist but the specific information is still not needed.',
      C: 'Separation of duties divides a function among people; it is not about a single file\'s relevance.',
      D: 'Mandatory vacation is a fraud-detection control, not access scoping.',
    },
    er: 'Forces the subtle distinction between least privilege (rights) and need-to-know (specific information relevance).',
  },
  {
    t: 'Personnel Security', s: 'Least privilege', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Key Security Controls for Personnel Management',
    q: 'Ensuring personnel have only the minimum level of access required to perform their job functions defines:',
    o: ['Least privilege', 'Separation of duties', 'Defense in depth', 'Due diligence'],
    a: 'A',
    wc: 'Least privilege grants the minimum access necessary to perform one\'s duties.',
    ww: {
      B: 'Separation of duties divides critical functions among multiple people.',
      C: 'Defense in depth layers multiple controls.',
      D: 'Due diligence is the ongoing effort to keep controls effective.',
    },
    er: 'Basic recall of the least-privilege definition.',
  },
  {
    t: 'Personnel Security', s: 'Employment lifecycle', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 1 > Security Management Concepts > Personnel Security Policies',
    q: 'Place the following personnel-security activities in the order they normally occur across the employment lifecycle. (Provide the option labels in order.)',
    o: [
      'Pre-employment screening and background checks',
      'Onboarding security training and policy acknowledgement',
      'Ongoing access management under least privilege',
      'Offboarding: access revocation and asset return',
    ],
    a: 'A,B,C,D',
    wc: 'The lifecycle runs from pre-hire screening, to onboarding, to ongoing management during employment, to offboarding at termination.',
    ww: {},
    er: 'Tests understanding of the personnel-security lifecycle order.',
  },
  {
    t: 'Personnel Security', s: 'Background checks', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Hiring Process',
    q: 'During hiring, screening and background checks primarily serve to:',
    o: [
      'Verify candidates\' suitability and trustworthiness before granting access',
      'Replace the need for onboarding training',
      'Eliminate the need for least privilege after hire',
      'Determine the company\'s annual marketing budget',
    ],
    a: 'A',
    wc: 'Screening and background checks (criminal history, prior employment, education, etc.) help ensure candidate suitability and trustworthiness.',
    ww: {
      B: 'Screening does not replace onboarding training.',
      C: 'Least privilege still applies after hire regardless of screening.',
      D: 'Budgeting is unrelated to personnel screening.',
    },
    er: 'Connects pre-employment screening to trust establishment.',
  },
  {
    t: 'Personnel Security', s: 'NDA', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Employee Agreements and Policies',
    q: 'Which agreement binds employees to protect sensitive information both during and after their employment?',
    o: ['Non-Disclosure Agreement (NDA)', 'Non-Compete Agreement', 'Acceptable Use Policy', 'Service Level Agreement'],
    a: 'A',
    wc: 'An NDA binds employees to protect sensitive information during and after their tenure.',
    ww: {
      B: 'A non-compete restricts joining competitors, not information protection per se.',
      C: 'An AUP defines acceptable use of company resources.',
      D: 'An SLA defines service expectations between parties, often with vendors.',
    },
    er: 'Recall of the NDA\'s confidentiality purpose spanning employment and beyond.',
  },
  {
    t: 'Personnel Security', s: 'Non-compete', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Employee Agreements and Policies',
    q: 'A clause that prevents an employee from joining competing firms for a specified period after leaving is a:',
    o: ['Non-Compete Agreement', 'Non-Disclosure Agreement', 'Acceptable Use Policy', 'Memorandum of Understanding'],
    a: 'A',
    wc: 'A non-compete agreement prevents employees from joining competing firms for a defined post-employment period.',
    ww: {
      B: 'An NDA protects confidential information, not employment with competitors.',
      C: 'An AUP governs use of company resources.',
      D: 'An MOU is a broad statement of intent between parties.',
    },
    er: 'Distinguishes non-compete from NDA and AUP.',
  },
  {
    t: 'Personnel Security', s: 'Acceptable Use Policy', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Employee Agreements and Policies',
    q: 'Which document defines the acceptable and secure ways employees may use company resources?',
    o: ['Acceptable Use Policy (AUP)', 'Non-Disclosure Agreement (NDA)', 'Non-Compete Agreement', 'Business Impact Analysis'],
    a: 'A',
    wc: 'The AUP defines acceptable and secure ways employees can use company resources.',
    ww: {
      B: 'An NDA covers confidentiality of information.',
      C: 'A non-compete restricts future competing employment.',
      D: 'A BIA assesses impacts for continuity planning.',
    },
    er: 'Recall of AUP purpose.',
  },
  {
    t: 'Personnel Security', s: 'Onboarding', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Onboarding Process',
    q: 'During onboarding, new hires are granted access to company resources based on which principle?',
    o: ['Least privilege', 'Maximum convenience', 'All-access by default', 'Anonymous access'],
    a: 'A',
    wc: 'Onboarding grants access to company resources based on the principle of least privilege.',
    ww: {
      B: 'Convenience-driven over-provisioning increases risk.',
      C: 'Default all-access violates least privilege.',
      D: 'Anonymous access undermines accountability.',
    },
    er: 'Ties onboarding provisioning to least privilege.',
  },
  {
    t: 'Personnel Security', s: 'Offboarding', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Offboarding Process',
    q: 'An employee is being terminated for cause. From a security standpoint, which action is MOST time-critical during offboarding?',
    o: [
      'Promptly revoking the employee\'s access rights to systems and facilities',
      'Scheduling their next performance review',
      'Updating the company org chart graphics',
      'Publishing a farewell announcement',
    ],
    a: 'A',
    wc: 'Offboarding must securely terminate access rights (and retrieve assets); prompt access revocation limits the window for retaliatory or unauthorized actions.',
    ww: {
      B: 'A terminated employee will not receive a future review; this is irrelevant.',
      C: 'Org-chart graphics are administrative and not security-critical.',
      D: 'A farewell announcement is not a security control.',
    },
    er: 'Prioritizes access revocation as the urgent offboarding security task.',
  },
  {
    t: 'Personnel Security', s: 'Exit interviews', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Offboarding Process',
    q: 'Exit interviews during offboarding primarily help the organization to:',
    o: [
      'Understand potential security concerns and reinforce confidentiality obligations',
      'Negotiate the departing employee\'s new salary',
      'Assign the employee additional system privileges',
      'Skip the need for access revocation',
    ],
    a: 'A',
    wc: 'Exit interviews help surface potential security concerns and reinforce confidentiality agreements as the employee departs.',
    ww: {
      B: 'Salary negotiation is irrelevant to a departing employee\'s security exit.',
      C: 'Offboarding revokes, not expands, privileges.',
      D: 'Access revocation is still required; the interview does not replace it.',
    },
    er: 'Connects exit interviews to confidentiality reinforcement and concern identification.',
  },
  {
    t: 'Personnel Security', s: 'Onboarding policy acknowledgement', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Onboarding Process',
    q: 'Requiring new hires to sign documents acknowledging they understand and will comply with security policies is called:',
    o: ['Policy acknowledgement', 'Risk acceptance', 'Penetration testing', 'Data classification'],
    a: 'A',
    wc: 'Policy acknowledgement requires new hires to sign agreements confirming understanding of and compliance with security policies.',
    ww: {
      B: 'Risk acceptance is a risk-response decision by management.',
      C: 'Penetration testing is a security assessment.',
      D: 'Data classification is an asset-security activity.',
    },
    er: 'Recall of the policy-acknowledgement step.',
  },
  // ---- Personnel safety & security ----
  {
    t: 'Personnel Safety and Security', s: 'Duress', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Personnel Safety and Security',
    q: 'Which control allows an employee under threat to silently signal for help without alerting the aggressor?',
    o: ['A duress code or silent alarm', 'A louder office paging system', 'A public social media post', 'A monthly newsletter'],
    a: 'A',
    wc: 'Duress codes or silent alarms let personnel alert security discreetly without escalating a dangerous situation.',
    ww: {
      B: 'A loud page would alert the aggressor and escalate danger.',
      C: 'Public posts are slow, visible, and unreliable for emergencies.',
      D: 'Newsletters are not emergency signaling mechanisms.',
    },
    er: 'Tests the purpose of duress signaling—covert alerting.',
  },
  {
    t: 'Personnel Safety and Security', s: 'Travel security', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Personnel Safety and Security',
    q: 'To protect organizational resources accessed by traveling employees over untrusted networks, the guide recommends:',
    o: ['Using VPNs for secure remote access', 'Disabling all authentication while traveling', 'Emailing passwords to oneself', 'Posting itineraries publicly'],
    a: 'A',
    wc: 'Travel security includes using VPNs for secure remote access to organizational resources.',
    ww: {
      B: 'Disabling authentication removes a critical control.',
      C: 'Emailing passwords exposes credentials.',
      D: 'Public itineraries increase personal and physical risk.',
    },
    er: 'Connects travel security to encrypted remote-access (VPN).',
  },
  {
    t: 'Personnel Safety and Security', s: 'Priority of life safety', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Personnel Safety and Security',
    q: 'During a building fire, an automated system can either keep electronic doors locked to protect a data center or unlock egress routes to let people exit. Which choice aligns with security best practice?',
    o: [
      'Unlock egress routes—human life safety takes precedence over asset protection',
      'Keep all doors locked to protect the data center at all costs',
      'Lock only the exits nearest to executives',
      'Disable fire alarms to avoid panic',
    ],
    a: 'A',
    wc: 'Human safety is the highest priority; emergency systems should fail to a state that permits safe egress, even at some risk to assets.',
    ww: {
      B: 'Trapping people to protect equipment is never acceptable; life safety comes first.',
      C: 'Selective locking still endangers lives and is discriminatory and unsafe.',
      D: 'Disabling alarms removes life-saving warning and is dangerous.',
    },
    er: 'Tests the overriding principle that life safety outranks asset protection.',
  },
  {
    t: 'Personnel Safety and Security', s: 'Emergency communication', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Personnel Safety and Security',
    q: 'A comprehensive personnel safety program should include emergency communication that:',
    o: [
      'Provides clear protocols, emergency contacts, and procedures for reporting incidents',
      'Relies solely on word of mouth between employees',
      'Is documented only in the CEO\'s personal notebook',
      'Is tested once at company founding and never again',
    ],
    a: 'A',
    wc: 'Emergency communication requires clear protocols and a plan including emergency contact numbers and reporting procedures.',
    ww: {
      B: 'Word of mouth is unreliable in emergencies.',
      C: 'A single private copy is not accessible when needed.',
      D: 'Plans must be regularly tested and drilled, not set once and forgotten.',
    },
    er: 'Highlights structured, documented, testable emergency communication.',
  },
  // ---- Due care / due diligence ----
  {
    t: 'Due Care and Due Diligence', s: 'Definitions', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Due Care and Due Diligence',
    q: 'Which statement BEST distinguishes due care from due diligence?',
    o: [
      'Due care is implementing reasonable security measures; due diligence is the ongoing effort to ensure they remain effective',
      'Due care is a one-time audit; due diligence is ignoring known risks',
      'Due care applies only to vendors; due diligence applies only to employees',
      'They are interchangeable terms with no practical difference',
    ],
    a: 'A',
    wc: 'Due care is the responsibility to implement effective security measures; due diligence is the ongoing effort to keep those measures updated and effective.',
    ww: {
      B: 'Due diligence is continuous attention to risk, not ignoring it.',
      C: 'Both concepts apply broadly, not to a single population.',
      D: 'They are distinct: doing the right thing (care) vs. continually verifying it (diligence).',
    },
    er: 'Tests the canonical care-vs-diligence distinction.',
  },
  {
    t: 'Due Care and Due Diligence', s: 'Applied', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Due Care and Due Diligence',
    q: 'An organization deployed strong controls two years ago but never revisited them; a breach exploited a control that had since become outdated. Which failure does this MOST clearly illustrate?',
    o: [
      'Lack of due diligence (ongoing review and updating)',
      'Lack of due care (never implementing any controls)',
      'Excessive least privilege',
      'Over-investment in awareness training',
    ],
    a: 'A',
    wc: 'Controls were implemented (due care) but never maintained or reassessed—an absence of due diligence, the ongoing effort to keep controls effective.',
    ww: {
      B: 'Controls were implemented, so due care was at least initially exercised; the gap is in maintenance.',
      C: 'Least privilege did not cause the outdated-control failure.',
      D: 'Awareness training is unrelated to the unmaintained technical control.',
    },
    er: 'Maps a "set and forget" failure specifically to missing due diligence.',
  },
  {
    t: 'Due Care and Due Diligence', s: 'Governance implications', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Due Care and Due Diligence',
    q: 'Why is understanding due care and due diligence considered crucial for legal and regulatory compliance?',
    o: [
      'Failing to exercise them can create legal liability and demonstrate negligence',
      'They eliminate the need for any documented policies',
      'They guarantee an organization will never be breached',
      'They apply only to non-regulated industries',
    ],
    a: 'A',
    wc: 'Not adhering to due care/due diligence can lead to legal liabilities and is central to corporate governance and compliance frameworks.',
    ww: {
      B: 'Policies remain essential; these concepts complement them.',
      C: 'No practice guarantees breach immunity.',
      D: 'They apply across industries, especially regulated ones.',
    },
    er: 'Connects due care/diligence to liability and governance.',
  },
];
