// Domain 1 — Part 3 (Q0078-...): Laws & regulations, intellectual property &
// licensing, export/import controls, cybercrime & threat actors, attack types,
// and investigation types.
module.exports = [
  // ---- Laws & regulations ----
  {
    t: 'Legal and Regulatory', s: 'GLBA', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which US law focuses on the privacy of financial data and prohibits sharing customers\' financial information without consent?',
    o: ['Gramm-Leach-Bliley Act (GLBA)', 'Health Insurance Portability and Accountability Act (HIPAA)', 'Sarbanes-Oxley Act (SOX)', 'Computer Fraud and Abuse Act (CFAA)'],
    a: 'A',
    wc: 'GLBA focuses on the privacy of financial data and prohibits sharing financial information without customer consent.',
    ww: {
      B: 'HIPAA protects health-related information.',
      C: 'SOX governs corporate financial disclosure accuracy for investors.',
      D: 'CFAA addresses computer fraud and abuse.',
    },
    er: 'Maps GLBA to financial-data privacy.',
  },
  {
    t: 'Legal and Regulatory', s: 'HIPAA', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which regulation establishes requirements for protecting health-related information in the United States?',
    o: ['HIPAA', 'GLBA', 'PCI DSS', 'GDPR'],
    a: 'A',
    wc: 'HIPAA establishes requirements for the protection of health-related information.',
    ww: {
      B: 'GLBA governs financial data privacy.',
      C: 'PCI DSS is a payment-card security standard, not a health regulation.',
      D: 'GDPR is the EU\'s general data protection regulation.',
    },
    er: 'Maps HIPAA to health information protection.',
  },
  {
    t: 'Legal and Regulatory', s: 'SOX', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'The Sarbanes-Oxley Act (SOX) primarily protects investors by:',
    o: [
      'Improving the accuracy and reliability of corporate financial disclosures',
      'Securing payment card transactions',
      'Protecting genetic information from discrimination',
      'Regulating cross-border encryption exports',
    ],
    a: 'A',
    wc: 'SOX protects investors by improving the accuracy and reliability of corporate disclosures.',
    ww: {
      B: 'Payment-card security is PCI DSS.',
      C: 'Genetic-information protection is GINA.',
      D: 'Encryption export is governed by EXIM controls/Wassenaar.',
    },
    er: 'Connects SOX to corporate financial-disclosure integrity.',
  },
  {
    t: 'Legal and Regulatory', s: 'PCI DSS nature', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which statement about the Payment Card Industry Data Security Standard (PCI DSS) is correct?',
    o: [
      'It is not a law but a standard enforced through fines or penalties by the payment card companies',
      'It is a US federal statute enforced by the Department of Justice',
      'It is an EU regulation enforced by data protection authorities',
      'It is an international treaty governing dual-use goods',
    ],
    a: 'A',
    wc: 'PCI DSS is an industry standard (not a law) enforced via contractual fines/penalties by the major card brands.',
    ww: {
      B: 'It is not a federal statute.',
      C: 'It is not an EU regulation; GDPR is.',
      D: 'Dual-use goods are governed by export-control arrangements like Wassenaar, not PCI DSS.',
    },
    er: 'Tests the frequently confused point that PCI DSS is a contractual standard, not law.',
  },
  {
    t: 'Legal and Regulatory', s: 'GDPR scope', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > General Data Protection Regulation (GDPR)',
    q: 'GDPR applies to:',
    o: [
      'All entities that process the personal data of EU residents, regardless of where the entity is located',
      'Only companies physically headquartered within the European Union',
      'Only government agencies inside the EU',
      'Only organizations that handle payment card data',
    ],
    a: 'A',
    wc: 'GDPR applies to all entities that process personal data of EU residents, giving it extraterritorial reach.',
    ww: {
      B: 'Location of the entity does not exempt it if it processes EU residents\' data.',
      C: 'It applies broadly to private and public entities, not only EU governments.',
      D: 'GDPR is about personal data generally, not only card data.',
    },
    er: 'Tests GDPR\'s extraterritorial, resident-based scope.',
  },
  {
    t: 'Legal and Regulatory', s: 'GDPR roles', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Roles Defined by GDPR',
    q: 'Under GDPR, the party that determines the purposes and means of processing personal data is the:',
    o: ['Controller', 'Processor', 'Data subject', 'Supervisory authority'],
    a: 'A',
    wc: 'The controller determines the purposes and means of processing personal data; the processor acts on the controller\'s behalf.',
    ww: {
      B: 'The processor processes data on behalf of the controller.',
      C: 'The data subject is the individual whose data is processed.',
      D: 'The supervisory authority is the regulator, not the processing decision-maker.',
    },
    er: 'Distinguishes GDPR controller from processor.',
  },
  {
    t: 'Legal and Regulatory', s: 'GDPR rights', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Rights Under GDPR',
    q: 'A customer asks a company to delete all personal data it holds about them. Which GDPR right are they exercising?',
    o: ['Erasure (right to be forgotten)', 'Rectification', 'Data portability', 'Restriction'],
    a: 'A',
    wc: 'The right to erasure, also called the right to be forgotten, lets subjects request deletion of their personal data.',
    ww: {
      B: 'Rectification is correcting/updating inaccurate data.',
      C: 'Data portability lets subjects reuse data across services.',
      D: 'Restriction limits how data is used, not deletion.',
    },
    er: 'Maps the deletion request to the erasure right.',
  },
  {
    t: 'Legal and Regulatory', s: 'GDPR rights', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Governance and Compliance > Rights Under GDPR',
    q: 'Which TWO of the following are rights granted to data subjects under GDPR? (Select TWO.)',
    o: [
      'The right to access their personal data',
      'The right to data portability across services',
      'The right to demand the company never be audited',
      'The right to set their employer\'s security budget',
    ],
    a: ['A', 'B'],
    wc: 'Access and data portability are explicit GDPR data-subject rights.',
    ww: {
      C: 'GDPR does not exempt controllers from audits; supervisory authorities can investigate.',
      D: 'Budget-setting is not a GDPR data-subject right.',
    },
    er: 'Confirms recognition of genuine GDPR rights versus distractors.',
  },
  {
    t: 'Legal and Regulatory', s: 'FTC Act', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which US law protects consumers against unfair or deceptive acts affecting commerce, including protection of personally identifiable information (PII)?',
    o: ['Federal Trade Commission Act (FTC Act)', 'HITECH', 'Basel II Accord', 'Economic Espionage Act'],
    a: 'A',
    wc: 'The FTC Act protects consumers against unfair or deceptive acts affecting commerce and addresses protection of PII.',
    ww: {
      B: 'HITECH mandates protection of PHI by HIPAA-covered entities.',
      C: 'Basel II is an international banking regulation.',
      D: 'The Economic Espionage Act protects trade secrets.',
    },
    er: 'Maps consumer-protection/PII to the FTC Act.',
  },
  {
    t: 'Legal and Regulatory', s: 'HITECH', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which act mandates protection of Protected Health Information (PHI) by entities covered under HIPAA?',
    o: ['HITECH Act', 'GLBA', 'SOX', 'PIPEDA'],
    a: 'A',
    wc: 'HITECH mandates protection of PHI by entities covered under HIPAA, strengthening HIPAA\'s requirements.',
    ww: {
      B: 'GLBA covers financial data.',
      C: 'SOX covers corporate financial disclosures.',
      D: 'PIPEDA is Canadian privacy law.',
    },
    er: 'Connects HITECH to PHI protection under HIPAA-covered entities.',
  },
  {
    t: 'Legal and Regulatory', s: 'GINA', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'An insurer is accused of denying coverage based on the results of an applicant\'s genetic test. Which law most directly prohibits this?',
    o: [
      'Genetic Information Nondiscrimination Act (GINA)',
      'Gramm-Leach-Bliley Act (GLBA)',
      'Sarbanes-Oxley Act (SOX)',
      'Computer Fraud and Abuse Act (CFAA)',
    ],
    a: 'A',
    wc: 'GINA prohibits discrimination based on genetic information in health insurance and employment.',
    ww: {
      B: 'GLBA concerns financial-data privacy.',
      C: 'SOX concerns financial disclosures.',
      D: 'CFAA concerns computer fraud and abuse.',
    },
    er: 'Maps genetic-information discrimination to GINA.',
  },
  {
    t: 'Legal and Regulatory', s: 'CFAA', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Cybercrime and Data Breaches',
    q: 'The Computer Fraud and Abuse Act (CFAA) is best described as:',
    o: [
      'Early major US cybercrime legislation focused on fraud and related activity involving computers',
      'An EU regulation governing personal data of residents',
      'A payment-card security standard',
      'An international arrangement controlling dual-use exports',
    ],
    a: 'A',
    wc: 'The CFAA was an early major US cybercrime law focused on fraud and related activities in connection with computers.',
    ww: {
      B: 'That describes GDPR.',
      C: 'That describes PCI DSS.',
      D: 'That describes the Wassenaar Arrangement.',
    },
    er: 'Identifies CFAA as foundational US computer-crime law.',
  },
  {
    t: 'Legal and Regulatory', s: 'FISMA', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Cybercrime And Data Breaches',
    q: 'Which act establishes cybersecurity standards and responsibilities for US federal agencies?',
    o: ['Federal Information Security Modernization Act (FISMA)', 'PCI DSS', 'GDPR', 'Creative Commons'],
    a: 'A',
    wc: 'FISMA establishes federal cybersecurity standards and centralizes related responsibilities for federal agencies.',
    ww: {
      B: 'PCI DSS is a private-sector card standard.',
      C: 'GDPR is an EU regulation.',
      D: 'Creative Commons is a licensing scheme, not a federal security law.',
    },
    er: 'Maps federal agency security standards to FISMA.',
  },
  {
    t: 'Legal and Regulatory', s: 'Law-to-domain mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    p: ['HIPAA', 'GLBA', 'SOX', 'GDPR'],
    q: 'Match each regulation (1-4) to the area it primarily governs (A-D).',
    o: [
      'Privacy of financial data at financial institutions',
      'Protection of health-related information',
      'Personal data of EU residents',
      'Accuracy of corporate financial disclosures for investors',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'HIPAA → health information (B); GLBA → financial-data privacy (A); SOX → corporate financial-disclosure accuracy (D); GDPR → EU residents\' personal data (C).',
    ww: {},
    er: 'Tests precise law-to-sector mapping across the core regulations.',
  },
  {
    t: 'Legal and Regulatory', s: 'Applicable law selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Determine Compliance Requirements',
    q: 'A US-based e-commerce company stores and processes the personal data of customers living in Germany and France. Which regulation most directly governs how it must handle that customer data?',
    o: ['GDPR', 'HIPAA', 'SOX', 'GLBA'],
    a: 'A',
    wc: 'Because the company processes personal data of EU residents, GDPR applies regardless of the company\'s US location.',
    ww: {
      B: 'HIPAA covers US health information, not general EU customer data.',
      C: 'SOX covers corporate financial disclosures, not customer personal data handling.',
      D: 'GLBA covers US financial-institution data privacy, not this scenario.',
    },
    er: 'Tests selecting the correct cross-border regulation by data-subject residency.',
  },
  {
    t: 'Legal and Regulatory', s: 'Applicable law selection', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'A retailer that accepts branded credit cards must comply with security requirements for storing and transmitting cardholder data. Which framework applies?',
    o: ['PCI DSS', 'HIPAA', 'GINA', 'FISMA'],
    a: 'A',
    wc: 'PCI DSS sets security standards for organizations that handle branded credit cards.',
    ww: {
      B: 'HIPAA covers health data.',
      C: 'GINA covers genetic information.',
      D: 'FISMA covers US federal agencies.',
    },
    er: 'Maps card-handling obligations to PCI DSS.',
  },
  {
    t: 'Legal and Regulatory', s: 'Cross-national compliance', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Determine Compliance Requirements',
    q: 'A company is contracting with vendors located in three different countries. From a compliance standpoint, the security professional should:',
    o: [
      'Consider the laws and regulations of each jurisdiction that applies to the engagement',
      'Apply only the laws of the company\'s home country and ignore the rest',
      'Assume all countries share identical regulations',
      'Defer entirely to whichever vendor has the lowest price',
    ],
    a: 'A',
    wc: 'When contracting across countries, laws vary by jurisdiction, so each applicable legal framework must be understood and addressed.',
    ww: {
      B: 'Home-country law alone may not satisfy foreign jurisdictions\' requirements.',
      C: 'Laws differ substantially between countries.',
      D: 'Price has no bearing on legal compliance obligations.',
    },
    er: 'Tests multi-jurisdiction compliance awareness.',
  },
  {
    t: 'Legal and Regulatory', s: 'US financial regulations', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Governance and Compliance > Important Laws and Regulations',
    q: 'Which TWO regulations are most associated with the financial sector? (Select TWO.)',
    o: [
      'Gramm-Leach-Bliley Act (GLBA)',
      'Sarbanes-Oxley Act (SOX)',
      'Health Insurance Portability and Accountability Act (HIPAA)',
      'Genetic Information Nondiscrimination Act (GINA)',
    ],
    a: ['A', 'B'],
    wc: 'GLBA governs financial-data privacy and SOX governs corporate financial disclosures—both financial-sector focused.',
    ww: {
      C: 'HIPAA is healthcare-focused.',
      D: 'GINA concerns genetic-information discrimination.',
    },
    er: 'Groups financial-sector regulations versus health/genetic ones.',
  },
  // ---- Intellectual property & licensing ----
  {
    t: 'Intellectual Property', s: 'Trade secret', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Licensing and Property Rights',
    q: 'A company protects its proprietary manufacturing process by keeping it secret and giving it competitive advantage, without registering it publicly. This protection is a:',
    o: ['Trade secret', 'Patent', 'Trademark', 'Copyright'],
    a: 'A',
    wc: 'A trade secret protects secret methods or processes (recipes, designs, algorithms) that give a competitive advantage, relying on secrecy rather than public registration.',
    ww: {
      B: 'A patent requires public disclosure in exchange for time-limited exclusivity.',
      C: 'A trademark protects brand identifiers like names and logos.',
      D: 'A copyright protects original creative/literary works.',
    },
    er: 'Distinguishes secrecy-based protection (trade secret) from registered protections.',
  },
  {
    t: 'Intellectual Property', s: 'Patent vs trademark vs copyright', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Licensing and Property Rights',
    q: 'Which IP protection covers brand identifiers such as a unique product name, logo, or slogan?',
    o: ['Trademark', 'Patent', 'Copyright', 'Trade secret'],
    a: 'A',
    wc: 'A trademark protects brand identifiers like names, logos, and slogans.',
    ww: {
      B: 'A patent protects inventions/designs.',
      C: 'A copyright protects creative/literary works.',
      D: 'A trade secret protects confidential competitive processes.',
    },
    er: 'Maps brand identifiers to trademarks.',
  },
  {
    t: 'Intellectual Property', s: 'Copyright', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Licensing and Property Rights',
    q: 'Using someone else\'s copyrighted material generally requires:',
    o: ['Permission or attribution as required by the license', 'Nothing, since copyright never restricts reuse', 'A patent filing', 'A trademark registration'],
    a: 'A',
    wc: 'Use of copyrighted material requires permission or attribution per the applicable terms.',
    ww: {
      B: 'Copyright does restrict reuse without permission.',
      C: 'Patents protect inventions, not reuse of creative works.',
      D: 'Trademarks protect brand identifiers, unrelated to copyrighted-work reuse.',
    },
    er: 'Tests basic copyright reuse obligations.',
  },
  {
    t: 'Intellectual Property', s: 'EULA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Licenses',
    q: 'An End User License Agreement (EULA) is best described as:',
    o: [
      'A binding agreement between the user and the license issuer governing product use',
      'A government statute regulating software exports',
      'A free public-domain dedication of a work',
      'An internal company data classification label',
    ],
    a: 'A',
    wc: 'A EULA is a binding agreement between the user and the license issuer defining how the product may be used.',
    ww: {
      B: 'Export regulation is governed by EXIM controls, not a EULA.',
      C: 'Public-domain dedication is different from a EULA\'s binding terms.',
      D: 'Classification labels are internal asset-security artifacts.',
    },
    er: 'Recall of EULA as a binding use agreement.',
  },
  {
    t: 'Intellectual Property', s: 'Perpetual license', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Licenses',
    q: 'A license that grants lifetime authorization to use a product is a:',
    o: ['Perpetual license', 'Subscription license', 'Creative Commons license', 'Trade secret'],
    a: 'A',
    wc: 'A perpetual license grants lifetime authorization to use the product.',
    ww: {
      B: 'A subscription license is time-limited and renews.',
      C: 'Creative Commons is a free-use license for copyrighted materials.',
      D: 'A trade secret is an IP protection, not a license type.',
    },
    er: 'Recall of perpetual-license meaning.',
  },
  {
    t: 'Intellectual Property', s: 'Creative Commons', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Licenses',
    q: 'Creative Commons (CC) licenses are primarily used to:',
    o: [
      'Grant free use of copyrighted materials under defined conditions',
      'Patent a novel invention',
      'Register a corporate trademark',
      'Control the export of encryption technology',
    ],
    a: 'A',
    wc: 'Creative Commons provides free-use licensing for copyrighted materials under specified conditions.',
    ww: {
      B: 'Patents protect inventions, not free reuse of works.',
      C: 'Trademark registration protects brand identifiers.',
      D: 'Encryption export is an EXIM matter.',
    },
    er: 'Maps CC to free copyrighted-work licensing.',
  },
  {
    t: 'Intellectual Property', s: 'Key IP protections', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Governance and Compliance > Licensing and Property Rights',
    q: 'Which TWO are recognized categories of intellectual property protection? (Select TWO.)',
    o: ['Patent', 'Copyright', 'Baseline', 'Tactical plan'],
    a: ['A', 'B'],
    wc: 'Patents and copyrights are key intellectual property protections.',
    ww: {
      C: 'A baseline is a minimum set of security controls, not an IP protection.',
      D: 'A tactical plan is a mid-term security plan, not an IP protection.',
    },
    er: 'Separates genuine IP protections from unrelated governance terms.',
  },
  {
    t: 'Intellectual Property', s: 'Corporate espionage', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Corporate Espionage',
    q: 'A competitor secretly obtains a company\'s confidential product formulas by bribing an insider. This activity is BEST characterized as:',
    o: [
      'Corporate espionage, which may constitute criminal activity beyond ethical competitive research',
      'Legitimate competitive intelligence gathering',
      'A standard licensing arrangement',
      'A protected exercise of fair use',
    ],
    a: 'A',
    wc: 'Secretly acquiring protected information without the owner\'s permission is corporate espionage, going beyond ethical research and potentially criminal.',
    ww: {
      B: 'Legitimate competitive intelligence uses public/ethical sources, not bribery and theft.',
      C: 'No license grants access; this is unauthorized acquisition.',
      D: 'Fair use concerns limited copyrighted-work use, not theft of trade secrets.',
    },
    er: 'Distinguishes illegal espionage from legitimate competitive intelligence.',
  },
  {
    t: 'Intellectual Property', s: 'WIPO', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > International Protection of Intellectual Property',
    q: 'The World Intellectual Property Organization (WIPO) primarily:',
    o: [
      'Provides technical assistance for international intellectual property protection',
      'Enforces US federal financial-disclosure rules',
      'Issues payment-card security standards',
      'Sets EU data-subject rights',
    ],
    a: 'A',
    wc: 'WIPO provides technical assistance for international IP protection.',
    ww: {
      B: 'Financial-disclosure rules are SOX (US).',
      C: 'Card standards are PCI DSS.',
      D: 'EU data-subject rights come from GDPR.',
    },
    er: 'Recall of WIPO\'s international IP role.',
  },
  // ---- Export/Import controls ----
  {
    t: 'Export and Import Controls', s: 'EXIM purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Export and Import Controls',
    q: 'Export and Import Controls (EXIM) primarily aim to:',
    o: [
      'Prevent unauthorized access to trade secrets, controlled technologies, and sensitive data across borders',
      'Standardize corporate financial reporting',
      'Define data-subject rights for EU residents',
      'Set minimum password complexity requirements',
    ],
    a: 'A',
    wc: 'EXIM controls regulate cross-border transfer of technology, goods, and services to prevent unauthorized access to controlled technologies and sensitive data.',
    ww: {
      B: 'Financial reporting is SOX, not EXIM.',
      C: 'EU data-subject rights are GDPR.',
      D: 'Password rules are technical/operational controls, not EXIM.',
    },
    er: 'Maps EXIM to cross-border technology/data control.',
  },
  {
    t: 'Export and Import Controls', s: 'Wassenaar Arrangement', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Export and Import Controls',
    q: 'The Wassenaar Arrangement is most relevant to which security-related export concern?',
    o: [
      'Controls on the export of items such as encryption technology across borders',
      'Privacy rights of EU data subjects',
      'Accuracy of public companies\' financial statements',
      'Protection of US health information',
    ],
    a: 'A',
    wc: 'The Wassenaar Arrangement governs export controls, including categories covering encryption technology (e.g., Category 5).',
    ww: {
      B: 'EU privacy rights come from GDPR.',
      C: 'Financial-statement accuracy is SOX.',
      D: 'Health-information protection is HIPAA.',
    },
    er: 'Connects Wassenaar to encryption/technology export controls.',
  },
  {
    t: 'Export and Import Controls', s: 'Dual-use goods', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Export and Import Controls',
    q: 'Mechanical components that could be used in both civilian products and military systems are an example of:',
    o: ['Dual-use goods', 'Data localization', 'A perpetual license', 'A privacy impact assessment'],
    a: 'A',
    wc: 'Dual-use goods have both civilian and military applications and are therefore subject to special export controls.',
    ww: {
      B: 'Data localization concerns keeping data within a country\'s borders.',
      C: 'A perpetual license is a software-use term.',
      D: 'A PIA assesses privacy controls.',
    },
    er: 'Recognizes the dual-use concept in export control.',
  },
  {
    t: 'Export and Import Controls', s: 'Data localization', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Export and Import Controls',
    q: 'A country requires that its citizens\' personal data be stored on servers physically located within its borders. This requirement is known as:',
    o: ['Data localization', 'Transborder data flow', 'Data portability', 'Data classification'],
    a: 'A',
    wc: 'Data localization mandates that certain data be stored (and sometimes processed) within a specific country\'s borders.',
    ww: {
      B: 'Transborder data flow refers to data crossing borders, the opposite emphasis.',
      C: 'Data portability is a GDPR right to reuse data across services.',
      D: 'Data classification is labeling data by sensitivity.',
    },
    er: 'Distinguishes data localization from transborder data flow.',
  },
  {
    t: 'Export and Import Controls', s: 'Encryption export', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Export and Import Controls',
    q: 'A US company plans to ship its strong-encryption software to customers in several countries. To avoid violating export controls, it should FIRST:',
    o: [
      'Verify compliance with applicable export-control categories (e.g., Wassenaar Category 5) before shipping',
      'Ship immediately and address any legal issues only if challenged',
      'Remove all encryption to avoid any controls, regardless of customer needs',
      'Assume software is exempt because it is intangible',
    ],
    a: 'A',
    wc: 'Encryption software exported without proper compliance can violate export-control categories (e.g., Wassenaar Category 5 Part 2), so compliance must be verified first.',
    ww: {
      B: 'Shipping first and reacting later risks legal violations and penalties.',
      C: 'Stripping needed functionality is not a compliance strategy and harms customers.',
      D: 'Software, including intangible delivery, is subject to export controls.',
    },
    er: 'Tests proactive export-control compliance for cryptographic software.',
  },
  // ---- Cybercrime, threat actors, attacks ----
  {
    t: 'Cybercrime and Threat Actors', s: 'Active vs passive attacks', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Cyber Attacks',
    q: 'An attacker passively eavesdrops on network traffic to learn information without altering any system resources. This is a:',
    o: ['Passive attack', 'Active attack', 'Zero-day attack', 'Destruction crime'],
    a: 'A',
    wc: 'A passive attack attempts to learn or use information from the system without affecting its resources.',
    ww: {
      B: 'An active attack alters system resources or affects operation.',
      C: 'A zero-day exploits a previously unknown vulnerability, not defined by passivity.',
      D: 'A destruction crime deliberately destroys data or systems.',
    },
    er: 'Distinguishes passive (observe) from active (alter) attacks.',
  },
  {
    t: 'Cybercrime and Threat Actors', s: 'Zero-day', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Cyber Attacks',
    q: 'A zero-day attack occurs when attackers exploit:',
    o: [
      'A previously unknown vulnerability that developers have not yet patched',
      'A vulnerability that was patched years ago',
      'A misconfigured but documented setting',
      'A user who shares their password willingly',
    ],
    a: 'A',
    wc: 'A zero-day exploits a previously unknown vulnerability that developers have not had time to address and patch.',
    ww: {
      B: 'An old patched vulnerability is not a zero-day.',
      C: 'A documented misconfiguration is a known issue, not a zero-day.',
      D: 'That describes social engineering, not a zero-day.',
    },
    er: 'Recall of the zero-day definition.',
  },
  {
    t: 'Cybercrime and Threat Actors', s: 'Insider threat', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Threat Actors',
    q: 'A disgruntled systems administrator with legitimate network access copies confidential files to sell to a competitor. This threat actor is BEST classified as:',
    o: ['Insider threat', 'Script kiddie', 'State actor', 'Hacktivist'],
    a: 'A',
    wc: 'An insider threat is an employee who has access to corporate networks and might exploit that access to steal information.',
    ww: {
      B: 'A script kiddie uses prebuilt tools and lacks sophisticated access/expertise; the key here is trusted insider access.',
      C: 'A state actor is government-sponsored; nothing indicates that.',
      D: 'A hacktivist is motivated by a cause; here the motive is personal/financial misuse of insider access.',
    },
    er: 'Tests recognizing insider misuse of legitimate access.',
  },
  {
    t: 'Cybercrime and Threat Actors', s: 'Script kiddie', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Threat Actors',
    q: 'An individual who uses existing scripts or tools to attack systems but lacks sophisticated expertise is a:',
    o: ['Script kiddie', 'State actor', 'Insider threat', 'Data steward'],
    a: 'A',
    wc: 'A script kiddie uses existing scripts or code to hack, lacking sophisticated expertise.',
    ww: {
      B: 'A state actor is a sophisticated government-sponsored attacker.',
      C: 'An insider threat misuses legitimate access.',
      D: 'A data steward is an internal data-expertise role, not a threat actor.',
    },
    er: 'Recall of the script-kiddie definition.',
  },
  {
    t: 'Cybercrime and Threat Actors', s: 'Threat actor types', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Threat Actors',
    q: 'Which TWO are types of threat actors described in the guide? (Select TWO.)',
    o: ['State actors', 'Insider threats', 'Baselines', 'Tactical plans'],
    a: ['A', 'B'],
    wc: 'State actors (government-sponsored) and insider threats (trusted employees who misuse access) are both threat-actor types.',
    ww: {
      C: 'A baseline is a minimum set of controls, not a threat actor.',
      D: 'A tactical plan is a planning horizon, not a threat actor.',
    },
    er: 'Separates threat-actor types from governance terms.',
  },
  {
    t: 'Cybercrime and Threat Actors', s: 'State actor', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Threat Actors',
    q: 'A highly resourced, government-sponsored group conducts a long-term espionage campaign against a defense contractor. This threat actor is BEST described as a:',
    o: ['State actor', 'Script kiddie', 'Casual hacker', 'Disgruntled customer'],
    a: 'A',
    wc: 'State actors are government-sponsored groups engaging in espionage and other cyber operations, typically well-resourced and persistent.',
    ww: {
      B: 'Script kiddies lack the sophistication and resources described.',
      C: 'A casual hacker would not mount a sustained, well-funded espionage campaign.',
      D: 'A disgruntled customer does not match a government-sponsored espionage profile.',
    },
    er: 'Tests recognizing the state-actor profile from resources and intent.',
  },
  // ---- Investigations (1.5) ----
  {
    t: 'Investigations', s: 'Investigation types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Incident Management > Investigations (administrative, criminal, civil, regulatory)',
    q: 'An internal investigation conducted to determine whether an employee violated company policy, used to support an HR decision, is which type of investigation?',
    o: ['Administrative', 'Criminal', 'Civil', 'Regulatory'],
    a: 'A',
    wc: 'Administrative investigations address internal policy violations and support internal/organizational decisions.',
    ww: {
      B: 'Criminal investigations involve potential violations of criminal law and law enforcement.',
      C: 'Civil investigations involve disputes between parties (e.g., contracts, damages).',
      D: 'Regulatory investigations involve compliance with a regulator\'s rules.',
    },
    er: 'Maps an internal policy-violation inquiry to the administrative type.',
  },
  {
    t: 'Investigations', s: 'Standards of proof', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Incident Management > Investigations (administrative, criminal, civil, regulatory)',
    q: 'A case that could send a defendant to prison generally requires a higher standard of proof than a lawsuit seeking monetary damages. This contrast is BETWEEN which two investigation/case types?',
    o: [
      'Criminal (beyond a reasonable doubt) vs civil (preponderance of the evidence)',
      'Administrative vs awareness',
      'Regulatory vs perpetual',
      'Civil vs Creative Commons',
    ],
    a: 'A',
    wc: 'Criminal cases require the highest standard (beyond a reasonable doubt), while civil cases use the lower preponderance-of-the-evidence standard.',
    ww: {
      B: '"Awareness" is a training concept, not a case type.',
      C: '"Perpetual" is a license type, not a case standard.',
      D: 'Creative Commons is a license, not an investigation type.',
    },
    er: 'Tests the differing standards of proof across criminal and civil matters.',
  },
  {
    t: 'Investigations', s: 'Regulatory investigation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Incident Management > Investigations (administrative, criminal, civil, regulatory)',
    q: 'An inquiry initiated by a government regulator to determine whether an organization complied with a specific industry rule is a(n):',
    o: ['Regulatory investigation', 'Administrative investigation', 'Criminal investigation', 'Civil investigation'],
    a: 'A',
    wc: 'A regulatory investigation examines compliance with a regulator\'s rules or standards for an industry.',
    ww: {
      B: 'Administrative investigations are internal policy matters.',
      C: 'Criminal investigations pursue violations of criminal law.',
      D: 'Civil investigations concern disputes between private parties.',
    },
    er: 'Distinguishes regulatory from administrative, criminal, and civil investigations.',
  },
];
