// Domain 1 — Part 1 (Q0001-Q0040): Ethics, CIA/authenticity/non-repudiation,
// security governance & planning, organizational roles & responsibilities.
module.exports = [
  // ---- ISC2 Code of Ethics (1.1) ----
  {
    t: 'ISC2 Code of Ethics', s: 'Canons of the Code of Ethics', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'Two canons of the ISC2 Code of Ethics appear to conflict in a given situation. According to ISC2 guidance, how should the canons be applied to resolve the conflict?',
    o: [
      'Apply the canons in the order they are presented, giving earlier canons precedence over later ones',
      'Apply whichever canon best protects the certified member from personal liability',
      'Apply the canon that most benefits the member\'s employer',
      'Ignore the canons and defer entirely to local law',
    ],
    a: 'A',
    wc: 'ISC2 states the canons are listed in order of precedence; when they conflict, the canon appearing first (protecting society and the public good) takes priority over later ones.',
    ww: {
      B: 'The Code exists to protect society and the profession, not to shield the member from liability.',
      C: 'Employer benefit is not the ordering principle; the public good comes first.',
      D: 'Law and the Code operate together; the Code is a condition of certification and is not discarded.',
    },
    er: 'Tests whether the candidate knows the canons have a defined order of precedence, led by protecting society and the common good.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Canons of the Code of Ethics', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'Which of the following is the FIRST canon of the ISC2 Code of Ethics?',
    o: [
      'Protect society, the common good, necessary public trust and confidence, and the infrastructure',
      'Act honorably, honestly, justly, responsibly, and legally',
      'Provide diligent and competent service to principals',
      'Advance and protect the profession',
    ],
    a: 'A',
    wc: 'The first canon is to protect society, the common good, necessary public trust and confidence, and the infrastructure.',
    ww: {
      B: 'This is the second canon.',
      C: 'This is the third canon.',
      D: 'This is the fourth canon.',
    },
    er: 'Confirms recall of the ordered canons, with society/public good first.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Professional ethics', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'A CISSP discovers that a popular product their employer sells contains a serious, exploitable vulnerability that endangers many customers. Management instructs the CISSP to stay silent to protect quarterly sales. Applying the Code of Ethics, what should most strongly guide the CISSP\'s response?',
    o: [
      'The duty to protect society and the public good outweighs the employer\'s sales interest',
      'The duty to provide service to principals means following the employer\'s instruction without question',
      'The member should resign immediately and take no further action',
      'The member should publicly disclose full exploit code to force a fix',
    ],
    a: 'A',
    wc: 'Protecting society and necessary public trust is the highest-precedence canon and outweighs short-term employer revenue; the member should pursue responsible remediation/disclosure.',
    ww: {
      B: 'Service to principals is a lower canon and never licenses endangering the public.',
      C: 'Resigning abandons the duty to protect society and does nothing to remediate the risk.',
      D: 'Releasing full exploit code recklessly harms customers and violates acting honorably and protecting society.',
    },
    er: 'Tests precedence of public protection over employer pressure, and responsible rather than reckless action.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Professional ethics', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'Which TWO behaviors are consistent with the canon "Act honorably, honestly, justly, responsibly, and legally"? (Select TWO.)',
    o: [
      'Accurately representing your qualifications and the limits of your expertise',
      'Reporting findings truthfully even when they are unflattering to your employer',
      'Exaggerating risk findings to win budget for a project you favor',
      'Withholding a conflict of interest from a client to keep an engagement',
    ],
    a: ['A', 'B'],
    wc: 'Honest representation of qualifications and truthful reporting both embody honorable, honest, and just conduct.',
    ww: {
      C: 'Exaggerating findings is dishonest and manipulative, violating the canon.',
      D: 'Concealing a conflict of interest is dishonest and unjust.',
    },
    er: 'Distinguishes honest professional conduct from self-serving misrepresentation.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Preamble and certification condition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'According to ISC2, adherence to the Code of Ethics is best described as which of the following?',
    o: [
      'A condition of certification that all certified members must follow',
      'A set of optional suggestions for new professionals',
      'A legal statute enforced by government regulators',
      'A guideline that applies only while taking the exam',
    ],
    a: 'A',
    wc: 'ISC2 states that strict adherence to the Code is a condition of certification.',
    ww: {
      B: 'It is mandatory, not optional.',
      C: 'It is a professional code, not government law.',
      D: 'It applies throughout a member\'s certified career, not only during the exam.',
    },
    er: 'Confirms the Code is binding for the duration of certification.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Professional ethics', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'A CISSP is asked to take on consulting work that directly competes with a current client\'s interests. The most ethically appropriate first step is to:',
    o: [
      'Disclose the potential conflict of interest to the affected parties',
      'Accept the work quietly because more income advances the profession',
      'Decline all future consulting to avoid any appearance of conflict',
      'Proceed but keep the two engagements secret from each other',
    ],
    a: 'A',
    wc: 'Acting honorably and justly requires disclosing conflicts of interest so affected parties can make informed decisions.',
    ww: {
      B: 'Income does not justify concealing a conflict; this violates honest/just conduct.',
      C: 'Blanket avoidance is unnecessary; disclosure and management of the conflict is the correct response.',
      D: 'Secrecy compounds the conflict and is dishonest.',
    },
    er: 'Tests conflict-of-interest handling through transparency.',
  },
  {
    t: 'ISC2 Code of Ethics', s: 'Advancing the profession', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Code of Ethics',
    q: 'Which action best fulfills the canon "Advance and protect the profession"?',
    o: [
      'Mentoring junior practitioners and discouraging unethical certification practices',
      'Refusing to share any knowledge so competitors cannot benefit',
      'Endorsing colleagues for skills you have not verified they possess',
      'Publicly disparaging other certifications to elevate your own',
    ],
    a: 'A',
    wc: 'Mentoring and upholding ethical standards strengthens and protects the profession, fulfilling the fourth canon.',
    ww: {
      B: 'Hoarding knowledge does not advance the profession.',
      C: 'Endorsing unverified skills is dishonest and harms the profession\'s credibility.',
      D: 'Disparaging others is unprofessional and does not protect the profession.',
    },
    er: 'Links the fourth canon to constructive, honest professional behavior.',
  },
  // ---- CIA Triad / authenticity / non-repudiation (1.2) ----
  {
    t: 'Information Security Concepts', s: 'CIA Triad', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'Ensuring that data is not disclosed to unauthorized persons or processes is the definition of which security principle?',
    o: ['Confidentiality', 'Integrity', 'Availability', 'Non-repudiation'],
    a: 'A',
    wc: 'Confidentiality ensures information is not disclosed to unauthorized parties—preventing people from seeing data they are not allowed to see.',
    ww: {
      B: 'Integrity concerns unauthorized alteration of data, not disclosure.',
      C: 'Availability concerns timely access for authorized users.',
      D: 'Non-repudiation prevents denial of an action\'s origin.',
    },
    er: 'Basic recall of the confidentiality definition.',
  },
  {
    t: 'Information Security Concepts', s: 'CIA Triad', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'An attacker modifies the dollar amounts stored in a bank\'s transaction database so that transfers are recorded incorrectly. Which element of the CIA triad is primarily violated?',
    o: ['Integrity', 'Confidentiality', 'Availability', 'Authenticity'],
    a: 'A',
    wc: 'Unauthorized alteration of stored data is an integrity violation—preventing data from being changed by those not allowed to change it.',
    ww: {
      B: 'No unauthorized disclosure of data is described.',
      C: 'The data remains accessible; availability is not the primary concern.',
      D: 'Authenticity concerns the legitimacy of the source of an action, which is secondary here to the data alteration itself.',
    },
    er: 'Maps an unauthorized-modification event to the integrity property.',
  },
  {
    t: 'Information Security Concepts', s: 'Availability', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'A ransomware outbreak encrypts files on production servers, blocking authorized users from accessing them, though the data is never read or altered by the attacker beyond encryption. Which CIA property is most directly impacted?',
    o: ['Availability', 'Confidentiality', 'Integrity', 'Non-repudiation'],
    a: 'A',
    wc: 'Blocking authorized access to data degrades availability—ensuring data is usable by authorized parties when needed.',
    ww: {
      B: 'The scenario specifies the data was not disclosed to unauthorized parties.',
      C: 'While encryption changes the bytes, the defining harm here is denial of access (availability), not silent corruption of legitimate content.',
      D: 'Non-repudiation is unrelated to access denial.',
    },
    er: 'Tests recognizing availability as the property denied by ransomware encryption.',
  },
  {
    t: 'Information Security Concepts', s: 'Non-repudiation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'Which security property proves that data or an action originated from a particular subject who cannot later deny it, and is typically accomplished using cryptography?',
    o: ['Non-repudiation', 'Availability', 'Confidentiality', 'Redundancy'],
    a: 'A',
    wc: 'Non-repudiation proves the origin of data or actions so the originator cannot dispute it, commonly enforced with cryptographic digital signatures.',
    ww: {
      B: 'Availability concerns access, not proof of origin.',
      C: 'Confidentiality concerns disclosure, not proof of origin.',
      D: 'Redundancy is a reliability technique, not a CIA/authenticity property.',
    },
    er: 'Connects non-repudiation to cryptographic proof of origin.',
  },
  {
    t: 'Information Security Concepts', s: 'Authenticity', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'A system verifies that a received message genuinely came from the claimed sender and was created by a legitimate source. Which property is being enforced?',
    o: ['Authenticity', 'Availability', 'Confidentiality', 'Anonymity'],
    a: 'A',
    wc: 'Authenticity ensures that data or an action came from a legitimate, verified source.',
    ww: {
      B: 'Availability concerns access, not source legitimacy.',
      C: 'Confidentiality concerns disclosure, not source legitimacy.',
      D: 'Anonymity is the opposite goal—hiding source identity.',
    },
    er: 'Distinguishes authenticity (legitimacy of source) from confidentiality and non-repudiation.',
  },
  {
    t: 'Information Security Concepts', s: 'CIA Triad trade-offs', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'A hospital must keep patient monitoring systems running continuously, even if that means occasionally relaxing strict access prompts during emergencies. This design choice prioritizes which CIA property, and at the potential expense of which other?',
    o: [
      'Prioritizes availability, potentially at the expense of confidentiality',
      'Prioritizes confidentiality, potentially at the expense of integrity',
      'Prioritizes integrity, potentially at the expense of availability',
      'Prioritizes non-repudiation, potentially at the expense of authenticity',
    ],
    a: 'A',
    wc: 'Keeping life-critical systems continuously usable favors availability; relaxing access prompts can weaken confidentiality controls.',
    ww: {
      B: 'The design relaxes access controls, which reduces confidentiality rather than prioritizing it.',
      C: 'No integrity trade-off is described; the trade is access continuity vs. access restriction.',
      D: 'Neither non-repudiation nor authenticity is the focus of continuous uptime decisions here.',
    },
    er: 'Tests understanding that CIA properties can conflict and must be balanced to business/mission priorities.',
  },
  {
    t: 'Information Security Concepts', s: 'CIA Triad', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'Which TWO controls primarily support the integrity element of the CIA triad? (Select TWO.)',
    o: [
      'Cryptographic hashing of files to detect unauthorized changes',
      'Digital signatures that detect tampering with a message',
      'Redundant power supplies and failover clustering',
      'Full-disk encryption of laptops at rest',
    ],
    a: ['A', 'B'],
    wc: 'Hashing and digital signatures both detect unauthorized modification, directly supporting integrity.',
    ww: {
      C: 'Redundant power and failover support availability.',
      D: 'Full-disk encryption protects confidentiality of data at rest.',
    },
    er: 'Separates integrity-focused controls from availability- and confidentiality-focused ones.',
  },
  {
    t: 'Information Security Concepts', s: 'Core principles', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'Beyond confidentiality, integrity, and availability, which two additional properties does the study guide list as core information security concepts?',
    o: [
      'Authenticity and non-repudiation',
      'Redundancy and scalability',
      'Anonymity and obscurity',
      'Profitability and efficiency',
    ],
    a: 'A',
    wc: 'The guide lists authenticity and non-repudiation alongside the CIA triad as core principles.',
    ww: {
      B: 'Redundancy and scalability are reliability/architecture qualities, not core security principles here.',
      C: 'Anonymity and obscurity are not the listed core principles.',
      D: 'Profitability and efficiency are business goals, not security properties.',
    },
    er: 'Confirms the expanded set of core properties taught in the guide.',
  },
  {
    t: 'Information Security Concepts', s: 'Non-repudiation vs authenticity', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Information Security Concepts',
    q: 'A digital signature on an email both proves the message came from the sender and prevents the sender from later denying they sent it. The "cannot later deny" aspect specifically provides:',
    o: ['Non-repudiation', 'Confidentiality', 'Availability', 'Least privilege'],
    a: 'A',
    wc: 'The inability of the originator to deny the action is non-repudiation; the proof-of-source aspect is authenticity, and both are delivered by the signature.',
    ww: {
      B: 'Signatures do not, by themselves, hide message contents (confidentiality).',
      C: 'Availability is unrelated to signing.',
      D: 'Least privilege is an access principle, not a property of a signature.',
    },
    er: 'Forces a precise distinction between the authenticity and non-repudiation aspects of a signature.',
  },
  // ---- Security governance, alignment, planning (1.3) ----
  {
    t: 'Security Governance', s: 'Top-down approach', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'Why does effective security governance require a top-down approach?',
    o: [
      'Support and direction for security must originate with senior management and flow down to all personnel',
      'Technical staff should define organizational risk appetite without executive input',
      'Security controls should be selected by end users based on personal preference',
      'Only the most junior employees understand day-to-day security needs',
    ],
    a: 'A',
    wc: 'In a top-down approach, senior management sets direction and support, which then flows to middle management and all other personnel—essential for security to be effective.',
    ww: {
      B: 'Risk appetite is set by senior leadership, not technical staff alone.',
      C: 'Control selection is governed by policy and risk decisions, not user preference.',
      D: 'Governance authority and accountability rest with leadership, not solely junior staff.',
    },
    er: 'Tests the governance principle that security is driven and sponsored from the top.',
  },
  {
    t: 'Security Governance', s: 'Security planning horizons', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'A long-term plan that outlines an organization\'s security goals and objectives over roughly a five-year horizon and is updated annually is best described as a:',
    o: ['Strategic plan', 'Tactical plan', 'Operational plan', 'Incident response runbook'],
    a: 'A',
    wc: 'The strategic plan is the long-term plan outlining goals over a multi-year horizon and is typically reviewed/updated annually.',
    ww: {
      B: 'A tactical plan is mid-term (about one year) and supports the strategic plan.',
      C: 'An operational plan is short-term and highly detailed.',
      D: 'A runbook is an operational procedure, not a planning horizon.',
    },
    er: 'Distinguishes strategic, tactical, and operational planning horizons.',
  },
  {
    t: 'Security Governance', s: 'Security planning horizons', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'Which plan is mid-term (approximately one year), designed to meet the security objectives defined in the strategic plan?',
    o: ['Tactical plan', 'Strategic plan', 'Operational plan', 'Capital plan'],
    a: 'A',
    wc: 'The tactical plan is mid-term (about one year) and is designed to achieve the objectives set in the strategic plan.',
    ww: {
      B: 'The strategic plan is the long-term plan it supports.',
      C: 'The operational plan is short-term and more granular.',
      D: 'A capital plan is a financial/budget plan, not a security planning horizon.',
    },
    er: 'Confirms the tactical layer\'s horizon and purpose.',
  },
  {
    t: 'Security Governance', s: 'Aligning security with the organization', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'The primary purpose of aligning the security program with organizational goals, culture, and operations is to:',
    o: [
      'Ensure security supports the business objectives rather than obstructing them',
      'Maximize the number of security controls regardless of business need',
      'Allow security to operate independently of business strategy',
      'Shift all risk decisions to the IT help desk',
    ],
    a: 'A',
    wc: 'Security must support the organization\'s objectives, principles, and strategies; alignment tailors security to business needs so it enables rather than blocks the mission.',
    ww: {
      B: 'More controls without business justification is not alignment and may impede operations.',
      C: 'Operating independently of strategy is the opposite of alignment.',
      D: 'Risk decisions belong to management with appropriate authority, not the help desk.',
    },
    er: 'Tests the business-enablement purpose of security alignment.',
  },
  {
    t: 'Security Governance', s: 'Organizational processes', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'A company is acquiring a smaller competitor. From a security governance perspective, what is the most important action regarding the existing security plans?',
    o: [
      'Review and update the security plans to account for the acquisition before integration proceeds',
      'Freeze all security changes until the next annual strategic review',
      'Adopt the acquired company\'s controls wholesale without assessment',
      'Delegate the decision to end users of both organizations',
    ],
    a: 'A',
    wc: 'Security plans must be reviewed and updated upon purchases, acquisitions, sales, or divestitures, because organizational structure changes affect risk and policy applicability.',
    ww: {
      B: 'Waiting for an annual review leaves the merged risk unmanaged during a high-risk period.',
      C: 'Adopting controls without assessment ignores due diligence and may import unknown risk.',
      D: 'Governance decisions of this magnitude rest with management, not end users.',
    },
    er: 'Tests the requirement to re-evaluate governance artifacts when organizational structure changes.',
  },
  {
    t: 'Security Governance', s: 'Security governance definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'Security governance is best defined as the practice of:',
    o: [
      'Ethically aligning business objectives with applicable laws, standards, and regulations',
      'Installing and patching all servers in the environment',
      'Writing the source code for security tools',
      'Performing day-to-day monitoring of firewall logs',
    ],
    a: 'A',
    wc: 'Governance defines how to ethically align business objectives to laws, standards, or regulations and sets how management acts in stakeholders\' best interest.',
    ww: {
      B: 'Patching is an operational task, not governance.',
      C: 'Coding tools is an engineering activity, not governance.',
      D: 'Log monitoring is an operational function, not governance.',
    },
    er: 'Separates strategic governance from operational/technical work.',
  },
  {
    t: 'Security Governance', s: 'Strategic vs operational', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'A new CISO finds that the security team has detailed daily procedures but no documented multi-year direction tied to business goals. Which planning gap should the CISO address FIRST to enable coherent governance?',
    o: [
      'Establish a strategic plan that links security to long-term business objectives',
      'Rewrite each server\'s operational hardening checklist',
      'Replace the ticketing system used by analysts',
      'Schedule more frequent firewall rule reviews',
    ],
    a: 'A',
    wc: 'Without a strategic plan, tactical and operational activities lack direction; the strategic layer must be established first so lower layers align to business objectives.',
    ww: {
      B: 'Operational checklists already exist; the gap is strategic direction.',
      C: 'Tooling changes do not resolve the absence of strategic alignment.',
      D: 'More frequent reviews are operational tuning, not the governance gap.',
    },
    er: 'Tests prioritization of the strategic layer when it is the missing governance element.',
  },
  {
    t: 'Security Governance', s: 'Planning hierarchy', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'Order the security plans from the LONGEST time horizon to the SHORTEST. (Provide the option labels in order.)',
    o: ['Strategic plan', 'Tactical plan', 'Operational plan'],
    a: 'A,B,C',
    wc: 'Strategic (long-term, multi-year) is broadest, tactical (about one year) supports it, and operational (short-term, detailed) is the most immediate.',
    ww: {},
    er: 'Tests the relative time horizons of the three planning layers.',
  },
  {
    t: 'Security Governance', s: 'Management support', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'For a security program to be effective, it must above all be:',
    o: [
      'Supported and sponsored by senior management',
      'Built entirely by external consultants',
      'Kept secret from most of the organization',
      'Focused only on perimeter firewalls',
    ],
    a: 'A',
    wc: 'The guide stresses that security must be supported by senior management to be effective, consistent with the top-down approach.',
    ww: {
      B: 'Consultants can assist, but executive sponsorship is the essential factor.',
      C: 'Awareness across the organization is needed; secrecy undermines effectiveness.',
      D: 'Perimeter-only focus ignores defense in depth and business alignment.',
    },
    er: 'Reinforces executive sponsorship as the foundation of an effective program.',
  },
  // ---- Organizational roles & responsibilities (1.3) ----
  {
    t: 'Organizational Roles and Responsibilities', s: 'CISO', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Which executive is responsible for the vision and strategy of the organization\'s security program?',
    o: ['Chief Information Security Officer (CISO)', 'Chief Financial Officer (CFO)', 'Chief Executive Officer (CEO)', 'Data Custodian'],
    a: 'A',
    wc: 'The CISO is responsible for the vision and strategy of the organization\'s security program.',
    ww: {
      B: 'The CFO is responsible for organizational finances and assets.',
      C: 'The CEO is responsible for everything relating to the organization overall, not specifically the security program strategy.',
      D: 'A data custodian implements data protection, an operational role.',
    },
    er: 'Recall of CISO accountability for security strategy.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'CIO vs CISO', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'How does the responsibility of the CIO differ from that of the CISO?',
    o: [
      'The CIO owns the vision/strategy for information systems; the CISO owns the vision/strategy for the security program',
      'The CIO owns the security program; the CISO owns physical facilities',
      'They are identical roles with different titles',
      'The CIO handles payroll while the CISO handles marketing',
    ],
    a: 'A',
    wc: 'The CIO is responsible for the vision and strategy of the organization\'s information systems, while the CISO is responsible for the vision and strategy of its security program.',
    ww: {
      B: 'The CISO, not the CIO, owns the security program; facilities are not the CISO\'s defining role.',
      C: 'They are distinct roles with different mandates.',
      D: 'Neither role is defined by payroll or marketing.',
    },
    er: 'Distinguishes information-systems leadership from security-program leadership.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Data Owner', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Who is responsible for the classification and protection of a given set of data?',
    o: ['Data Owner', 'Data Custodian', 'System Administrator', 'Auditor'],
    a: 'A',
    wc: 'The data owner is responsible for the classification and protection decisions for their data.',
    ww: {
      B: 'The custodian implements protection but does not set classification.',
      C: 'The administrator maintains the system, a privileged operational role.',
      D: 'The auditor verifies compliance, not classification ownership.',
    },
    er: 'Separates data ownership (decision/accountability) from custody (implementation).',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Data Custodian', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'A data owner classifies a dataset as "Confidential" and specifies it must be encrypted at rest. The team member who actually configures and maintains that encryption on the storage system is acting as the:',
    o: ['Data Custodian', 'Data Owner', 'Data Steward', 'Security Manager'],
    a: 'A',
    wc: 'Implementing and maintaining the protection the owner specifies (e.g., encryption) is the custodian\'s responsibility.',
    ww: {
      B: 'The owner sets classification and protection requirements but does not necessarily implement them.',
      C: 'The steward provides subject-matter expertise for specific data, not hands-on protection implementation.',
      D: 'The security manager develops and manages the broader security program.',
    },
    er: 'Tests the owner-vs-custodian distinction in an applied setting.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Data Steward', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Which role provides subject-matter expertise for specific data, such as ensuring it is used and interpreted correctly?',
    o: ['Data Steward', 'Data Custodian', 'Administrator', 'User'],
    a: 'A',
    wc: 'The data steward provides subject-matter expertise for specific data.',
    ww: {
      B: 'The custodian implements protection, not subject-matter expertise.',
      C: 'The administrator maintains the system.',
      D: 'A user simply accesses the system.',
    },
    er: 'Recall of the steward\'s SME function.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Security roles', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Which security role is primarily responsible for detecting, analyzing, and responding to security threats and attacks?',
    o: ['Security Analyst', 'Security Engineer', 'Security Manager', 'Data Owner'],
    a: 'A',
    wc: 'The security analyst detects, analyzes, and responds to security threats and attacks.',
    ww: {
      B: 'The security engineer designs, tests, and implements security solutions.',
      C: 'The security manager develops and manages the security program and its personnel.',
      D: 'The data owner sets classification and protection for data.',
    },
    er: 'Distinguishes analyst (detect/respond) from engineer (design/build) and manager (program).',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Auditor', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'To preserve independence, the role responsible for auditing compliance with the security policy should NOT also be the person who:',
    o: [
      'Implements and maintains the information systems being audited',
      'Reads published security awareness emails',
      'Attends company all-hands meetings',
      'Completes annual security training',
    ],
    a: 'A',
    wc: 'The auditor verifies compliance and must remain independent from the administrator who implements/maintains the systems—separating these duties avoids a conflict of interest.',
    ww: {
      B: 'Reading awareness emails does not compromise audit independence.',
      C: 'Attending meetings is unrelated to audit independence.',
      D: 'Completing training does not conflict with the audit role.',
    },
    er: 'Connects auditor independence to separation of duties from system administration.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Administrator privilege', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'In the system roles described by the guide, the administrator is best characterized as a:',
    o: [
      'Privileged role responsible for implementing and maintaining the information system',
      'Non-privileged subject who only accesses the system',
      'External regulator who enforces national law',
      'Role that sets the organization\'s risk appetite',
    ],
    a: 'A',
    wc: 'The administrator is a privileged role responsible for implementing and maintaining the information system.',
    ww: {
      B: 'That describes a user, not an administrator.',
      C: 'Regulators are external to the system role model.',
      D: 'Risk appetite is set by senior management, not the administrator.',
    },
    er: 'Recall of the administrator as a privileged operational role.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Boards and committees', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Boards and committees primarily exist within an organization to:',
    o: [
      'Make key organizational decisions and provide oversight',
      'Perform daily patching of endpoints',
      'Write application source code',
      'Respond to individual help-desk tickets',
    ],
    a: 'A',
    wc: 'Boards and committees are groups responsible for making key organizational decisions and providing governance oversight.',
    ww: {
      B: 'Patching is an operational task handled by IT staff.',
      C: 'Coding is an engineering function.',
      D: 'Help-desk response is an operational support task.',
    },
    er: 'Reinforces the governance/oversight purpose of boards and committees.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'CEO accountability', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'After a major breach, regulators ask who holds ultimate accountability for everything relating to the organization, including its overall risk posture. The most accurate answer is the:',
    o: ['Chief Executive Officer (CEO)', 'Security Analyst', 'Data Custodian', 'Help-desk technician'],
    a: 'A',
    wc: 'The CEO is responsible for everything relating to the organization, holding ultimate accountability even when functions are delegated.',
    ww: {
      B: 'The analyst handles detection and response, not ultimate organizational accountability.',
      C: 'The custodian implements data protection at an operational level.',
      D: 'The technician provides support and has no organizational accountability.',
    },
    er: 'Tests that ultimate accountability rests at the top even when duties are delegated.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'CFO scope', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'The Chief Financial Officer (CFO) is responsible for everything relating to:',
    o: ['Organizational finances and assets', 'The security program\'s technical controls', 'Source code repositories', 'Physical badge issuance'],
    a: 'A',
    wc: 'The CFO is responsible for everything relating to organizational finances and assets.',
    ww: {
      B: 'Security controls fall under the CISO.',
      C: 'Code repositories fall under engineering/IT, not the CFO.',
      D: 'Badge issuance is a physical security operational task.',
    },
    er: 'Recall of CFO scope.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Role separation', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'Which TWO statements correctly describe data-related responsibilities? (Select TWO.)',
    o: [
      'The data owner decides the classification level of the data',
      'The data custodian implements the protection mechanisms for the data',
      'The user defines the organization\'s data retention policy',
      'The auditor implements encryption on the storage array',
    ],
    a: ['A', 'B'],
    wc: 'Owners set classification; custodians implement protection—the canonical separation between accountability and implementation.',
    ww: {
      C: 'Retention policy is set by owners/management, not end users.',
      D: 'Auditors verify compliance and must stay independent of implementation tasks like configuring encryption.',
    },
    er: 'Reinforces the owner/custodian/auditor/user separation.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'Roles-to-responsibilities mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    p: [
      'Data Owner',
      'Data Custodian',
      'Auditor',
      'Security Engineer',
    ],
    q: 'Match each role (1-4) to its primary responsibility (A-D).',
    o: [
      'Implements and maintains data protection mechanisms',
      'Sets data classification and protection requirements',
      'Designs, tests, and implements security solutions',
      'Verifies compliance with the security policy',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Data Owner → sets classification/protection (B); Data Custodian → implements protection (A); Auditor → verifies compliance (D); Security Engineer → designs/tests/implements solutions (C).',
    ww: {},
    er: 'Tests precise mapping of governance and operational roles to their defining duties.',
  },
  {
    t: 'Organizational Roles and Responsibilities', s: 'User role', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Organizational Roles and Responsibilities',
    q: 'In the system role model, a "user" is best defined as:',
    o: [
      'A subject with access to the information system',
      'The person who sets the organization\'s strategic security vision',
      'The privileged maintainer of the system',
      'The independent reviewer of policy compliance',
    ],
    a: 'A',
    wc: 'A user is a subject with access to the information system.',
    ww: {
      B: 'Strategic vision is the CISO\'s responsibility.',
      C: 'The privileged maintainer is the administrator.',
      D: 'Independent compliance review is the auditor\'s role.',
    },
    er: 'Recall of the user definition within the system role model.',
  },
  {
    t: 'Security Governance', s: 'Stakeholder interest', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Management Concepts > Aligning Security and the Organization',
    q: 'Security governance "sets the stage for how an organization\'s management will act." Acting in this capacity, management is expected to act primarily in the best interest of:',
    o: ['The business stakeholders', 'The most technically skilled engineer', 'External attackers', 'The lowest-cost vendor'],
    a: 'A',
    wc: 'Governance establishes that management acts in the best interest of the business stakeholders.',
    ww: {
      B: 'Individual technical skill does not define whose interests governance serves.',
      C: 'Acting for attackers is nonsensical and contrary to governance.',
      D: 'Cost minimization is not the governing interest; stakeholder interest is.',
    },
    er: 'Anchors governance to stakeholder interest as the guiding principle.',
  },
];
