// Domain 1 — Part 4 (final): Security policy framework, risk management
// concepts & response, controls & countermeasures, continuous monitoring,
// risk frameworks, quantitative/qualitative risk, risk assessment process,
// threat modeling, supply chain risk management, BCP/DR requirements.
module.exports = [
  // ---- Security policy framework (1.6) ----
  {
    t: 'Security Documentation', s: 'Policy vs standard vs procedure', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Security Compliance Artifacts',
    q: 'Which security document provides detailed, step-by-step instructions on how to implement a standard?',
    o: ['Procedure', 'Policy', 'Baseline', 'Guideline'],
    a: 'A',
    wc: 'A procedure provides detailed, step-by-step instructions on how to implement standards.',
    ww: {
      B: 'A policy is a high-level statement of management intent and goals.',
      C: 'A baseline defines the minimum security controls required to meet a standard.',
      D: 'A guideline offers recommendations/best practices when standards are unclear or non-specific.',
    },
    er: 'Distinguishes procedure (how-to steps) from policy, baseline, and guideline.',
  },
  {
    t: 'Security Documentation', s: 'Baseline', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Security Compliance Artifacts',
    q: 'The minimum set of security controls required to meet a standard, adjustable only through formal change management, is a:',
    o: ['Baseline', 'Guideline', 'Procedure', 'Policy'],
    a: 'A',
    wc: 'A baseline is the minimum security controls required to meet standards, changeable through formal change management.',
    ww: {
      B: 'A guideline is a non-mandatory recommendation.',
      C: 'A procedure is step-by-step implementation detail.',
      D: 'A policy is high-level management direction.',
    },
    er: 'Recall of baseline as the mandatory minimum control set.',
  },
  {
    t: 'Security Documentation', s: 'Guideline', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Security Compliance Artifacts',
    q: 'Which document type is a recommendation or best practice used when standards or procedures are unclear or non-specific, and is generally NOT mandatory?',
    o: ['Guideline', 'Standard', 'Baseline', 'Procedure'],
    a: 'A',
    wc: 'A guideline provides recommendations/best practices when standards or procedures are unclear or non-specific, and is advisory rather than mandatory.',
    ww: {
      B: 'A standard is a mandatory, specific requirement.',
      C: 'A baseline is a mandatory minimum control set.',
      D: 'A procedure is mandatory step-by-step instruction.',
    },
    er: 'Identifies the guideline as the advisory document.',
  },
  {
    t: 'Security Documentation', s: 'Standard', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Security Compliance Artifacts',
    q: 'A document that sets specific, mandatory requirements aligning with organizational policy (for example, requiring AES-256 for data at rest) is a:',
    o: ['Standard', 'Guideline', 'Policy', 'Baseline'],
    a: 'A',
    wc: 'A standard sets specific mandatory requirements that align with and detail how to comply with policy.',
    ww: {
      B: 'A guideline is advisory, not mandatory.',
      C: 'A policy is higher-level intent, not the specific requirement.',
      D: 'A baseline is the minimum control set; the specific mandatory requirement is the standard.',
    },
    er: 'Distinguishes a standard\'s specific mandate from policy and guideline.',
  },
  {
    t: 'Security Documentation', s: 'Policy types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Security Governance and Compliance > Types of Policies',
    q: 'A policy that defines the organization\'s overall security goals and responsibilities at the highest level is a(n):',
    o: ['Organizational (program) policy', 'Issue-specific policy', 'System-specific policy', 'Acceptable use procedure'],
    a: 'A',
    wc: 'An organizational (program) policy defines organization-wide security goals and responsibilities.',
    ww: {
      B: 'An issue-specific policy addresses a particular topic (e.g., email use).',
      C: 'A system-specific policy applies to a particular system.',
      D: 'A procedure is implementation detail, not a policy tier.',
    },
    er: 'Distinguishes organizational, issue-specific, and system-specific policies.',
  },
  {
    t: 'Security Documentation', s: 'Document hierarchy', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Security Governance and Compliance > Security Compliance Artifacts',
    q: 'Which TWO statements about security documentation are correct? (Select TWO.)',
    o: [
      'Standards are mandatory and detail specific requirements that support policy',
      'Guidelines are advisory recommendations used when standards are unclear',
      'Policies are step-by-step technical instructions for administrators',
      'Baselines are optional suggestions that require no change control',
    ],
    a: ['A', 'B'],
    wc: 'Standards are mandatory and specific; guidelines are advisory best practices—both stated correctly.',
    ww: {
      C: 'Policies are high-level intent; procedures (not policies) are step-by-step instructions.',
      D: 'Baselines are mandatory minimums adjusted only through formal change management, not optional.',
    },
    er: 'Tests correct relationships among policy, standard, baseline, procedure, and guideline.',
  },
  // ---- Risk management concepts & response (1.9) ----
  {
    t: 'Risk Management Concepts', s: 'Risk formula', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Risk Management Concepts',
    q: 'According to the guide, risk arises from the combination of:',
    o: ['Threats and vulnerabilities', 'Policies and procedures', 'Awareness and training', 'Patents and trademarks'],
    a: 'A',
    wc: 'Threats and vulnerabilities together create risk; risk management identifies, assesses, and mitigates that risk.',
    ww: {
      B: 'Policies and procedures are governance documents, not the components of risk.',
      C: 'Awareness and training are controls that reduce risk, not its definition.',
      D: 'Patents and trademarks are IP protections, unrelated to the risk formula.',
    },
    er: 'Confirms the threat-plus-vulnerability basis of risk.',
  },
  {
    t: 'Risk Management Concepts', s: 'Risk response - transfer', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Management > Risk Response and Monitoring',
    q: 'A company purchases cyber-insurance so that a third party bears much of the financial loss from a potential breach. Which risk response is this?',
    o: ['Risk assignment (transfer)', 'Risk avoidance', 'Risk acceptance', 'Risk deterrence'],
    a: 'A',
    wc: 'Transferring the responsibility/accountability of a risk to another party (e.g., via insurance) is risk assignment (transfer).',
    ww: {
      B: 'Avoidance means not undertaking the risky activity at all.',
      C: 'Acceptance means acknowledging and bearing the residual risk.',
      D: 'Deterrence implements controls to discourage the threat, not shift the loss.',
    },
    er: 'Maps insurance to risk transfer/assignment.',
  },
  {
    t: 'Risk Management Concepts', s: 'Risk response - avoidance', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Management > Risk Response and Monitoring',
    q: 'After assessing the risk, a company decides NOT to launch a new product line that would expose it to unacceptable regulatory risk. Which risk response is this?',
    o: ['Risk avoidance', 'Risk acceptance', 'Risk mitigation', 'Risk assignment'],
    a: 'A',
    wc: 'Choosing not to engage in an activity that introduces higher risk is risk avoidance.',
    ww: {
      B: 'Acceptance would mean proceeding and bearing the residual risk.',
      C: 'Mitigation would mean proceeding but reducing the risk with controls.',
      D: 'Assignment would mean transferring the risk to another party.',
    },
    er: 'Maps declining the risky activity to avoidance.',
  },
  {
    t: 'Risk Management Concepts', s: 'Residual risk & acceptance', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Risk Response and Monitoring',
    q: 'After applying controls, management formally acknowledges and decides to live with the remaining risk. The remaining risk and the decision are, respectively:',
    o: [
      'Residual risk; risk acceptance',
      'Inherent risk; risk avoidance',
      'Total risk; risk assignment',
      'Threat; risk deterrence',
    ],
    a: 'A',
    wc: 'The risk left after responses are applied is residual risk; choosing to live with it is risk acceptance.',
    ww: {
      B: 'Inherent risk is the risk before controls; avoidance is declining the activity.',
      C: 'Total risk is before controls; assignment transfers risk to another party.',
      D: 'A threat is a potential cause of harm; deterrence discourages it.',
    },
    er: 'Tests the residual-risk concept and its acceptance.',
  },
  {
    t: 'Risk Management Concepts', s: 'Risk mitigation', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Risk Response and Monitoring',
    q: 'Implementing controls to reduce a risk to an acceptable level is known as:',
    o: ['Risk mitigation', 'Risk acceptance', 'Risk avoidance', 'Risk transfer'],
    a: 'A',
    wc: 'Risk mitigation reduces risk to an acceptable level through various controls.',
    ww: {
      B: 'Acceptance bears the risk without reducing it.',
      C: 'Avoidance declines the risky activity entirely.',
      D: 'Transfer shifts the risk to another party.',
    },
    er: 'Recall of mitigation as risk reduction via controls.',
  },
  {
    t: 'Risk Management Concepts', s: 'Risk response strategies', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Risk Management > Risk Response and Monitoring',
    q: 'Which TWO of the following are recognized risk response strategies in the guide? (Select TWO.)',
    o: ['Risk deterrence', 'Risk acceptance', 'Risk amplification', 'Risk capitalization'],
    a: ['A', 'B'],
    wc: 'Risk deterrence (deterrent controls to reduce likelihood/impact) and risk acceptance (bearing residual risk) are recognized responses.',
    ww: {
      C: '"Risk amplification" is not a recognized response—organizations seek to reduce, not amplify, risk.',
      D: '"Risk capitalization" is not a defined risk response strategy.',
    },
    er: 'Separates genuine risk responses from invented terms.',
  },
  // ---- Controls & countermeasures (1.9) ----
  {
    t: 'Controls and Countermeasures', s: 'Control categories', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Controls and Countermeasures',
    q: 'A security awareness policy that employees must follow is which CATEGORY of control?',
    o: ['Administrative', 'Technical (logical)', 'Physical', 'Recovery'],
    a: 'A',
    wc: 'Administrative controls are procedures and processes (soft/process controls), such as policies and training.',
    ww: {
      B: 'Technical/logical controls protect assets through hardware/software mechanisms.',
      C: 'Physical controls protect tangible assets and facilities.',
      D: '"Recovery" is a control TYPE (function), not one of the three categories.',
    },
    er: 'Distinguishes control categories (admin/technical/physical) from control types.',
  },
  {
    t: 'Controls and Countermeasures', s: 'Control types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Types of Controls',
    q: 'A locked door with a "Authorized Personnel Only" sign that discourages intruders before any attempt is primarily which TYPE of control?',
    o: ['Deterrent', 'Corrective', 'Recovery', 'Compensating'],
    a: 'A',
    wc: 'Deterrent controls discourage unauthorized actions before they occur; signage that dissuades intrusion is deterrent.',
    ww: {
      B: 'Corrective controls modify the environment to fix issues after an event.',
      C: 'Recovery controls restore operations after an event.',
      D: 'Compensating controls substitute for a primary control that is infeasible.',
    },
    er: 'Tests classifying a control by its function (deter before the act).',
  },
  {
    t: 'Controls and Countermeasures', s: 'Control types', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Management > Types of Controls',
    q: 'An organization cannot apply the required encryption on a legacy system, so it isolates that system on a restricted network segment to provide equivalent protection. The network isolation is BEST classified as which type of control?',
    o: ['Compensating', 'Detective', 'Deterrent', 'Directive'],
    a: 'A',
    wc: 'A compensating control provides an alternative that supports or substitutes for a primary control that cannot be implemented.',
    ww: {
      B: 'Detective controls discover events after they occur; isolation is preventive/compensating here.',
      C: 'Deterrent controls discourage actions psychologically; isolation actively restricts access.',
      D: 'Directive controls direct behavior via policy; this is a technical substitute control.',
    },
    er: 'Tests recognizing a compensating control when the primary control is infeasible.',
  },
  {
    t: 'Controls and Countermeasures', s: 'Defense in depth', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Controls and Countermeasures',
    q: 'Combining administrative, technical, and physical controls in multiple layers so that no single failure exposes the asset is the strategy known as:',
    o: ['Defense in depth', 'Single sign-on', 'Risk acceptance', 'Data localization'],
    a: 'A',
    wc: 'Defense in depth layers multiple, varied controls so the failure of one does not compromise the whole.',
    ww: {
      B: 'Single sign-on is an authentication convenience, not a layered-defense strategy.',
      C: 'Risk acceptance is a risk response, not a control architecture.',
      D: 'Data localization concerns where data is stored geographically.',
    },
    er: 'Recall of defense in depth as layered, varied controls.',
  },
  {
    t: 'Controls and Countermeasures', s: 'Cost-benefit principle', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Management > Controls and Countermeasures',
    q: 'A proposed safeguard costs $50,000 per year to protect an asset whose total value is $20,000. According to the cost-benefit principle, the organization should:',
    o: [
      'Reconsider, because a control should not cost more than the value of the asset it protects',
      'Implement it immediately, since more security is always better',
      'Implement it because all assets must have maximum protection',
      'Transfer the asset\'s ownership to avoid the decision',
    ],
    a: 'A',
    wc: 'The cost-benefit principle states a control\'s cost should not exceed the asset value or the benefit gained; spending $50k to protect a $20k asset is not justified.',
    ww: {
      B: '"More is always better" ignores cost-benefit and wastes resources.',
      C: 'Maximum protection regardless of value contradicts the cost-benefit principle.',
      D: 'Transferring ownership does not address the disproportionate safeguard cost.',
    },
    er: 'Applies the safeguard cost-vs-asset-value principle.',
  },
  {
    t: 'Controls and Countermeasures', s: 'Control categories', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Risk Management > Controls and Countermeasures',
    q: 'Which TWO are categories (not types) of security controls? (Select TWO.)',
    o: ['Technical (logical) controls', 'Physical controls', 'Detective controls', 'Corrective controls'],
    a: ['A', 'B'],
    wc: 'Technical/logical and physical are control CATEGORIES (alongside administrative). Detective and corrective are control TYPES/functions.',
    ww: {
      C: 'Detective is a control type/function, not a category.',
      D: 'Corrective is a control type/function, not a category.',
    },
    er: 'Reinforces the category-vs-type distinction.',
  },
  // ---- Continuous monitoring ----
  {
    t: 'Continuous Monitoring', s: 'NIST SP 800-137', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Continuous Monitoring',
    q: 'Which framework is identified as the primary CISSP-exam reference for Information Security Continuous Monitoring (ISCM)?',
    o: ['NIST SP 800-137', 'ISO 28000', 'PCI DSS', 'NIST SP 800-30'],
    a: 'A',
    wc: 'NIST SP 800-137 (ISCM) is highlighted as the primary continuous-monitoring reference for the exam.',
    ww: {
      B: 'ISO 28000 is a supply-chain security management standard.',
      C: 'PCI DSS is a payment-card security standard.',
      D: 'NIST SP 800-30 covers risk assessment, not continuous monitoring specifically.',
    },
    er: 'Maps ISCM to NIST SP 800-137.',
  },
  {
    t: 'Continuous Monitoring', s: 'Scope', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Continuous Monitoring',
    q: 'How does continuous monitoring (continuous improvement) differ from simple system monitoring?',
    o: [
      'It evaluates the effectiveness of all types of security controls, not just log/system status review',
      'It is limited strictly to reviewing firewall logs',
      'It only runs once during system authorization',
      'It replaces the need for any security controls',
    ],
    a: 'A',
    wc: 'Continuous monitoring focuses on evaluating security control implementations and effectiveness across all control types—broader than log-file or system-status review.',
    ww: {
      B: 'It is not restricted to firewall logs or log review.',
      C: 'It is ongoing, not a one-time authorization activity.',
      D: 'It assesses controls; it does not replace them.',
    },
    er: 'Tests that continuous monitoring evaluates control effectiveness broadly.',
  },
  // ---- Risk frameworks ----
  {
    t: 'Risk Frameworks', s: 'NIST RMF steps', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 1 > Risk Management > Risk Frameworks',
    q: 'Place the following NIST Risk Management Framework (RMF) steps in their correct order, beginning after the Prepare step. (Provide the option labels in order.)',
    o: ['Categorize', 'Select', 'Implement', 'Assess', 'Authorize', 'Monitor'],
    a: 'A,B,C,D,E,F',
    wc: 'Following Prepare, the RMF proceeds: Categorize the system, Select controls, Implement them, Assess effectiveness, Authorize operation based on residual risk, then Monitor continuously.',
    ww: {},
    er: 'Tests the ordered RMF lifecycle (NIST SP 800-37).',
  },
  {
    t: 'Risk Frameworks', s: 'NIST CSF core functions', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > NIST Cybersecurity Framework',
    q: 'Which set correctly lists the five core functions of the NIST Cybersecurity Framework (CSF)?',
    o: [
      'Identify, Protect, Detect, Respond, Recover',
      'Plan, Do, Check, Act, Review',
      'Prepare, Categorize, Select, Implement, Authorize',
      'Avoid, Transfer, Mitigate, Accept, Deter',
    ],
    a: 'A',
    wc: 'The NIST CSF core functions are Identify, Protect, Detect, Respond, and Recover.',
    ww: {
      B: 'Plan-Do-Check-Act is the Deming cycle, not the CSF core.',
      C: 'Those are RMF steps, not CSF functions.',
      D: 'Those are risk-response strategies, not CSF functions.',
    },
    er: 'Recall of the five CSF core functions.',
  },
  {
    t: 'Risk Frameworks', s: 'COSO vs ISO 31000', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Risk Frameworks',
    q: 'Which framework is an enterprise risk management framework used primarily for corporate governance and compliance with Sarbanes-Oxley?',
    o: ['COSO', 'ISO 31000', 'NIST SP 800-137', 'SABSA'],
    a: 'A',
    wc: 'COSO is an enterprise risk management framework used primarily for corporate governance and SOX compliance.',
    ww: {
      B: 'ISO 31000 is a general, industry-agnostic risk management framework.',
      C: 'NIST SP 800-137 covers continuous monitoring.',
      D: 'SABSA is a business-driven security architecture framework.',
    },
    er: 'Distinguishes COSO (governance/SOX) from general and architecture frameworks.',
  },
  {
    t: 'Risk Frameworks', s: 'SABSA', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Understanding SABSA',
    q: 'SABSA is best described as a framework for:',
    o: [
      'Developing business-driven, risk-focused security architectures aligned to business objectives',
      'Protecting payment card data in retail environments',
      'Governing the export of dual-use technologies',
      'Defining EU data-subject privacy rights',
    ],
    a: 'A',
    wc: 'SABSA provides a structured approach to business-driven, risk-focused security architecture that traces decisions back to business requirements.',
    ww: {
      B: 'Payment-card protection is PCI DSS.',
      C: 'Dual-use export is governed by EXIM/Wassenaar.',
      D: 'EU privacy rights come from GDPR.',
    },
    er: 'Identifies SABSA as a business-aligned security architecture framework.',
  },
  {
    t: 'Risk Frameworks', s: 'ISO/IEC 27001', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > ISO/IEC 27001',
    q: 'ISO/IEC 27001 is primarily a standard for:',
    o: [
      'Establishing and managing an information security management system (ISMS) to manage information security risk',
      'Securing the physical supply chain of goods',
      'Rating the severity of software vulnerabilities',
      'Controlling cross-border encryption exports',
    ],
    a: 'A',
    wc: 'ISO/IEC 27001 defines requirements for an ISMS to manage information security risks and ensure compliance, grounded in the CIA triad.',
    ww: {
      B: 'Supply-chain security management is ISO 28000.',
      C: 'Vulnerability severity rating is associated with CVSS, not ISO 27001.',
      D: 'Encryption export is an EXIM/Wassenaar matter.',
    },
    er: 'Maps ISO 27001 to ISMS-based risk management.',
  },
  // ---- Quantitative & qualitative risk (1.9) ----
  {
    t: 'Quantitative Risk', s: 'SLE calculation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'An asset is valued at $200,000. A particular fire scenario is expected to destroy 25% of the asset. What is the Single Loss Expectancy (SLE)?',
    o: ['$50,000', '$25,000', '$200,000', '$800,000'],
    a: 'A',
    wc: 'SLE = Asset Value × Exposure Factor = $200,000 × 0.25 = $50,000.',
    ww: {
      B: '$25,000 would result from a 12.5% EF, not 25%.',
      C: '$200,000 is the full asset value (100% EF), not 25%.',
      D: '$800,000 incorrectly multiplies rather than applies the 25% exposure factor.',
    },
    er: 'Tests the SLE = AV × EF calculation.',
  },
  {
    t: 'Quantitative Risk', s: 'ALE calculation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'A single loss event costs $50,000 (SLE) and is expected to occur twice per year (ARO = 2). What is the Annualized Loss Expectancy (ALE)?',
    o: ['$100,000', '$50,000', '$25,000', '$2,000'],
    a: 'A',
    wc: 'ALE = SLE × ARO = $50,000 × 2 = $100,000.',
    ww: {
      B: '$50,000 is the SLE for a single occurrence, not annualized.',
      C: '$25,000 would halve rather than double the SLE.',
      D: '$2,000 confuses the ARO value with a dollar amount.',
    },
    er: 'Tests the ALE = SLE × ARO calculation.',
  },
  {
    t: 'Quantitative Risk', s: 'EF definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'The Exposure Factor (EF) represents:',
    o: [
      'The percentage of an asset\'s value likely to be lost if a risk is realized',
      'The number of times per year a risk occurs',
      'The total monetary cost of acquiring the asset',
      'The annual cost of a safeguard',
    ],
    a: 'A',
    wc: 'The EF is the percentage of asset value that could be lost when a risk is realized.',
    ww: {
      B: 'That describes the Annualized Rate of Occurrence (ARO).',
      C: 'That describes the Asset Value (AV).',
      D: 'That describes the annual cost of a safeguard.',
    },
    er: 'Recall of EF as a percentage of loss.',
  },
  {
    t: 'Quantitative Risk', s: 'ARO definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'The Annualized Rate of Occurrence (ARO) is:',
    o: [
      'The estimated frequency at which a specific risk is expected to occur within a year',
      'The percentage of asset value lost per event',
      'The total value of the asset',
      'The expected loss from a single event',
    ],
    a: 'A',
    wc: 'ARO is the estimated number of times a specific risk is expected to occur within a year.',
    ww: {
      B: 'That is the Exposure Factor (EF).',
      C: 'That is the Asset Value (AV).',
      D: 'That is the Single Loss Expectancy (SLE).',
    },
    er: 'Recall of ARO as annual frequency.',
  },
  {
    t: 'Quantitative Risk', s: 'Calculation sequence', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'A server worth $40,000 faces a threat with a 50% exposure factor that is expected to occur 3 times per year. What is the ALE?',
    o: ['$60,000', '$20,000', '$120,000', '$6,000'],
    a: 'A',
    wc: 'SLE = $40,000 × 0.50 = $20,000; ALE = SLE × ARO = $20,000 × 3 = $60,000.',
    ww: {
      B: '$20,000 is the SLE, not the annualized figure.',
      C: '$120,000 applies the full asset value (100% EF) instead of 50%.',
      D: '$6,000 misplaces a decimal in the calculation.',
    },
    er: 'Tests chaining SLE = AV × EF then ALE = SLE × ARO.',
  },
  {
    t: 'Quantitative Risk', s: 'Quantitative vs qualitative', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'Which statement BEST distinguishes quantitative from qualitative risk assessment?',
    o: [
      'Quantitative uses numerical/monetary values; qualitative uses subjective rankings such as high/medium/low',
      'Quantitative uses color codes; qualitative uses precise dollar figures',
      'Quantitative is always faster and requires no data',
      'They produce identical outputs and are interchangeable',
    ],
    a: 'A',
    wc: 'Quantitative assessment uses numerical/monetary values (AV, SLE, ALE), while qualitative uses subjective judgment and categories like high/low/moderate.',
    ww: {
      B: 'Reversed: color codes/categories are qualitative; dollar figures are quantitative.',
      C: 'Quantitative analysis requires substantial data and is not effort-free.',
      D: 'They differ in method and output and are not interchangeable.',
    },
    er: 'Tests the core difference between the two assessment approaches.',
  },
  {
    t: 'Quantitative Risk', s: 'Calculation order', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'Which TWO equations are correct as defined in the guide? (Select TWO.)',
    o: [
      'SLE = Asset Value × Exposure Factor',
      'ALE = SLE × Annualized Rate of Occurrence',
      'ALE = Asset Value × Exposure Factor',
      'SLE = ALE × Annualized Rate of Occurrence',
    ],
    a: ['A', 'B'],
    wc: 'SLE = AV × EF and ALE = SLE × ARO are the correct definitions.',
    ww: {
      C: 'AV × EF yields SLE, not ALE.',
      D: 'This inverts the relationship; ALE is derived from SLE, not vice versa.',
    },
    er: 'Tests precise knowledge of the SLE and ALE formulas.',
  },
  {
    t: 'Qualitative Risk', s: 'Delphi technique', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Conducting Risk Assessments',
    q: 'The Delphi technique supports qualitative risk assessment by:',
    o: [
      'Gathering anonymous expert consensus to reduce bias and undue influence',
      'Calculating exact monetary loss figures',
      'Automatically scanning systems for vulnerabilities',
      'Encrypting data at rest',
    ],
    a: 'A',
    wc: 'The Delphi technique gathers consensus among experts through anonymous feedback, helping make unbiased decisions.',
    ww: {
      B: 'Exact monetary figures are the realm of quantitative assessment.',
      C: 'Vulnerability scanning is a technical assessment activity, not Delphi.',
      D: 'Encryption is a control, not a consensus technique.',
    },
    er: 'Maps anonymous expert consensus to the Delphi technique.',
  },
  // ---- Risk assessment process / tolerance ----
  {
    t: 'Risk Assessment Process', s: 'Risk tolerance/appetite', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Understanding Risk Assessments',
    q: 'The level of risk an organization is willing to accept is referred to as its:',
    o: ['Risk tolerance (risk appetite)', 'Exposure factor', 'Residual control', 'Annualized loss expectancy'],
    a: 'A',
    wc: 'Risk tolerance/risk appetite is the level of risk an organization is willing to accept.',
    ww: {
      B: 'Exposure factor is the percentage of asset value lost in an event.',
      C: '"Residual control" is not a defined term; residual risk is what remains after controls.',
      D: 'ALE is a calculated annual loss figure, not a willingness threshold.',
    },
    er: 'Recall of the risk tolerance/appetite concept.',
  },
  {
    t: 'Risk Assessment Process', s: 'NIST SP 800-30', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Assessment > NIST Special Publication 800-30 Risk Assessment Steps',
    q: 'Under NIST SP 800-30, after conducting the assessment a team must communicate findings to senior management. The guidance emphasizes that this reporting should be:',
    o: [
      'Expressed in understandable business language to aid management decision-making',
      'Written only in deep technical jargon for engineers',
      'Withheld from management to avoid alarm',
      'Limited to a single numerical score with no context',
    ],
    a: 'A',
    wc: 'NIST SP 800-30 reporting communicates findings to senior management in understandable business language to aid decision-making.',
    ww: {
      B: 'Technical jargon impairs management decision-making.',
      C: 'Withholding findings defeats the purpose of the assessment.',
      D: 'A bare score without context does not support informed decisions.',
    },
    er: 'Tests audience-appropriate risk reporting to leadership.',
  },
  // ---- Threat modeling (1.10) ----
  {
    t: 'Threat Modeling', s: 'STRIDE', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Threat Modeling Methodologies',
    q: 'In the STRIDE threat-modeling methodology, the "R" represents which threat category?',
    o: ['Repudiation', 'Reconnaissance', 'Recovery', 'Redundancy'],
    a: 'A',
    wc: 'STRIDE stands for Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, and Elevation of privilege; "R" is Repudiation.',
    ww: {
      B: 'Reconnaissance is an attack phase, not a STRIDE element.',
      C: 'Recovery is a control function, not a STRIDE element.',
      D: 'Redundancy is an availability technique, not a STRIDE element.',
    },
    er: 'Tests knowledge of the STRIDE categories.',
  },
  {
    t: 'Threat Modeling', s: 'Methodology selection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Threat Modeling Methodologies',
    q: 'Which of the following is a recognized threat-modeling methodology referenced in the guide?',
    o: ['PASTA', 'PIPEDA', 'PCI DSS', 'PERT'],
    a: 'A',
    wc: 'PASTA (Process for Attack Simulation and Threat Analysis) is a recognized threat-modeling methodology, alongside STRIDE and DREAD.',
    ww: {
      B: 'PIPEDA is a Canadian privacy law.',
      C: 'PCI DSS is a payment-card security standard.',
      D: 'PERT is a project-scheduling technique, not threat modeling.',
    },
    er: 'Identifies PASTA as a threat-modeling methodology among distractors.',
  },
  {
    t: 'Threat Modeling', s: 'Attack surface', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Assessment > Threat Modeling Concepts',
    q: 'In threat modeling, the sum of all points where an attacker could attempt to enter or extract data from a system is the:',
    o: ['Attack surface', 'Exposure factor', 'Residual risk', 'Security baseline'],
    a: 'A',
    wc: 'The attack surface is the total set of points (interfaces, inputs) through which an attacker could interact with or compromise a system.',
    ww: {
      B: 'Exposure factor is a percentage of loss in quantitative risk.',
      C: 'Residual risk is the risk remaining after controls.',
      D: 'A baseline is a minimum control set.',
    },
    er: 'Recall of the attack-surface concept.',
  },
  {
    t: 'Threat Modeling', s: 'Proactive vs reactive', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Assessment > Threat Modeling Concepts',
    q: 'A development team performs threat modeling during the DESIGN phase of a new application, before any code is written, to anticipate attacks. This approach is BEST described as:',
    o: ['Proactive threat modeling', 'Reactive threat modeling', 'Penetration testing', 'Incident response'],
    a: 'A',
    wc: 'Anticipating threats early (e.g., at design, before exploitation) is a proactive approach to threat modeling.',
    ww: {
      B: 'A reactive approach responds after threats or incidents have manifested.',
      C: 'Penetration testing actively tests a running system, not design-phase modeling.',
      D: 'Incident response handles events after they occur.',
    },
    er: 'Distinguishes proactive (design-time) from reactive threat modeling.',
  },
  // ---- Supply chain risk management (1.11) ----
  {
    t: 'Supply Chain Risk Management', s: 'SCRM definition', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 1 > Risk Management > Supply Chain Risk Management',
    q: 'Supply Chain Risk Management (SCRM) primarily addresses risks arising from:',
    o: [
      'An organization\'s dependence on external vendors and suppliers for goods and services',
      'Employees\' personal travel itineraries',
      'The accuracy of corporate financial statements',
      'The classification level of internal documents',
    ],
    a: 'A',
    wc: 'SCRM addresses security risks in the supply chain due to dependencies on external sources for operational components, goods, and services.',
    ww: {
      B: 'Travel safety is a personnel-security topic, not SCRM.',
      C: 'Financial-statement accuracy is a SOX/governance concern.',
      D: 'Document classification is an asset-security activity.',
    },
    er: 'Maps SCRM to third-party/vendor dependency risk.',
  },
  {
    t: 'Supply Chain Risk Management', s: 'Supply chain risk types', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 1 > Risk Management > Supply Chain Risk Management',
    q: 'Which TWO are recognized categories of supply-chain risk described in the guide? (Select TWO.)',
    o: [
      'Hardware risks such as counterfeit components',
      'Software risks such as vulnerabilities or malicious code',
      'Risk appetite risks such as choosing the wrong color code',
      'Awareness risks such as fewer posters in the lobby',
    ],
    a: ['A', 'B'],
    wc: 'The guide lists hardware risks (counterfeits, embedded spyware), software risks (vulnerabilities, malcode, licensing), and service risks as supply-chain risk categories.',
    ww: {
      C: '"Risk appetite color codes" relate to qualitative assessment, not a supply-chain risk category.',
      D: 'Poster counts relate to awareness delivery, not supply-chain risk.',
    },
    er: 'Identifies genuine supply-chain risk categories.',
  },
  {
    t: 'Supply Chain Risk Management', s: 'SLAs and assessments', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Risk Management > Supply Chain Risk Management',
    q: 'An organization wants to hold a critical cloud supplier contractually accountable for specific security requirements and define how compliance will be verified. The MOST appropriate mechanism is to:',
    o: [
      'Establish a Service Level Agreement (SLA) that defines the security requirements and verification',
      'Rely on a verbal understanding with the vendor\'s sales representative',
      'Assume the vendor\'s marketing claims are sufficient assurance',
      'Avoid documenting requirements to remain flexible',
    ],
    a: 'A',
    wc: 'SLAs with suppliers define specific security requirements and acquisition policies, and support assessment of compliance.',
    ww: {
      B: 'Verbal understandings are unenforceable and unverifiable.',
      C: 'Marketing claims are not contractual assurance.',
      D: 'Failing to document requirements undermines accountability and verification.',
    },
    er: 'Tests using SLAs to enforce and verify supplier security obligations.',
  },
  // ---- BCP / DR requirements (1.7) ----
  {
    t: 'Business Continuity', s: 'BC requirements', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 1 > Business Continuity and Disaster Recovery > Business Continuity (BC) requirements',
    q: 'Objective 1.7 focuses on identifying, analyzing, assessing, prioritizing, and implementing requirements for:',
    o: ['Business Continuity (BC)', 'Software licensing', 'Cryptographic key generation', 'Marketing campaigns'],
    a: 'A',
    wc: 'Objective 1.7 concerns identifying, analyzing, assessing, prioritizing, and implementing Business Continuity (BC) requirements.',
    ww: {
      B: 'Software licensing is part of legal/IP topics.',
      C: 'Key generation is a cryptography topic.',
      D: 'Marketing campaigns are unrelated to continuity planning.',
    },
    er: 'Anchors objective 1.7 to Business Continuity requirements.',
  },
  {
    t: 'Business Continuity', s: 'Prioritization via impact', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 1 > Business Continuity and Disaster Recovery > Business Continuity (BC) requirements',
    q: 'When implementing Business Continuity requirements, an organization must decide which processes to restore first after a disruption. This prioritization should be driven primarily by:',
    o: [
      'The relative criticality and impact of each business process on the organization',
      'Which department complained most loudly',
      'The alphabetical order of system names',
      'The personal preference of the newest employee',
    ],
    a: 'A',
    wc: 'BC requirements are prioritized by analyzing and assessing the criticality and impact of business processes, so the most critical are restored first.',
    ww: {
      B: 'Loudness of complaints is not an objective impact-based criterion.',
      C: 'Alphabetical ordering ignores business criticality.',
      D: 'Personal preference is not a valid prioritization basis.',
    },
    er: 'Tests impact/criticality-driven prioritization in continuity planning.',
  },
];
