// Domain 7 — Part 1: Detective & preventative measures — IDS/IPS (detection
// methods, deployment), honeypots, whitelisting/blacklisting, sandboxing,
// security operations concepts (need-to-know, least privilege, SoD, job
// rotation, PAM), third-party services.
module.exports = [
  {
    t: 'IDS/IPS', s: 'IDS vs IPS', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > IDS/IPS Systems',
    q: 'The KEY functional difference between an IDS and an IPS is that an IPS:',
    o: [
      'Can actively block/stop detected malicious traffic, not just alert on it',
      'Only logs events and never alerts',
      'Cannot detect any intrusions',
      'Is a physical lock on the server room',
    ],
    a: 'A',
    wc: 'An IDS detects and alerts on suspicious activity; an IPS can additionally take preventive action (block/drop) inline to stop the threat.',
    ww: {
      B: 'An IDS does alert; the distinction is the IPS\'s ability to actively block.',
      C: 'Both detect intrusions; the IPS also prevents.',
      D: 'IDS/IPS are logical controls, not physical locks.',
    },
    er: 'Distinguishes IPS (prevent/block) from IDS (detect/alert).',
  },
  {
    t: 'IDS/IPS', s: 'Signature vs anomaly detection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Detection Types',
    q: 'An organization wants its IDS to catch brand-new, never-before-seen attacks (not just known ones). Which detection method is MOST suitable, and what is its main drawback?',
    o: [
      'Behavior/anomaly-based detection; it is prone to false positives and needs a baseline learning period',
      'Signature-based detection; it cannot be updated',
      'Behavior-based detection; it can only detect known signatures',
      'Signature-based detection; it never needs updates',
    ],
    a: 'A',
    wc: 'Behavior/anomaly-based detection compares activity to a learned baseline of "normal," so it can flag novel attacks—but it is prone to false positives and requires a learning period.',
    ww: {
      B: 'Signature-based detection only catches known patterns and does require updates.',
      C: 'Behavior-based detection is precisely what catches unknown (non-signature) activity.',
      D: 'Signature-based detection requires constant updates for new threats.',
    },
    er: 'Maps novel-attack detection to anomaly-based (with false-positive drawback).',
  },
  {
    t: 'IDS/IPS', s: 'Signature-based', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Detection Types',
    q: 'Knowledge-based (signature-based) intrusion detection works by:',
    o: [
      'Matching activity against a database of known attack patterns/signatures',
      'Learning a baseline of normal behavior over time',
      'Randomly blocking traffic',
      'Encrypting all network packets',
    ],
    a: 'A',
    wc: 'Signature/knowledge-based detection (pattern matching) compares observed activity to known attack signatures and requires constant updates to detect emerging threats.',
    ww: {
      B: 'Learning a baseline of normal is behavior/anomaly-based detection.',
      C: 'Signature detection is targeted, not random.',
      D: 'It detects patterns; it does not encrypt packets.',
    },
    er: 'Maps known-pattern matching to signature-based detection.',
  },
  {
    t: 'IDS/IPS', s: 'NIDS vs HIDS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Host-Based IDS (HIDS) and Host-Based IPS (HIPS)',
    q: 'A limitation of a Host-Based IDS (HIDS) compared to a Network-Based IDS (NIDS) is that the HIDS:',
    o: [
      'Cannot analyze network-wide threats; it only monitors activity on its own host',
      'Cannot monitor any host activity',
      'Is unable to detect file changes',
      'Only works on wireless networks',
    ],
    a: 'A',
    wc: 'A HIDS monitors a specific host\'s activity but cannot see network-level threats or misconfigurations across the network—that is the NIDS\'s role.',
    ww: {
      B: 'Monitoring host activity is exactly what a HIDS does.',
      C: 'HIDS can detect host file/integrity changes.',
      D: 'HIDS is not limited to wireless networks.',
    },
    er: 'Tests the host-scope limitation of HIDS vs NIDS.',
  },
  {
    t: 'IDS/IPS', s: 'Stateful protocol analysis', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Stateful Protocol Analysis',
    q: 'Stateful protocol analysis detection identifies threats by:',
    o: [
      'Comparing observed events against expected protocol states using vendor signature profiles',
      'Only matching simple string signatures',
      'Learning a statistical baseline of user behavior',
      'Blocking all traffic by default',
    ],
    a: 'A',
    wc: 'Stateful protocol analysis evaluates events against the known/expected states of a communication protocol (using vendor-provided profiles) to detect protocol anomalies.',
    ww: {
      B: 'Simple string matching describes basic signature detection.',
      C: 'Statistical baselining of behavior is anomaly-based detection.',
      D: 'It analyzes protocol state; it does not block everything by default.',
    },
    er: 'Maps protocol-state analysis to stateful protocol analysis.',
  },
  {
    t: 'Honeypots', s: 'Purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Honeypots and Honeynets',
    q: 'A honeypot is primarily deployed to:',
    o: [
      'Lure and observe attackers using a decoy system, diverting them from real assets',
      'Provide backup power to the data center',
      'Encrypt production databases',
      'Replace the corporate firewall',
    ],
    a: 'A',
    wc: 'A honeypot is a decoy system designed to attract attackers so their methods can be studied and they are diverted from real production systems (a honeynet is a network of honeypots).',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'A honeypot is a decoy, not a database-encryption tool.',
      D: 'A honeypot complements, not replaces, a firewall.',
    },
    er: 'Tests the decoy/observation purpose of honeypots.',
  },
  {
    t: 'Preventative Controls', s: 'Whitelisting vs blacklisting', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Whitelisting',
    q: 'A high-security environment wants to allow ONLY explicitly approved applications to run and block everything else. Which approach fits, and what is it also called?',
    o: [
      'Whitelisting — "permit by exception" (deny by default)',
      'Blacklisting — "deny by exception" (allow by default)',
      'Blacklisting — "permit by exception"',
      'Whitelisting — "allow everything by default"',
    ],
    a: 'A',
    wc: 'Whitelisting permits only specified actions/applications and denies everything else by default ("permit by exception")—stricter and more secure, ideal for high-security needs.',
    ww: {
      B: 'Blacklisting allows everything except listed items (less strict).',
      C: 'Blacklisting is "deny by exception," not "permit by exception."',
      D: 'Whitelisting denies by default, not allows everything.',
    },
    er: 'Maps allow-only-approved to whitelisting ("permit by exception").',
  },
  {
    t: 'Preventative Controls', s: 'Blacklisting', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Blacklisting',
    q: 'Blacklisting ("deny by exception") is characterized by:',
    o: [
      'Denying specific listed items and allowing everything else by default',
      'Allowing only explicitly approved items',
      'Blocking all traffic with no exceptions',
      'Encrypting all data at rest',
    ],
    a: 'A',
    wc: 'Blacklisting denies specific actions/items while allowing everything else by default—less secure than whitelisting but favors availability.',
    ww: {
      B: 'Allowing only approved items is whitelisting.',
      C: 'Blacklisting allows non-listed items; it does not block everything.',
      D: 'Encryption is unrelated to blacklisting.',
    },
    er: 'Tests the allow-by-default nature of blacklisting.',
  },
  {
    t: 'Preventative Controls', s: 'Sandboxing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Sandboxing',
    q: 'Sandboxing (confinement) protects systems by:',
    o: [
      'Running code in an isolated environment so it cannot affect the rest of the system',
      'Providing redundant power to servers',
      'Routing packets between subnets',
      'Issuing digital certificates',
    ],
    a: 'A',
    wc: 'Sandboxing/confinement isolates code execution so untrusted or suspicious software cannot harm the host or other systems.',
    ww: {
      B: 'Redundant power is a UPS/generator function.',
      C: 'Packet routing is a network function.',
      D: 'Certificate issuance is a PKI/CA function.',
    },
    er: 'Recall of sandboxing/confinement.',
  },
  {
    t: 'Security Operations Concepts', s: 'Separation of duties', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Separation or Segregation of Duties',
    q: 'Separation (segregation) of duties in security operations primarily:',
    o: [
      'Prevents any single individual from compromising security controls by dividing responsibilities',
      'Gives one administrator full control for efficiency',
      'Eliminates the need for logging',
      'Allows users to approve their own changes',
    ],
    a: 'A',
    wc: 'Separation of duties divides responsibilities so no single person can both perform and conceal a malicious or erroneous action—reducing fraud and conflict of interest.',
    ww: {
      B: 'Concentrating control in one person defeats SoD.',
      C: 'SoD does not remove logging requirements.',
      D: 'Self-approval undermines the control.',
    },
    er: 'Tests the fraud-prevention purpose of SoD.',
  },
  {
    t: 'Security Operations Concepts', s: 'Job rotation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Job Rotation',
    q: 'A finance department rotates staff through different roles every few months. Besides cross-training, what security BENEFIT does job rotation provide?',
    o: [
      'It can expose fraud/errors that a single person could otherwise hide over time',
      'It permanently removes the need for separation of duties',
      'It guarantees no employee will ever leave',
      'It encrypts the payroll database',
    ],
    a: 'A',
    wc: 'Job rotation makes it harder for one person to conceal ongoing fraud/errors (a successor may discover it) and reduces dependence on any single individual.',
    ww: {
      B: 'Job rotation complements, not replaces, separation of duties.',
      C: 'Rotation does not control attrition.',
      D: 'Rotation does not perform database encryption.',
    },
    er: 'Tests the fraud-detection benefit of job rotation.',
  },
  {
    t: 'Security Operations Concepts', s: 'Privileged account management', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Privileged Account Management',
    q: 'Privileged account management in security operations focuses on:',
    o: [
      'Controlling and monitoring the use of elevated/administrative accounts',
      'Assigning IP addresses to endpoints',
      'Providing fire suppression in the data center',
      'Encrypting wireless traffic',
    ],
    a: 'A',
    wc: 'Privileged account management controls, restricts, and monitors elevated accounts because they are high-value targets and high-impact if misused.',
    ww: {
      B: 'IP assignment is DHCP\'s function.',
      C: 'Fire suppression is a physical control.',
      D: 'Wireless encryption is WPA2/WPA3.',
    },
    er: 'Tests the elevated-account focus of privileged account management.',
  },
  {
    t: 'Security Operations Concepts', s: 'Need to know vs least privilege', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Security Operation Concepts',
    q: 'In the guide\'s framing, how does least privilege differ in emphasis from need-to-know?',
    o: [
      'Least privilege focuses on functional access (what you can do); need-to-know focuses on data access (what you can see)',
      'They are identical concepts',
      'Least privilege grants maximum access; need-to-know grants none',
      'Need-to-know applies only to wireless networks',
    ],
    a: 'A',
    wc: 'The guide notes least privilege emphasizes functional access rights, while need-to-know restricts access to specific data/information required for duties.',
    ww: {
      B: 'They are related but distinct in emphasis (function vs data).',
      C: 'Least privilege grants minimum, not maximum, access.',
      D: 'Need-to-know is not limited to wireless networks.',
    },
    er: 'Distinguishes least privilege (function) from need-to-know (data).',
  },
  {
    t: 'Preventative Controls', s: 'Control categorization', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Detective and Preventative Measures > Detective and Preventative Concepts',
    q: 'Which TWO are PREVENTATIVE controls (designed to stop violations before they occur)? (Select TWO.)',
    o: ['Application whitelisting', 'A firewall blocking unauthorized traffic', 'Reviewing IDS alert logs after an event', 'Analyzing logs during an investigation'],
    a: ['A', 'B'],
    wc: 'Whitelisting and a blocking firewall prevent violations before they happen; reviewing logs/alerts after the fact is detective.',
    ww: {
      C: 'Reviewing alert logs after an event is a detective activity.',
      D: 'Analyzing logs during an investigation is detective/forensic.',
    },
    er: 'Separates preventative from detective controls.',
  },
  {
    t: 'IDS/IPS', s: 'Detection-method mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 7 > Detective and Preventative Measures > Detection Types',
    p: ['Signature-based detection', 'Anomaly-based detection', 'Stateful protocol analysis'],
    q: 'Match each IDS detection method (1-3) to its description (A-C).',
    o: [
      'Compares activity to a learned baseline of normal behavior',
      'Matches activity against a database of known attack patterns',
      'Evaluates events against expected protocol states',
    ],
    a: '1-B,2-A,3-C',
    wc: 'Signature-based → known attack patterns (B); Anomaly-based → baseline of normal (A); Stateful protocol analysis → expected protocol states (C).',
    ww: {},
    er: 'Tests mapping of IDS detection methods.',
  },
  {
    t: 'IDS/IPS', s: 'NIPS deployment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > IDS and IPS Deployment Types',
    q: 'A Network-Based IPS (NIPS) is BEST positioned to:',
    o: [
      'Monitor and block malicious traffic across network segments inline',
      'Monitor only a single host\'s file integrity',
      'Provide backup power',
      'Issue user credentials',
    ],
    a: 'A',
    wc: 'A NIPS sits inline on the network to monitor and actively block malicious traffic across segments network-wide.',
    ww: {
      B: 'Single-host file integrity monitoring is a HIDS/HIPS function.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Credential issuance is an IAM function.',
    },
    er: 'Tests the network-wide inline role of NIPS.',
  },
  {
    t: 'Third-Party Security', s: 'Integration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Third-Party Involvement in Incident Response',
    q: 'When using third-party security services, a key best practice is to:',
    o: [
      'Integrate their roles into the incident response plan, covering both detection and prevention',
      'Give them unrestricted access with no oversight',
      'Exclude them entirely from any incident planning',
      'Assume they need no contractual security requirements',
    ],
    a: 'A',
    wc: 'Third-party providers should be integrated into the incident response plan with defined roles in detection and prevention, and governed by appropriate contracts/SLAs.',
    ww: {
      B: 'Unrestricted, unmonitored access is a major risk.',
      C: 'Excluding them from planning leaves gaps if they are involved operationally.',
      D: 'Contractual security requirements (SLAs) are essential for third parties.',
    },
    er: 'Tests integrating third parties into incident response planning.',
  },
  {
    t: 'Honeypots', s: 'Padded cell', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Advanced Honeypot Deployment',
    q: 'A "padded cell" works alongside an IDS by:',
    o: [
      'Transferring a detected attacker into an isolated, simulated environment in real time',
      'Permanently deleting the attacker\'s device',
      'Encrypting all production data',
      'Providing redundant power',
    ],
    a: 'A',
    wc: 'A padded cell is a protected, isolated environment that an IDS redirects an attacker into once detected, containing them away from real systems.',
    ww: {
      B: 'It isolates, not destroys, the attacker\'s device.',
      C: 'It is a containment environment, not an encryption tool.',
      D: 'Redundant power is unrelated to a padded cell.',
    },
    er: 'Tests the IDS-triggered isolation role of a padded cell.',
  },
  {
    t: 'IDS/IPS', s: 'False positives', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Behavior-Based Detection (Anomaly-Based)',
    q: 'After deploying an anomaly-based IDS, the SOC is flooded with alerts for legitimate-but-unusual activity. The MOST likely cause is:',
    o: [
      'False positives from an immature/insufficient baseline of normal behavior',
      'The IDS only uses known signatures',
      'The network has no traffic at all',
      'The IDS is a physical access control',
    ],
    a: 'A',
    wc: 'Anomaly-based detection is prone to false positives, especially before the baseline of normal behavior is well established (the learning period).',
    ww: {
      B: 'Signature-only detection would not flag unusual-but-unknown activity as anomalies.',
      C: 'Alerts indicate there is traffic to analyze.',
      D: 'An IDS is a logical control, not a physical access control.',
    },
    er: 'Maps anomaly-detection alert floods to false positives/baseline immaturity.',
  },
  {
    t: 'Security Operations Concepts', s: 'Least privilege', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Security Operation Concepts',
    q: 'Applying least privilege in security operations means:',
    o: [
      'Granting subjects only the access required to perform their job functions',
      'Giving all operators administrator rights',
      'Allowing anonymous access to systems',
      'Removing all access controls',
    ],
    a: 'A',
    wc: 'Least privilege grants only the minimum access necessary, limiting the damage from compromise or misuse.',
    ww: {
      B: 'Universal admin rights violate least privilege.',
      C: 'Anonymous access undermines accountability.',
      D: 'Removing access controls is the opposite of least privilege.',
    },
    er: 'Recall of least privilege in operations.',
  },
  {
    t: 'Detective Controls', s: 'Detective vs preventative', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Detective and Preventative Concepts',
    q: 'Which is an example of a DETECTIVE control?',
    o: [
      'An IDS that alerts on suspicious activity',
      'A firewall that blocks unauthorized ports',
      'Application whitelisting that prevents unapproved software',
      'A locked door that stops entry',
    ],
    a: 'A',
    wc: 'Detective controls identify/announce that an event has occurred (e.g., an IDS alert); the others prevent events from occurring.',
    ww: {
      B: 'A blocking firewall is preventative.',
      C: 'Whitelisting is preventative.',
      D: 'A locked door is a preventative physical control.',
    },
    er: 'Distinguishes detective (alert) from preventative controls.',
  },
  {
    t: 'IDS/IPS', s: 'WIDS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Wireless IDS and Wireless IPS',
    q: 'A Wireless IDS (WIDS) is specifically designed to:',
    o: [
      'Monitor wireless network traffic for protocol-related anomalies (e.g., rogue APs)',
      'Monitor only wired host file integrity',
      'Provide backup generator power',
      'Encrypt email messages',
    ],
    a: 'A',
    wc: 'A WIDS monitors wireless traffic for anomalies such as rogue access points and wireless-specific attacks.',
    ww: {
      B: 'Wired host file integrity is a HIDS concern.',
      C: 'Generator power is unrelated.',
      D: 'Email encryption is S/MIME/PGP.',
    },
    er: 'Tests the wireless focus of a WIDS.',
  },
  {
    t: 'Preventative Controls', s: 'Defense in depth', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Defense Mechanisms Against Malware',
    q: 'Layered security (defense in depth) against malware means:',
    o: [
      'Using multiple, overlapping controls so no single failure leads to compromise',
      'Relying on one antivirus product alone',
      'Disabling all security to improve performance',
      'Encrypting only the company logo',
    ],
    a: 'A',
    wc: 'Defense in depth layers multiple controls (e.g., anti-malware, awareness training, filtering) so the failure of one does not result in compromise.',
    ww: {
      B: 'A single control is the opposite of layered defense.',
      C: 'Disabling security increases risk.',
      D: 'Encrypting a logo provides no meaningful protection.',
    },
    er: 'Recall of layered defense against malware.',
  },
  {
    t: 'Security Operations Concepts', s: 'SoD scenario', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Separation or Segregation of Duties',
    q: 'A single administrator can create user accounts AND approve their own access requests AND clear the audit logs. Which principle is violated, and what is the risk?',
    o: [
      'Separation of duties; one person could grant and hide unauthorized access',
      'Defense in depth; the network is too segmented',
      'Least common mechanism; too many shared components',
      'Fail-secure; the system fails open',
    ],
    a: 'A',
    wc: 'Concentrating account creation, approval, and log-clearing in one person violates separation of duties—enabling that person to grant and conceal unauthorized access.',
    ww: {
      B: 'Defense in depth concerns layered controls, not this concentration of duties.',
      C: 'Least common mechanism concerns shared components, not duty concentration.',
      D: 'Fail-secure concerns failure behavior, not duty separation.',
    },
    er: 'Maps concentrated conflicting duties to an SoD violation.',
  },
];
