// Domain 7 — Part 4: Business continuity (BCP/BIA, MTD/RTO/RPO), disaster
// recovery (DRP, recovery sites, recovery strategies), fail-secure/open,
// BC vs DR, disasters, DR processes and testing.
module.exports = [
  // ---- BIA metrics ----
  {
    t: 'Business Impact Analysis', s: 'MTD', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Measures of Impact',
    q: 'Maximum Tolerable Downtime (MTD) represents:',
    o: [
      'The longest a critical process can be down before the business is unacceptably impacted',
      'The time it takes to restore the process',
      'The maximum acceptable data loss',
      'The cost of a backup tape',
    ],
    a: 'A',
    wc: 'MTD is the maximum time a critical asset/process can be unavailable before causing unacceptable business impact.',
    ww: {
      B: 'Time to restore is the Recovery Time Objective (RTO).',
      C: 'Maximum acceptable data loss is the Recovery Point Objective (RPO).',
      D: 'Backup-tape cost is unrelated to MTD.',
    },
    er: 'Recall of MTD.',
  },
  {
    t: 'Business Impact Analysis', s: 'RTO', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Measures of Impact',
    q: 'The Recovery Time Objective (RTO) is:',
    o: [
      'The planned/targeted time to restore a critical process after disruption',
      'The maximum acceptable amount of data loss',
      'The maximum downtime the business can tolerate before impact',
      'The frequency of full backups',
    ],
    a: 'A',
    wc: 'RTO is the targeted duration to recover/restore a critical process; it should be less than or equal to the MTD.',
    ww: {
      B: 'Acceptable data loss is the RPO.',
      C: 'Maximum tolerable downtime is the MTD.',
      D: 'Backup frequency relates to (but is not) the RPO.',
    },
    er: 'Recall of RTO.',
  },
  {
    t: 'Business Impact Analysis', s: 'RPO', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Measures of Impact',
    q: 'A database is backed up every 6 hours. After a crash, the most recent backup is used to restore it. The amount of data that may be lost (since the last backup) corresponds to which metric?',
    o: [
      'Recovery Point Objective (RPO)',
      'Recovery Time Objective (RTO)',
      'Maximum Tolerable Downtime (MTD)',
      'Mean Time Between Failures (MTBF)',
    ],
    a: 'A',
    wc: 'RPO is the maximum acceptable data loss, determined by backup availability/frequency—here up to 6 hours of data since the last backup.',
    ww: {
      B: 'RTO is the time to restore, not the data-loss amount.',
      C: 'MTD is the maximum tolerable downtime.',
      D: 'MTBF is a reliability metric, not a recovery point.',
    },
    er: 'Maps acceptable data loss/backup frequency to RPO.',
  },
  {
    t: 'Business Impact Analysis', s: 'RTO vs MTD', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Measures of Impact',
    q: 'A process has an MTD of 1 hour, but the current recovery capability has an RTO of 3 hours. What does this indicate?',
    o: [
      'The recovery capability is insufficient; RTO must be reduced to within the MTD',
      'Everything is fine because RTO can exceed MTD',
      'The RPO is automatically satisfied',
      'The MTD should be ignored',
    ],
    a: 'A',
    wc: 'The RTO must be less than or equal to the MTD. An RTO (3h) exceeding the MTD (1h) means recovery is too slow and capabilities must be improved.',
    ww: {
      B: 'An RTO exceeding the MTD is a gap, not acceptable.',
      C: 'RPO concerns data loss and is a separate metric.',
      D: 'The MTD is the business constraint that drives recovery targets.',
    },
    er: 'Tests the RTO ≤ MTD relationship.',
  },
  {
    t: 'Business Impact Analysis', s: 'BIA purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Impact Analysis',
    q: 'The Business Impact Analysis (BIA) primarily aims to:',
    o: [
      'Identify critical business functions and the impact of their disruption to prioritize recovery',
      'Encrypt all data at rest',
      'Configure the corporate firewall',
      'Design the office floor plan',
    ],
    a: 'A',
    wc: 'The BIA identifies critical business functions (CBFs), evaluates disruption impacts, and determines criticality/tolerance to prioritize recovery and continuity strategies.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Firewall configuration is an operations task.',
      D: 'Floor-plan design is unrelated to the BIA.',
    },
    er: 'Tests the BIA\'s focus on CBFs and impacts.',
  },
  {
    t: 'Business Impact Analysis', s: 'Metric mapping', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Measures of Impact',
    q: 'Which set correctly pairs the recovery metrics with what they measure?',
    o: [
      'MTD = max tolerable downtime; RTO = time to restore; RPO = max data loss',
      'MTD = max data loss; RTO = downtime tolerance; RPO = restore time',
      'MTD = restore time; RTO = data loss; RPO = downtime tolerance',
      'All three measure the same thing',
    ],
    a: 'A',
    wc: 'MTD = maximum tolerable downtime; RTO = targeted time to restore; RPO = maximum acceptable data loss.',
    ww: {
      B: 'These pairings are scrambled.',
      C: 'These pairings are scrambled.',
      D: 'The three metrics measure distinct things.',
    },
    er: 'Tests correct mapping of MTD/RTO/RPO.',
  },
  // ---- Recovery sites ----
  {
    t: 'Recovery Sites', s: 'Hot site', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    q: 'A hot site is characterized by:',
    o: [
      'Being fully equipped with near-real-time data, ready within minutes to a few hours (most expensive)',
      'Having no computing equipment at all (cheapest)',
      'Pre-configured equipment but requiring data transport (~12 hours)',
      'Being a paper-only document review',
    ],
    a: 'A',
    wc: 'A hot site is fully equipped with systems, networks, and near-real-time data, enabling recovery within minutes to a few hours—at the highest cost.',
    ww: {
      B: 'No equipment/cheapest describes a cold site.',
      C: 'Pre-configured but needing data transport (~12h) describes a warm site.',
      D: 'A paper review is a checklist DR test, not a site.',
    },
    er: 'Recall of the hot site.',
  },
  {
    t: 'Recovery Sites', s: 'Cold site', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    q: 'A cold site is BEST described as:',
    o: [
      'Minimal infrastructure with no computing equipment—cheapest but longest to activate (days/weeks)',
      'Fully equipped with near-real-time data',
      'Pre-configured equipment ready in about 12 hours',
      'A mobile trailer configured as a hot site',
    ],
    a: 'A',
    wc: 'A cold site provides space/basic infrastructure but no computing equipment, making it the least expensive but slowest to bring online (days to weeks).',
    ww: {
      B: 'Fully equipped/near-real-time is a hot site.',
      C: 'Pre-configured ~12h is a warm site.',
      D: 'A mobile site is typically configured as a warm site.',
    },
    er: 'Recall of the cold site.',
  },
  {
    t: 'Recovery Sites', s: 'Warm site', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    q: 'A warm site differs from a hot site primarily because a warm site:',
    o: [
      'Has pre-configured equipment but requires data to be transported/loaded (taking ~12 hours)',
      'Has no equipment whatsoever',
      'Has near-real-time data ready in minutes',
      'Is only a tabletop exercise',
    ],
    a: 'A',
    wc: 'A warm site has pre-configured computing equipment and basic infrastructure but needs recent data brought from the primary site, taking around 12 hours to activate.',
    ww: {
      B: 'No equipment describes a cold site.',
      C: 'Near-real-time data ready in minutes describes a hot site.',
      D: 'A tabletop exercise is a DR test, not a site.',
    },
    er: 'Distinguishes the warm site (mid-tier) from hot/cold.',
  },
  {
    t: 'Recovery Sites', s: 'Site selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    q: 'A bank requires its critical systems to resume within an hour of a disaster and cannot tolerate significant data loss. Which recovery site is MOST appropriate despite higher cost?',
    o: ['Hot site', 'Cold site', 'A reciprocal/shared paper agreement only', 'No recovery site'],
    a: 'A',
    wc: 'A near-zero RTO/RPO requirement justifies a hot site, which is fully equipped with near-real-time data and recovers within minutes to a few hours.',
    ww: {
      B: 'A cold site takes days/weeks—far exceeding a one-hour requirement.',
      C: 'A paper agreement alone does not provide rapid technical recovery.',
      D: 'No recovery site cannot meet the stringent requirement.',
    },
    er: 'Maps stringent RTO/RPO to a hot site.',
  },
  {
    t: 'Recovery Sites', s: 'Site-type mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    p: ['Cold site', 'Warm site', 'Hot site'],
    q: 'Match each recovery site (1-3) to its characteristic (A-C).',
    o: [
      'Pre-configured equipment; needs data transport (~12 hours to activate)',
      'No computing equipment; cheapest; days/weeks to activate',
      'Fully equipped with near-real-time data; ready in minutes to hours; most expensive',
    ],
    a: '1-B,2-A,3-C',
    wc: 'Cold → no equipment/cheapest/slowest (B); Warm → pre-configured, needs data (~12h) (A); Hot → fully equipped/near-real-time/fastest/most expensive (C).',
    ww: {},
    er: 'Tests mapping of recovery site types to characteristics.',
  },
  {
    t: 'Recovery Sites', s: 'Shared site', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Additional Recovery Site Options',
    q: 'A shared recovery site arrangement between organizations is typically governed by a:',
    o: [
      'Mutual Assistance Agreement (MAA) / reciprocal agreement',
      'Wireless pre-shared key',
      'Software license (EULA)',
      'Master boot record',
    ],
    a: 'A',
    wc: 'A shared site is used with one or more organizations under a Mutual Assistance Agreement (MAA)/reciprocal agreement defining responsibilities.',
    ww: {
      B: 'A wireless PSK is a network secret, not a site agreement.',
      C: 'A EULA governs software use.',
      D: 'An MBR is a disk structure.',
    },
    er: 'Maps shared sites to MAA/reciprocal agreements.',
  },
  {
    t: 'Recovery Sites', s: 'Cloud recovery', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Additional Recovery Site Options',
    q: 'When using a cloud-managed recovery site, a critical contractual element to define is the:',
    o: [
      'Service Level Agreement (SLA) specifying service levels, performance, and cost',
      'Master boot record configuration',
      'Wireless SSID',
      'Office seating chart',
    ],
    a: 'A',
    wc: 'A cloud recovery site (typically warm/hot) needs a well-defined SLA covering service levels, performance, and cost to ensure recovery expectations are met.',
    ww: {
      B: 'MBR configuration is unrelated to cloud recovery SLAs.',
      C: 'An SSID is a wireless network name.',
      D: 'A seating chart is unrelated.',
    },
    er: 'Tests the SLA requirement for cloud recovery sites.',
  },
  // ---- Recovery strategies ----
  {
    t: 'Recovery Strategies', s: 'Failover cluster', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Server Protection',
    q: 'A failover cluster improves availability by:',
    o: [
      'Automatically shifting workloads to a standby node when the active node fails',
      'Encrypting all data on the server',
      'Blocking unauthorized network ports',
      'Issuing user credentials',
    ],
    a: 'A',
    wc: 'A failover cluster detects node failure and automatically moves the workload to a healthy standby node, minimizing downtime.',
    ww: {
      B: 'Encryption protects confidentiality, not availability via failover.',
      C: 'Port blocking is a firewall function.',
      D: 'Credential issuance is an IAM function.',
    },
    er: 'Tests the high-availability role of failover clusters.',
  },
  {
    t: 'Recovery Strategies', s: 'Load balancing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Server Protection',
    q: 'Load balancing supports availability primarily by:',
    o: [
      'Distributing traffic/workload across multiple servers to avoid overload and single points of failure',
      'Encrypting traffic between two endpoints',
      'Permanently deleting old logs',
      'Assigning MAC addresses',
    ],
    a: 'A',
    wc: 'Load balancing spreads requests across multiple servers, improving performance and resilience by avoiding overload and single points of failure.',
    ww: {
      B: 'Encryption is a confidentiality control, not load distribution.',
      C: 'Log deletion is unrelated to load balancing.',
      D: 'MAC assignment is hardware-based.',
    },
    er: 'Tests the availability benefit of load balancing.',
  },
  {
    t: 'Recovery Strategies', s: 'Fail secure vs fail open', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Device Failure and Security',
    q: 'An electronic door lock loses power. To protect a high-security vault (prioritizing confidentiality/integrity), it should be configured to:',
    o: [
      'Fail secure (remain locked on failure)',
      'Fail open (unlock on failure) regardless of context',
      'Fail open to maximize convenience',
      'Stay in its last state with no defined behavior',
    ],
    a: 'A',
    wc: 'For a high-security area prioritizing confidentiality/integrity, the lock should fail secure (stay locked) on power loss—though life-safety areas may instead require fail-open for egress.',
    ww: {
      B: 'Failing open would expose the vault; it conflicts with the stated priority.',
      C: 'Convenience does not justify exposing a high-security vault.',
      D: 'An undefined failure state is unsafe and unacceptable.',
    },
    er: 'Tests fail-secure for confidentiality/integrity priorities (vs fail-open for life safety).',
  },
  {
    t: 'Recovery Strategies', s: 'Fail open for safety', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Device Failure and Security',
    q: 'During a power failure, an electronically controlled emergency EXIT door in an occupied office should:',
    o: [
      'Fail open (unlock) to allow safe egress, prioritizing human life safety',
      'Fail secure (stay locked) to protect assets, trapping occupants',
      'Stay locked permanently',
      'Disable the fire alarm',
    ],
    a: 'A',
    wc: 'Life safety takes precedence: emergency egress doors should fail open (unlock) so people can exit safely, even at some risk to assets.',
    ww: {
      B: 'Failing secure here would trap occupants—unacceptable for life safety.',
      C: 'Permanent locking endangers occupants during emergencies.',
      D: 'Disabling the fire alarm removes a life-safety warning.',
    },
    er: 'Tests fail-open for life-safety egress.',
  },
  {
    t: 'Recovery Strategies', s: 'Power protection', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Power Protection',
    q: 'Which TWO are power-protection measures used to maintain availability during outages? (Select TWO.)',
    o: [
      'Uninterruptible Power Supply (UPS) for short outages',
      'Backup generators for long outages',
      'A network load balancer',
      'A perimeter firewall',
    ],
    a: ['A', 'B'],
    wc: 'A UPS bridges short outages and generators sustain long ones—both are power-protection measures.',
    ww: {
      C: 'A load balancer distributes traffic; it is not a power-protection device.',
      D: 'A firewall filters traffic; it is not a power-protection device.',
    },
    er: 'Identifies power-protection measures (UPS + generator).',
  },
  {
    t: 'Recovery Strategies', s: 'QoS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Network Communications',
    q: 'Quality of Service (QoS) supports continuity of network communications by:',
    o: [
      'Prioritizing critical traffic to maintain performance during congestion',
      'Encrypting all stored data',
      'Physically guarding the data center',
      'Destroying old backup tapes',
    ],
    a: 'A',
    wc: 'QoS prioritizes critical/time-sensitive traffic so essential communications maintain acceptable performance even during congestion.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Physical guarding is a facility control.',
      D: 'Tape destruction is a sanitization activity.',
    },
    er: 'Tests the traffic-prioritization role of QoS.',
  },
  // ---- BC vs DR / disasters ----
  {
    t: 'BC vs DR', s: 'Distinction', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity vs. Disaster Recovery',
    q: 'Which statement BEST distinguishes Business Continuity (BC) from Disaster Recovery (DR)?',
    o: [
      'BC keeps the overall business operating during disruption; DR focuses on restoring IT systems/infrastructure after a disaster',
      'BC restores IT systems; DR keeps the business running',
      'They are identical processes',
      'BC applies only to wireless networks',
    ],
    a: 'A',
    wc: 'BC is the broader effort to keep critical business functions running during/after disruption; DR is the IT-focused subset that restores systems and infrastructure.',
    ww: {
      B: 'This reverses BC and DR.',
      C: 'They are related but distinct in scope.',
      D: 'BC is not limited to wireless networks.',
    },
    er: 'Distinguishes BC (business) from DR (IT restoration).',
  },
  {
    t: 'Disasters', s: 'Natural vs man-made', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Disasters',
    q: 'Which TWO of the following are MAN-MADE disasters? (Select TWO.)',
    o: ['Sabotage', 'Terrorism', 'Earthquake', 'Flood'],
    a: ['A', 'B'],
    wc: 'Man-made disasters include human-caused events such as sabotage and terrorism (and utility attacks); earthquakes and floods are natural disasters.',
    ww: {
      C: 'An earthquake is a natural disaster.',
      D: 'A flood is a natural disaster.',
    },
    er: 'Separates man-made disasters from natural ones.',
  },
  {
    t: 'Disasters', s: 'Site location risk', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Natural Disaster Considerations',
    q: 'Facility LOCATION determines natural-disaster risk. Which TWO location factors should be assessed during site selection? (Select TWO.)',
    o: [
      'Whether the site sits in an earthquake zone',
      'Whether the site sits in a flood zone',
      'The color of the building exterior',
      'The brand of the office coffee machine',
    ],
    a: ['A', 'B'],
    wc: 'Earthquake-zone and flood-zone exposure are key location-based natural-disaster considerations for site selection.',
    ww: {
      C: 'Building color does not affect disaster risk.',
      D: 'Coffee-machine brand is irrelevant.',
    },
    er: 'Identifies location-based natural-disaster risk factors.',
  },
  {
    t: 'Disaster Recovery', s: 'DRP focus', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Planning',
    q: 'A Disaster Recovery Plan (DRP) is primarily focused on:',
    o: [
      'Restoring IT infrastructure and systems after a disaster, minimizing downtime and data loss',
      'Marketing the company\'s products',
      'Hiring new employees',
      'Designing the company logo',
    ],
    a: 'A',
    wc: 'A DRP focuses on restoring IT infrastructure/systems after a disaster to minimize downtime and data loss.',
    ww: {
      B: 'Marketing is unrelated to a DRP.',
      C: 'Hiring is an HR function.',
      D: 'Logo design is unrelated.',
    },
    er: 'Tests the IT-restoration focus of a DRP.',
  },
  {
    t: 'Business Continuity', s: 'BCP goal', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity Planning',
    q: 'The goal of Business Continuity Planning (BCP) is to:',
    o: [
      'Ensure critical business functions can continue during and after a disruption',
      'Increase the speed of the office Wi-Fi',
      'Reduce the number of employees',
      'Encrypt the company website',
    ],
    a: 'A',
    wc: 'BCP ensures the organization can maintain or quickly resume critical business functions through and after a disruptive event.',
    ww: {
      B: 'Wi-Fi speed is unrelated to BCP goals.',
      C: 'Headcount reduction is not a BCP goal.',
      D: 'Website encryption is a separate control.',
    },
    er: 'Tests the continuity goal of BCP.',
  },
  {
    t: 'Disaster Recovery', s: 'DR testing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Testing',
    q: 'Why is regular testing of the DR plan essential?',
    o: [
      'To verify the plan actually works and to find gaps before a real disaster',
      'To increase the company\'s marketing reach',
      'To replace the need for backups',
      'To assign blame for past incidents',
    ],
    a: 'A',
    wc: 'DR testing validates that recovery procedures work as intended and reveals gaps/outdated assumptions before an actual disaster occurs.',
    ww: {
      B: 'Marketing is unrelated to DR testing.',
      C: 'Testing complements, not replaces, backups.',
      D: 'Testing aims at improvement, not blame.',
    },
    er: 'Tests the validate-and-find-gaps purpose of DR testing.',
  },
  {
    t: 'Recovery Strategies', s: 'Strategy selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Recovery Strategies',
    q: 'A web application must remain available even if a single server fails, with no manual intervention. Which combination BEST achieves this?',
    o: [
      'A failover cluster with load balancing across redundant servers',
      'A single server with a faster CPU',
      'A cold site activated manually after failure',
      'Disabling monitoring to reduce load',
    ],
    a: 'A',
    wc: 'A failover cluster plus load balancing across redundant servers provides automatic, continuous availability if a node fails.',
    ww: {
      B: 'A single faster server is still a single point of failure.',
      C: 'A manually activated cold site cannot provide seamless, no-intervention availability.',
      D: 'Disabling monitoring reduces visibility and does not improve availability.',
    },
    er: 'Maps no-downtime availability to clustering + load balancing.',
  },
  {
    t: 'Business Impact Analysis', s: 'Critical business functions', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Impact Analysis',
    q: 'Identifying Critical Business Functions (CBFs) in a BIA helps the organization to:',
    o: [
      'Prioritize which processes to recover first and allocate continuity resources accordingly',
      'Decide the company holiday schedule',
      'Choose the office paint color',
      'Set the marketing budget',
    ],
    a: 'A',
    wc: 'Identifying CBFs lets the organization prioritize recovery efforts and allocate continuity resources to the most business-critical processes.',
    ww: {
      B: 'Holiday scheduling is unrelated.',
      C: 'Paint color is irrelevant.',
      D: 'Marketing budgets are not a BIA output.',
    },
    er: 'Tests the prioritization value of identifying CBFs.',
  },
  {
    t: 'Disaster Recovery', s: 'NIST 800-34', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Impact Analysis',
    q: 'Which NIST publication provides contingency planning guidance for information systems?',
    o: ['NIST SP 800-34', 'NIST SP 800-88', 'NIST SP 800-207', 'NIST SP 800-128'],
    a: 'A',
    wc: 'NIST SP 800-34 is the Contingency Planning Guide for Federal Information Systems, covering BIA and recovery planning.',
    ww: {
      B: 'NIST SP 800-88 covers media sanitization.',
      C: 'NIST SP 800-207 covers Zero Trust Architecture.',
      D: 'NIST SP 800-128 covers configuration management.',
    },
    er: 'Maps contingency planning guidance to NIST SP 800-34.',
  },
  {
    t: 'Recovery Sites', s: 'Mobile site', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Additional Recovery Site Options',
    q: 'A mobile recovery site is BEST described as:',
    o: [
      'A self-contained site in a trailer/container (often a warm site) that can be towed where needed',
      'A fully online hot site with no physical presence',
      'A paper-based reciprocal agreement',
      'A backup tape stored off-site',
    ],
    a: 'A',
    wc: 'A mobile site is a self-contained unit in a trailer/container (typically configured as a warm site) that can be transported to a needed location.',
    ww: {
      B: 'A mobile site is a physical, transportable unit.',
      C: 'A paper agreement is a shared-site arrangement, not a mobile site.',
      D: 'A backup tape is media, not a recovery site.',
    },
    er: 'Recall of the mobile recovery site.',
  },
  {
    t: 'Recovery Strategies', s: 'Recovery measures', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Recovery Strategies',
    q: 'Which TWO are technical strategies that improve recovery/availability of critical servers? (Select TWO.)',
    o: ['Failover clustering', 'Load balancing', 'Disabling all backups', 'Removing redundant power'],
    a: ['A', 'B'],
    wc: 'Failover clustering and load balancing both improve availability and resilience of critical servers.',
    ww: {
      C: 'Disabling backups removes the means of recovery.',
      D: 'Removing redundant power reduces resilience.',
    },
    er: 'Identifies availability/recovery strategies.',
  },
  {
    t: 'Disasters', s: 'Non-disaster', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Disasters',
    q: 'In disaster classification, a "non-disaster" refers to:',
    o: [
      'A minor disruption or device/service failure that does not constitute a full disaster',
      'A catastrophic earthquake',
      'A coordinated terrorist attack',
      'A complete loss of the primary facility',
    ],
    a: 'A',
    wc: 'A non-disaster is a smaller-scale disruption (e.g., a single device/service failure) that is handled without invoking full disaster recovery.',
    ww: {
      B: 'An earthquake is a natural disaster.',
      C: 'A terrorist attack is a man-made disaster.',
      D: 'Total facility loss is a major disaster, not a non-disaster.',
    },
    er: 'Recall of the non-disaster category.',
  },
  {
    t: 'Business Continuity', s: 'Management approval', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity Planning',
    q: 'For a business continuity program to be effective, it must have:',
    o: [
      'Senior management approval, support, and resources',
      'No documentation, to remain flexible',
      'A single person responsible with no backup',
      'Marketing department ownership only',
    ],
    a: 'A',
    wc: 'Effective continuity planning requires senior management approval, sponsorship, and resource allocation, plus training and testing.',
    ww: {
      B: 'Continuity plans must be documented to be actionable.',
      C: 'Reliance on one person with no backup is itself a continuity risk.',
      D: 'Continuity is an organization-wide concern, not marketing-only.',
    },
    er: 'Tests the need for management sponsorship of BCP.',
  },
  {
    t: 'Disaster Recovery', s: 'DR process', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Processes',
    q: 'After a disaster is declared, a well-defined DR process primarily provides:',
    o: [
      'Specific, ordered steps to follow during and after the disaster to restore operations',
      'A marketing campaign timeline',
      'A list of employee birthdays',
      'The office snack inventory',
    ],
    a: 'A',
    wc: 'DR processes define the specific steps organizations follow during and after a disaster to restore operations in a controlled, prioritized way.',
    ww: {
      B: 'Marketing timelines are unrelated to DR processes.',
      C: 'Employee birthdays are irrelevant.',
      D: 'Snack inventory is irrelevant.',
    },
    er: 'Tests the purpose of defined DR processes.',
  },
  {
    t: 'Recovery Strategies', s: 'Data protection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Strategies',
    q: 'Maintaining off-site or redundant copies of data primarily supports which recovery objective?',
    o: [
      'Limiting data loss (improving the achievable RPO)',
      'Encrypting the office Wi-Fi',
      'Reducing employee turnover',
      'Increasing marketing reach',
    ],
    a: 'A',
    wc: 'Frequent, redundant/off-site backups reduce potential data loss, improving the achievable Recovery Point Objective (RPO).',
    ww: {
      B: 'Wi-Fi encryption is a separate control.',
      C: 'Turnover is an HR concern.',
      D: 'Marketing reach is unrelated.',
    },
    er: 'Connects redundant/off-site data to RPO.',
  },
  {
    t: 'Business Impact Analysis', s: 'BIA steps', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Impact Analysis',
    q: 'A team beginning a BIA should FIRST:',
    o: [
      'Identify critical business processes and their stakeholders',
      'Purchase a hot site immediately',
      'Encrypt all employee laptops',
      'Launch a penetration test',
    ],
    a: 'A',
    wc: 'A BIA begins by identifying critical business processes and stakeholders, then evaluates impacts and determines tolerance levels (MTD/RTO/RPO).',
    ww: {
      B: 'Selecting recovery sites comes after understanding criticality and requirements.',
      C: 'Laptop encryption is a control, not the first BIA step.',
      D: 'A penetration test is a separate assessment activity.',
    },
    er: 'Tests the first step of a BIA (identify CBFs/stakeholders).',
  },
  {
    t: 'Recovery Strategies', s: 'Fail secure definition', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Device Failure and Security',
    q: '"Fail secure" means that upon failure, a control defaults to a state that:',
    o: [
      'Preserves security (e.g., remains locked/denied)',
      'Maximizes access regardless of security',
      'Permanently destroys data',
      'Disables all logging',
    ],
    a: 'A',
    wc: 'Fail secure (fail closed) defaults to a protected state on failure—e.g., a lock that stays locked—favoring confidentiality/integrity.',
    ww: {
      B: 'Maximizing access on failure is fail-open.',
      C: 'Failing secure does not destroy data.',
      D: 'Fail-secure does not concern logging.',
    },
    er: 'Recall of fail-secure behavior.',
  },
  {
    t: 'Recovery Sites', s: 'Cost vs speed tradeoff', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Types of Recovery Sites',
    q: 'A small nonprofit with a tight budget can tolerate several days of downtime for its non-critical systems. Which recovery site is the MOST cost-appropriate?',
    o: ['Cold site', 'Hot site', 'Fully redundant active-active data centers', 'Two hot sites in different regions'],
    a: 'A',
    wc: 'When days of downtime are acceptable and budget is tight, a cold site (cheapest, slowest) is the cost-appropriate choice.',
    ww: {
      B: 'A hot site is the most expensive—overkill for non-critical, downtime-tolerant systems.',
      C: 'Active-active data centers are very costly and unnecessary here.',
      D: 'Two hot sites is the most expensive option, far exceeding the need.',
    },
    er: 'Maps budget-constrained, downtime-tolerant needs to a cold site.',
  },
  {
    t: 'BC vs DR', s: 'Scope', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity vs. Disaster Recovery',
    q: 'Which is broader in scope?',
    o: [
      'Business Continuity (BC), which encompasses keeping the whole business running',
      'Disaster Recovery (DR), which is broader than BC',
      'They have identical scope',
      'Neither addresses business operations',
    ],
    a: 'A',
    wc: 'BC is the broader discipline (people, processes, facilities, and IT) of keeping the business running; DR is the narrower IT-restoration component.',
    ww: {
      B: 'DR is a subset of BC, not broader.',
      C: 'Their scopes differ.',
      D: 'Both address business operations/continuity in different scopes.',
    },
    er: 'Tests that BC is broader than DR.',
  },
  {
    t: 'Business Impact Analysis', s: 'Risk assessment in BIA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Risk Assessment',
    q: 'The risk assessment within a BIA evaluates:',
    o: [
      'The probability and impact of threat events affecting critical assets',
      'The office coffee consumption',
      'The marketing conversion rate',
      'The color scheme of dashboards',
    ],
    a: 'A',
    wc: 'A BIA\'s risk assessment evaluates the probability and impact of threat events on critical assets/processes (qualitatively and/or quantitatively).',
    ww: {
      B: 'Coffee consumption is irrelevant.',
      C: 'Marketing metrics are unrelated to BIA risk.',
      D: 'Dashboard colors are irrelevant.',
    },
    er: 'Tests the probability/impact focus of BIA risk assessment.',
  },
  {
    t: 'Disaster Recovery', s: 'Recovery vs continuity timing', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Strategies',
    q: 'Conceptually, disaster recovery activities tend to focus on the ____, while business continuity focuses on the ____.',
    o: [
      'Restoration of IT after the event; keeping critical functions running throughout',
      'Marketing plan; hiring plan',
      'Coffee supply; parking spaces',
      'Wireless SSID; firewall rules',
    ],
    a: 'A',
    wc: 'DR concentrates on restoring IT systems/infrastructure after a disaster; BC focuses on sustaining critical business functions throughout the disruption.',
    ww: {
      B: 'Marketing/hiring plans are not the BC/DR distinction.',
      C: 'Coffee/parking are irrelevant.',
      D: 'SSIDs/firewall rules are network specifics, not the BC/DR distinction.',
    },
    er: 'Reinforces the DR (restore IT) vs BC (sustain functions) distinction.',
  },
  {
    t: 'Recovery Strategies', s: 'Redundancy concept', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Server Protection',
    q: 'Building redundancy into critical systems primarily protects which security property?',
    o: ['Availability', 'Confidentiality', 'Non-repudiation', 'Anonymity'],
    a: 'A',
    wc: 'Redundancy (clusters, redundant power, multiple sites) primarily supports availability by removing single points of failure.',
    ww: {
      B: 'Confidentiality concerns disclosure, not redundancy.',
      C: 'Non-repudiation concerns proof of origin.',
      D: 'Anonymity is unrelated to redundancy.',
    },
    er: 'Maps redundancy to availability.',
  },
  {
    t: 'Disaster Recovery', s: 'Backup/site coordination', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Data Backup Strategies',
    q: 'An organization maintains a warm site but has never tested restoring its backups there. What is the MOST significant risk?',
    o: [
      'Backups may fail to restore at the site when a real disaster strikes',
      'The warm site will become a hot site automatically',
      'The RPO will drop to zero on its own',
      'The MTD will no longer matter',
    ],
    a: 'A',
    wc: 'Untested backups/recovery procedures may not actually restore at the warm site during a real disaster—testing is essential to validate recoverability.',
    ww: {
      B: 'A warm site does not automatically upgrade to a hot site.',
      C: 'RPO does not improve to zero without changes to backup strategy.',
      D: 'The MTD remains the business constraint regardless.',
    },
    er: 'Tests the risk of untested backups/recovery at a site.',
  },
  {
    t: 'Business Continuity', s: 'Training and exercises', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity Planning',
    q: 'Training, education, and regular exercises in a continuity program help ensure that:',
    o: [
      'Personnel know their roles and the plan works when actually needed',
      'The plan never has to be updated',
      'Backups become unnecessary',
      'The marketing team meets its quota',
    ],
    a: 'A',
    wc: 'Training and exercises ensure staff understand their continuity roles and validate the plan\'s effectiveness before a real event.',
    ww: {
      B: 'Plans must be updated as the environment changes.',
      C: 'Backups remain essential.',
      D: 'Marketing quotas are unrelated.',
    },
    er: 'Tests the role of training/exercises in continuity readiness.',
  },
  {
    t: 'Disasters', s: 'Man-made assessment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Man-Made Disaster Considerations',
    q: 'To assess man-made disaster risk for a facility, the guide suggests reviewing:',
    o: [
      'Local crime rates and police reports',
      'The building\'s paint brand',
      'The CEO\'s favorite restaurant',
      'The office plant species',
    ],
    a: 'A',
    wc: 'Crime rates and local police reports help assess man-made risks (e.g., theft, vandalism, sabotage) to a facility.',
    ww: {
      B: 'Paint brand is irrelevant to disaster risk.',
      C: 'Restaurant preferences are irrelevant.',
      D: 'Plant species are irrelevant.',
    },
    er: 'Tests crime-data review for man-made risk assessment.',
  },
  {
    t: 'Business Impact Analysis', s: 'Quantitative vs qualitative', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Risk Assessment',
    q: 'A BIA risk assessment that ranks impacts using categories like high/medium/low (rather than dollar figures) is:',
    o: ['Qualitative assessment', 'Quantitative assessment', 'A penetration test', 'A configuration baseline'],
    a: 'A',
    wc: 'A qualitative assessment ranks risk using subjective categories (high/medium/low); a quantitative assessment uses numeric/monetary values.',
    ww: {
      B: 'Quantitative assessment uses numeric/monetary values.',
      C: 'A penetration test is an offensive security assessment.',
      D: 'A configuration baseline is a known-good config reference.',
    },
    er: 'Distinguishes qualitative from quantitative BIA assessment.',
  },
  {
    t: 'Recovery Strategies', s: 'Single point of failure', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Server Protection',
    q: 'An audit finds the entire e-commerce platform depends on one database server with no redundancy. This is BEST described as:',
    o: [
      'A single point of failure that should be mitigated with redundancy/clustering',
      'An acceptable design requiring no change',
      'A confidentiality control',
      'A form of separation of duties',
    ],
    a: 'A',
    wc: 'A lone, non-redundant critical component is a single point of failure; redundancy (clustering, replication, failover) mitigates the availability risk.',
    ww: {
      B: 'A critical SPOF is a risk that should be addressed, not accepted as-is.',
      C: 'Redundancy concerns availability, not confidentiality.',
      D: 'Separation of duties is an access/authorization control, unrelated here.',
    },
    er: 'Maps a lone critical component to a single point of failure.',
  },
  {
    t: 'Disaster Recovery', s: 'Recovery vs restoration', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Strategies',
    q: 'Disaster recovery strategies include both short-term and long-term techniques because:',
    o: [
      'Immediate measures stabilize operations while longer-term efforts fully restore normal capability',
      'Short-term and long-term mean exactly the same thing',
      'Only long-term recovery matters',
      'Recovery should never be planned in advance',
    ],
    a: 'A',
    wc: 'DR uses short-term measures to stabilize/resume critical functions quickly and longer-term efforts to fully restore normal operations.',
    ww: {
      B: 'They address different time horizons of recovery.',
      C: 'Both short- and long-term recovery are important.',
      D: 'Recovery must be planned in advance to be effective.',
    },
    er: 'Tests the short-term/long-term recovery distinction.',
  },
  {
    t: 'Recovery Strategies', s: 'UPS role', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Power Protection',
    q: 'During a brief power flicker, a UPS protects equipment by:',
    o: [
      'Providing immediate battery power to keep systems running',
      'Encrypting the data on disk',
      'Blocking malicious network traffic',
      'Issuing digital certificates',
    ],
    a: 'A',
    wc: 'A UPS supplies immediate battery-backed power during short outages/fluctuations, preventing abrupt shutdowns.',
    ww: {
      B: 'Disk encryption is a confidentiality control.',
      C: 'Blocking traffic is a firewall/IPS function.',
      D: 'Certificate issuance is a PKI function.',
    },
    er: 'Tests the immediate-power role of a UPS.',
  },
  {
    t: 'Business Continuity', s: 'Plan maintenance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Business Continuity Planning',
    q: 'A continuity/DR plan should be reviewed and updated:',
    o: [
      'Regularly and after significant organizational or environmental changes',
      'Only once, when first written',
      'Never, to maintain consistency',
      'Only after a catastrophic failure',
    ],
    a: 'A',
    wc: 'Plans must be reviewed/updated regularly and after major changes (systems, staff, facilities, threats) to remain effective.',
    ww: {
      B: 'A one-time plan quickly becomes outdated.',
      C: 'Never updating leaves the plan stale and ineffective.',
      D: 'Waiting for a catastrophe to update is reactive and risky.',
    },
    er: 'Tests the need to maintain continuity/DR plans.',
  },
  {
    t: 'Disaster Recovery', s: 'Order of restoration', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Business Continuity and Disaster Recovery > Disaster Recovery Processes',
    q: 'When restoring systems after a disaster, which should generally be brought back FIRST?',
    o: [
      'The most critical business functions/systems (per the BIA prioritization)',
      'The least important systems, alphabetically',
      'Whichever system an individual prefers',
      'Only the cafeteria ordering system',
    ],
    a: 'A',
    wc: 'Restoration should follow BIA-driven prioritization, bringing the most critical business functions/systems back first to minimize business impact.',
    ww: {
      B: 'Alphabetical/least-important ordering ignores business criticality.',
      C: 'Personal preference is not a valid prioritization basis.',
      D: 'Non-critical systems should not take precedence over critical ones.',
    },
    er: 'Tests BIA-driven restoration prioritization.',
  },
];
