// Domain 7 — Part 2: Malware (types, anti-malware, scanning), logging &
// monitoring (SIEM, MITRE ATT&CK, Cyber Kill Chain, SOAR, UBA, threat intel),
// configuration & change management, patch management.
module.exports = [
  // ---- Malware ----
  {
    t: 'Malware', s: 'Worm vs virus', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware',
    q: 'The KEY difference between a worm and a virus is that a worm:',
    o: [
      'Self-propagates across networks without needing a host file or user action',
      'Always requires a user to open an infected file',
      'Cannot spread between systems',
      'Only encrypts files for ransom',
    ],
    a: 'A',
    wc: 'A worm self-replicates and spreads across networks on its own, whereas a virus typically needs to attach to a host file and rely on user action to spread.',
    ww: {
      B: 'Requiring a user to open a file describes a virus, not a worm.',
      C: 'Worms spread between systems—that is their hallmark.',
      D: 'Encrypting files for ransom describes ransomware.',
    },
    er: 'Distinguishes self-propagating worms from host-dependent viruses.',
  },
  {
    t: 'Malware', s: 'Logic bomb', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware',
    q: 'A logic bomb is malware that:',
    o: [
      'Executes its malicious payload when a specific condition or trigger is met',
      'Self-propagates across networks immediately',
      'Provides remote control of a device',
      'Displays unwanted advertisements',
    ],
    a: 'A',
    wc: 'A logic bomb lies dormant until a defined condition/trigger (date, event, action) is met, then executes its payload.',
    ww: {
      B: 'Immediate self-propagation describes a worm.',
      C: 'Remote control describes a RAT.',
      D: 'Unwanted ads describe adware.',
    },
    er: 'Maps condition-triggered execution to a logic bomb.',
  },
  {
    t: 'Malware', s: 'RAT', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware',
    q: 'A Remote Access Trojan (RAT) primarily enables an attacker to:',
    o: [
      'Gain covert remote control over an infected device',
      'Display advertisements to generate revenue',
      'Synchronize system clocks',
      'Provide backup power',
    ],
    a: 'A',
    wc: 'A RAT gives an attacker covert remote control of the infected system, often for surveillance, data theft, or lateral movement.',
    ww: {
      B: 'Revenue-generating ads describe adware.',
      C: 'Clock synchronization is NTP.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Maps covert remote control to a RAT.',
  },
  {
    t: 'Malware', s: 'Polymorphic virus', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Viruses by Behavior',
    q: 'A polymorphic virus is difficult for signature-based antivirus to detect because it:',
    o: [
      'Changes its code/appearance with each infection to evade signature matching',
      'Always uses the exact same byte pattern',
      'Cannot replicate at all',
      'Only runs on wireless networks',
    ],
    a: 'A',
    wc: 'A polymorphic virus mutates its code/signature on each infection, defeating static signature matching and requiring heuristic/behavioral detection.',
    ww: {
      B: 'A constant byte pattern would be easy to signature-match.',
      C: 'Polymorphic viruses do replicate (while mutating).',
      D: 'They are not limited to wireless networks.',
    },
    er: 'Maps signature evasion via mutation to polymorphic viruses.',
  },
  {
    t: 'Malware', s: 'Macro virus', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Virus Types by Infection Method',
    q: 'A macro virus typically spreads through:',
    o: [
      'Malicious macros embedded in documents (e.g., word processor/spreadsheet files)',
      'The master boot record only',
      'Wireless access points exclusively',
      'Physical door locks',
    ],
    a: 'A',
    wc: 'A macro virus is written in the macro language of applications and embeds in documents, executing when the document is opened with macros enabled.',
    ww: {
      B: 'MBR infection describes a master boot record virus.',
      C: 'Macro viruses spread via documents, not only wireless.',
      D: 'Door locks are physical controls.',
    },
    er: 'Maps document-macro infection to macro viruses.',
  },
  {
    t: 'Anti-Malware', s: 'On-access vs on-demand', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware Scanning',
    q: 'An antivirus product scans every file the moment it is opened or executed. Which scanning mode is this, and how does it differ from the alternative?',
    o: [
      'On-access scanning; it checks files in real time as they are used, vs on-demand which runs on a schedule/manually',
      'On-demand scanning; it only runs once a year',
      'On-access scanning; it never checks files in real time',
      'On-demand scanning; it scans every file as it opens',
    ],
    a: 'A',
    wc: 'On-access scanning inspects files in real time as they are accessed/executed; on-demand scanning runs on a schedule or when manually initiated.',
    ww: {
      B: 'On-demand is not limited to yearly; and the scenario describes real-time access.',
      C: 'On-access does check in real time—that defines it.',
      D: 'Real-time-as-opened is on-access, not on-demand.',
    },
    er: 'Distinguishes on-access (real-time) from on-demand (scheduled/manual) scanning.',
  },
  {
    t: 'Anti-Malware', s: 'Heuristic analysis', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Anti-Malware',
    q: 'Heuristic (behavior-based) malware analysis improves on pure signature detection by:',
    o: [
      'Identifying suspicious behavior/characteristics, helping catch new or unknown malware',
      'Only matching exact known signatures',
      'Requiring no analysis at all',
      'Encrypting the infected files',
    ],
    a: 'A',
    wc: 'Heuristic analysis evaluates code behavior/characteristics (statically or dynamically) to flag previously unseen malware that lacks a known signature.',
    ww: {
      B: 'Exact-signature matching is the limitation heuristics overcome.',
      C: 'Heuristics involve analysis, not its absence.',
      D: 'Detection does not encrypt the files.',
    },
    er: 'Maps unknown-malware detection to heuristic analysis.',
  },
  {
    t: 'Anti-Malware', s: 'Functions', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Anti-Malware Functions',
    q: 'When antivirus software isolates an infected file so it cannot execute or spread, but does not delete it, this action is called:',
    o: ['Quarantine', 'Disinfect', 'Delete', 'Encrypt'],
    a: 'A',
    wc: 'Quarantine isolates the suspicious/infected file (preventing execution/spread) while preserving it for review or recovery.',
    ww: {
      B: 'Disinfect attempts to clean the malware from the file.',
      C: 'Delete removes the file entirely.',
      D: 'Encrypt is not an anti-malware response function here.',
    },
    er: 'Recall of the quarantine function.',
  },
  {
    t: 'Malware', s: 'Malware-type mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware',
    p: ['Ransomware', 'Keylogger', 'Trojan horse', 'Botnet'],
    q: 'Match each malware type (1-4) to its description (A-D).',
    o: [
      'Records keystrokes to capture credentials/data',
      'Encrypts data and demands payment for the key',
      'A network of compromised devices controlled by an attacker',
      'Malicious software disguised as a legitimate program',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Ransomware → encrypts for ransom (B); Keylogger → records keystrokes (A); Trojan horse → disguised malware (D); Botnet → network of compromised devices (C).',
    ww: {},
    er: 'Tests mapping of malware types to descriptions.',
  },
  // ---- Logging & monitoring ----
  {
    t: 'Logging and Monitoring', s: 'SIEM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Security Information and Event Management (SIEM)',
    q: 'A Security Information and Event Management (SIEM) system primarily:',
    o: [
      'Aggregates and correlates logs/events from many sources for centralized analysis and alerting',
      'Provides backup power to the data center',
      'Physically guards the building entrance',
      'Encrypts wireless traffic',
    ],
    a: 'A',
    wc: 'A SIEM centralizes log/event collection, correlation, and alerting across the environment, supporting detection and investigation.',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'Physical guarding is a facility control.',
      D: 'Wireless encryption is WPA2/WPA3.',
    },
    er: 'Tests the central log aggregation/correlation role of SIEM.',
  },
  {
    t: 'Logging and Monitoring', s: 'Cyber Kill Chain', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 7 > Detective and Preventative Measures > Cyber Kill Chain',
    q: 'Order these stages of the Cyber Kill Chain as an intrusion progresses. (Provide the option labels in order.)',
    o: ['Reconnaissance', 'Weaponization', 'Delivery', 'Exploitation', 'Installation', 'Command and Control (C2)', 'Actions on Objectives'],
    a: 'A,B,C,D,E,F,G',
    wc: 'The Cyber Kill Chain runs: Reconnaissance, Weaponization, Delivery, Exploitation, Installation, Command and Control, and Actions on Objectives.',
    ww: {},
    er: 'Tests the ordered Cyber Kill Chain stages.',
  },
  {
    t: 'Logging and Monitoring', s: 'MITRE ATT&CK', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > MITRE ATT&CK Framework',
    q: 'The MITRE ATT&CK framework is BEST described as:',
    o: [
      'A knowledge base of adversary tactics, techniques, and procedures (TTPs)',
      'A wireless encryption standard',
      'A backup power configuration',
      'A type of fire suppression system',
    ],
    a: 'A',
    wc: 'MITRE ATT&CK catalogs real-world adversary tactics, techniques, and procedures, used for threat modeling, detection engineering, and defense.',
    ww: {
      B: 'Wireless encryption standards are WPA2/WPA3.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Maps adversary TTP knowledge base to MITRE ATT&CK.',
  },
  {
    t: 'Logging and Monitoring', s: 'SOAR', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Security Orchestration, Automation and Response (SOAR)',
    q: 'A SOC is overwhelmed by repetitive alert triage. Which technology automates and orchestrates response workflows (runbooks) to reduce manual effort?',
    o: ['SOAR (Security Orchestration, Automation, and Response)', 'A cold recovery site', 'A padded cell', 'A UPS'],
    a: 'A',
    wc: 'SOAR orchestrates and automates response workflows (runbooks/playbooks) across tools, reducing repetitive manual work and speeding response.',
    ww: {
      B: 'A cold site is a DR recovery facility.',
      C: 'A padded cell isolates attackers, not automates SOC workflows.',
      D: 'A UPS provides backup power.',
    },
    er: 'Maps automated/orchestrated response workflows to SOAR.',
  },
  {
    t: 'Logging and Monitoring', s: 'UBA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Behavior Analytics',
    q: 'User Behavior Analytics (UBA) helps detect threats by:',
    o: [
      'Establishing baselines of normal user activity and flagging anomalous behavior (e.g., insider threats)',
      'Encrypting all data at rest',
      'Routing packets between subnets',
      'Providing backup generator power',
    ],
    a: 'A',
    wc: 'UBA models normal user behavior and flags deviations (e.g., unusual access patterns), aiding detection of compromised accounts and insider threats.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Packet routing is a network function.',
      D: 'Generator power is unrelated.',
    },
    er: 'Tests the anomalous-user-behavior detection of UBA.',
  },
  {
    t: 'Logging and Monitoring', s: 'Log protection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Protecting Log Files',
    q: 'To preserve the integrity and usefulness of logs for monitoring, an organization should:',
    o: [
      'Centralize logs on protected servers and restrict who can modify them',
      'Allow every user to edit log files',
      'Store logs only on the system that generated them',
      'Disable logging to save disk space',
    ],
    a: 'A',
    wc: 'Centralizing logs on protected/remote servers with restricted modification protects against tampering and supports reliable monitoring and investigation.',
    ww: {
      B: 'Universal edit rights destroy log integrity.',
      C: 'Local-only logs can be altered/destroyed by an attacker on that host.',
      D: 'Disabling logging eliminates the audit trail.',
    },
    er: 'Tests centralized, protected log storage.',
  },
  {
    t: 'Logging and Monitoring', s: 'Threat intelligence', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Threat Intelligence',
    q: 'Threat intelligence primarily helps an organization to:',
    o: [
      'Make informed, proactive security decisions using analyzed information about threats and TTPs',
      'Provide redundant power during outages',
      'Assign IP addresses to hosts',
      'Encrypt the company website',
    ],
    a: 'A',
    wc: 'Threat intelligence gathers and analyzes information about threats/TTPs to support proactive, informed defensive decisions.',
    ww: {
      B: 'Redundant power is a UPS/generator function.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'Website encryption is TLS/HTTPS.',
    },
    er: 'Tests the proactive-decision value of threat intelligence.',
  },
  // ---- Configuration & change management ----
  {
    t: 'Change Management', s: 'Change control purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Configuration Management > Change Control',
    q: 'The PRIMARY security purpose of a formal change control process is to:',
    o: [
      'Ensure changes are reviewed/approved so they do not introduce misconfigurations or security incidents',
      'Allow any administrator to change production without review',
      'Eliminate the need for backups',
      'Speed up changes by skipping testing',
    ],
    a: 'A',
    wc: 'Change control provides structured review/approval of updates and configuration changes, maintaining security and preventing misconfigurations or incidents.',
    ww: {
      B: 'Unreviewed production changes are exactly what change control prevents.',
      C: 'Change control does not remove the need for backups.',
      D: 'Skipping testing increases the risk of incidents.',
    },
    er: 'Tests the review/approval purpose of change control.',
  },
  {
    t: 'Configuration Management', s: 'Baseline', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Configuration Management > Implementation Phase',
    q: 'In configuration management, a secure baseline configuration serves as:',
    o: [
      'A documented reference for consistent, secure deployment of configuration items',
      'A list of employees authorized to take vacation',
      'A backup generator schedule',
      'A wireless encryption key',
    ],
    a: 'A',
    wc: 'A secure baseline defines a known-good configuration for each configuration item (CI), used as a reference for consistent, secure deployments and drift detection.',
    ww: {
      B: 'Vacation lists are unrelated to configuration baselines.',
      C: 'Generator schedules are power-management items.',
      D: 'A wireless key is a network secret, not a config baseline.',
    },
    er: 'Tests the role of a secure configuration baseline.',
  },
  {
    t: 'Configuration Management', s: 'NIST 800-128 phases', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 7 > Configuration Management > Configuration Management',
    q: 'Order the four main phases of security-focused configuration management (NIST SP 800-128). (Provide the option labels in order.)',
    o: ['Planning', 'Identifying and implementing configurations', 'Controlling configuration changes', 'Monitoring'],
    a: 'A,B,C,D',
    wc: 'NIST SP 800-128 configuration management proceeds: Planning, Identifying/Implementing configurations, Controlling changes, and Monitoring.',
    ww: {},
    er: 'Tests the ordered configuration management phases.',
  },
  {
    t: 'Patch Management', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Configuration Management > System Patch Management',
    q: 'Patch management primarily reduces risk by:',
    o: [
      'Applying vendor updates to fix known vulnerabilities in a controlled way',
      'Encrypting all network traffic',
      'Providing backup power',
      'Assigning IP addresses',
    ],
    a: 'A',
    wc: 'Patch management deploys updates to remediate known vulnerabilities, ideally tested and rolled out through change control to avoid disruption.',
    ww: {
      B: 'Traffic encryption is a separate control.',
      C: 'Backup power is a UPS/generator function.',
      D: 'IP assignment is DHCP\'s function.',
    },
    er: 'Tests the vulnerability-remediation purpose of patch management.',
  },
  {
    t: 'Patch Management', s: 'Test before deploy', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Configuration Management > System Patch Management',
    q: 'A critical patch is released. Before deploying it broadly to production, the BEST practice is to:',
    o: [
      'Test the patch in a non-production environment and deploy via change control',
      'Push it to all production systems immediately with no testing',
      'Ignore it until the next annual review',
      'Disable patching entirely to avoid downtime',
    ],
    a: 'A',
    wc: 'Patches should be tested in a representative non-production environment and rolled out through change control to balance security with stability.',
    ww: {
      B: 'Untested mass deployment risks outages from a faulty patch.',
      C: 'Delaying critical patches leaves known vulnerabilities exposed.',
      D: 'Disabling patching leaves systems vulnerable indefinitely.',
    },
    er: 'Tests test-then-deploy patch practice.',
  },
  {
    t: 'Configuration Management', s: 'Media management', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Configuration Management > Media Management',
    q: 'Media management as part of configuration/operations involves:',
    o: [
      'Protecting and controlling physical and digital media (e.g., drives, tapes, cloud storage)',
      'Designing marketing campaigns',
      'Scheduling employee lunches',
      'Routing BGP between autonomous systems',
    ],
    a: 'A',
    wc: 'Media management secures and controls physical and digital media—hard drives, backup tapes, and cloud storage—across their lifecycle.',
    ww: {
      B: 'Marketing campaigns are unrelated.',
      C: 'Lunch scheduling is unrelated.',
      D: 'BGP routing is a network function.',
    },
    er: 'Tests the scope of media management.',
  },
  {
    t: 'Malware', s: 'Ransomware response', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware',
    q: 'Ransomware has encrypted files on several endpoints. Which combination BEST supports recovery WITHOUT paying the ransom?',
    o: [
      'Isolating affected systems and restoring from clean, tested offline backups',
      'Paying immediately to guarantee data return',
      'Connecting all systems together to share the decryptor',
      'Disabling all backups to save space',
    ],
    a: 'A',
    wc: 'Containing the spread (isolation) and restoring from clean, tested, offline backups enables recovery without funding criminals or trusting attacker-provided keys.',
    ww: {
      B: 'Paying does not guarantee recovery and encourages further attacks.',
      C: 'Interconnecting systems risks spreading the ransomware further.',
      D: 'Disabling backups removes the very means of recovery.',
    },
    er: 'Maps ransomware recovery to isolation + clean offline backups.',
  },
  {
    t: 'Anti-Malware', s: 'Scanning modes', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Detective and Preventative Measures > Types of Malware Scanning',
    q: 'Which TWO are recognized anti-malware scanning modes? (Select TWO.)',
    o: ['On-access scanning', 'On-demand scanning', 'On-vacation scanning', 'On-paper scanning'],
    a: ['A', 'B'],
    wc: 'On-access (real-time) and on-demand (scheduled/manual) are the two anti-malware scanning modes.',
    ww: {
      C: '"On-vacation scanning" is not a real mode.',
      D: '"On-paper scanning" is not an anti-malware mode.',
    },
    er: 'Identifies anti-malware scanning modes.',
  },
  {
    t: 'Logging and Monitoring', s: 'Log entry components', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Detective and Preventative Measures > Essential Components of Log Entries',
    q: 'Which TWO elements are essential components of a useful log entry for investigations? (Select TWO.)',
    o: [
      'An accurate timestamp of when the event occurred',
      'The source/identity associated with the event',
      'The marketing slogan of the company',
      'The color of the server chassis',
    ],
    a: ['A', 'B'],
    wc: 'Accurate timestamps (synchronized time) and the source/identity tied to the event are essential so activity can be correlated and attributed during investigations.',
    ww: {
      C: 'A slogan is irrelevant to log analysis.',
      D: 'Chassis color is irrelevant.',
    },
    er: 'Identifies essential log-entry components.',
  },
  {
    t: 'EOL/EOS', s: 'End of life', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > End of Life (EOL) and End of Support (EOS)',
    q: 'Running software that has reached End of Life (EOL)/End of Support (EOS) is a security risk because:',
    o: [
      'The vendor no longer issues security patches, leaving known vulnerabilities unfixed',
      'It automatically gains new security features',
      'It cannot run on any hardware',
      'It encrypts itself for protection',
    ],
    a: 'A',
    wc: 'EOL/EOS software stops receiving vendor security updates, so newly discovered vulnerabilities remain unpatched—such systems should be replaced or isolated.',
    ww: {
      B: 'EOL/EOS removes support; it does not add features.',
      C: 'EOL software may still run; the risk is lack of patches.',
      D: 'EOL software does not self-encrypt for protection.',
    },
    er: 'Tests the unpatched-vulnerability risk of EOL/EOS software.',
  },
  {
    t: 'Logging and Monitoring', s: 'Kill chain disruption', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Cyber Kill Chain',
    q: 'The defensive value of the Cyber Kill Chain model is that:',
    o: [
      'Disrupting any single stage can break the attack before the adversary achieves their objective',
      'It guarantees attacks can never succeed',
      'It is a wireless encryption protocol',
      'It only applies to physical security',
    ],
    a: 'A',
    wc: 'Because an intrusion must progress through ordered stages, defenders who detect and disrupt any stage can stop the attack before its final objective.',
    ww: {
      B: 'No model guarantees prevention of all attacks.',
      C: 'It is an intrusion model, not wireless encryption.',
      D: 'It applies to cyber intrusions broadly, not only physical security.',
    },
    er: 'Tests the disrupt-any-stage defensive concept of the kill chain.',
  },
  {
    t: 'Malware', s: 'Spyware vs adware', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Detective and Preventative Measures > Additional Malware Types',
    q: 'Spyware is distinguished from adware in that spyware primarily:',
    o: [
      'Covertly gathers information about a user without consent',
      'Displays unwanted advertisements to generate revenue',
      'Encrypts files for ransom',
      'Provides backup power',
    ],
    a: 'A',
    wc: 'Spyware covertly collects user information/activity; adware focuses on displaying unwanted advertisements.',
    ww: {
      B: 'Displaying ads describes adware.',
      C: 'Encrypting for ransom describes ransomware.',
      D: 'Backup power is unrelated.',
    },
    er: 'Distinguishes spyware (surveillance) from adware (ads).',
  },
  {
    t: 'Configuration Management', s: 'Provisioning/automation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Configuration Management > Provisioning and Automation',
    q: 'Using automation to create, manage, or destroy configuration items consistently helps security by:',
    o: [
      'Reducing manual errors and enforcing consistent, repeatable secure configurations',
      'Removing the need for any baseline',
      'Allowing untracked ad-hoc changes',
      'Disabling change control',
    ],
    a: 'A',
    wc: 'Automated provisioning enforces consistent, repeatable configurations (from baselines), reducing manual error and configuration drift.',
    ww: {
      B: 'Automation relies on baselines as references.',
      C: 'Untracked ad-hoc changes undermine configuration management.',
      D: 'Automation should operate within change control, not replace it.',
    },
    er: 'Tests the consistency benefit of provisioning automation.',
  },
];
