// Domain 7 — Part 3: Incident management (steps), security investigations
// (types, burden of proof), evidence (types, rules, chain of custody), and
// digital forensics (eDiscovery/EDRM, forensic process).
module.exports = [
  // ---- Incident management ----
  {
    t: 'Incident Management', s: 'CBK steps order', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 7 > Incident Management > Incident Management Steps (CBK)',
    q: 'Order the incident management steps as listed in the (ISC)² CBK. (Provide the option labels in order.)',
    o: ['Detection', 'Response', 'Mitigation', 'Reporting', 'Recovery', 'Remediation', 'Lessons Learned'],
    a: 'A,B,C,D,E,F,G',
    wc: 'The CBK incident management steps are: Detection, Response, Mitigation, Reporting, Recovery, Remediation, and Lessons Learned.',
    ww: {},
    er: 'Tests the ordered CBK incident management steps.',
  },
  {
    t: 'Incident Management', s: 'Preparation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Incident Management Steps (NIST Mapping)',
    q: 'In the NIST incident response model, the Preparation phase includes:',
    o: [
      'Establishing the IR policy, forming the incident response team, and deploying tools (IDS, DLP, etc.)',
      'Eradicating malware from infected hosts',
      'Writing the final lessons-learned report',
      'Restoring systems from backup',
    ],
    a: 'A',
    wc: 'Preparation establishes the incident response policy, defines incidents/priorities, forms the IR team with roles/contacts, and deploys necessary tools before incidents occur.',
    ww: {
      B: 'Eradication occurs during containment/eradication/recovery, not preparation.',
      C: 'The lessons-learned report is post-incident activity.',
      D: 'Restoring from backup is part of recovery.',
    },
    er: 'Tests the contents of the NIST Preparation phase.',
  },
  {
    t: 'Incident Management', s: 'Detection and triage', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Detection and Analysis',
    q: 'A SOC analyst receives many alerts and must determine which represent genuine incidents requiring response. This analysis/prioritization activity is called:',
    o: ['Triage', 'Remediation', 'Lessons learned', 'Provisioning'],
    a: 'A',
    wc: 'Triage analyzes and prioritizes events to confirm genuine incidents and determine response urgency during the detection/analysis phase.',
    ww: {
      B: 'Remediation addresses root causes after response.',
      C: 'Lessons learned is the post-incident review.',
      D: 'Provisioning is an identity/configuration activity.',
    },
    er: 'Maps event analysis/prioritization to triage.',
  },
  {
    t: 'Incident Management', s: 'Lessons learned', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Lessons Learned',
    q: 'The PRIMARY purpose of the lessons-learned (post-incident) phase is to:',
    o: [
      'Analyze how the incident was handled and improve future response plans/controls',
      'Assign blame to a single employee',
      'Immediately delete all incident logs',
      'Pay any ransom demanded',
    ],
    a: 'A',
    wc: 'Lessons learned reviews incident handling, identifies gaps and root causes, and drives improvements to plans, controls, and processes.',
    ww: {
      B: 'The goal is improvement, not blame assignment.',
      C: 'Logs should be retained, not deleted, for analysis and evidence.',
      D: 'Paying ransom is not the purpose of lessons learned.',
    },
    er: 'Tests the improvement focus of lessons learned.',
  },
  {
    t: 'Incident Management', s: 'Containment priority', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Detection and Analysis',
    q: 'Active malware is spreading laterally across the network during an incident. After detection/analysis, what is the MOST immediate priority?',
    o: [
      'Contain/mitigate the spread (e.g., isolate affected systems) to limit damage',
      'Write the executive summary',
      'Conduct the annual security awareness training',
      'Schedule next year\'s penetration test',
    ],
    a: 'A',
    wc: 'Once an incident is confirmed and spreading, containment/mitigation (isolating affected systems) is the immediate priority to limit damage before eradication and recovery.',
    ww: {
      B: 'Reporting/executive summaries come after stabilizing the situation.',
      C: 'Awareness training is not an immediate incident-response action.',
      D: 'Scheduling future tests does not address the active incident.',
    },
    er: 'Prioritizes containment/mitigation during active spread.',
  },
  // ---- Investigations ----
  {
    t: 'Investigations', s: 'Investigation types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Investigations',
    q: 'An inquiry into whether an organization complied with a specific industry regulator\'s rules is which type of investigation?',
    o: ['Regulatory', 'Administrative', 'Criminal', 'Civil'],
    a: 'A',
    wc: 'A regulatory investigation examines compliance with a regulator\'s rules/standards for an industry.',
    ww: {
      B: 'Administrative investigations address internal policy matters.',
      C: 'Criminal investigations pursue violations of criminal law.',
      D: 'Civil investigations concern disputes between private parties.',
    },
    er: 'Distinguishes regulatory from other investigation types.',
  },
  {
    t: 'Investigations', s: 'Burden of proof', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Burden of Proof Standards',
    q: 'A cyber case may be pursued criminally (risking imprisonment) or civilly (seeking damages). Which correctly pairs each with its standard of proof?',
    o: [
      'Criminal = beyond a reasonable doubt; Civil = preponderance of the evidence',
      'Criminal = preponderance of the evidence; Civil = beyond a reasonable doubt',
      'Both use beyond a reasonable doubt',
      'Both use preponderance of the evidence',
    ],
    a: 'A',
    wc: 'Criminal cases require the higher "beyond a reasonable doubt" standard; civil cases use the lower "preponderance of the evidence" standard.',
    ww: {
      B: 'This reverses the two standards.',
      C: 'Civil cases use the lower preponderance standard, not beyond a reasonable doubt.',
      D: 'Criminal cases use the higher beyond-a-reasonable-doubt standard.',
    },
    er: 'Tests criminal vs civil standards of proof.',
  },
  {
    t: 'Investigations', s: 'Administrative investigation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Investigations',
    q: 'An internal investigation into a suspected violation of company policy, used to support an HR decision, is a(n):',
    o: ['Administrative investigation', 'Criminal investigation', 'Regulatory investigation', 'Civil investigation'],
    a: 'A',
    wc: 'Administrative investigations address internal policy violations and inform organizational/HR decisions.',
    ww: {
      B: 'Criminal investigations involve law enforcement and criminal law.',
      C: 'Regulatory investigations concern compliance with a regulator.',
      D: 'Civil investigations involve disputes between parties.',
    },
    er: 'Maps an internal policy inquiry to an administrative investigation.',
  },
  {
    t: 'Investigations', s: 'MO analysis', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Investigations',
    q: 'Modus Operandi (MO) analysis in an investigation focuses on:',
    o: [
      'The attacker\'s characteristic methods/patterns of operation',
      'The brand of the victim\'s laptop',
      'The office floor plan',
      'The company\'s marketing budget',
    ],
    a: 'A',
    wc: 'MO analysis studies the attacker\'s characteristic methods and patterns, which can help attribute or anticipate behavior.',
    ww: {
      B: 'Laptop brand is not the focus of MO analysis.',
      C: 'Floor plans are unrelated to MO.',
      D: 'Marketing budgets are irrelevant.',
    },
    er: 'Tests the meaning of MO analysis.',
  },
  // ---- Evidence ----
  {
    t: 'Evidence', s: 'Best evidence rule', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Key Evidence Rules',
    q: 'The "best evidence rule" generally requires that:',
    o: [
      'Original documents/evidence be used whenever possible (copies are secondary and may be inadmissible)',
      'Only photocopies are ever admissible',
      'Verbal testimony always outweighs documents',
      'Evidence be destroyed after the case',
    ],
    a: 'A',
    wc: 'The best evidence rule favors original documents/evidence; copies are secondary and can be challenged for authenticity.',
    ww: {
      B: 'The rule prefers originals over copies, not the reverse.',
      C: 'The rule is about document originals, not testimony precedence.',
      D: 'Evidence must be preserved, not destroyed.',
    },
    er: 'Tests the best evidence rule (prefer originals).',
  },
  {
    t: 'Evidence', s: 'Hearsay', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Testimonial Evidence',
    q: 'Hearsay evidence is:',
    o: [
      'Information relayed from someone who did not directly witness the event',
      'A witness\'s account of something they personally observed',
      'An expert\'s professional opinion',
      'Physical evidence collected at the scene',
    ],
    a: 'A',
    wc: 'Hearsay is secondhand information from someone who did not directly witness the event, and is often subject to admissibility limits.',
    ww: {
      B: 'A firsthand account is direct evidence.',
      C: 'An expert opinion is opinion evidence.',
      D: 'Physical scene evidence is not testimonial hearsay.',
    },
    er: 'Tests the definition of hearsay evidence.',
  },
  {
    t: 'Evidence', s: 'Circumstantial vs corroborative', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Additional Evidence Types',
    q: 'Video footage that supports and verifies the access logs already collected is an example of which evidence type?',
    o: ['Corroborative evidence', 'Circumstantial evidence', 'Hearsay evidence', 'Opinion evidence'],
    a: 'A',
    wc: 'Corroborative evidence supports or verifies other evidence (e.g., video footage alongside access logs), strengthening a case.',
    ww: {
      B: 'Circumstantial evidence implies a fact indirectly rather than verifying existing evidence.',
      C: 'Hearsay is secondhand information.',
      D: 'Opinion evidence is an expert\'s professional judgment.',
    },
    er: 'Maps supporting/verifying evidence to corroborative evidence.',
  },
  {
    t: 'Evidence', s: 'Direct evidence', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Testimonial Evidence',
    q: 'Direct evidence is BEST described as:',
    o: [
      'Witness testimony based on firsthand observation',
      'Secondhand information from a non-witness',
      'An expert\'s opinion',
      'Facts that only imply an event occurred',
    ],
    a: 'A',
    wc: 'Direct evidence is testimony from a witness who personally observed the event.',
    ww: {
      B: 'Secondhand non-witness information is hearsay.',
      C: 'An expert opinion is opinion evidence.',
      D: 'Indirectly implied facts are circumstantial evidence.',
    },
    er: 'Recall of direct evidence.',
  },
  {
    t: 'Evidence', s: 'Chain of custody', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Chain of Custody',
    q: 'A laptop seized as evidence is later challenged in court because no one can prove who handled it between seizure and analysis. Which control was inadequately maintained?',
    o: [
      'Chain of custody',
      'Load balancing',
      'Whitelisting',
      'Quality of Service (QoS)',
    ],
    a: 'A',
    wc: 'Chain of custody documents who handled evidence, when, and how—an unbroken, documented chain is required to preserve evidentiary integrity and admissibility.',
    ww: {
      B: 'Load balancing distributes traffic; it is unrelated to evidence.',
      C: 'Whitelisting is a preventative software control.',
      D: 'QoS prioritizes network traffic, unrelated to evidence handling.',
    },
    er: 'Maps unprovable evidence handling to a broken chain of custody.',
  },
  {
    t: 'Evidence', s: 'Evidence types', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Incident Management > Types of Testimonial Evidence',
    q: 'Which TWO are recognized types of testimonial evidence? (Select TWO.)',
    o: ['Direct evidence', 'Opinion evidence', 'Failover evidence', 'Whitelisted evidence'],
    a: ['A', 'B'],
    wc: 'Direct evidence (firsthand observation) and opinion evidence (expert judgment) are testimonial evidence types, along with hearsay.',
    ww: {
      C: '"Failover evidence" is not an evidence type (failover is a recovery technique).',
      D: '"Whitelisted evidence" is not an evidence type.',
    },
    er: 'Identifies testimonial evidence types.',
  },
  // ---- Digital forensics ----
  {
    t: 'Digital Forensics', s: 'Forensic process order', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 7 > Incident Management > Forensic Process in Incident Response',
    q: 'Order the core digital forensic process stages within incident response. (Provide the option labels in order.)',
    o: ['Collection', 'Examination', 'Analysis', 'Reporting'],
    a: 'A,B,C,D',
    wc: 'The forensic process proceeds: Collection (acquire evidence), Examination (extract relevant data), Analysis (interpret findings), and Reporting (document conclusions).',
    ww: {},
    er: 'Tests the ordered forensic process stages.',
  },
  {
    t: 'Digital Forensics', s: 'Order of volatility', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Forensic Process in Incident Response',
    q: 'During live evidence collection on a running system, which data should generally be captured FIRST to avoid losing it?',
    o: [
      'Volatile data such as RAM contents and active network connections',
      'Archived backup tapes in off-site storage',
      'Printed documents in a filing cabinet',
      'Data on powered-off hard drives',
    ],
    a: 'A',
    wc: 'The order of volatility dictates collecting the most volatile data first (e.g., RAM, running processes, network connections) before it is lost, then less-volatile media.',
    ww: {
      B: 'Off-site backup tapes are non-volatile and can be collected later.',
      C: 'Printed documents are static and not volatile.',
      D: 'Powered-off drives retain data and are less volatile than RAM.',
    },
    er: 'Tests the order-of-volatility principle in forensics.',
  },
  {
    t: 'Digital Forensics', s: 'eDiscovery', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Digital Forensics',
    q: 'Digital forensics, when applied to identifying electronic evidence for legal proceedings, is also referred to as:',
    o: ['eDiscovery (electronic data discovery)', 'Load balancing', 'Whitelisting', 'Quality of Service'],
    a: 'A',
    wc: 'Digital forensics for legal evidence is also called eDiscovery/electronic data discovery, following a structured reference model (EDRM).',
    ww: {
      B: 'Load balancing distributes traffic.',
      C: 'Whitelisting is a preventative control.',
      D: 'QoS prioritizes network traffic.',
    },
    er: 'Maps electronic legal-evidence discovery to eDiscovery.',
  },
  {
    t: 'Digital Forensics', s: 'Preserve evidence', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 7 > Incident Management > Purpose of Digital Forensics',
    q: 'To analyze a compromised hard drive forensically while keeping the evidence admissible, an investigator should:',
    o: [
      'Work from a forensic image/copy and protect the original, maintaining chain of custody',
      'Boot and use the original drive directly to save time',
      'Reformat the drive before analysis',
      'Share the drive freely without documentation',
    ],
    a: 'A',
    wc: 'Forensic best practice analyzes a verified bit-for-bit image (often with write-blocking), preserving the original and documenting chain of custody to maintain integrity/admissibility.',
    ww: {
      B: 'Using the original directly risks altering evidence and breaking admissibility.',
      C: 'Reformatting destroys the evidence.',
      D: 'Undocumented sharing breaks chain of custody.',
    },
    er: 'Tests image-and-preserve forensic practice.',
  },
  {
    t: 'Digital Forensics', s: 'Reporting', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Digital Forensic Incident Response',
    q: 'The reporting stage of a digital forensic investigation emphasizes:',
    o: [
      'Accuracy and authenticity, presenting admissible evidence with clear explanations',
      'Speed over correctness',
      'Omitting how conclusions were reached',
      'Deleting the underlying evidence',
    ],
    a: 'A',
    wc: 'Forensic reporting focuses on accuracy/authenticity, documenting how conclusions were reached and presenting admissible evidence clearly (e.g., for court).',
    ww: {
      B: 'Sacrificing correctness undermines admissibility.',
      C: 'The methodology must be documented, not omitted.',
      D: 'Evidence must be preserved, not deleted.',
    },
    er: 'Tests forensic reporting emphasis on accuracy/admissibility.',
  },
  {
    t: 'Incident Management', s: 'IR team', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Incident Management Steps (NIST Mapping)',
    q: 'Forming an Incident Response Team (IRT) with defined roles and contacts BEFORE an incident occurs is part of which phase?',
    o: ['Preparation', 'Recovery', 'Lessons learned', 'Remediation'],
    a: 'A',
    wc: 'Establishing the IR team, roles, responsibilities, and contacts is a Preparation activity, done before incidents occur.',
    ww: {
      B: 'Recovery restores normal operations after an incident.',
      C: 'Lessons learned is a post-incident review.',
      D: 'Remediation fixes root causes after response.',
    },
    er: 'Maps IR team formation to the Preparation phase.',
  },
  {
    t: 'Investigations', s: 'Evidence collection techniques', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 7 > Incident Management > Evidence Collection Techniques',
    q: 'Which TWO are recognized evidence collection techniques in investigations? (Select TWO.)',
    o: ['Interviewing witnesses', 'Surveillance', 'Disabling all logging', 'Deleting suspect files'],
    a: ['A', 'B'],
    wc: 'Interviewing and surveillance (along with interrogation and digital forensics) are recognized evidence collection techniques.',
    ww: {
      C: 'Disabling logging destroys potential evidence.',
      D: 'Deleting suspect files destroys evidence.',
    },
    er: 'Identifies valid evidence-collection techniques.',
  },
  {
    t: 'Digital Forensics', s: 'Investigator competence', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Considerations for Forensic Investigations',
    q: 'A key consideration for forensic investigations is that investigators should:',
    o: [
      'Be competent, follow consistent policy/process, and maintain chain of custody',
      'Improvise without documented procedures',
      'Avoid documenting any of their steps',
      'Work alone with no accountability',
    ],
    a: 'A',
    wc: 'Forensic investigators should be competent, aware of data sources, and follow consistent policies/processes while maintaining chain of custody for admissibility.',
    ww: {
      B: 'Improvising without procedures undermines repeatability and admissibility.',
      C: 'Steps must be documented for the evidence to hold up.',
      D: 'Accountability and documented handling are essential.',
    },
    er: 'Tests forensic investigator best practices.',
  },
  {
    t: 'Incident Management', s: 'Investigation trigger', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Investigation Process',
    q: 'In the guide\'s model, a security investigation is typically INITIATED by:',
    o: [
      'The incident response process identifying an event that warrants investigation',
      'The marketing department\'s campaign launch',
      'The annual budget approval',
      'A scheduled office cleaning',
    ],
    a: 'A',
    wc: 'Incident response initiates the investigation when an event is detected/confirmed that requires deeper inquiry (administrative, civil, criminal, or regulatory).',
    ww: {
      B: 'Marketing campaigns do not trigger security investigations.',
      C: 'Budget approval is unrelated.',
      D: 'Office cleaning is unrelated.',
    },
    er: 'Connects investigation initiation to incident response.',
  },
  {
    t: 'Evidence', s: 'Opinion evidence', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Testimonial Evidence',
    q: 'Opinion evidence is provided by:',
    o: [
      'Subject-matter experts offering professional opinions on the evidence',
      'A witness who saw the event firsthand',
      'A non-witness relaying secondhand information',
      'A network load balancer',
    ],
    a: 'A',
    wc: 'Opinion evidence comes from qualified experts offering professional opinions to help interpret technical evidence.',
    ww: {
      B: 'Firsthand observation is direct evidence.',
      C: 'Secondhand information is hearsay.',
      D: 'A load balancer is a network device, not an evidence source.',
    },
    er: 'Recall of opinion (expert) evidence.',
  },
  {
    t: 'Investigations', s: 'Criminal investigation', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Types of Investigations',
    q: 'A criminal investigation differs from the other investigation types in that it:',
    o: [
      'Concerns potential violations of criminal law and can lead to prosecution',
      'Only addresses internal company policy',
      'Cannot involve law enforcement',
      'Uses no evidence at all',
    ],
    a: 'A',
    wc: 'A criminal investigation addresses potential violations of criminal law, may involve law enforcement, and can lead to prosecution under the highest standard of proof.',
    ww: {
      B: 'Internal policy matters are administrative investigations.',
      C: 'Criminal investigations commonly involve law enforcement.',
      D: 'Evidence is central to a criminal investigation.',
    },
    er: 'Distinguishes criminal investigations.',
  },
  {
    t: 'Incident Management', s: 'Remediation vs recovery', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 7 > Incident Management > Detection and Analysis',
    q: 'In incident handling, how does remediation differ from recovery?',
    o: [
      'Recovery restores normal operations; remediation addresses the root cause to prevent recurrence',
      'They are the same step with different names',
      'Remediation restores systems; recovery assigns blame',
      'Recovery deletes all evidence',
    ],
    a: 'A',
    wc: 'Recovery returns affected systems to normal operation; remediation fixes the underlying root cause/vulnerability so the incident does not recur.',
    ww: {
      B: 'They are distinct steps with different goals.',
      C: 'This reverses the definitions; remediation addresses root cause.',
      D: 'Recovery restores operations; it does not delete evidence.',
    },
    er: 'Distinguishes recovery (restore) from remediation (root cause).',
  },
];
