// Domain 4 — Part 2: OSI & TCP/IP models, PDUs, encapsulation, TCP handshake,
// IP addressing (classes, RFC 1918, NAT/PAT, CIDR, IPv6), broadcast/collision
// domains, and routing.
module.exports = [
  // ---- OSI / TCP-IP ----
  {
    t: 'OSI Model', s: 'Layer functions', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > OSI Model Layers',
    q: 'Routing and logical addressing for packet delivery between networks occur at which OSI layer?',
    o: ['Layer 3 (Network)', 'Layer 2 (Data Link)', 'Layer 4 (Transport)', 'Layer 7 (Application)'],
    a: 'A',
    wc: 'Layer 3 (Network) manages routing and logical (IP) addressing for packet transfer between networks.',
    ww: {
      B: 'Layer 2 handles MAC addressing and frames within a segment.',
      C: 'Layer 4 manages end-to-end logical connections (TCP/UDP).',
      D: 'Layer 7 provides the application interface.',
    },
    er: 'Maps routing/logical addressing to Layer 3.',
  },
  {
    t: 'OSI Model', s: 'Transport layer', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > OSI Model Layers',
    q: 'The OSI Transport layer (Layer 4) is responsible for:',
    o: [
      'Controlling logical end-to-end connections (e.g., TCP connection-oriented, UDP connectionless)',
      'Converting frames into bits for the physical medium',
      'Resolving IP addresses to MAC addresses',
      'Providing the human user interface',
    ],
    a: 'A',
    wc: 'Layer 4 controls end-to-end logical connections—TCP (connection-oriented) and UDP (connectionless).',
    ww: {
      B: 'Bit conversion for the medium is Layer 1 (Physical).',
      C: 'IP-to-MAC resolution (ARP) is a Layer 2/3 function.',
      D: 'The user interface is Layer 7 (Application).',
    },
    er: 'Maps end-to-end TCP/UDP connections to Layer 4.',
  },
  {
    t: 'OSI Model', s: 'PDU per layer', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Protocol Data Unit (PDU)',
    q: 'At the OSI Network layer, the protocol data unit (PDU) is called a:',
    o: ['Packet', 'Segment', 'Frame', 'Bit'],
    a: 'A',
    wc: 'The Network layer PDU is the packet; Transport = segment, Data Link = frame, Physical = bits.',
    ww: {
      B: 'A segment is the Transport-layer PDU.',
      C: 'A frame is the Data Link-layer PDU.',
      D: 'Bits are the Physical-layer PDU.',
    },
    er: 'Recall of the Network-layer PDU.',
  },
  {
    t: 'OSI Model', s: 'Layer-to-PDU mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 4 > Networking Concepts > Protocol Data Unit (PDU)',
    p: ['Transport layer', 'Network layer', 'Data Link layer', 'Physical layer'],
    q: 'Match each OSI layer (1-4) to its protocol data unit (A-D).',
    o: ['Packet', 'Segment', 'Bits', 'Frame'],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Transport → Segment (B); Network → Packet (A); Data Link → Frame (D); Physical → Bits (C).',
    ww: {},
    er: 'Tests mapping of layers to their PDUs.',
  },
  {
    t: 'OSI Model', s: 'Encapsulation order', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 4 > Networking Concepts > Encapsulation Process',
    q: 'During encapsulation, data is wrapped as it moves DOWN the stack from the sending application to the wire. Order the PDUs from first formed to last. (Provide the option labels in order.)',
    o: ['Data (Application)', 'Segment (Transport)', 'Packet (Network)', 'Frame (Data Link)'],
    a: 'A,B,C,D',
    wc: 'Encapsulation proceeds Data → Segment → Packet → Frame (then bits on the wire) as each lower layer adds its header.',
    ww: {},
    er: 'Tests the encapsulation order down the stack.',
  },
  {
    t: 'TCP/IP', s: 'TCP three-way handshake', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 4 > Networking Concepts > TCP Three-Way Handshake',
    q: 'Order the messages of the TCP three-way handshake. (Provide the option labels in order.)',
    o: ['SYN', 'SYN-ACK', 'ACK'],
    a: 'A,B,C',
    wc: 'The TCP handshake is SYN (client initiates), SYN-ACK (server acknowledges and responds), ACK (client confirms), after which data transfer begins.',
    ww: {},
    er: 'Tests the TCP handshake sequence.',
  },
  {
    t: 'TCP/IP', s: 'TCP vs UDP', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Networking Concepts > Layer 4 - Transport Layer Protocols',
    q: 'A live video-conferencing application prioritizes low latency and can tolerate occasional lost frames. Which transport protocol is the BETTER fit, and why?',
    o: [
      'UDP, because it is connectionless and avoids handshake/retransmission overhead',
      'TCP, because guaranteed delivery is essential for real-time video',
      'ARP, because it resolves addresses quickly',
      'ICMP, because it carries the video payload efficiently',
    ],
    a: 'A',
    wc: 'UDP is connectionless and lightweight (no handshake/retransmission), favoring low-latency real-time media that tolerates minor loss; TCP\'s reliability adds latency.',
    ww: {
      B: 'TCP\'s retransmission/ordering adds latency that harms real-time media.',
      C: 'ARP resolves IP-to-MAC; it does not carry application data.',
      D: 'ICMP carries control/status messages, not video payloads.',
    },
    er: 'Tests choosing UDP for latency-sensitive media.',
  },
  {
    t: 'TCP/IP', s: 'Connection-oriented', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 4 - Transport Layer Protocols',
    q: 'Which transport protocol is connection-oriented and provides reliable, ordered delivery using a handshake?',
    o: ['TCP', 'UDP', 'IP', 'ICMP'],
    a: 'A',
    wc: 'TCP is connection-oriented, establishing a session via the three-way handshake and providing reliable, ordered delivery.',
    ww: {
      B: 'UDP is connectionless and does not guarantee delivery.',
      C: 'IP is a connectionless Layer 3 routing protocol.',
      D: 'ICMP carries status/error messages, not reliable data streams.',
    },
    er: 'Maps reliable, connection-oriented delivery to TCP.',
  },
  // ---- IP addressing ----
  {
    t: 'IP Addressing', s: 'RFC 1918 private ranges', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IPv4 Private Address Ranges (RFC 1918)',
    q: 'Which of the following is a private (RFC 1918) IPv4 address range?',
    o: ['10.0.0.0 – 10.255.255.255', '8.0.0.0 – 8.255.255.255', '1.0.0.0 – 1.255.255.255', '224.0.0.0 – 239.255.255.255'],
    a: 'A',
    wc: 'RFC 1918 private ranges are 10.0.0.0/8, 172.16.0.0–172.31.255.255 (/12), and 192.168.0.0/16; 10.x is private.',
    ww: {
      B: '8.0.0.0/8 is public address space.',
      C: '1.0.0.0/8 is public address space.',
      D: '224.0.0.0–239.255.255.255 is Class D multicast, not private unicast.',
    },
    er: 'Identifies the 10.0.0.0/8 private range.',
  },
  {
    t: 'IP Addressing', s: 'NAT/PAT', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IPv4 Private Address Ranges (RFC 1918)',
    q: 'Network Address Translation (NAT) primarily enables:',
    o: [
      'Private internal IP addresses to be translated to public addresses for internet routing',
      'Encryption of all packets leaving the network',
      'Automatic assignment of MAC addresses',
      'Resolution of domain names to IP addresses',
    ],
    a: 'A',
    wc: 'NAT translates private (RFC 1918) addresses to public addresses (and back) so internal hosts can communicate over the internet; PAT maps many hosts to one public IP via ports.',
    ww: {
      B: 'NAT does not encrypt traffic.',
      C: 'MAC assignment is done by hardware, not NAT.',
      D: 'Name-to-IP resolution is DNS\'s job.',
    },
    er: 'Maps private-to-public translation to NAT.',
  },
  {
    t: 'IP Addressing', s: 'PAT', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Networking Concepts > IPv4 Private Address Ranges (RFC 1918)',
    q: 'A small office has 50 internal hosts but only one public IP address from its ISP, and all hosts need internet access. Which technique makes this possible?',
    o: [
      'Port Address Translation (PAT), mapping many private hosts to one public IP using unique ports',
      'Assigning each host a Class A public block',
      'Disabling NAT entirely',
      'Using DNSSEC to share the address',
    ],
    a: 'A',
    wc: 'PAT (NAT overload) maps many internal hosts to a single public IP by tracking unique source ports per connection.',
    ww: {
      B: 'A single ISP-assigned public IP cannot provide a public block per host.',
      C: 'Disabling NAT would leave private hosts unable to route to the internet.',
      D: 'DNSSEC authenticates DNS responses; it does not share an IP among hosts.',
    },
    er: 'Maps many-to-one public IP sharing to PAT.',
  },
  {
    t: 'IP Addressing', s: 'CIDR', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > CIDR Notation for Subnet Masks',
    q: 'The CIDR notation /24 corresponds to which subnet mask?',
    o: ['255.255.255.0', '255.0.0.0', '255.255.0.0', '255.255.255.255'],
    a: 'A',
    wc: '/24 means 24 network bits, i.e., the mask 255.255.255.0 (the traditional Class C default).',
    ww: {
      B: '255.0.0.0 is /8.',
      C: '255.255.0.0 is /16.',
      D: '255.255.255.255 is /32 (a single host).',
    },
    er: 'Maps /24 to 255.255.255.0.',
  },
  {
    t: 'IP Addressing', s: 'Multicast class', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IPv4 Classes',
    q: 'IPv4 addresses in the range 224.0.0.0 – 239.255.255.255 (Class D) are reserved for:',
    o: ['Multicasting', 'Private internal addressing', 'Loopback testing', 'Experimental use'],
    a: 'A',
    wc: 'Class D (224.0.0.0–239.255.255.255) is reserved for multicast.',
    ww: {
      B: 'Private addressing uses RFC 1918 ranges in Classes A/B/C.',
      C: 'Loopback is 127.0.0.0/8.',
      D: 'Experimental use is Class E (240.0.0.0+).',
    },
    er: 'Maps Class D to multicast.',
  },
  {
    t: 'IP Addressing', s: 'IPv6 benefits', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Benefits of IPv6',
    q: 'A benefit of IPv6 over IPv4 highlighted in the guide is that IPv6:',
    o: [
      'Has a vast address space and built-in autoconfiguration that reduces the need for NAT',
      'Uses shorter 32-bit addresses than IPv4',
      'Cannot support quality of service',
      'Eliminates the need for any routing',
    ],
    a: 'A',
    wc: 'IPv6 provides an enormous address space and built-in configuration (reducing reliance on NAT/DHCP), plus features like scoped addresses and QoS.',
    ww: {
      B: 'IPv6 uses 128-bit addresses, longer than IPv4\'s 32-bit.',
      C: 'IPv6 supports QoS for traffic prioritization.',
      D: 'IPv6 still relies on routing between networks.',
    },
    er: 'Tests IPv6 address-space/autoconfiguration benefits.',
  },
  {
    t: 'IP Addressing', s: 'Private vs public', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Networking Concepts > IPv4 Private Address Ranges (RFC 1918)',
    q: 'Which TWO address ranges are RFC 1918 private ranges? (Select TWO.)',
    o: ['172.16.0.0 – 172.31.255.255', '192.168.0.0 – 192.168.255.255', '11.0.0.0 – 11.255.255.255', '200.1.0.0 – 200.1.255.255'],
    a: ['A', 'B'],
    wc: '172.16.0.0–172.31.255.255 and 192.168.0.0/16 are RFC 1918 private ranges (along with 10.0.0.0/8).',
    ww: {
      C: '11.0.0.0/8 is public address space (only 10.0.0.0/8 is private in Class A).',
      D: '200.1.x is public address space.',
    },
    er: 'Identifies the 172.16/12 and 192.168/16 private ranges.',
  },
  // ---- Domains / routing ----
  {
    t: 'Network Domains', s: 'Broadcast vs collision domain', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Network Domains',
    q: 'Which statement about broadcast and collision domains is correct?',
    o: [
      'A switch separates collision domains per port, while a router separates broadcast domains',
      'A hub separates both collision and broadcast domains per port',
      'A router places all connected networks in one broadcast domain',
      'Switches and hubs are functionally identical for collision domains',
    ],
    a: 'A',
    wc: 'Each switch port is its own collision domain; routers bound broadcast domains (broadcasts do not cross a router by default).',
    ww: {
      B: 'A hub is a single shared collision domain (no separation per port).',
      C: 'Routers separate broadcast domains rather than merging them.',
      D: 'A hub is one collision domain; a switch gives each port its own—so they differ.',
    },
    er: 'Tests how switches and routers bound collision/broadcast domains.',
  },
  {
    t: 'Routing', s: 'Static vs dynamic routes', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Types of Routes',
    q: 'A dynamic route differs from a static route in that a dynamic route is:',
    o: [
      'Automatically learned and updated by routing protocols exchanging information with neighbors',
      'Manually configured and never changes',
      'Always more secure than any static route',
      'Only usable on wireless networks',
    ],
    a: 'A',
    wc: 'Dynamic routes are learned/updated automatically via routing protocols that share information with neighboring routers, adapting to topology changes.',
    ww: {
      B: 'Manual, unchanging configuration describes a static route.',
      C: 'Dynamic routing is not inherently more secure; it can introduce protocol risks.',
      D: 'Dynamic routing is used on wired and wireless networks alike.',
    },
    er: 'Distinguishes dynamic (learned) from static (manual) routes.',
  },
  {
    t: 'Routing', s: 'Distance vector vs link state', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Routing Protocol Types',
    q: 'A link-state routing protocol differs from a distance-vector protocol in that link-state protocols:',
    o: [
      'Build a map of the overall network state to select the most reliable/fastest routes',
      'Choose paths based only on hop count and direction',
      'Cannot operate within an autonomous system',
      'Never converge after a topology change',
    ],
    a: 'A',
    wc: 'Link-state protocols compute routes from a complete view of network topology/state (e.g., OSPF), often yielding faster, more reliable paths than hop-count-based distance-vector protocols.',
    ww: {
      B: 'Choosing by hop count/direction describes distance-vector protocols (e.g., RIP).',
      C: 'Link-state protocols (like OSPF) commonly run as interior gateway protocols within an AS.',
      D: 'Link-state protocols do converge; they are often faster to converge than distance-vector.',
    },
    er: 'Contrasts link-state topology awareness with distance-vector hop counting.',
  },
  {
    t: 'Routing', s: 'BGP / EGP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Types of Routing Protocols',
    q: 'Border Gateway Protocol (BGP) is used to exchange routing information:',
    o: [
      'Between different autonomous systems (as an exterior gateway protocol)',
      'Only within a single switch',
      'Between USB devices on a host',
      'To assign IP addresses to clients',
    ],
    a: 'A',
    wc: 'BGP is the exterior gateway protocol used to exchange routing information between autonomous systems (e.g., across the internet).',
    ww: {
      B: 'Switch-internal forwarding is not BGP\'s role.',
      C: 'USB device communication is unrelated to routing.',
      D: 'IP assignment is DHCP\'s function.',
    },
    er: 'Maps inter-AS routing to BGP/EGP.',
  },
  {
    t: 'Routing', s: 'IGP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Types of Routing Protocols',
    q: 'Interior Gateway Protocols (IGPs) such as OSPF are used to exchange routing information:',
    o: [
      'Within the same autonomous system',
      'Only between competing internet service providers',
      'Exclusively over Bluetooth links',
      'To translate private IPs to public IPs',
    ],
    a: 'A',
    wc: 'IGPs (e.g., OSPF, EIGRP, RIP) exchange routing data within a single autonomous system; EGPs (e.g., BGP) operate between autonomous systems.',
    ww: {
      B: 'Routing between different systems/ISPs is the role of EGPs like BGP.',
      C: 'IGPs are not limited to Bluetooth and typically run over wired/enterprise links.',
      D: 'IP translation is NAT, not a routing protocol.',
    },
    er: 'Maps intra-AS routing to IGPs.',
  },
  {
    t: 'Routing', s: 'Autonomous system', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Types of Routing Protocols',
    q: 'An Autonomous System (AS) is best described as:',
    o: [
      'A collection of network devices managed under a single routing policy',
      'A single laptop with no network connection',
      'A type of fire suppression system',
      'A wireless encryption protocol',
    ],
    a: 'A',
    wc: 'An AS is a set of networks/devices under a common administration and routing policy, identified by an AS number for inter-AS routing.',
    ww: {
      B: 'A standalone laptop is not an AS.',
      C: 'Fire suppression is a physical control, unrelated to routing.',
      D: 'Wireless encryption (e.g., WPA2) is not an AS.',
    },
    er: 'Recall of the autonomous system concept.',
  },
  {
    t: 'IP Addressing', s: 'MAC vs IP address', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IP Networking',
    q: 'Which statement correctly contrasts a MAC address with an IP address?',
    o: [
      'A MAC address is a physical Layer 2 hardware address; an IP address is a logical Layer 3 address',
      'A MAC address is logical and an IP address is physical',
      'Both are assigned by DHCP at boot time',
      'Both operate only at Layer 7',
    ],
    a: 'A',
    wc: 'A MAC address is a hardware (physical) address used at Layer 2; an IP address is a logical Layer 3 address that can change (e.g., via DHCP).',
    ww: {
      B: 'This reverses the definitions—MAC is physical, IP is logical.',
      C: 'MAC addresses are burned into hardware, not assigned by DHCP (which assigns IPs).',
      D: 'They operate at Layers 2 and 3, not Layer 7.',
    },
    er: 'Distinguishes physical MAC from logical IP addressing.',
  },
  {
    t: 'Routing', s: 'Routing protocol types', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Networking Concepts > Key Routing Protocols',
    q: 'Which TWO are distance-vector routing protocols? (Select TWO.)',
    o: ['RIP', 'BGP', 'OSPF', 'TLS'],
    a: ['A', 'B'],
    wc: 'RIP and BGP are categorized as distance-vector (BGP is a path-vector variant) in the guide; OSPF is link-state and TLS is not a routing protocol.',
    ww: {
      C: 'OSPF is a link-state protocol.',
      D: 'TLS is a transport-layer security protocol, not a routing protocol.',
    },
    er: 'Identifies distance-vector protocols versus link-state and non-routing protocols.',
  },
  {
    t: 'OSI Model', s: 'Data Link layer', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > OSI Model Layers',
    q: 'MAC addressing and frame delivery within a local segment occur at which OSI layer?',
    o: ['Layer 2 (Data Link)', 'Layer 3 (Network)', 'Layer 4 (Transport)', 'Layer 5 (Session)'],
    a: 'A',
    wc: 'Layer 2 (Data Link) handles hardware (MAC) addressing and frame delivery within a network segment.',
    ww: {
      B: 'Layer 3 handles logical IP addressing and routing between networks.',
      C: 'Layer 4 handles end-to-end transport (TCP/UDP).',
      D: 'Layer 5 manages sessions.',
    },
    er: 'Maps MAC/frame delivery to Layer 2.',
  },
  {
    t: 'OSI Model', s: 'Session layer', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > OSI Model Layers',
    q: 'Establishing, maintaining, and terminating communication sessions between applications is the role of which OSI layer?',
    o: ['Layer 5 (Session)', 'Layer 1 (Physical)', 'Layer 3 (Network)', 'Layer 2 (Data Link)'],
    a: 'A',
    wc: 'Layer 5 (Session) establishes, maintains, and terminates sessions between communicating systems.',
    ww: {
      B: 'Layer 1 transmits raw bits.',
      C: 'Layer 3 routes packets.',
      D: 'Layer 2 delivers frames within a segment.',
    },
    er: 'Maps session management to Layer 5.',
  },
  {
    t: 'IP Addressing', s: 'IPv4 class A', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IPv4 Classes',
    q: 'A Class A IPv4 network has which default subnet mask?',
    o: ['255.0.0.0 (/8)', '255.255.0.0 (/16)', '255.255.255.0 (/24)', '255.255.255.255 (/32)'],
    a: 'A',
    wc: 'Class A uses a default /8 mask (255.0.0.0), providing a large number of hosts per network.',
    ww: {
      B: '/16 (255.255.0.0) is the Class B default.',
      C: '/24 (255.255.255.0) is the Class C default.',
      D: '/32 denotes a single host, not a class default.',
    },
    er: 'Maps Class A to the /8 default mask.',
  },
  {
    t: 'TCP/IP', s: 'TCP/IP model layers', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > TCP Three-Way Handshake',
    q: 'The four-layer TCP/IP model consists of the Application, Transport, Internet, and ________ layers.',
    o: ['Link (Network Access)', 'Session', 'Presentation', 'Data Center'],
    a: 'A',
    wc: 'The TCP/IP model has four layers: Application, Transport, Internet, and Link (Network Access).',
    ww: {
      B: 'Session is an OSI layer, not a separate TCP/IP model layer.',
      C: 'Presentation is an OSI layer, folded into Application in TCP/IP.',
      D: '"Data Center" is not a TCP/IP model layer.',
    },
    er: 'Recall of the four TCP/IP model layers.',
  },
  {
    t: 'Communications', s: 'Converged protocols', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Converged Protocols',
    q: 'iSCSI is an example of a converged protocol because it:',
    o: [
      'Merges the SCSI storage protocol with IP networking to allow remote storage access',
      'Encrypts all wireless traffic using AES',
      'Replaces the need for any cabling',
      'Routes traffic only within a single VLAN',
    ],
    a: 'A',
    wc: 'iSCSI converges the SCSI storage command protocol with TCP/IP networking, enabling block storage access over standard IP networks.',
    ww: {
      B: 'AES wireless encryption (WPA2/3) is unrelated to iSCSI.',
      C: 'iSCSI runs over IP networks, which require cabling/infrastructure.',
      D: 'iSCSI is not limited to a single VLAN.',
    },
    er: 'Tests the converged (storage + IP) nature of iSCSI.',
  },
  {
    t: 'Communications', s: 'Covert channels', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Networking Concepts > Multilayer Protocols',
    q: 'An attacker hides data exfiltration inside the unused fields and timing of an otherwise legitimate protocol so it blends with normal traffic. This abuse of encapsulation is known as:',
    o: ['A covert channel (storage or timing)', 'A broadcast storm', 'A three-way handshake', 'A default route'],
    a: 'A',
    wc: 'Covert channels (storage- or timing-based) abuse encapsulation/protocol features to hide unauthorized communication within legitimate-looking traffic, often bypassing detection.',
    ww: {
      B: 'A broadcast storm is excessive broadcast traffic, not hidden exfiltration.',
      C: 'A three-way handshake establishes a TCP connection.',
      D: 'A default route is a routing configuration, not a hidden channel.',
    },
    er: 'Maps hidden protocol-based exfiltration to covert channels.',
  },
  {
    t: 'IP Addressing', s: 'Loopback', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > IP Networking',
    q: 'The IPv4 address 127.0.0.1 is commonly used as the:',
    o: ['Loopback (localhost) address for testing the local TCP/IP stack', 'Default gateway for all networks', 'Broadcast address of every subnet', 'Standard public DNS server'],
    a: 'A',
    wc: '127.0.0.1 is the loopback/localhost address used to test the local TCP/IP stack on the host itself.',
    ww: {
      B: 'The default gateway is a router interface address, not loopback.',
      C: 'A broadcast address is the highest address in a subnet, not 127.0.0.1.',
      D: '127.0.0.1 is internal to the host, not a public DNS server.',
    },
    er: 'Recall of the loopback address.',
  },
  {
    t: 'TCP/IP', s: 'Encapsulation concept', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Encapsulation Process',
    q: 'During encapsulation, what happens to data as it moves down the OSI stack?',
    o: [
      'Each layer adds its own header (and sometimes trailer) information',
      'Each layer removes a header to expose the payload',
      'The data is encrypted at every layer automatically',
      'The data is converted to a single packet with no changes',
    ],
    a: 'A',
    wc: 'Encapsulation adds headers (and trailers) at each descending layer, forming segments, packets, frames, and finally bits; the reverse (de-encapsulation) strips them on receipt.',
    ww: {
      B: 'Removing headers is de-encapsulation, which occurs on the receiving side moving up the stack.',
      C: 'Encapsulation itself does not automatically encrypt at every layer.',
      D: 'The data changes form (segment/packet/frame/bits) as headers are added.',
    },
    er: 'Tests the header-adding nature of encapsulation.',
  },
];
