// Domain 4 — Part 4: Network attacks (reconnaissance, spoofing/poisoning, DoS)
// and wireless security (modes, SSID, WEP/WPA/WPA2/WPA3, wireless attacks,
// Bluetooth, MDM).
module.exports = [
  // ---- Reconnaissance ----
  {
    t: 'Reconnaissance Attacks', s: 'Passive vs active', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Reconnaissance Attacks',
    q: 'Gathering information about a target using publicly available sources (OSINT) without directly interacting with the target systems is:',
    o: ['Passive reconnaissance', 'Active reconnaissance', 'A denial-of-service attack', 'ARP poisoning'],
    a: 'A',
    wc: 'Passive reconnaissance collects information from public sources (OSINT) without touching the target, making it harder to detect.',
    ww: {
      B: 'Active reconnaissance directly probes the target (e.g., port scanning), which can be detected.',
      C: 'A DoS attack disrupts availability, not information gathering.',
      D: 'ARP poisoning is a spoofing attack, not reconnaissance via OSINT.',
    },
    er: 'Distinguishes passive (OSINT) from active reconnaissance.',
  },
  {
    t: 'Reconnaissance Attacks', s: 'Active recon', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Reconnaissance Attacks',
    q: 'An attacker runs a port scan against a company\'s public IP range to find open services. This activity is BEST classified as:',
    o: ['Active reconnaissance', 'Passive reconnaissance', 'A teardrop attack', 'A replay attack'],
    a: 'A',
    wc: 'Port scanning directly interacts with the target to enumerate open services, which is active reconnaissance (and is detectable by monitoring).',
    ww: {
      B: 'Passive recon uses public sources without touching the target; scanning is direct interaction.',
      C: 'A teardrop attack sends overlapping fragments to crash a host, not enumerate services.',
      D: 'A replay attack reuses captured messages, not scanning.',
    },
    er: 'Maps port scanning to active reconnaissance.',
  },
  {
    t: 'Reconnaissance Attacks', s: 'Recon types', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Security and Attacks > Reconnaissance Attacks',
    q: 'Which TWO activities are forms of reconnaissance? (Select TWO.)',
    o: ['Open-source intelligence (OSINT) gathering', 'Port and service scanning', 'Reinstalling encryption keys', 'Flooding a server with traffic'],
    a: ['A', 'B'],
    wc: 'OSINT gathering (passive) and port/service scanning (active) are reconnaissance activities used to profile a target.',
    ww: {
      C: 'Reinstalling encryption keys describes a KRACK attack, not reconnaissance.',
      D: 'Flooding a server is a denial-of-service attack.',
    },
    er: 'Identifies passive and active reconnaissance forms.',
  },
  // ---- Spoofing / poisoning ----
  {
    t: 'Spoofing and Poisoning', s: 'ARP poisoning', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Key Attack Methods',
    q: 'On a LAN, an attacker sends forged ARP replies so that traffic destined for the gateway is instead sent to the attacker\'s machine, enabling interception. This attack is:',
    o: ['ARP spoofing/poisoning (enabling a man-in-the-middle)', 'DNS poisoning', 'A Smurf attack', 'War driving'],
    a: 'A',
    wc: 'ARP poisoning sends forged ARP replies that map the gateway\'s IP to the attacker\'s MAC, letting the attacker intercept traffic (man-in-the-middle) on the local segment.',
    ww: {
      B: 'DNS poisoning corrupts name resolution, not ARP/MAC mappings on the LAN.',
      C: 'A Smurf attack is an ICMP amplification DoS, not interception.',
      D: 'War driving is searching for wireless networks while moving.',
    },
    er: 'Maps forged-ARP interception to ARP poisoning/MITM.',
  },
  {
    t: 'Spoofing and Poisoning', s: 'DNS poisoning', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Key Attack Methods',
    q: 'An attacker alters DNS records so users typing a legitimate bank URL are redirected to a malicious look-alike site. This is DNS poisoning, and the BEST defense is:',
    o: [
      'DNSSEC, which authenticates DNS responses',
      'Disabling all logging',
      'Using a hub instead of a switch',
      'Lengthening the office fence',
    ],
    a: 'A',
    wc: 'DNS poisoning redirects traffic via forged DNS data; DNSSEC adds cryptographic authentication of DNS responses to detect/prevent tampering.',
    ww: {
      B: 'Disabling logging reduces visibility and does not defend DNS integrity.',
      C: 'A hub worsens security and does not protect DNS.',
      D: 'A taller fence is a physical control unrelated to DNS poisoning.',
    },
    er: 'Maps DNS poisoning defense to DNSSEC.',
  },
  {
    t: 'Spoofing and Poisoning', s: 'IP spoofing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Key Attack Methods',
    q: 'IP spoofing involves:',
    o: [
      'Forging the source IP address in packet headers to appear as a trusted source',
      'Changing a device\'s MAC address to bypass filtering',
      'Redirecting DNS lookups to malicious servers',
      'Flooding a target with ICMP echo replies',
    ],
    a: 'A',
    wc: 'IP spoofing manipulates the source IP in packet headers to impersonate a trusted host and bypass IP-based controls.',
    ww: {
      B: 'Changing a MAC address is MAC spoofing.',
      C: 'Redirecting DNS lookups is DNS spoofing/poisoning.',
      D: 'Flooding with ICMP replies relates to a Smurf/amplification DoS.',
    },
    er: 'Distinguishes IP spoofing from MAC/DNS spoofing.',
  },
  {
    t: 'Spoofing and Poisoning', s: 'MAC spoofing defense', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Defensive Measures',
    q: 'Which control helps defend against MAC spoofing at the data link layer by restricting which devices may use a switch port?',
    o: ['Port security / MAC filtering', 'DNSSEC', 'A backup generator', 'A wet-pipe sprinkler'],
    a: 'A',
    wc: 'Port security/MAC filtering restricts switch ports to authorized MAC addresses, reducing the risk of spoofing at Layer 2.',
    ww: {
      B: 'DNSSEC protects DNS responses, not switch-port MAC access.',
      C: 'A generator provides power, not MAC access control.',
      D: 'A sprinkler is a fire-suppression control.',
    },
    er: 'Maps Layer 2 spoofing defense to port security/MAC filtering.',
  },
  {
    t: 'Spoofing and Poisoning', s: 'Spoofing types', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Security and Attacks > Key Attack Methods',
    q: 'Which TWO of the following are spoofing/poisoning attacks? (Select TWO.)',
    o: ['ARP poisoning', 'DNS spoofing', 'Teardrop attack', 'War chalking'],
    a: ['A', 'B'],
    wc: 'ARP poisoning and DNS spoofing falsify mappings/records to redirect or intercept traffic.',
    ww: {
      C: 'A teardrop attack is a DoS using overlapping fragments, not spoofing.',
      D: 'War chalking is marking locations of wireless networks, not spoofing.',
    },
    er: 'Identifies spoofing/poisoning attacks.',
  },
  // ---- DoS ----
  {
    t: 'Denial of Service', s: 'Smurf attack', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Reflection and Amplification Attacks',
    q: 'A Smurf attack amplifies traffic against a victim by:',
    o: [
      'Spoofing the victim\'s IP and broadcasting ICMP echo requests so many hosts reply to the victim',
      'Sending oversized packets that exceed the MTU',
      'Reinstalling WPA2 encryption keys',
      'Marking sidewalks with network symbols',
    ],
    a: 'A',
    wc: 'A Smurf attack spoofs the victim\'s source IP and sends ICMP echo requests to a broadcast address; all responders flood the victim with replies (amplification).',
    ww: {
      B: 'Oversized packets exceeding MTU describe a Ping of Death.',
      C: 'Reinstalling WPA2 keys describes KRACK.',
      D: 'Marking locations is war chalking.',
    },
    er: 'Maps ICMP broadcast amplification to the Smurf attack.',
  },
  {
    t: 'Denial of Service', s: 'Fraggle attack', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Reflection and Amplification Attacks',
    q: 'A Fraggle attack is similar to a Smurf attack but uses which protocol for its echo flood?',
    o: ['UDP', 'ICMP', 'TCP', 'ARP'],
    a: 'A',
    wc: 'A Fraggle attack is the UDP-echo analog of the Smurf attack (which uses ICMP echo).',
    ww: {
      B: 'ICMP echo is used by the Smurf attack.',
      C: 'TCP is not the protocol used in a Fraggle attack.',
      D: 'ARP is not used for the Fraggle echo flood.',
    },
    er: 'Distinguishes Fraggle (UDP) from Smurf (ICMP).',
  },
  {
    t: 'Denial of Service', s: 'Ping of Death', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Legacy Attacks',
    q: 'A Ping of Death attack crashes vulnerable systems by:',
    o: [
      'Sending malformed or oversized packets that exceed the maximum allowed size (MTU)',
      'Spoofing ARP replies on the LAN',
      'Cracking WPA2 handshakes',
      'Forging DNS records',
    ],
    a: 'A',
    wc: 'A Ping of Death sends oversized/malformed packets exceeding the MTU that some systems mishandle, causing crashes.',
    ww: {
      B: 'Forging ARP replies is ARP poisoning.',
      C: 'Cracking WPA2 handshakes relates to KRACK/wireless attacks.',
      D: 'Forging DNS records is DNS poisoning.',
    },
    er: 'Maps oversized-packet crashes to Ping of Death.',
  },
  {
    t: 'Denial of Service', s: 'Land attack', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Legacy Attacks',
    q: 'A Land attack causes a target to malfunction by sending SYN packets where:',
    o: [
      'The source and destination IP are both set to the target\'s own address',
      'The payload is encrypted with the target\'s public key',
      'The DNS record points to a malicious site',
      'The ARP table is flooded with random MACs',
    ],
    a: 'A',
    wc: 'A Land attack spoofs SYN packets with the target\'s own IP as both source and destination, causing the machine to attempt to connect to itself and hang/crash.',
    ww: {
      B: 'Encryption with a public key is not how a Land attack works.',
      C: 'Pointing DNS to a malicious site is DNS poisoning.',
      D: 'Flooding the ARP table is a different (CAM/ARP) attack.',
    },
    er: 'Maps the self-addressed SYN to a Land attack.',
  },
  {
    t: 'Denial of Service', s: 'Teardrop attack', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Legacy Attacks',
    q: 'A Teardrop attack crashes a system by sending:',
    o: [
      'Fragmented packets with overlapping payloads that fail during reassembly',
      'A single oversized ping packet',
      'Forged ARP replies',
      'Unsolicited Bluetooth messages',
    ],
    a: 'A',
    wc: 'A Teardrop attack sends overlapping/malformed IP fragments that crash systems unable to correctly reassemble them.',
    ww: {
      B: 'A single oversized ping is the Ping of Death.',
      C: 'Forged ARP replies are ARP poisoning.',
      D: 'Unsolicited Bluetooth messages are bluejacking.',
    },
    er: 'Maps overlapping-fragment crashes to Teardrop.',
  },
  {
    t: 'Denial of Service', s: 'DoS vs DDoS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Denial of Service Attacks',
    q: 'A Distributed Denial of Service (DDoS) attack differs from a basic DoS attack in that a DDoS:',
    o: [
      'Uses many compromised systems (a botnet) to flood the target simultaneously',
      'Always targets only wireless networks',
      'Encrypts the victim\'s files for ransom',
      'Relies on a single host with a slow connection',
    ],
    a: 'A',
    wc: 'A DDoS leverages many distributed, often compromised hosts (a botnet) to overwhelm the target, making it harder to block than a single-source DoS.',
    ww: {
      B: 'DDoS can target any network service, not only wireless.',
      C: 'Encrypting files for ransom is ransomware, not DDoS.',
      D: 'A single slow host describes a limited DoS, not a distributed attack.',
    },
    er: 'Distinguishes distributed (botnet) DDoS from single-source DoS.',
  },
  {
    t: 'Denial of Service', s: 'DoS protection', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Security and Attacks > Protection Strategies',
    q: 'Which TWO strategies help mitigate denial-of-service attacks? (Select TWO.)',
    o: ['Rate limiting and traffic analysis', 'Load balancing and network redundancy', 'Disabling all firewalls', 'Sharing admin passwords widely'],
    a: ['A', 'B'],
    wc: 'Rate limiting/traffic analysis and load balancing/redundancy help absorb and detect DoS traffic, reducing impact on any single point.',
    ww: {
      C: 'Disabling firewalls removes a key filtering defense.',
      D: 'Sharing admin passwords harms security and does not mitigate DoS.',
    },
    er: 'Identifies sound DoS mitigations.',
  },
  {
    t: 'Network Attacks', s: 'Attack-to-description mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 4 > Network Security and Attacks > Legacy Attacks',
    p: ['Smurf attack', 'Land attack', 'ARP poisoning', 'DNS poisoning'],
    q: 'Match each network attack (1-4) to its description (A-D).',
    o: [
      'Forges ARP replies to intercept LAN traffic (MITM)',
      'Spoofs the victim IP and floods it via ICMP broadcast replies',
      'Alters DNS records to redirect users to malicious sites',
      'Sends SYN packets with the target\'s IP as both source and destination',
    ],
    a: '1-B,2-D,3-A,4-C',
    wc: 'Smurf → ICMP broadcast amplification (B); Land → self-addressed SYN (D); ARP poisoning → forged ARP/MITM (A); DNS poisoning → altered DNS records (C).',
    ww: {},
    er: 'Tests mapping of network attacks to their mechanisms.',
  },
  // ---- Wireless ----
  {
    t: 'Wireless Security', s: 'WEP weakness', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Encryption Protocols',
    q: 'Wired Equivalent Privacy (WEP) is considered insecure largely because it:',
    o: [
      'Uses the weak RC4 cipher with flawed key handling',
      'Uses 256-bit AES with strong key management',
      'Requires multi-factor authentication for every packet',
      'Cannot be used on any wireless network',
    ],
    a: 'A',
    wc: 'WEP relies on the RC4 stream cipher with weak IV/key handling, making it easily cracked; it should be replaced by WPA2/WPA3.',
    ww: {
      B: 'WEP does not use AES; that describes WPA2/WPA3.',
      C: 'WEP does not use per-packet MFA.',
      D: 'WEP can technically run on wireless networks but is insecure.',
    },
    er: 'Maps WEP weakness to RC4/key handling.',
  },
  {
    t: 'Wireless Security', s: 'WPA2', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Encryption Protocols',
    q: 'WPA2 improved wireless security over WPA primarily by introducing:',
    o: [
      'CCMP with AES encryption',
      'The RC4 stream cipher',
      'Cleartext transmission',
      'WPS PIN-only authentication',
    ],
    a: 'A',
    wc: 'WPA2 uses CCMP (based on AES), providing stronger encryption than WPA\'s TKIP and WEP\'s RC4.',
    ww: {
      B: 'RC4 is the weak cipher used by WEP.',
      C: 'WPA2 encrypts traffic; it is not cleartext.',
      D: 'WPS is a convenience feature with security weaknesses, not WPA2\'s core improvement.',
    },
    er: 'Maps WPA2 to CCMP/AES.',
  },
  {
    t: 'Wireless Security', s: 'WPA3', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Encryption Protocols',
    q: 'WPA3 strengthens key exchange against offline password-guessing attacks by using:',
    o: [
      'Simultaneous Authentication of Equals (SAE)',
      'The RC4 cipher',
      'WEP-style shared keys',
      'Cleartext PSK exchange',
    ],
    a: 'A',
    wc: 'WPA3 introduces SAE (Simultaneous Authentication of Equals) for a more secure handshake that resists offline dictionary attacks, plus stronger AES key sizes.',
    ww: {
      B: 'RC4 is the weak WEP cipher.',
      C: 'WEP shared keys are insecure and not used by WPA3.',
      D: 'WPA3 does not exchange the PSK in cleartext.',
    },
    er: 'Maps WPA3 secure key exchange to SAE.',
  },
  {
    t: 'Wireless Security', s: 'Encryption protocol order', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Wireless Networking Introduction > Encryption Protocols',
    q: 'Which TWO wireless security protocols are considered STRONG/current choices (versus deprecated ones)? (Select TWO.)',
    o: ['WPA2', 'WPA3', 'WEP', 'Open (no encryption)'],
    a: ['A', 'B'],
    wc: 'WPA2 (CCMP/AES) and WPA3 (SAE/AES) are the strong, current choices; WEP and open networks are insecure/deprecated.',
    ww: {
      C: 'WEP is deprecated and easily broken.',
      D: 'An open network provides no encryption.',
    },
    er: 'Separates strong wireless encryption from deprecated options.',
  },
  {
    t: 'Wireless Security', s: 'WPS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Wi-Fi Protected Setup (WPS)',
    q: 'Why is Wi-Fi Protected Setup (WPS) generally NOT recommended?',
    o: [
      'Its PIN-based setup is vulnerable to brute-force attacks',
      'It uses 256-bit AES that is too strong to manage',
      'It requires fiber-optic cabling',
      'It only works on wired networks',
    ],
    a: 'A',
    wc: 'WPS uses short PINs that are susceptible to brute-force attacks, so it is discouraged despite its convenience.',
    ww: {
      B: 'WPS is weak, not too strong.',
      C: 'WPS is a wireless feature unrelated to fiber cabling.',
      D: 'WPS is for wireless setup, not wired networks.',
    },
    er: 'Tests the WPS PIN brute-force weakness.',
  },
  {
    t: 'Wireless Attacks', s: 'Evil twin', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'At an airport, an attacker sets up a rogue access point named "Airport_Free_WiFi" that mimics the legitimate network to capture victims\' credentials. This is BEST described as:',
    o: ['An evil twin attack', 'War chalking', 'A teardrop attack', 'A Smurf attack'],
    a: 'A',
    wc: 'An evil twin is a fake access point impersonating a legitimate SSID to lure users and capture their credentials/traffic.',
    ww: {
      B: 'War chalking marks the locations of wireless networks.',
      C: 'A teardrop attack is a fragmentation DoS.',
      D: 'A Smurf attack is an ICMP amplification DoS.',
    },
    er: 'Maps a credential-capturing impostor AP to an evil twin.',
  },
  {
    t: 'Wireless Attacks', s: 'Rogue AP', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'An employee plugs an unauthorized wireless access point into the corporate LAN to get better Wi-Fi at their desk. The security concern is that this is a:',
    o: [
      'Rogue access point that bypasses network security controls',
      'Legitimate redundancy improvement',
      'Form of DNSSEC',
      'A required part of 802.1X',
    ],
    a: 'A',
    wc: 'A rogue access point is an unauthorized AP connected to the network that bypasses security controls and creates an uncontrolled entry point.',
    ww: {
      B: 'Unauthorized APs are a security risk, not sanctioned redundancy.',
      C: 'DNSSEC authenticates DNS responses; it is unrelated.',
      D: '802.1X is port-based access control, not an unauthorized AP.',
    },
    er: 'Maps an unauthorized AP to a rogue access point.',
  },
  {
    t: 'Wireless Attacks', s: 'KRACK', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'A Key Reinstallation Attack (KRACK) exploits a weakness in:',
    o: [
      'The WPA2 four-way handshake, forcing reuse of encryption keys',
      'The DNS resolution process',
      'The ARP cache on a switch',
      'The TCP three-way handshake',
    ],
    a: 'A',
    wc: 'KRACK manipulates the WPA2 four-way handshake to force nonce/key reinstallation, enabling decryption/replay of wireless traffic.',
    ww: {
      B: 'DNS resolution is targeted by DNS poisoning, not KRACK.',
      C: 'ARP cache manipulation is ARP poisoning.',
      D: 'The TCP handshake is unrelated to WPA2 key reinstallation.',
    },
    er: 'Maps KRACK to the WPA2 handshake.',
  },
  {
    t: 'Wireless Attacks', s: 'War driving', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'Driving around an area with a device to locate and identify vulnerable wireless networks is called:',
    o: ['War driving', 'War chalking', 'Bluejacking', 'Bluesnarfing'],
    a: 'A',
    wc: 'War driving is moving through an area to discover and map wireless networks (often to find vulnerable ones).',
    ww: {
      B: 'War chalking marks the discovered networks\' locations.',
      C: 'Bluejacking sends unsolicited Bluetooth messages.',
      D: 'Bluesnarfing steals data over Bluetooth.',
    },
    er: 'Recall of war driving.',
  },
  {
    t: 'Wireless Attacks', s: 'War chalking', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'Marking physical locations with symbols to indicate the presence of open or vulnerable wireless networks is:',
    o: ['War chalking', 'War driving', 'Signal jamming', 'An evil twin'],
    a: 'A',
    wc: 'War chalking uses symbols/markings to advertise the location and characteristics of nearby wireless networks for others to exploit.',
    ww: {
      B: 'War driving is the act of moving around to find networks.',
      C: 'Signal jamming is a wireless DoS.',
      D: 'An evil twin is an impostor access point.',
    },
    er: 'Recall of war chalking.',
  },
  {
    t: 'Wireless Attacks', s: 'Signal jamming', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'Wireless signal jamming is a form of which attack category?',
    o: ['Denial of service (DoS)', 'Spoofing', 'Reconnaissance', 'Privilege escalation'],
    a: 'A',
    wc: 'Signal jamming floods the radio frequency to disrupt wireless communications—a denial-of-service attack on availability.',
    ww: {
      B: 'Spoofing falsifies identity/records, not RF disruption.',
      C: 'Reconnaissance gathers information rather than disrupting service.',
      D: 'Privilege escalation gains higher access, not RF disruption.',
    },
    er: 'Classifies jamming as a wireless DoS.',
  },
  {
    t: 'Bluetooth Security', s: 'Bluesnarfing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Bluetooth Security Threats',
    q: 'Forcing a Bluetooth connection to access and steal stored data from a device is known as:',
    o: ['Bluesnarfing', 'Bluejacking', 'Bluebugging', 'War driving'],
    a: 'A',
    wc: 'Bluesnarfing forces a Bluetooth connection to access/steal data stored on the target device.',
    ww: {
      B: 'Bluejacking sends unsolicited messages, not data theft.',
      C: 'Bluebugging takes control of the device to execute commands.',
      D: 'War driving is wireless-network discovery.',
    },
    er: 'Distinguishes bluesnarfing (data theft) from other Bluetooth attacks.',
  },
  {
    t: 'Bluetooth Security', s: 'Bluebugging', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Bluetooth Security Threats',
    q: 'Gaining control of a device over Bluetooth to execute commands without the user\'s knowledge is:',
    o: ['Bluebugging', 'Bluejacking', 'Bluesnarfing', 'War chalking'],
    a: 'A',
    wc: 'Bluebugging gives an attacker control of a device to execute commands covertly over Bluetooth.',
    ww: {
      B: 'Bluejacking only sends unsolicited messages.',
      C: 'Bluesnarfing steals stored data but does not necessarily control the device.',
      D: 'War chalking marks wireless network locations.',
    },
    er: 'Maps covert device control to bluebugging.',
  },
  {
    t: 'Bluetooth Security', s: 'Bluetooth attacks', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Wireless Networking Introduction > Bluetooth Security Threats',
    q: 'Which TWO are Bluetooth-specific security threats? (Select TWO.)',
    o: ['Bluejacking', 'Bluesnarfing', 'Smurf attack', 'DNS poisoning'],
    a: ['A', 'B'],
    wc: 'Bluejacking (unsolicited messages) and bluesnarfing (data theft) are Bluetooth-specific attacks.',
    ww: {
      C: 'A Smurf attack is an ICMP amplification DoS on IP networks.',
      D: 'DNS poisoning targets name resolution, not Bluetooth.',
    },
    er: 'Identifies Bluetooth-specific attacks.',
  },
  {
    t: 'Wireless Concepts', s: 'SSID types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Service Set Identifiers (SSID)',
    q: 'The BSSID in a wireless network refers to:',
    o: [
      'The MAC address of a specific access point',
      'The human-readable network name only',
      'The encryption key used by clients',
      'The IP address of the default gateway',
    ],
    a: 'A',
    wc: 'The BSSID (Basic SSID) is the MAC address of a specific access point; the ESSID is the network name shared across multiple APs.',
    ww: {
      B: 'The network name is the SSID/ESSID, not the BSSID.',
      C: 'The encryption key is separate from the BSSID.',
      D: 'The gateway IP is unrelated to the BSSID.',
    },
    er: 'Distinguishes BSSID (AP MAC) from ESSID (network name).',
  },
  {
    t: 'Wireless Concepts', s: 'Wireless modes', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Wireless Network Modes',
    q: 'In wireless infrastructure mode, client devices communicate:',
    o: [
      'Through a central access point rather than directly peer-to-peer',
      'Only directly device-to-device with no access point',
      'Exclusively over fiber-optic cable',
      'Without any radio frequencies',
    ],
    a: 'A',
    wc: 'Infrastructure mode routes client traffic through a central access point; ad-hoc mode is the peer-to-peer alternative with no AP.',
    ww: {
      B: 'Direct device-to-device with no AP describes ad-hoc mode.',
      C: 'Wireless uses radio, not fiber cabling.',
      D: 'Wireless inherently uses radio frequencies.',
    },
    er: 'Distinguishes infrastructure (AP-based) from ad-hoc mode.',
  },
  {
    t: 'Mobile Device Management', s: 'Remote wipe', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Wireless Networking Introduction > Mobile Device Management Controls',
    q: 'An employee\'s smartphone containing corporate data is lost. Which MDM control BEST protects the data on that device?',
    o: [
      'Remote device sanitization (remote wipe), ideally combined with device encryption',
      'Disabling the company VPN for everyone',
      'Increasing the office Wi-Fi signal strength',
      'Removing the screen lock to ease recovery',
    ],
    a: 'A',
    wc: 'MDM remote wipe lets administrators sanitize a lost/stolen device remotely; with data-at-rest encryption, the data is protected even before the wipe completes.',
    ww: {
      B: 'Disabling the VPN does not protect data already on the lost device.',
      C: 'Wi-Fi signal strength is irrelevant to protecting a lost device.',
      D: 'Removing the screen lock weakens protection of the device.',
    },
    er: 'Maps protecting a lost device to MDM remote wipe + encryption.',
  },
  {
    t: 'Mobile Device Management', s: 'Geofencing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Mobile Device Management Controls',
    q: 'An MDM "geofencing" control enforces security policies based on:',
    o: [
      'The physical location of the device',
      'The color of the device case',
      'The number of installed apps',
      'The brand of the device charger',
    ],
    a: 'A',
    wc: 'Geofencing applies location-based access and permissions, e.g., restricting features when a device leaves an approved area.',
    ww: {
      B: 'Case color is irrelevant to geofencing.',
      C: 'App count is not the basis of geofencing.',
      D: 'Charger brand is irrelevant.',
    },
    er: 'Maps location-based MDM policy to geofencing.',
  },
  {
    t: 'Mobile Device Management', s: 'MDM controls', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Wireless Networking Introduction > Mobile Device Management Controls',
    q: 'Which TWO are MDM controls that protect enterprise mobile devices? (Select TWO.)',
    o: ['Enforcing encryption for data at rest', 'Configuring inactivity/session timeouts', 'Disabling all device passcodes', 'Allowing untrusted app installation'],
    a: ['A', 'B'],
    wc: 'Encryption of data at rest and inactivity/session timeouts are MDM controls that reduce data exposure on mobile devices.',
    ww: {
      C: 'Disabling passcodes weakens device security.',
      D: 'Allowing untrusted apps increases malware risk.',
    },
    er: 'Identifies protective MDM controls.',
  },
  {
    t: 'Wireless Security', s: 'General Wi-Fi hardening', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Wireless Networking Introduction > General Wi-Fi Security Measures',
    q: 'Which is a recommended general measure to harden a wireless network?',
    o: [
      'Change default passwords/SSIDs and use WPA2 or WPA3 encryption',
      'Leave the network open to maximize compatibility',
      'Keep the factory default admin password',
      'Broadcast the admin credentials in the SSID',
    ],
    a: 'A',
    wc: 'Changing default credentials/SSIDs and using strong encryption (WPA2/WPA3) are core wireless hardening steps, ideally with a defense-in-depth approach.',
    ww: {
      B: 'An open network exposes traffic to anyone in range.',
      C: 'Default admin passwords are widely known and easily abused.',
      D: 'Broadcasting credentials in the SSID exposes them to attackers.',
    },
    er: 'Identifies sound wireless hardening practices.',
  },
  {
    t: 'Wireless Attacks', s: 'Evil twin vs rogue AP', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Key Wireless Network Attacks',
    q: 'What primarily distinguishes an evil twin from a generic rogue access point?',
    o: [
      'An evil twin deliberately impersonates a legitimate SSID to deceive users into connecting',
      'An evil twin is always authorized by IT',
      'A rogue AP always uses WPA3 encryption',
      'An evil twin only affects wired networks',
    ],
    a: 'A',
    wc: 'An evil twin is a rogue AP specifically configured to mimic a legitimate network\'s SSID to trick users; a generic rogue AP is simply an unauthorized AP, not necessarily impersonating one.',
    ww: {
      B: 'An evil twin is malicious and unauthorized, not IT-sanctioned.',
      C: 'A rogue AP\'s encryption is attacker-chosen and often weak/open, not guaranteed WPA3.',
      D: 'Evil twins target wireless clients, not wired-only networks.',
    },
    er: 'Tests the impersonation distinction of an evil twin.',
  },
  {
    t: 'Wireless Concepts', s: 'OFDM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Wireless Networking Introduction > Orthogonal Frequency Division Multiplexing (OFDM)',
    q: 'Orthogonal Frequency Division Multiplexing (OFDM) improves wireless throughput by:',
    o: [
      'Dividing data into multiple substreams sent over separate subchannels',
      'Sending all data on a single narrow frequency',
      'Encrypting frames with RC4',
      'Eliminating the need for any access point',
    ],
    a: 'A',
    wc: 'OFDM splits data into multiple substreams across separate orthogonal subchannels, increasing throughput and resilience to interference.',
    ww: {
      B: 'OFDM uses multiple subchannels, not a single narrow frequency.',
      C: 'OFDM is a modulation/multiplexing method, not an encryption cipher.',
      D: 'OFDM does not remove the need for an access point.',
    },
    er: 'Recall of OFDM multi-subchannel operation.',
  },
];
