// Domain 4 — Part 1: Network components/hardware (by OSI layer), infrastructure
// operations (UPS/generators/EOS), transmission media, topologies, network
// types, and network monitoring.
module.exports = [
  // ---- Network devices by layer ----
  {
    t: 'Network Components', s: 'Switch', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A network switch primarily forwards frames to the correct port based on:',
    o: ['The destination MAC address (Layer 2)', 'The destination IP subnet only', 'The application port number only', 'The cable color'],
    a: 'A',
    wc: 'A switch operates at Layer 2, directing frames to the appropriate port based on destination MAC address (multilayer switches can also do Layer 3).',
    ww: {
      B: 'Routing by IP subnet is a Layer 3 router function (though multilayer switches can also route).',
      C: 'Port-number filtering is a transport/application-layer firewall function.',
      D: 'Cable color is irrelevant to switching decisions.',
    },
    er: 'Maps MAC-based frame forwarding to a Layer 2 switch.',
  },
  {
    t: 'Network Components', s: 'Router', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A router operates primarily at which OSI layer to forward packets between networks?',
    o: ['Layer 3 (Network)', 'Layer 1 (Physical)', 'Layer 2 (Data Link)', 'Layer 7 (Application)'],
    a: 'A',
    wc: 'A router operates at Layer 3, using a route table/policies to forward packets between different networks based on IP addresses.',
    ww: {
      B: 'Layer 1 devices (repeaters/hubs) deal with raw bits/signals.',
      C: 'Layer 2 devices (switches/bridges) forward by MAC address.',
      D: 'Layer 7 is the application layer, not routing.',
    },
    er: 'Maps IP packet forwarding to a Layer 3 router.',
  },
  {
    t: 'Network Components', s: 'Hub vs switch', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'Why is a switch generally more secure and efficient than a hub?',
    o: [
      'A switch forwards frames only to the destination port, while a hub repeats traffic to all ports',
      'A switch encrypts all traffic while a hub does not',
      'A hub operates at Layer 3 while a switch operates at Layer 1',
      'A hub performs deep packet inspection',
    ],
    a: 'A',
    wc: 'A switch directs frames only to the intended port (reducing exposure and collisions), whereas a hub repeats incoming signals out all ports.',
    ww: {
      B: 'Neither device encrypts traffic by default.',
      C: 'A hub is a Layer 1 device and a switch is Layer 2 (this is reversed).',
      D: 'Deep packet inspection is an NGFW capability, not a hub function.',
    },
    er: 'Contrasts selective switch forwarding with hub flooding.',
  },
  {
    t: 'Network Components', s: 'Gateway', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'Which device connects network segments that use DIFFERENT protocols, translating between them?',
    o: ['Gateway', 'Repeater', 'Hub', 'Bridge'],
    a: 'A',
    wc: 'A gateway connects networks using different protocols, performing translation between them.',
    ww: {
      B: 'A repeater regenerates signals on the same medium (Layer 1).',
      C: 'A hub repeats signals to all ports (Layer 1).',
      D: 'A bridge connects two segments using the SAME protocol (Layer 2).',
    },
    er: 'Maps protocol translation to a gateway.',
  },
  {
    t: 'Network Components', s: 'Brouter', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A "brouter" is best described as a device that:',
    o: [
      'Combines bridge and router functions—routing at Layer 3 when possible, otherwise bridging at Layer 2',
      'Only repeats electrical signals at Layer 1',
      'Encrypts all traffic at the application layer',
      'Assigns IP addresses dynamically to hosts',
    ],
    a: 'A',
    wc: 'A brouter combines a bridge and a router, routing using Layer 3 when possible and defaulting to Layer 2 bridging otherwise.',
    ww: {
      B: 'Signal repetition at Layer 1 describes a repeater.',
      C: 'Application-layer encryption is unrelated to a brouter.',
      D: 'Dynamic IP assignment is DHCP\'s function.',
    },
    er: 'Recall of the brouter\'s combined bridge/router behavior.',
  },
  {
    t: 'Network Components', s: 'Repeater', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A repeater is a Layer 1 device whose primary purpose is to:',
    o: ['Regenerate and extend a signal to overcome distance/attenuation', 'Route packets between subnets', 'Filter traffic by application content', 'Translate between different protocols'],
    a: 'A',
    wc: 'A repeater regenerates/amplifies signals at the physical layer to extend transmission distance.',
    ww: {
      B: 'Routing between subnets is a Layer 3 router function.',
      C: 'Application-content filtering is an application-layer proxy/NGFW function.',
      D: 'Protocol translation is a gateway function.',
    },
    er: 'Maps signal regeneration to a Layer 1 repeater.',
  },
  {
    t: 'Network Components', s: 'Device-to-layer mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    p: ['Hub/Repeater', 'Switch/Bridge', 'Router', 'Application-level proxy'],
    q: 'Match each network device (1-4) to the OSI layer at which it primarily operates (A-D).',
    o: [
      'Layer 2 (Data Link)',
      'Layer 1 (Physical)',
      'Layer 7 (Application)',
      'Layer 3 (Network)',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Hub/Repeater → Layer 1 (B); Switch/Bridge → Layer 2 (A); Router → Layer 3 (D); Application-level proxy → Layer 7 (C).',
    ww: {},
    er: 'Tests mapping of devices to their OSI layers.',
  },
  {
    t: 'Network Components', s: 'Proxy', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A proxy that makes requests to the internet on behalf of internal clients primarily helps security by:',
    o: [
      'Hiding internal client details and allowing inspection/filtering of requests',
      'Increasing the broadcast domain size',
      'Encrypting all data at rest',
      'Assigning MAC addresses to hosts',
    ],
    a: 'A',
    wc: 'A proxy acts as an intermediary, concealing internal hosts and enabling content inspection/filtering of outbound/inbound requests.',
    ww: {
      B: 'Proxies do not exist to enlarge broadcast domains.',
      C: 'Data-at-rest encryption is unrelated to a forwarding proxy.',
      D: 'MAC assignment is not a proxy function.',
    },
    er: 'Tests the intermediary/concealment role of a proxy.',
  },
  // ---- Infrastructure operations ----
  {
    t: 'Network Infrastructure', s: 'UPS types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Network Infrastructure Operations',
    q: 'Which UPS type continuously powers equipment from its battery/inverter, providing the cleanest, most consistent power with no transfer time?',
    o: ['Online (double-conversion) UPS', 'Standby (offline) UPS', 'Line-interactive UPS', 'A diesel generator'],
    a: 'A',
    wc: 'An online/double-conversion UPS always powers the load through the battery/inverter, delivering consistent, clean power with effectively no transfer delay.',
    ww: {
      B: 'A standby/offline UPS only switches to battery when power fails, with a brief transfer time.',
      C: 'A line-interactive UPS adds automatic voltage regulation but is not full double-conversion.',
      D: 'A generator provides long-term backup power but is not a UPS and has startup delay.',
    },
    er: 'Distinguishes online (double-conversion) from standby and line-interactive UPS.',
  },
  {
    t: 'Network Infrastructure', s: 'Line-interactive UPS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Network Infrastructure Operations',
    q: 'A line-interactive UPS adds which capability over a basic standby UPS?',
    o: [
      'Automatic Voltage Regulation (AVR) to stabilize power fluctuations',
      'Routing packets between subnets',
      'Deep packet inspection of traffic',
      'Wireless access point functionality',
    ],
    a: 'A',
    wc: 'A line-interactive UPS includes AVR to stabilize voltage fluctuations (sags/surges) without switching to battery.',
    ww: {
      B: 'Routing is a router function.',
      C: 'Deep packet inspection is an NGFW feature.',
      D: 'Wireless access is a WAP function.',
    },
    er: 'Maps AVR to the line-interactive UPS.',
  },
  {
    t: 'Network Infrastructure', s: 'Generators', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Network Components > Network Infrastructure Operations',
    q: 'A data center needs to maintain operations through a multi-hour utility outage. Beyond a UPS, what provides the LONG-TERM backup power, and what does it require?',
    o: [
      'A generator, which requires a steady fuel supply and regular maintenance',
      'A larger broadcast domain, which requires more switches',
      'A line-interactive UPS alone, which needs no fuel',
      'A proxy server, which requires more bandwidth',
    ],
    a: 'A',
    wc: 'A generator provides long-term backup power for extended outages but requires a steady fuel supply and regular maintenance/testing; the UPS bridges the gap until the generator starts.',
    ww: {
      B: 'Broadcast domains are unrelated to power continuity.',
      C: 'A UPS provides only short-duration power and cannot sustain multi-hour outages.',
      D: 'A proxy is a network-traffic intermediary, not a power source.',
    },
    er: 'Pairs long-term outage coverage with generators (UPS bridges short term).',
  },
  {
    t: 'Network Infrastructure', s: 'EOL vs EOS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Network Infrastructure Operations',
    q: 'When a vendor announces End of Service (EOS) for a network appliance, it means:',
    o: [
      'The vendor will no longer provide support and updates for the product',
      'The product instantly stops functioning',
      'The product gains new premium features',
      'The product\'s warranty is automatically extended indefinitely',
    ],
    a: 'A',
    wc: 'End of Service/Support means the vendor terminates support and updates; running such gear risks unpatched vulnerabilities and should be planned for replacement.',
    ww: {
      B: 'The device may still run; the risk is lack of support/patches.',
      C: 'EOS removes support; it does not add features.',
      D: 'EOS typically coincides with the end of warranty/support, not extension.',
    },
    er: 'Recall of EOS as the end of vendor support/updates.',
  },
  // ---- Transmission media ----
  {
    t: 'Transmission Media', s: 'Fiber optic', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Fiber Optic Cabling',
    q: 'A key SECURITY advantage of fiber-optic cabling over copper twisted pair is that fiber:',
    o: [
      'Does not emit electromagnetic signals that can be tapped via emanations and resists EMI',
      'Is always cheaper and easier to install',
      'Automatically encrypts the data it carries',
      'Requires no physical protection at all',
    ],
    a: 'A',
    wc: 'Fiber transmits light through a glass core, producing no electromagnetic emanations to intercept and being immune to EMI—harder to tap passively than copper.',
    ww: {
      B: 'Fiber is typically more expensive and harder to terminate than copper.',
      C: 'Fiber does not encrypt data; it is just a medium.',
      D: 'Fiber still requires physical protection from damage and intrusion.',
    },
    er: 'Tests fiber\'s emanation/EMI security advantage.',
  },
  {
    t: 'Transmission Media', s: 'Plenum cable', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Components > Fiber Optic Cabling',
    q: 'Cabling must be run through a building\'s air-handling (plenum) spaces above the ceiling. Which cable property is MOST important for safety here?',
    o: [
      'Plenum-rated cabling that emits less toxic smoke when burning',
      'The brightest-colored jacket available',
      'The lowest-cost cable regardless of fire rating',
      'A cable with the highest possible bandwidth only',
    ],
    a: 'A',
    wc: 'Plenum spaces circulate air; plenum-rated cable uses fire-resistant jacketing that emits less toxic smoke if it burns, a life-safety requirement.',
    ww: {
      B: 'Jacket color does not affect fire safety in plenum spaces.',
      C: 'Using non-plenum cable in plenum spaces violates fire codes and endangers life.',
      D: 'Bandwidth alone does not address the plenum fire-safety requirement.',
    },
    er: 'Tests plenum-rated cable selection for air-handling spaces.',
  },
  {
    t: 'Transmission Media', s: 'Twisted pair shielding', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Twisted Pair Cables',
    q: 'Shielded Twisted Pair (STP) is preferable to Unshielded Twisted Pair (UTP) primarily in environments with:',
    o: [
      'High electromagnetic interference (EMI)',
      'No power at all',
      'Only wireless devices',
      'Exclusively fiber endpoints',
    ],
    a: 'A',
    wc: 'STP adds shielding to reduce the effects of EMI/crosstalk, making it preferable in electrically noisy environments; UTP is cheaper where EMI is low.',
    ww: {
      B: 'Cabling choice is unrelated to the absence of power.',
      C: 'Wireless devices do not use twisted-pair cabling.',
      D: 'Fiber endpoints would use fiber, not twisted pair.',
    },
    er: 'Maps EMI environments to the value of STP shielding.',
  },
  {
    t: 'Transmission Media', s: 'Network topology', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Transmission Media - Part 1',
    q: 'Which network topology provides the HIGHEST redundancy because every node connects to every other node?',
    o: ['Mesh topology', 'Bus topology', 'Star topology', 'Single point-to-point link'],
    a: 'A',
    wc: 'A (full) mesh topology connects every node to every other node, maximizing redundancy and fault tolerance at higher cost.',
    ww: {
      B: 'A bus topology shares a single backbone—a single break can disrupt the segment.',
      C: 'A star topology depends on a central device whose failure affects all nodes.',
      D: 'A single link offers no redundancy.',
    },
    er: 'Maps full interconnection/redundancy to mesh topology.',
  },
  {
    t: 'Transmission Media', s: 'Star topology', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Components > Transmission Media - Part 1',
    q: 'In a star topology where all hosts connect to a single central switch, what is the PRIMARY availability concern?',
    o: [
      'The central device is a single point of failure for the whole segment',
      'Every host can read every other host\'s traffic by default',
      'Adding a new host requires rewiring all existing hosts',
      'It cannot support more than two devices',
    ],
    a: 'A',
    wc: 'In a star topology, all nodes depend on the central device; its failure takes down the entire segment, making it a single point of failure.',
    ww: {
      B: 'A switch (unlike a hub) does not flood all traffic to every host by default.',
      C: 'Adding a host only requires connecting it to the central device, not rewiring others.',
      D: 'A star can support many devices, limited by the central device\'s capacity.',
    },
    er: 'Tests the single-point-of-failure risk of star topology.',
  },
  {
    t: 'Network Types', s: 'LAN/WAN/MAN/PAN', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Network Types',
    q: 'A network connecting devices across a large geographic area, such as between cities or countries, is a:',
    o: ['Wide Area Network (WAN)', 'Local Area Network (LAN)', 'Personal Area Network (PAN)', 'Metropolitan Area Network (MAN)'],
    a: 'A',
    wc: 'A WAN spans large geographic areas (e.g., between cities/countries), often using carrier links.',
    ww: {
      B: 'A LAN covers a small area like a single building or campus.',
      C: 'A PAN covers a very short range around a person (e.g., Bluetooth).',
      D: 'A MAN spans a city/metropolitan area—larger than a LAN but smaller than a WAN.',
    },
    er: 'Distinguishes WAN from LAN/MAN/PAN by scope.',
  },
  {
    t: 'Network Types', s: 'PAN', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Network Types',
    q: 'Bluetooth connecting a phone to nearby wireless earbuds is an example of a:',
    o: ['Personal Area Network (PAN)', 'Wide Area Network (WAN)', 'Metropolitan Area Network (MAN)', 'Storage Area Network'],
    a: 'A',
    wc: 'A PAN is a very short-range network around an individual, commonly using Bluetooth.',
    ww: {
      B: 'A WAN spans large geographic distances.',
      C: 'A MAN spans a metropolitan area.',
      D: 'A SAN is a specialized storage network, not a personal Bluetooth link.',
    },
    er: 'Maps short-range Bluetooth to a PAN.',
  },
  {
    t: 'Communications', s: 'Baseband vs broadband', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Types of Communications',
    q: 'Which statement correctly distinguishes baseband from broadband transmission?',
    o: [
      'Baseband uses the entire medium for a single channel; broadband divides the medium into multiple channels',
      'Baseband always uses fiber; broadband always uses copper',
      'Broadband can carry only one signal at a time',
      'Baseband is wireless and broadband is wired',
    ],
    a: 'A',
    wc: 'Baseband dedicates the whole medium to one signal/channel at a time, while broadband splits the medium into multiple simultaneous channels/frequencies.',
    ww: {
      B: 'Neither is tied to a specific cable type by definition.',
      C: 'Broadband carries multiple signals simultaneously, not just one.',
      D: 'Both can be wired; the distinction is single vs. multiple channels.',
    },
    er: 'Tests the single-channel vs multi-channel distinction.',
  },
  {
    t: 'Communications', s: 'Duplex', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Communication Methods',
    q: 'A communication method that allows both parties to send and receive data SIMULTANEOUSLY is:',
    o: ['Full duplex', 'Half duplex', 'Simplex', 'Baseband'],
    a: 'A',
    wc: 'Full duplex permits simultaneous two-way communication; half duplex allows two-way but only one direction at a time; simplex is one-way only.',
    ww: {
      B: 'Half duplex allows only one direction at a time.',
      C: 'Simplex is strictly one-way.',
      D: 'Baseband refers to channel usage, not directionality.',
    },
    er: 'Distinguishes full duplex from half duplex and simplex.',
  },
  // ---- Network monitoring ----
  {
    t: 'Network Monitoring', s: 'SNMP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Monitoring Protocols',
    q: 'Which protocol is widely used to monitor and manage the status of network devices (e.g., routers, switches)?',
    o: ['SNMP (Simple Network Management Protocol)', 'SMTP', 'ARP', 'FTP'],
    a: 'A',
    wc: 'SNMP is used to monitor and manage network devices, collecting status and performance data (use SNMPv3 for security).',
    ww: {
      B: 'SMTP routes email.',
      C: 'ARP resolves IP addresses to MAC addresses.',
      D: 'FTP transfers files.',
    },
    er: 'Maps device monitoring/management to SNMP.',
  },
  {
    t: 'Network Monitoring', s: 'ICMP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Monitoring Protocols',
    q: 'Which protocol is used by the ping and traceroute utilities to report communication status, and has no assigned port?',
    o: ['ICMP', 'SNMP', 'HTTP', 'DHCP'],
    a: 'A',
    wc: 'ICMP provides communication status and error messages and underlies ping and traceroute; it has no port number.',
    ww: {
      B: 'SNMP manages devices and uses ports 161/162.',
      C: 'HTTP serves web content on port 80.',
      D: 'DHCP assigns IP addresses on ports 67/68.',
    },
    er: 'Maps ping/traceroute to ICMP.',
  },
  {
    t: 'Network Monitoring', s: 'Monitoring process', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 4 > Network Components > Process of Network Monitoring',
    q: 'Order the network monitoring process steps as described in the guide. (Provide the option labels in order.)',
    o: ['Collection', 'Monitoring', 'Detection', 'Action'],
    a: 'A,B,C,D',
    wc: 'The monitoring process flows from collecting data, to monitoring it, to detecting anomalies, to taking action.',
    ww: {},
    er: 'Tests the ordered network-monitoring process.',
  },
  {
    t: 'Network Monitoring', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Purposes of Network Monitoring',
    q: 'A primary security-related purpose of network monitoring is to:',
    o: [
      'Observe network performance and detect anomalies that may indicate a security issue',
      'Permanently prevent any device from ever failing',
      'Encrypt all data at rest automatically',
      'Replace the need for firewalls entirely',
    ],
    a: 'A',
    wc: 'Network monitoring focuses on performance and visibility, enabling detection of anomalies that can indicate attacks or failures.',
    ww: {
      B: 'Monitoring detects issues; it cannot prevent all hardware failures.',
      C: 'Monitoring does not perform data-at-rest encryption.',
      D: 'Monitoring complements, not replaces, firewalls.',
    },
    er: 'Ties monitoring to visibility and anomaly detection.',
  },
  {
    t: 'Network Components', s: 'Device selection', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'Which TWO devices make forwarding decisions using Layer 2 (MAC) information? (Select TWO.)',
    o: ['Bridge', 'Switch', 'Router', 'Repeater'],
    a: ['A', 'B'],
    wc: 'Bridges and switches are Layer 2 devices that forward based on MAC addresses.',
    ww: {
      C: 'A router forwards at Layer 3 using IP addresses.',
      D: 'A repeater operates at Layer 1, regenerating signals without MAC decisions.',
    },
    er: 'Identifies the Layer 2 forwarding devices.',
  },
  {
    t: 'Network Infrastructure', s: 'Redundancy', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Components > Network Infrastructure Operations',
    q: 'Which TWO measures improve the AVAILABILITY of network infrastructure during power problems? (Select TWO.)',
    o: ['Uninterruptible Power Supplies (UPS)', 'Backup generators', 'Disabling all monitoring', 'Using a hub instead of a switch'],
    a: ['A', 'B'],
    wc: 'UPS units cover short outages/fluctuations and generators sustain long outages—both improve availability.',
    ww: {
      C: 'Disabling monitoring reduces visibility and does not aid power availability.',
      D: 'Replacing a switch with a hub harms performance/security and is unrelated to power.',
    },
    er: 'Identifies power-availability measures.',
  },
  {
    t: 'Transmission Media', s: 'Coaxial cable', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Coaxial Cable',
    q: 'Coaxial cable carries signals over which medium?',
    o: ['A copper core surrounded by shielding', 'A glass core using light', 'Open-air radio waves only', 'Fiber strands bundled together'],
    a: 'A',
    wc: 'Coaxial cable uses a central copper conductor surrounded by insulation and metallic shielding to carry electrical signals.',
    ww: {
      B: 'A glass core using light describes fiber optic cable.',
      C: 'Open-air radio waves describe wireless transmission.',
      D: 'Bundled fiber strands describe fiber cabling, not coax.',
    },
    er: 'Recall of coaxial cable construction.',
  },
  {
    t: 'Network Components', s: 'WAP', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Components > Hardware Operations',
    q: 'A Wireless Access Point (WAP) primarily:',
    o: [
      'Bridges wireless client devices onto a wired network',
      'Routes packets between autonomous systems on the internet',
      'Generates backup power for the data center',
      'Sanitizes magnetic media',
    ],
    a: 'A',
    wc: 'A WAP connects wireless clients to a wired LAN, acting as a bridge between the wireless and wired segments.',
    ww: {
      B: 'Inter-AS routing on the internet is a BGP/router function.',
      C: 'Backup power is a generator/UPS function.',
      D: 'Media sanitization is a data-destruction activity.',
    },
    er: 'Maps wireless-to-wired bridging to a WAP.',
  },
  {
    t: 'Communications', s: 'CSMA', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Collision Management',
    q: 'Wireless networks use CSMA/CA rather than CSMA/CD primarily because:',
    o: [
      'Stations cannot reliably detect collisions on wireless media, so they try to AVOID them',
      'Wireless media never experience any contention',
      'Collision detection is illegal on wireless networks',
      'CSMA/CA encrypts all wireless frames',
    ],
    a: 'A',
    wc: 'On shared wireless media, a transmitting station cannot reliably hear collisions (hidden-node problem), so CSMA/CA focuses on avoidance rather than detection (CSMA/CD, used on wired Ethernet).',
    ww: {
      B: 'Wireless media do experience contention; that is why a MAC method is needed.',
      C: 'There is no legal prohibition; it is a technical limitation.',
      D: 'CSMA/CA is a media-access method, not an encryption scheme.',
    },
    er: 'Explains why wireless uses collision avoidance (CA) vs detection (CD).',
  },
];
