// Domain 4 — Part 3: Protocols by layer (secure vs unsecure), multilayer/
// converged protocols, firewalls (types & architecture), IPsec, secure
// communication channels (VPN), and Network Access Control (NAC).
module.exports = [
  // ---- Secure vs unsecure protocols ----
  {
    t: 'Communication Protocols', s: 'Secure remote access', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 7 - Application Layer Protocols',
    q: 'Which protocol should REPLACE Telnet for remote command-line administration because it encrypts the session?',
    o: ['SSH', 'HTTP', 'SNMPv1', 'FTP'],
    a: 'A',
    wc: 'SSH provides encrypted remote access and should replace Telnet, which transmits credentials and commands in cleartext.',
    ww: {
      B: 'HTTP is for unencrypted web traffic, not remote shell access.',
      C: 'SNMPv1 monitors devices and is itself insecure; it is not a remote shell.',
      D: 'FTP transfers files in cleartext and is not a secure remote shell.',
    },
    er: 'Maps secure remote administration to SSH over Telnet.',
  },
  {
    t: 'Communication Protocols', s: 'Secure web', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 7 - Application Layer Protocols',
    q: 'HTTPS provides secure web communication primarily by using:',
    o: ['TLS (formerly SSL) to encrypt the session', 'ARP to resolve addresses', 'NAT to translate addresses', 'ICMP to confirm delivery'],
    a: 'A',
    wc: 'HTTPS secures web traffic by layering HTTP over TLS (which replaced SSL), providing confidentiality and integrity.',
    ww: {
      B: 'ARP resolves IP-to-MAC addresses; it does not encrypt web traffic.',
      C: 'NAT translates addresses; it does not provide encryption.',
      D: 'ICMP carries status/error messages, not web encryption.',
    },
    er: 'Maps HTTPS security to TLS.',
  },
  {
    t: 'Communication Protocols', s: 'Cleartext protocols', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Networking Concepts > Layer 7 - Application Layer Protocols',
    q: 'A security review finds employees logging into a device management interface over Telnet across the corporate LAN. What is the PRIMARY risk and best remediation?',
    o: [
      'Credentials travel in cleartext and can be sniffed; replace Telnet with SSH',
      'Telnet uses too much bandwidth; switch to UDP',
      'Telnet encrypts too strongly; downgrade to HTTP',
      'There is no risk because it is on the internal LAN',
    ],
    a: 'A',
    wc: 'Telnet sends credentials and commands in cleartext, exposing them to sniffing (including internal threats); SSH provides an encrypted replacement.',
    ww: {
      B: 'The risk is confidentiality (cleartext), not bandwidth.',
      C: 'Telnet does not encrypt at all; HTTP is also cleartext.',
      D: 'Internal networks are not inherently trusted (insider/lateral-movement risk).',
    },
    er: 'Tests recognizing cleartext-protocol exposure and the SSH remediation.',
  },
  {
    t: 'Communication Protocols', s: 'DNP3 / ICS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Important Protocol to Know for the Exam',
    q: 'DNP3 is a protocol most commonly associated with:',
    o: [
      'Industrial control systems (e.g., electric, water, oil and gas)',
      'Encrypting email messages',
      'Resolving domain names',
      'Assigning IP addresses to laptops',
    ],
    a: 'A',
    wc: 'DNP3 (Distributed Network Protocol v3) is widely used in industrial control systems such as electric utilities, water/wastewater, and oil and gas.',
    ww: {
      B: 'Email encryption uses S/MIME or PGP, not DNP3.',
      C: 'Name resolution is DNS.',
      D: 'IP assignment is DHCP.',
    },
    er: 'Maps DNP3 to ICS environments.',
  },
  // ---- Firewalls ----
  {
    t: 'Firewalls', s: 'Stateful vs stateless', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Stateful Inspection Firewall',
    q: 'How does a stateful inspection firewall improve on a static (stateless) packet-filtering firewall?',
    o: [
      'It tracks the state of active connections to decide which packets belong to a legitimate session',
      'It only inspects the source IP and nothing else',
      'It operates exclusively at Layer 1',
      'It cannot block any traffic',
    ],
    a: 'A',
    wc: 'A stateful firewall maintains a state table of active connections (Layers 3-4), allowing return traffic that belongs to established sessions and blocking unsolicited packets.',
    ww: {
      B: 'Inspecting only source IP describes basic stateless filtering.',
      C: 'Stateful inspection works at Layers 3-4, not Layer 1.',
      D: 'Stateful firewalls do block traffic based on policy and state.',
    },
    er: 'Tests the connection-state advantage of stateful firewalls.',
  },
  {
    t: 'Firewalls', s: 'Static packet filter', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Static Packet Filtering Firewall',
    q: 'A static packet-filtering firewall makes allow/deny decisions based on:',
    o: [
      'Source/destination IP addresses, protocols, and port numbers',
      'The full application payload content',
      'The user\'s biometric data',
      'The physical temperature of the device',
    ],
    a: 'A',
    wc: 'A static (stateless) packet filter operates at Layer 3 and filters on IPs, protocols, and ports without tracking connection state.',
    ww: {
      B: 'Deep application-payload inspection is done by application-level gateways/NGFWs.',
      C: 'Biometrics are an authentication factor, not a packet-filter criterion.',
      D: 'Device temperature is irrelevant to filtering.',
    },
    er: 'Recall of stateless packet-filter criteria.',
  },
  {
    t: 'Firewalls', s: 'Application-level gateway', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Proxy Firewall',
    q: 'An application-level gateway (proxy firewall) provides stronger content filtering than a packet filter because it:',
    o: [
      'Inspects and manages application-layer (Layer 7) data, not just headers',
      'Only looks at MAC addresses',
      'Operates faster with no performance impact',
      'Ignores the application data entirely',
    ],
    a: 'A',
    wc: 'An application-level gateway operates at Layer 7, inspecting and filtering application data for detailed content control (at some performance cost).',
    ww: {
      B: 'MAC-only inspection is a Layer 2 concern, not an application gateway.',
      C: 'Deeper inspection typically reduces performance, not improves it.',
      D: 'Inspecting application data is precisely its purpose.',
    },
    er: 'Tests Layer 7 inspection by application-level gateways.',
  },
  {
    t: 'Firewalls', s: 'NGFW', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Next Generation Firewall (NGFW)',
    q: 'A Next-Generation Firewall (NGFW) typically adds which capabilities beyond traditional firewalls?',
    o: [
      'Deep packet inspection, intrusion prevention, and application awareness',
      'Only stateless port filtering',
      'Physical fire suppression',
      'Magnetic media sanitization',
    ],
    a: 'A',
    wc: 'NGFWs combine traditional filtering with deep packet inspection, integrated IPS, application awareness, and threat intelligence.',
    ww: {
      B: 'Stateless port filtering is the most basic firewall capability, not an NGFW addition.',
      C: 'Fire suppression is a physical control.',
      D: 'Media sanitization is a data-destruction activity.',
    },
    er: 'Tests NGFW advanced capabilities.',
  },
  {
    t: 'Firewalls', s: 'Firewall-type mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 4 > Network Security and Attacks > Types of Firewalls',
    p: ['Static packet filter', 'Stateful inspection', 'Application-level gateway', 'NGFW'],
    q: 'Match each firewall type (1-4) to its description (A-D).',
    o: [
      'Tracks connection state across Layers 3-4',
      'Filters on IP/protocol/port with no state (Layer 3)',
      'Adds IPS, deep packet inspection, and application awareness',
      'Inspects application-layer (Layer 7) content as a proxy',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Static packet filter → stateless L3 (B); Stateful inspection → tracks state L3-4 (A); Application-level gateway → L7 proxy (D); NGFW → IPS/DPI/app-aware (C).',
    ww: {},
    er: 'Tests mapping of firewall types to capabilities.',
  },
  {
    t: 'Firewall Architecture', s: 'Screened subnet (DMZ)', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Screened Subnet (DMZ)',
    q: 'A company wants to host public web servers while keeping its internal network isolated, using two firewalls to create a buffer zone. This architecture is a:',
    o: [
      'Screened subnet (DMZ)',
      'Single bastion host with no firewall',
      'Flat network with all hosts in one zone',
      'A mesh topology of switches',
    ],
    a: 'A',
    wc: 'A screened subnet (DMZ) uses two firewalls to place public-facing servers in a buffer zone between the internet and the internal network, limiting exposure.',
    ww: {
      B: 'A lone bastion host without firewalls does not create the two-firewall buffer described.',
      C: 'A flat network provides no isolation between public and internal hosts.',
      D: 'A switch mesh is a topology, not a firewall security architecture.',
    },
    er: 'Maps a two-firewall public buffer zone to a screened subnet/DMZ.',
  },
  {
    t: 'Firewall Architecture', s: 'Bastion host', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Bastion Host',
    q: 'A bastion host is:',
    o: [
      'A hardened, exposed system specifically built to withstand attacks at a network boundary',
      'A device that assigns IP addresses to clients',
      'A backup generator for the firewall',
      'A wireless access point for guests',
    ],
    a: 'A',
    wc: 'A bastion host is a hardened, often internet-facing system designed and locked down to resist attacks, frequently placed in or at the edge of a DMZ.',
    ww: {
      B: 'IP assignment is DHCP\'s function.',
      C: 'A generator provides backup power.',
      D: 'A guest WAP is a wireless access device, not a bastion host.',
    },
    er: 'Recall of the hardened, exposed bastion host.',
  },
  // ---- IPsec / VPN ----
  {
    t: 'IPsec', s: 'Transport vs tunnel mode', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > IPsec Operational Modes',
    q: 'A company is building a site-to-site VPN across the internet and wants the ENTIRE original IP packet (header and payload) protected. Which IPsec mode should it use?',
    o: [
      'Tunnel mode (encrypts the full packet, including the original header)',
      'Transport mode (encrypts only the payload, leaving the header exposed)',
      'Cleartext mode for efficiency',
      'Half-duplex mode',
    ],
    a: 'A',
    wc: 'IPsec tunnel mode encrypts the entire original packet (header + payload) and is typical for site-to-site/gateway VPNs; transport mode protects only the payload.',
    ww: {
      B: 'Transport mode leaves the original header exposed—less suited to full site-to-site protection.',
      C: 'There is no "cleartext mode" for a secure VPN.',
      D: 'Half-duplex is a communication directionality, not an IPsec mode.',
    },
    er: 'Maps full-packet protection (site-to-site VPN) to IPsec tunnel mode.',
  },
  {
    t: 'IPsec', s: 'AH vs ESP', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Components of IPsec',
    q: 'Which IPsec component provides CONFIDENTIALITY (encryption) of the data, in addition to integrity and authentication?',
    o: [
      'Encapsulating Security Payload (ESP)',
      'Authentication Header (AH)',
      'ISAKMP',
      'Security Association (SA)',
    ],
    a: 'A',
    wc: 'ESP provides confidentiality (encryption) plus integrity and authentication; AH provides integrity/authentication/non-repudiation but does NOT encrypt.',
    ww: {
      B: 'AH provides integrity and authentication but no encryption (no confidentiality).',
      C: 'ISAKMP manages security associations/keys; it is not the data-encrypting component.',
      D: 'An SA defines the parameters of a connection, not the encryption mechanism itself.',
    },
    er: 'Distinguishes ESP (encrypts) from AH (no encryption).',
  },
  {
    t: 'IPsec', s: 'ISAKMP / SA', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Security Associations and ISAKMP',
    q: 'In IPsec, a Security Association (SA) defines:',
    o: [
      'The agreed security protocols, algorithms, and keys for a connection',
      'The physical cable type used',
      'The office building floor plan',
      'The DNS server addresses',
    ],
    a: 'A',
    wc: 'An SA specifies the security protocols, algorithms, and key material for an IPsec connection; ISAKMP negotiates and manages SAs.',
    ww: {
      B: 'Cable type is a physical-media concern, not an SA.',
      C: 'Floor plans are facility design, unrelated to SAs.',
      D: 'DNS server addresses are unrelated to IPsec SAs.',
    },
    er: 'Recall of what an IPsec SA defines.',
  },
  {
    t: 'Secure Channels', s: 'VPN purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Endpoint Security',
    q: 'A Virtual Private Network (VPN) primarily provides:',
    o: [
      'A secure, encrypted tunnel for data across an untrusted network',
      'Automatic assignment of MAC addresses',
      'Physical fire suppression in the data center',
      'Faster CPU performance on endpoints',
    ],
    a: 'A',
    wc: 'A VPN creates an encrypted tunnel (e.g., via IPsec or TLS) so data can traverse untrusted networks (like the internet) securely.',
    ww: {
      B: 'MAC addresses are hardware-assigned, not VPN-provided.',
      C: 'Fire suppression is a physical control.',
      D: 'A VPN does not increase CPU speed.',
    },
    er: 'Recall of the VPN encrypted-tunnel purpose.',
  },
  {
    t: 'Secure Channels', s: 'L2TP/IPsec', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 2 - Data Link Layer Protocols',
    q: 'L2TP is often paired with IPsec for VPNs because L2TP by itself:',
    o: [
      'Provides tunneling but no encryption, so IPsec adds the confidentiality',
      'Encrypts data too strongly to be practical',
      'Cannot create a tunnel at all',
      'Is a physical-layer cabling standard',
    ],
    a: 'A',
    wc: 'L2TP creates the tunnel but does not encrypt; IPsec is added to provide encryption/confidentiality (L2TP/IPsec).',
    ww: {
      B: 'L2TP provides no encryption on its own, so it is not "too strong."',
      C: 'L2TP does create tunnels; it just lacks encryption.',
      D: 'L2TP is a tunneling protocol, not a physical cabling standard.',
    },
    er: 'Explains why L2TP is combined with IPsec.',
  },
  // ---- NAC ----
  {
    t: 'Network Access Control', s: 'NAC purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Network Access Control',
    q: 'Network Access Control (NAC) primarily enforces security by:',
    o: [
      'Checking a device\'s posture/compliance before (and during) granting it network access',
      'Encrypting data at rest on file servers',
      'Assigning public IP addresses to all devices',
      'Replacing the need for any authentication',
    ],
    a: 'A',
    wc: 'NAC assesses device identity and posture (e.g., patch level, configuration) before admitting it, and can monitor compliance afterward, quarantining non-compliant devices.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'NAC controls access; it is not a public IP assignment service.',
      D: 'NAC complements authentication; it does not eliminate it.',
    },
    er: 'Tests the posture/compliance-checking purpose of NAC.',
  },
  {
    t: 'Network Access Control', s: 'Pre vs post-admission', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Types of NAC Implementations',
    q: 'A laptop fails its health check (missing patches) when it connects. The NAC system places it on a restricted remediation network until it updates. Which NAC concepts are demonstrated?',
    o: [
      'Pre-admission control with a quarantine/remediation network',
      'Post-admission control that ignores device health',
      'Agentless DNS resolution',
      'Static NAT translation',
    ],
    a: 'A',
    wc: 'Pre-admission NAC evaluates device posture before granting full access; non-compliant devices are sent to a quarantine/remediation network to be fixed.',
    ww: {
      B: 'Ignoring device health contradicts the health-check described.',
      C: 'Agentless DNS resolution is unrelated to posture-based quarantine.',
      D: 'Static NAT is an address-translation method, not NAC posture control.',
    },
    er: 'Maps health-check + quarantine to pre-admission NAC.',
  },
  {
    t: 'Network Access Control', s: '802.1X', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Network Access Control',
    q: 'IEEE 802.1X is used to provide:',
    o: [
      'Port-based network access control requiring authentication before a device is allowed on the network',
      'A fire suppression standard for data centers',
      'A wireless cable category rating',
      'A method to assign multicast addresses',
    ],
    a: 'A',
    wc: '802.1X provides port-based network access control, requiring a device/user to authenticate (often via RADIUS) before the switch port or WLAN grants access.',
    ww: {
      B: 'Fire suppression standards are unrelated to 802.1X.',
      C: 'Cable categories (Cat5/6) are unrelated to 802.1X.',
      D: 'Multicast addressing is Class D IP, not 802.1X.',
    },
    er: 'Maps port-based authenticated access to 802.1X.',
  },
  {
    t: 'Secure Channels', s: 'Email security', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Email Security',
    q: 'Which approach BEST provides confidentiality and integrity for email message content?',
    o: [
      'End-to-end message encryption/signing (e.g., S/MIME or PGP)',
      'Sending email over plain SMTP with no protections',
      'Disabling spam filters',
      'Using a longer display name',
    ],
    a: 'A',
    wc: 'S/MIME or PGP provide message-level encryption and digital signatures, protecting confidentiality and integrity (and enabling sender authentication).',
    ww: {
      B: 'Plain SMTP transmits messages in cleartext without protection.',
      C: 'Disabling spam filters weakens, not strengthens, email security.',
      D: 'A display name does not secure message content.',
    },
    er: 'Maps email content protection to S/MIME/PGP.',
  },
  {
    t: 'Secure Channels', s: 'VoIP security', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 4 > Network Security and Attacks > Voice Communications',
    q: 'Because VoIP carries voice over the IP network, a key security consideration is that it:',
    o: [
      'Inherits IP network threats (e.g., eavesdropping, DoS) and should be segmented/encrypted',
      'Is immune to network attacks because it carries voice',
      'Cannot be encrypted under any circumstances',
      'Requires a separate copper telephone line per call',
    ],
    a: 'A',
    wc: 'VoIP runs over IP and is exposed to network threats like eavesdropping and DoS; segmentation (e.g., voice VLANs) and encryption help protect it.',
    ww: {
      B: 'Carrying voice does not exempt VoIP from IP-based attacks.',
      C: 'VoIP can be encrypted (e.g., SRTP/TLS).',
      D: 'VoIP uses the existing IP infrastructure, not a copper line per call.',
    },
    er: 'Tests VoIP inheriting IP network risks.',
  },
  {
    t: 'Communication Protocols', s: 'Secure protocol selection', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Networking Concepts > Communication Protocols',
    q: 'Which TWO protocols provide built-in encryption/security for their function? (Select TWO.)',
    o: ['SSH', 'HTTPS', 'Telnet', 'FTP'],
    a: ['A', 'B'],
    wc: 'SSH (secure remote access) and HTTPS (TLS-encrypted web) provide built-in security; Telnet and FTP transmit data in cleartext.',
    ww: {
      C: 'Telnet is an unencrypted remote-access protocol.',
      D: 'FTP transmits files and credentials in cleartext.',
    },
    er: 'Separates secure protocols from cleartext ones.',
  },
  {
    t: 'Firewalls', s: 'Firewall deployment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Deployment Strategies',
    q: 'A Web Application Firewall (WAF) differs from a traditional network firewall in that it:',
    o: [
      'Inspects and filters HTTP/HTTPS application traffic to protect web apps (e.g., from injection/XSS)',
      'Only filters based on MAC addresses',
      'Provides backup power to web servers',
      'Routes traffic between autonomous systems',
    ],
    a: 'A',
    wc: 'A WAF focuses on application-layer web traffic, protecting web applications from attacks like SQL injection and cross-site scripting.',
    ww: {
      B: 'MAC filtering is a Layer 2 control, not a WAF function.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Inter-AS routing is a BGP/router function.',
    },
    er: 'Maps web-app-layer protection to a WAF.',
  },
  {
    t: 'IPsec', s: 'AH non-repudiation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Components of IPsec',
    q: 'The IPsec Authentication Header (AH) provides integrity, authentication, and non-repudiation, but notably does NOT provide:',
    o: ['Confidentiality (encryption of the data)', 'Protection against replay', 'Data integrity', 'Source authentication'],
    a: 'A',
    wc: 'AH provides integrity, authentication, non-repudiation, and anti-replay, but it does not encrypt the data (no confidentiality)—ESP is needed for that.',
    ww: {
      B: 'AH does help protect against replay attacks.',
      C: 'AH does provide data integrity.',
      D: 'AH does provide source authentication.',
    },
    er: 'Tests that AH lacks confidentiality (no encryption).',
  },
  {
    t: 'Network Access Control', s: 'NAC deployment models', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 4 > Network Security and Attacks > Deployment Models',
    q: 'Which TWO are NAC deployment models described in the guide? (Select TWO.)',
    o: ['Agent-based NAC', 'Agentless NAC', 'Tunnel-mode NAC', 'Multicast NAC'],
    a: ['A', 'B'],
    wc: 'NAC can be deployed agent-based (software on the endpoint) or agentless (no installed agent); these are the two models described.',
    ww: {
      C: '"Tunnel-mode" is an IPsec mode, not a NAC deployment model.',
      D: '"Multicast NAC" is not a defined NAC deployment model.',
    },
    er: 'Identifies the agent-based vs agentless NAC models.',
  },
  {
    t: 'Communication Protocols', s: 'ARP', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 2 - Data Link Layer Protocols',
    q: 'The Address Resolution Protocol (ARP) is used to:',
    o: [
      'Resolve a known IP address to its corresponding MAC address',
      'Resolve a domain name to an IP address',
      'Encrypt web traffic',
      'Assign dynamic IP addresses to clients',
    ],
    a: 'A',
    wc: 'ARP maps a known IP (Layer 3) address to a MAC (Layer 2) address for local frame delivery.',
    ww: {
      B: 'Name-to-IP resolution is DNS.',
      C: 'Web traffic encryption is TLS/HTTPS.',
      D: 'Dynamic IP assignment is DHCP.',
    },
    er: 'Maps IP-to-MAC resolution to ARP.',
  },
  {
    t: 'Firewalls', s: 'Firewall as first line', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Firewalls Concepts',
    q: 'In network defense, firewalls are commonly described as:',
    o: [
      'A first line of defense that controls traffic between trust zones',
      'A backup power source for the network',
      'A method of physically destroying data',
      'A protocol for resolving domain names',
    ],
    a: 'A',
    wc: 'Firewalls form a first line of network defense, enforcing policy on traffic between zones of differing trust.',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'Data destruction is sanitization, not a firewall.',
      D: 'Name resolution is DNS.',
    },
    er: 'Recall of firewalls as a first line of network defense.',
  },
  {
    t: 'Secure Channels', s: 'Remote access auth', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Objective 4.3',
    q: 'To strengthen remote-access security for a VPN, the BEST practice among these is to:',
    o: [
      'Require multi-factor authentication for remote users',
      'Allow any device to connect without checks',
      'Share a single VPN password across all employees',
      'Disable logging of remote connections',
    ],
    a: 'A',
    wc: 'Requiring MFA significantly reduces the risk of compromised remote-access credentials being used by attackers.',
    ww: {
      B: 'Allowing unchecked devices invites compromised endpoints onto the network.',
      C: 'Shared passwords destroy accountability and are easily leaked.',
      D: 'Disabling logging removes visibility and forensic capability.',
    },
    er: 'Maps strong remote-access security to MFA.',
  },
  {
    t: 'Firewall Architecture', s: 'Multi-homed firewall', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Firewall Architecture',
    q: 'A multi-homed firewall is characterized by:',
    o: [
      'Having multiple network interfaces connecting different network segments/zones',
      'Having exactly one network interface',
      'Being unable to enforce any policy',
      'Operating only at the physical layer',
    ],
    a: 'A',
    wc: 'A multi-homed firewall has two or more network interfaces, each connected to a different segment/zone, allowing it to control traffic between them.',
    ww: {
      B: 'A single interface would be single-homed, not multi-homed.',
      C: 'Multi-homed firewalls do enforce policy between their interfaces.',
      D: 'Firewalls operate at Layers 3-7, not only the physical layer.',
    },
    er: 'Recall of the multi-interface multi-homed firewall.',
  },
  {
    t: 'Communication Protocols', s: 'DNS', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 4 > Networking Concepts > Layer 7 - Application Layer Protocols',
    q: 'The Domain Name System (DNS) primarily:',
    o: [
      'Resolves human-readable domain names to IP addresses',
      'Encrypts all email in transit',
      'Assigns MAC addresses to network cards',
      'Provides backup power to servers',
    ],
    a: 'A',
    wc: 'DNS translates domain names (e.g., example.com) into IP addresses so traffic can be routed.',
    ww: {
      B: 'Email encryption is handled by S/MIME/PGP/TLS, not DNS.',
      C: 'MAC addresses are hardware-assigned, not by DNS.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Recall of DNS name resolution.',
  },
  {
    t: 'Firewalls', s: 'Screened host', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 4 > Network Security and Attacks > Screened Host',
    q: 'A screened-host architecture combines a packet-filtering router with:',
    o: [
      'A bastion host that the router directs external traffic to',
      'Two separate internet connections',
      'A wireless mesh of access points',
      'A magnetic degausser',
    ],
    a: 'A',
    wc: 'A screened host uses a screening router plus a bastion host; the router filters traffic and directs permitted external traffic to the hardened bastion host.',
    ww: {
      B: 'Dual internet connections describe redundancy, not the screened-host design.',
      C: 'A wireless mesh is a topology, not this firewall architecture.',
      D: 'A degausser destroys data; it is unrelated to firewall architecture.',
    },
    er: 'Tests the router + bastion host screened-host design.',
  },
];
