// Domain 6 — Part 4: Software testing methods, code reviews (SAST/DAST, Fagan),
// misuse & interface testing, compliance testing (SOC/PCI/CSA STAR), test
// coverage analysis, and analyzing/reporting results.
module.exports = [
  // ---- Software testing ----
  {
    t: 'Software Testing', s: 'Unit testing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'Unit testing focuses on:',
    o: [
      'Individual components, scripts, or features in isolation',
      'How the entire integrated system meets all requirements',
      'How two or more technologies work together',
      'Whether a change broke previously working functionality',
    ],
    a: 'A',
    wc: 'Unit testing targets specific applications, scripts, or components in isolation, assessing a feature\'s security/performance/usability.',
    ww: {
      B: 'Testing the entire system against requirements is system/acceptance testing.',
      C: 'Testing how technologies work together is integration testing.',
      D: 'Checking that changes did not break existing functionality is regression testing.',
    },
    er: 'Distinguishes unit testing from system/integration/regression.',
  },
  {
    t: 'Software Testing', s: 'Integration testing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'Integration testing verifies:',
    o: [
      'How two or more components/technologies work together',
      'A single isolated function only',
      'That the entire system meets acceptance criteria',
      'The speed of the office network',
    ],
    a: 'A',
    wc: 'Integration testing checks that combined components/technologies interact correctly.',
    ww: {
      B: 'A single isolated function is unit testing.',
      C: 'Whole-system acceptance is system testing.',
      D: 'Network speed is unrelated to integration testing.',
    },
    er: 'Recall of integration testing.',
  },
  {
    t: 'Software Testing', s: 'Regression testing', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'After patching a bug, a team re-runs tests to confirm the fix did not break any previously working features. This is:',
    o: ['Regression testing', 'Unit testing', 'Smoke testing', 'Fuzz testing'],
    a: 'A',
    wc: 'Regression testing ensures recent changes have not adversely affected existing functionality.',
    ww: {
      B: 'Unit testing checks an isolated component, not the impact of a change on the whole.',
      C: 'Smoke testing is a quick basic-functionality check after a build.',
      D: 'Fuzz testing sends invalid input to find flaws.',
    },
    er: 'Maps "did the change break anything" to regression testing.',
  },
  {
    t: 'Software Testing', s: 'System/acceptance testing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'System testing (also called acceptance testing or a reasonableness check) verifies that:',
    o: [
      'The software meets its functional and security requirements as a whole',
      'A single function behaves correctly in isolation',
      'Invalid inputs cause crashes',
      'Two modules exchange data',
    ],
    a: 'A',
    wc: 'System/acceptance testing validates the complete software against its functional and security requirements.',
    ww: {
      B: 'Isolated single-function testing is unit testing.',
      C: 'Driving crashes via invalid input is fuzz testing.',
      D: 'Module-to-module data exchange is integration testing.',
    },
    er: 'Recall of system/acceptance testing.',
  },
  {
    t: 'Software Testing', s: 'Smoke testing', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'Smoke testing is BEST described as:',
    o: [
      'A quick check that the basic functionality works after a new build',
      'An exhaustive test of every code path',
      'A penetration test of the network perimeter',
      'A review of the disaster recovery plan',
    ],
    a: 'A',
    wc: 'Smoke testing quickly verifies that the core functionality of a build works before deeper testing proceeds.',
    ww: {
      B: 'Exhaustive path testing is coverage-focused, not a quick smoke test.',
      C: 'A perimeter pen test is unrelated to build smoke testing.',
      D: 'Reviewing a DR plan is a checklist DR test.',
    },
    er: 'Recall of smoke testing.',
  },
  {
    t: 'Software Testing', s: 'Fuzz testing', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'Fuzz testing discovers vulnerabilities by:',
    o: [
      'Sending invalid, unexpected, or random data to an application to see how it responds',
      'Reviewing source code line by line without running it',
      'Encrypting the application\'s database',
      'Synchronizing system clocks',
    ],
    a: 'A',
    wc: 'Fuzz testing injects invalid/unexpected/random inputs to uncover crashes, vulnerabilities, or performance issues.',
    ww: {
      B: 'Reviewing code without running it is static testing (SAST).',
      C: 'Encrypting a database is unrelated to fuzzing.',
      D: 'Clock synchronization is NTP, not fuzzing.',
    },
    er: 'Maps invalid-input testing to fuzzing.',
  },
  {
    t: 'Software Testing', s: 'Mutation vs generational fuzzing', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Mutation Fuzzing (Dumb Fuzzing)',
    q: 'Which statement correctly distinguishes mutation fuzzing from generational fuzzing?',
    o: [
      'Mutation (dumb) fuzzing alters valid data to create invalid inputs; generational (smart) fuzzing builds inputs from a model',
      'Mutation fuzzing builds inputs from a model; generational fuzzing alters valid data',
      'Both are identical and use no input data',
      'Neither produces invalid inputs',
    ],
    a: 'A',
    wc: 'Mutation (dumb) fuzzing modifies existing valid data into invalid inputs; generational (smart) fuzzing synthesizes inputs using a model of the expected format.',
    ww: {
      B: 'This reverses the two techniques.',
      C: 'They differ in how inputs are produced.',
      D: 'Both produce invalid inputs to probe the target.',
    },
    er: 'Distinguishes mutation (dumb) from generational (smart) fuzzing.',
  },
  // ---- Code reviews ----
  {
    t: 'Code Review', s: 'SAST vs DAST', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Static Testing',
    q: 'A security team wants to find insecure code patterns early by analyzing source code WITHOUT executing the application. Which approach fits BEST?',
    o: [
      'Static Application Security Testing (SAST)',
      'Dynamic Application Security Testing (DAST)',
      'Fuzz testing in production',
      'A full interruption DR test',
    ],
    a: 'A',
    wc: 'SAST analyzes source code without running it, catching insecure patterns early in development.',
    ww: {
      B: 'DAST analyzes the application while it runs, not the static source.',
      C: 'Fuzzing runs the application with malformed input; it is dynamic.',
      D: 'A full interruption test is a DR exercise, unrelated to code analysis.',
    },
    er: 'Maps source-without-execution analysis to SAST.',
  },
  {
    t: 'Code Review', s: 'DAST', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Static Testing',
    q: 'Dynamic Application Security Testing (DAST) analyzes an application:',
    o: [
      'While it is running, often when code cannot be taken out of production',
      'Only by reading source code in a text editor',
      'By degaussing the storage media',
      'By reviewing the disaster recovery plan',
    ],
    a: 'A',
    wc: 'DAST tests a running application (often in production-like conditions), observing behavior rather than reading static source.',
    ww: {
      B: 'Reading static source is SAST.',
      C: 'Degaussing destroys magnetic media.',
      D: 'DR-plan review is a DR test, not code analysis.',
    },
    er: 'Maps running-application analysis to DAST.',
  },
  {
    t: 'Code Review', s: 'Fagan inspection', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Fagan Inspection Process (Phased Code Review Process)',
    q: 'In the Fagan inspection process, which phase immediately FOLLOWS the Inspection phase?',
    o: ['Rework', 'Planning', 'Overview', 'Follow-up'],
    a: 'A',
    wc: 'The Fagan inspection order is Planning, Overview, Inspection, Rework, Follow-up—so Rework directly follows Inspection (remediating the flaws found).',
    ww: {
      B: 'Planning is the first phase, before Overview and Inspection.',
      C: 'Overview precedes Inspection.',
      D: 'Follow-up is the final phase, after Rework.',
    },
    er: 'Tests the Fagan phase ordering (Rework follows Inspection).',
  },
  {
    t: 'Code Review', s: 'Fagan inspection purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Fagan Inspection Process (Phased Code Review Process)',
    q: 'The Fagan inspection is BEST described as a:',
    o: [
      'Structured, phased formal code review process to find defects/vulnerabilities',
      'Automated penetration test',
      'A type of wireless encryption',
      'A disaster recovery test',
    ],
    a: 'A',
    wc: 'A Fagan inspection is a formal, phased code-review process (planning through follow-up) used to identify defects and vulnerabilities.',
    ww: {
      B: 'It is a manual code review, not an automated pen test.',
      C: 'It is unrelated to wireless encryption.',
      D: 'It is not a DR test.',
    },
    er: 'Recall of the Fagan inspection as a formal code review.',
  },
  {
    t: 'Code Review', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Software Code Reviews',
    q: 'The purpose of a software code review is to:',
    o: [
      'Identify flaws, defects, and security vulnerabilities before deployment',
      'Increase the application\'s marketing appeal',
      'Encrypt the production database',
      'Provide backup power to the build server',
    ],
    a: 'A',
    wc: 'Code reviews analyze developed code to find flaws, defects, and security vulnerabilities before the software is deployed.',
    ww: {
      B: 'Marketing appeal is not the goal of a code review.',
      C: 'Database encryption is a separate control.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Recall of the code-review purpose.',
  },
  // ---- Misuse & interface testing ----
  {
    t: 'Misuse Testing', s: 'Definition', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Misuse Testing',
    q: 'Misuse (abuse case) testing evaluates software by:',
    o: [
      'Simulating improper or malicious use from an attacker\'s perspective',
      'Confirming the software meets only its happy-path requirements',
      'Measuring the office network bandwidth',
      'Reviewing the data retention schedule',
    ],
    a: 'A',
    wc: 'Misuse/abuse-case testing models how an attacker or careless user might misuse the system, uncovering vulnerabilities the normal use cases miss.',
    ww: {
      B: 'Testing only the happy path is standard functional testing, not misuse testing.',
      C: 'Bandwidth measurement is unrelated.',
      D: 'Retention scheduling is a data-management task.',
    },
    er: 'Maps attacker-perspective abuse testing to misuse testing.',
  },
  {
    t: 'Misuse Testing', s: 'UML', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Misuse Test Visualization - UML Diagram',
    q: 'In misuse testing, UML diagrams are used to:',
    o: [
      'Map legitimate user and attacker (misuse) interactions to highlight vulnerabilities',
      'Encrypt the source code automatically',
      'Score vulnerabilities with CVSS',
      'Synchronize system clocks',
    ],
    a: 'A',
    wc: 'UML diagrams in misuse testing visually map both legitimate use and potential misuse by attackers, highlighting vulnerabilities and security requirements.',
    ww: {
      B: 'UML diagrams do not encrypt code.',
      C: 'CVSS scoring is a separate severity activity.',
      D: 'Clock synchronization is NTP, not UML.',
    },
    er: 'Maps misuse visualization to UML diagrams.',
  },
  {
    t: 'Interface Testing', s: 'Purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Interface Testing',
    q: 'Interface testing focuses on:',
    o: [
      'The connections between components/systems and how data is exchanged securely',
      'Only the visual color scheme of the UI',
      'The physical temperature of the server room',
      'The financial audit of the company',
    ],
    a: 'A',
    wc: 'Interface testing evaluates connections (API, UI, physical interfaces) and validates secure, correct data exchange, including error handling and recovery.',
    ww: {
      B: 'UI color is a cosmetic detail, not the focus of interface testing.',
      C: 'Server room temperature is an environmental concern.',
      D: 'Financial audits are unrelated to interface testing.',
    },
    er: 'Tests the data-exchange focus of interface testing.',
  },
  {
    t: 'Interface Testing', s: 'Key areas', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Key Areas for Interface Testing',
    q: 'Which TWO are key areas evaluated during interface testing? (Select TWO.)',
    o: ['Error handling for unexpected inputs', 'Secure session management', 'The CEO\'s travel itinerary', 'The cafeteria menu rotation'],
    a: ['A', 'B'],
    wc: 'Interface testing examines error handling, security controls, session management, and recovery/resilience of the interface.',
    ww: {
      C: 'A travel itinerary is unrelated to interface testing.',
      D: 'The cafeteria menu is irrelevant.',
    },
    er: 'Identifies key interface-testing areas.',
  },
  {
    t: 'Interface Testing', s: 'Interface types', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Interface Testing',
    q: 'Which TWO are types of interfaces that interface testing evaluates? (Select TWO.)',
    o: ['Application Programming Interface (API)', 'User Interface (UI)', 'A fire extinguisher', 'A parking permit'],
    a: ['A', 'B'],
    wc: 'Interface testing covers APIs (software-to-software), user interfaces (UI), and physical interfaces.',
    ww: {
      C: 'A fire extinguisher is a safety device, not a software interface.',
      D: 'A parking permit is unrelated.',
    },
    er: 'Identifies testable interface types.',
  },
  // ---- Compliance testing ----
  {
    t: 'Compliance Testing', s: 'SOC reports', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'A SaaS provider wants a report attesting to its SECURITY and privacy controls that it can share (under NDA) with prospective customers\' auditors. Which SOC report fits BEST?',
    o: ['SOC 2', 'SOC 1', 'SOC 3', 'PCI ROC'],
    a: 'A',
    wc: 'SOC 2 reports on security, availability, processing integrity, confidentiality, and privacy controls—appropriate for detailed sharing with customers/auditors under NDA.',
    ww: {
      B: 'SOC 1 focuses on controls relevant to financial reporting.',
      C: 'SOC 3 is a high-level public summary, lacking the detail auditors need.',
      D: 'A PCI ROC concerns payment-card compliance, not general security-control attestation.',
    },
    er: 'Maps security/privacy control attestation to SOC 2.',
  },
  {
    t: 'Compliance Testing', s: 'SOC report mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    p: ['SOC 1', 'SOC 2', 'SOC 3'],
    q: 'Match each SOC report (1-3) to its focus (A-C).',
    o: [
      'Security and privacy controls (detailed, for restricted distribution)',
      'Controls relevant to financial reporting',
      'A high-level summary suitable for public/general use',
    ],
    a: '1-B,2-A,3-C',
    wc: 'SOC 1 → financial-reporting controls (B); SOC 2 → security/privacy controls (A); SOC 3 → high-level public summary (C).',
    ww: {},
    er: 'Tests mapping of SOC report types to their focus.',
  },
  {
    t: 'Compliance Testing', s: 'SOC 3', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'A SOC 3 report is intended to be:',
    o: [
      'A high-level summary suitable for public/general distribution',
      'A detailed financial-controls report for auditors',
      'A penetration test report',
      'A disaster recovery checklist',
    ],
    a: 'A',
    wc: 'SOC 3 provides a high-level, general-use summary that can be shared publicly, unlike the detailed SOC 1/SOC 2 reports.',
    ww: {
      B: 'Detailed financial-controls reporting is SOC 1.',
      C: 'A pen test report is a different artifact.',
      D: 'A DR checklist is a continuity document.',
    },
    er: 'Recall of SOC 3 as a public summary.',
  },
  {
    t: 'Compliance Testing', s: 'CSA STAR', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'In the CSA STAR program for cloud security, Level 1 versus Level 2 differ in that Level 1 is:',
    o: [
      'A self-assessment, while Level 2 involves a third-party audit',
      'A third-party audit, while Level 2 is a self-assessment',
      'A penetration test, while Level 2 is a vulnerability scan',
      'A financial report, while Level 2 is a privacy report',
    ],
    a: 'A',
    wc: 'CSA STAR Level 1 is a self-assessment (suited to lower-risk environments); Level 2 involves an independent third-party audit (for higher-risk environments).',
    ww: {
      B: 'This reverses the two levels.',
      C: 'STAR levels are assurance tiers, not pen test vs scan.',
      D: 'STAR is about cloud security assurance, not financial vs privacy reports.',
    },
    er: 'Distinguishes CSA STAR Level 1 (self) from Level 2 (third-party audit).',
  },
  {
    t: 'Compliance Testing', s: 'Purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'Compliance testing helps an organization demonstrate:',
    o: [
      'Due care and ongoing due diligence in meeting required standards',
      'That it never needs any security controls',
      'That its marketing campaigns are effective',
      'That the office Wi-Fi is fast',
    ],
    a: 'A',
    wc: 'Compliance testing (via assessments and audits) verifies controls are properly implemented, demonstrating due care and ongoing due diligence.',
    ww: {
      B: 'Compliance requires controls, not their absence.',
      C: 'Marketing effectiveness is unrelated.',
      D: 'Wi-Fi speed is not a compliance outcome.',
    },
    er: 'Connects compliance testing to due care/diligence.',
  },
  {
    t: 'Compliance Testing', s: 'SSAE 18', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'SSAE 18 is the standard under which which type of reports are produced?',
    o: ['SOC reports', 'WPA3 certificates', 'CVE identifiers', 'Fire safety certificates'],
    a: 'A',
    wc: 'SSAE 18 is the attestation standard under which SOC 1/2/3 reports are produced.',
    ww: {
      B: 'WPA3 is a wireless encryption protocol.',
      C: 'CVE identifiers come from MITRE.',
      D: 'Fire safety certificates are physical-safety documents.',
    },
    er: 'Maps SSAE 18 to SOC reports.',
  },
  // ---- Coverage analysis ----
  {
    t: 'Test Coverage', s: 'Branch coverage', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Branch Coverage',
    q: 'Branch coverage ensures that:',
    o: [
      'Each decision branch (e.g., both true and false paths) in the code has been tested',
      'Every line of code has been executed at least once',
      'Each program function has been called',
      'Every loop has been exercised',
    ],
    a: 'A',
    wc: 'Branch coverage verifies that each decision branch (each outcome of a conditional) has been tested.',
    ww: {
      B: 'Executing every line is statement coverage.',
      C: 'Calling each function is function coverage.',
      D: 'Exercising loops is loop coverage.',
    },
    er: 'Distinguishes branch coverage from statement/function/loop coverage.',
  },
  {
    t: 'Test Coverage', s: 'Statement coverage', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Statement Coverage',
    q: 'Statement coverage measures whether:',
    o: [
      'Each individual code statement has been executed during testing',
      'Each decision branch outcome was tested',
      'Every loop iteration boundary was tested',
      'Every interface was fuzzed',
    ],
    a: 'A',
    wc: 'Statement coverage tracks whether each executable statement in the code has been run at least once during testing.',
    ww: {
      B: 'Testing each branch outcome is branch coverage.',
      C: 'Loop-boundary testing is loop coverage.',
      D: 'Fuzzing interfaces is a different activity.',
    },
    er: 'Recall of statement coverage.',
  },
  {
    t: 'Test Coverage', s: 'Coverage calculation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Test Coverage Analysis',
    q: 'A test suite exercises 30 of a module\'s 60 executable statements. The statement coverage and the implied confidence level are:',
    o: [
      '50% coverage (tested items divided by total items)',
      '200% coverage',
      '30% coverage',
      'Cannot be determined from the numbers given',
    ],
    a: 'A',
    wc: 'Coverage = items tested / total items = 30/60 = 50%; higher coverage generally implies greater confidence in testing.',
    ww: {
      B: '200% is impossible; coverage cannot exceed 100%.',
      C: '30% would require 18 of 60, not 30 of 60.',
      D: 'The ratio is directly computable from the figures.',
    },
    er: 'Tests the coverage = tested/total calculation.',
  },
  {
    t: 'Test Coverage', s: 'Loop coverage', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Loop Coverage',
    q: 'Loop coverage is important for security/reliability because it helps prevent:',
    o: [
      'Service outages caused by improperly terminating (continuous) loops',
      'Weak wireless encryption',
      'Physical tailgating into the building',
      'DNS poisoning',
    ],
    a: 'A',
    wc: 'Loop coverage tests loop behavior (including boundaries), helping catch loops that never terminate and could cause outages.',
    ww: {
      B: 'Wireless encryption is unrelated to loop coverage.',
      C: 'Tailgating is a physical-security issue.',
      D: 'DNS poisoning is a network attack, not a loop defect.',
    },
    er: 'Connects loop coverage to preventing runaway-loop outages.',
  },
  {
    t: 'Test Coverage', s: 'Function coverage', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Functional Coverage (Function Coverage)',
    q: 'Function (functional) coverage ensures that:',
    o: [
      'Each program function has been tested/called for verification',
      'Each loop boundary is exercised',
      'Every statement is executed',
      'Each decision branch is tested',
    ],
    a: 'A',
    wc: 'Function coverage verifies that each program function has been exercised during testing.',
    ww: {
      B: 'Loop boundaries are loop coverage.',
      C: 'Executing every statement is statement coverage.',
      D: 'Testing each branch is branch coverage.',
    },
    er: 'Recall of function coverage.',
  },
  // ---- Analyzing & reporting ----
  {
    t: 'Reporting', s: 'Executive summary', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Executive Summary',
    q: 'The executive summary of a test/assessment report is primarily written for:',
    o: [
      'Senior management, focusing on critical findings and business impact',
      'Developers, with line-by-line code fixes',
      'Attackers, with full exploit code',
      'The facilities team, with HVAC settings',
    ],
    a: 'A',
    wc: 'The executive summary targets senior management, summarizing critical findings, recommendations, and business impacts in non-technical terms.',
    ww: {
      B: 'Line-by-line fixes belong in the technical report for developers.',
      C: 'Reports are not written for attackers.',
      D: 'HVAC settings are unrelated to the executive summary.',
    },
    er: 'Tests the audience/purpose of the executive summary.',
  },
  {
    t: 'Reporting', s: 'Assessment vs audit report', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Reports',
    q: 'Which statement BEST distinguishes an assessment report from an audit report?',
    o: [
      'An assessment report conveys security findings/recommendations, while an audit report attests to compliance status against criteria',
      'An assessment report is only for attackers',
      'An audit report contains no findings at all',
      'They are identical documents with different titles',
    ],
    a: 'A',
    wc: 'An assessment report communicates security findings and recommendations; an audit report formally attests to compliance status against defined criteria.',
    ww: {
      B: 'Reports are for stakeholders, not attackers.',
      C: 'Audit reports do contain findings (compliance status/exceptions).',
      D: 'They serve distinct purposes.',
    },
    er: 'Distinguishes assessment reports from audit reports.',
  },
  {
    t: 'Reporting', s: 'Ethical disclosure', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Ethical Disclosure',
    q: 'Ethical disclosure of test findings primarily ensures:',
    o: [
      'Transparency and adherence to the Code of Ethics when reporting vulnerabilities',
      'That vulnerabilities are sold to the highest bidder',
      'That findings are hidden from the affected organization',
      'That exploit code is posted publicly before any fix',
    ],
    a: 'A',
    wc: 'Ethical disclosure reports findings transparently and responsibly, consistent with the Code of Ethics—giving the organization the chance to remediate.',
    ww: {
      B: 'Selling vulnerabilities is unethical and harmful.',
      C: 'Hiding findings from the affected org defeats the purpose of testing.',
      D: 'Public exploit release before a fix is reckless.',
    },
    er: 'Tests responsible/ethical disclosure principles.',
  },
  {
    t: 'Reporting', s: 'Report components', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Key Report Components',
    q: 'Which TWO are key components typically included in a security test report? (Select TWO.)',
    o: [
      'Identified threats and vulnerabilities',
      'Criticality and likelihood of findings',
      'The CEO\'s lunch order',
      'The office floor cleaning schedule',
    ],
    a: ['A', 'B'],
    wc: 'Reports include identified threats/vulnerabilities and their criticality/likelihood (and exposure) to support prioritized remediation.',
    ww: {
      C: 'A lunch order is irrelevant.',
      D: 'A cleaning schedule is unrelated to the security report.',
    },
    er: 'Identifies legitimate report components.',
  },
  {
    t: 'Reporting', s: 'Remediation recommendations', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Remediation Recommendations',
    q: 'Remediation recommendations in a report typically suggest:',
    o: [
      'Corrective actions such as patches, updates, or additional security controls',
      'That all findings be ignored',
      'That the company stop logging events',
      'That the report be deleted immediately',
    ],
    a: 'A',
    wc: 'Remediation recommendations propose corrective actions (patches, updates, controls) to address findings, sometimes noting exceptions where remediation is deferred.',
    ww: {
      B: 'Ignoring findings leaves risk unaddressed.',
      C: 'Stopping logging reduces visibility and accountability.',
      D: 'Deleting the report destroys the deliverable and audit trail.',
    },
    er: 'Tests the purpose of remediation recommendations.',
  },
  {
    t: 'Software Testing', s: 'Sanity check', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Software Tests',
    q: 'A sanity check in software testing is:',
    o: [
      'A quick validation of a feature\'s viability early in development',
      'An exhaustive test of every code branch',
      'A full penetration test of the network',
      'A complete disaster recovery failover',
    ],
    a: 'A',
    wc: 'A sanity check quickly validates whether a feature/idea is viable early on before investing in deeper testing.',
    ww: {
      B: 'Exhaustive branch testing is coverage-focused, not a quick sanity check.',
      C: 'A network pen test is unrelated.',
      D: 'A DR failover is a continuity test.',
    },
    er: 'Recall of the sanity check.',
  },
  {
    t: 'Code Review', s: 'Static vs dynamic', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Static Testing',
    q: 'The KEY difference between static and dynamic testing is that static testing:',
    o: [
      'Analyzes code WITHOUT executing it, while dynamic testing runs the code',
      'Runs the code, while dynamic testing only reads it',
      'Requires the application to be in production',
      'Is only used for hardware',
    ],
    a: 'A',
    wc: 'Static testing (SAST) examines code without running it; dynamic testing (DAST) analyzes the running application.',
    ww: {
      B: 'This reverses static and dynamic.',
      C: 'Static testing examines source and does not require production.',
      D: 'These methods apply to software, not only hardware.',
    },
    er: 'Distinguishes static (no execution) from dynamic (execution) testing.',
  },
  {
    t: 'Software Testing', s: 'Knowledge-based testing', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Software Testing Methods',
    q: 'Which TWO are recognized software testing approaches based on tester knowledge of the system? (Select TWO.)',
    o: ['White box testing', 'Black box testing', 'Degaussing testing', 'Fire-drill testing'],
    a: ['A', 'B'],
    wc: 'White box (full knowledge), black box (no knowledge), and gray box (partial) are knowledge-based testing approaches.',
    ww: {
      C: 'Degaussing destroys magnetic media; it is not a software testing approach.',
      D: '"Fire-drill testing" is not a software testing knowledge category.',
    },
    er: 'Identifies knowledge-based software testing approaches.',
  },
  {
    t: 'Compliance Testing', s: 'SOC 1', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Compliance Testing',
    q: 'A SOC 1 report focuses on controls relevant to:',
    o: ['Financial reporting', 'Wireless encryption strength', 'Fire suppression systems', 'Office furniture inventory'],
    a: 'A',
    wc: 'SOC 1 addresses controls relevant to a service organization\'s impact on its customers\' financial reporting.',
    ww: {
      B: 'Wireless encryption is unrelated to SOC 1.',
      C: 'Fire suppression is a physical control.',
      D: 'Furniture inventory is unrelated.',
    },
    er: 'Maps financial-reporting controls to SOC 1.',
  },
  {
    t: 'Test Coverage', s: 'Condition coverage', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Condition Coverage',
    q: 'Condition coverage differs from branch coverage in that condition coverage evaluates:',
    o: [
      'Each individual boolean sub-condition within a decision',
      'Only whether each function was called',
      'Only whether each statement executed',
      'Only whether each loop ran once',
    ],
    a: 'A',
    wc: 'Condition coverage checks each boolean sub-condition (operand) within a decision, which is finer-grained than branch coverage (which checks decision outcomes).',
    ww: {
      B: 'Function calls are function coverage.',
      C: 'Statement execution is statement coverage.',
      D: 'Loop execution is loop coverage.',
    },
    er: 'Distinguishes condition coverage from branch coverage.',
  },
  {
    t: 'Reporting', s: 'Audience targeting', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Analyzing Test Results',
    q: 'Effective test reports tailor content to different audiences by:',
    o: [
      'Providing an executive summary for leadership and a detailed technical report for practitioners',
      'Writing one identical report for everyone in deep technical jargon',
      'Omitting all findings to avoid alarm',
      'Sending only raw scanner output with no analysis',
    ],
    a: 'A',
    wc: 'Reports should serve their audiences: an executive summary (business impact) for leadership and a technical report (detailed findings/remediation) for practitioners.',
    ww: {
      B: 'Jargon-only reports impair leadership decision-making.',
      C: 'Omitting findings defeats the report\'s purpose.',
      D: 'Raw output without analysis is not actionable.',
    },
    er: 'Tests audience-appropriate reporting.',
  },
  {
    t: 'Misuse Testing', s: 'Combined use', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Application of Misuse Testing',
    q: 'Misuse testing is often conducted ALONGSIDE which other activities?',
    o: [
      'Risk analysis, threat modeling, and penetration testing',
      'Payroll processing and invoicing',
      'HVAC maintenance and landscaping',
      'Marketing and sales outreach',
    ],
    a: 'A',
    wc: 'Misuse testing is frequently combined with risk analysis, threat modeling, security assessments, and penetration testing to map possible attack vectors.',
    ww: {
      B: 'Payroll/invoicing are financial operations.',
      C: 'HVAC/landscaping are facilities tasks.',
      D: 'Marketing/sales are unrelated to misuse testing.',
    },
    er: 'Connects misuse testing to related security activities.',
  },
];
