// Domain 6 — Part 3: Penetration testing (purpose, RoE, knowledge types,
// teams, phases, BAS) and log reviews.
module.exports = [
  {
    t: 'Penetration Testing', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing',
    q: 'How does a penetration test differ from a vulnerability assessment?',
    o: [
      'A penetration test actively exploits vulnerabilities to demonstrate real risk',
      'A penetration test only lists weaknesses without testing them',
      'A penetration test never requires authorization',
      'A penetration test only reviews documentation',
    ],
    a: 'A',
    wc: 'A penetration test simulates an attack and exploits vulnerabilities to demonstrate actual, achievable risk—going beyond merely identifying weaknesses.',
    ww: {
      B: 'Listing weaknesses without exploiting is a vulnerability assessment.',
      C: 'Pen tests require authorization (rules of engagement).',
      D: 'Document review is an audit/checklist activity, not exploitation.',
    },
    er: 'Distinguishes exploitation (pen test) from identification (vuln assessment).',
  },
  {
    t: 'Penetration Testing', s: 'Rules of engagement', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Rules of Engagement',
    q: 'Before any penetration test begins, the single MOST important document to establish is the:',
    o: [
      'Rules of engagement (defining scope, methods, objectives, and authorization)',
      'Employee cafeteria schedule',
      'Marketing brochure',
      'Office seating chart',
    ],
    a: 'A',
    wc: 'The rules of engagement define scope, methods, and objectives and—critically—provide legal authorization, ensuring the test is performed ethically and lawfully.',
    ww: {
      B: 'A cafeteria schedule is irrelevant to a pen test.',
      C: 'A marketing brochure has no bearing on test authorization.',
      D: 'A seating chart does not authorize or scope a test.',
    },
    er: 'Tests the centrality of rules of engagement (scope + legal authorization).',
  },
  {
    t: 'Penetration Testing', s: 'Knowledge types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Penetration Tests',
    q: 'In a BLACK box penetration test, the testers:',
    o: [
      'Have no prior knowledge of the target, increasing discovery effort and cost',
      'Have full knowledge of all system details',
      'Are given partial information about the system',
      'Are employees of the target with admin access',
    ],
    a: 'A',
    wc: 'Black box testers start with no internal knowledge, requiring more discovery effort and typically costing more, while simulating an external attacker.',
    ww: {
      B: 'Full knowledge describes white box testing.',
      C: 'Partial information describes grey box testing.',
      D: 'Insider admin access is not the black-box premise.',
    },
    er: 'Maps no-knowledge testing to black box.',
  },
  {
    t: 'Penetration Testing', s: 'Knowledge types', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Penetration Tests',
    q: 'A WHITE box penetration test is typically more cost-effective than black box because testers:',
    o: [
      'Have full system knowledge, reducing time spent on discovery',
      'Must discover everything from scratch',
      'Are forbidden from seeing any documentation',
      'Cannot use any tools',
    ],
    a: 'A',
    wc: 'White box testers receive full system details, so they spend less time on discovery—often making the engagement more efficient/cost-effective.',
    ww: {
      B: 'Discovering everything from scratch describes black box testing.',
      C: 'White box testers are given documentation, not denied it.',
      D: 'Testers may use tools in any test type.',
    },
    er: 'Maps full-knowledge efficiency to white box testing.',
  },
  {
    t: 'Penetration Testing', s: 'Grey box', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Penetration Tests',
    q: 'A grey box penetration test provides testers with:',
    o: [
      'Partial knowledge of the system (a mix of white and black box)',
      'No information at all',
      'Complete administrator credentials to everything',
      'Only the physical building address',
    ],
    a: 'A',
    wc: 'Grey box testing gives testers some information while keeping other elements hidden—a blend of white and black box approaches.',
    ww: {
      B: 'No information describes black box testing.',
      C: 'Full admin access goes beyond the partial-knowledge grey box premise.',
      D: 'Only an address would be closer to black box, not grey box.',
    },
    er: 'Recall of grey box (partial knowledge).',
  },
  {
    t: 'Testing Teams', s: 'Red team', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Testing Teams',
    q: 'In security testing, the RED team plays which role?',
    o: ['Simulates the attacker', 'Defends against the simulated attack', 'Combines attack and defense to improve posture', 'Writes the financial audit report'],
    a: 'A',
    wc: 'The red team simulates adversaries, attempting to breach defenses; the blue team defends; the purple team integrates both.',
    ww: {
      B: 'Defending is the blue team\'s role.',
      C: 'Combining both is the purple team.',
      D: 'Financial audit reporting is unrelated to red teaming.',
    },
    er: 'Recall of the red team (attacker) role.',
  },
  {
    t: 'Testing Teams', s: 'Blue team', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Testing Teams',
    q: 'The BLUE team in a security exercise is responsible for:',
    o: ['Defending against the simulated attacks', 'Simulating the attacker', 'Approving the budget', 'Writing application source code'],
    a: 'A',
    wc: 'The blue team defends systems and responds to the red team\'s simulated attacks.',
    ww: {
      B: 'Simulating attacks is the red team\'s role.',
      C: 'Budget approval is a management function.',
      D: 'Writing source code is a development task.',
    },
    er: 'Recall of the blue team (defender) role.',
  },
  {
    t: 'Testing Teams', s: 'Purple team', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Testing Teams',
    q: 'A PURPLE team primarily exists to:',
    o: [
      'Combine red and blue team efforts to improve overall security posture',
      'Replace both the red and blue teams permanently',
      'Conduct only financial audits',
      'Manage the data center HVAC',
    ],
    a: 'A',
    wc: 'The purple team integrates red (offense) and blue (defense) so findings translate directly into improved detection and defense.',
    ww: {
      B: 'Purple teaming complements, not permanently replaces, red/blue functions.',
      C: 'Financial audits are unrelated to purple teaming.',
      D: 'HVAC management is a facilities function.',
    },
    er: 'Tests the integrative role of the purple team.',
  },
  {
    t: 'Testing Teams', s: 'Team-to-role mapping', d: 'medium', qt: 'matching',
    sec: 'Domain 6 > Conduct Security Testing > Testing Teams',
    p: ['Red team', 'Blue team', 'Purple team'],
    q: 'Match each security testing team (1-3) to its role (A-C).',
    o: [
      'Defends against simulated attacks',
      'Simulates the attacker',
      'Integrates offense and defense to improve posture',
    ],
    a: '1-B,2-A,3-C',
    wc: 'Red → simulates the attacker (B); Blue → defends (A); Purple → integrates offense/defense (C).',
    ww: {},
    er: 'Tests mapping of testing teams to their roles.',
  },
  {
    t: 'Breach and Attack Simulation', s: 'BAS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Breach and Attack Simulation (BAS)',
    q: 'Breach and Attack Simulation (BAS) tools primarily:',
    o: [
      'Automatically and continuously test whether security controls detect and respond to threats',
      'Permanently remove all vulnerabilities',
      'Replace the need for any monitoring',
      'Provide physical access control to facilities',
    ],
    a: 'A',
    wc: 'BAS automates simulated attacks to validate whether controls detect and respond effectively, highlighting gaps for remediation—often continuously.',
    ww: {
      B: 'BAS validates controls; it does not remove vulnerabilities by itself.',
      C: 'BAS complements, not replaces, monitoring.',
      D: 'Physical access control is unrelated to BAS.',
    },
    er: 'Tests the automated control-validation purpose of BAS.',
  },
  {
    t: 'Penetration Testing', s: 'Phases order', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'Order the penetration testing phases as described in the guide. (Provide the option labels in order.)',
    o: [
      'Discovery (passive reconnaissance)',
      'Scanning (active reconnaissance)',
      'Exploitation',
      'Post-exploitation',
      'Reporting',
    ],
    a: 'A,B,C,D,E',
    wc: 'Pen testing proceeds: Discovery (passive recon/OSINT), Scanning (active recon), Exploitation, Post-exploitation (lateral movement/persistence/covering tracks), and Reporting.',
    ww: {},
    er: 'Tests the ordered penetration testing phases.',
  },
  {
    t: 'Penetration Testing', s: 'Discovery phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'The discovery (reconnaissance) phase of a penetration test focuses on:',
    o: [
      'Passive information gathering (OSINT/footprinting) without interacting with the target',
      'Exploiting vulnerabilities with Metasploit',
      'Moving laterally across compromised systems',
      'Writing the executive summary',
    ],
    a: 'A',
    wc: 'The discovery phase uses passive reconnaissance—OSINT and footprinting—to gather information without touching the target.',
    ww: {
      B: 'Exploitation occurs in a later phase.',
      C: 'Lateral movement is part of post-exploitation.',
      D: 'The executive summary belongs to the reporting phase.',
    },
    er: 'Maps passive OSINT/footprinting to the discovery phase.',
  },
  {
    t: 'Penetration Testing', s: 'Scanning phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'The scanning phase of a penetration test involves:',
    o: [
      'Active reconnaissance such as ping sweeps, port scans, and banner grabbing',
      'Passive OSINT only, with no system interaction',
      'Covering tracks by deleting log files',
      'Negotiating the rules of engagement',
    ],
    a: 'A',
    wc: 'The scanning (active reconnaissance) phase interacts with the target—ping sweeps, port scans, banner grabbing, vulnerability scans—to identify weaknesses.',
    ww: {
      B: 'Passive-only OSINT is the discovery phase.',
      C: 'Covering tracks occurs in post-exploitation.',
      D: 'Rules of engagement are agreed before testing begins.',
    },
    er: 'Maps active recon (scanning) to the scanning phase.',
  },
  {
    t: 'Penetration Testing', s: 'Post-exploitation', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'After gaining a foothold on one server, a tester pivots to other systems, maintains access, and removes evidence of activity. Which phase does this represent?',
    o: ['Post-exploitation', 'Discovery', 'Scanning', 'Reporting'],
    a: 'A',
    wc: 'Post-exploitation uses initial access to move laterally, maintain access/persistence, and cover tracks (evading detection).',
    ww: {
      B: 'Discovery is passive pre-attack information gathering.',
      C: 'Scanning is active reconnaissance before exploitation.',
      D: 'Reporting documents findings after testing.',
    },
    er: 'Maps lateral movement/persistence/track-covering to post-exploitation.',
  },
  {
    t: 'Penetration Testing', s: 'Reporting phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'The reporting phase of a penetration test should include:',
    o: [
      'An executive summary and a technical report, mapping findings to the rules of engagement',
      'Only a single CVSS number with no context',
      'Live exploit code released publicly before remediation',
      'No documentation, to keep results secret from the client',
    ],
    a: 'A',
    wc: 'The reporting phase documents findings, vulnerabilities, and remediation for different audiences (executive summary + technical report), mapping results to the rules of engagement.',
    ww: {
      B: 'A bare score without context does not help remediation.',
      C: 'Releasing exploits publicly before fixes is reckless and unethical.',
      D: 'The client must receive documented findings—that is the deliverable.',
    },
    er: 'Tests appropriate pen-test reporting content.',
  },
  {
    t: 'Penetration Testing', s: 'Post-test cleanup', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'After completing an authorized penetration test, the team should perform post-test cleanup, which means:',
    o: [
      'Recovering affected hosts, removing tools/scripts, and restoring systems to their original state',
      'Leaving backdoors in place for future tests',
      'Permanently deleting the client\'s production data',
      'Publishing the client\'s vulnerabilities online',
    ],
    a: 'A',
    wc: 'Post-test cleanup restores systems to their original state—recovering hosts and removing any tools, scripts, or artifacts introduced during testing.',
    ww: {
      B: 'Leaving backdoors is unethical and dangerous.',
      C: 'Deleting production data is destructive and out of scope.',
      D: 'Publishing client vulnerabilities violates confidentiality and ethics.',
    },
    er: 'Tests the restore-to-original-state goal of post-test cleanup.',
  },
  {
    t: 'Penetration Testing', s: 'Physical scope', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing',
    q: 'Penetration testing can target which of the following?',
    o: [
      'Both logical controls (networks/software) and physical controls (locks/cameras)',
      'Only wireless networks',
      'Only printed documents',
      'Only the HVAC system',
    ],
    a: 'A',
    wc: 'Pen tests can assess both logical controls (network/software systems) and physical controls (locks, cameras), depending on scope.',
    ww: {
      B: 'Pen tests are not limited to wireless.',
      C: 'They are not limited to printed documents.',
      D: 'They are not limited to HVAC.',
    },
    er: 'Tests the logical-and-physical scope of pen testing.',
  },
  {
    t: 'Log Reviews', s: 'NTP clock sync', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Log Reviews',
    q: 'During an incident investigation, logs from different servers show inconsistent timestamps, making it hard to correlate events. Which control would have PREVENTED this problem?',
    o: [
      'Synchronizing all systems to a common time source via NTP',
      'Disabling logging on half the servers',
      'Storing logs only on the compromised host',
      'Using a different time zone per server with no reference',
    ],
    a: 'A',
    wc: 'Synchronizing clocks via NTP ensures consistent timestamps across systems, which is essential for correlating events during log review and investigations.',
    ww: {
      B: 'Disabling logging removes the evidence entirely.',
      C: 'Storing logs only on the compromised host risks tampering and loss.',
      D: 'Unreferenced per-server time zones worsen correlation problems.',
    },
    er: 'Maps timestamp correlation to NTP clock synchronization.',
  },
  {
    t: 'Log Reviews', s: 'Log protection', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Log Protection and Security Best Practices',
    q: 'To protect log integrity, a recommended practice is to:',
    o: [
      'Store logs on a remote/centralized server and periodically hash them',
      'Keep logs only on the originating host with no copies',
      'Allow all users to edit logs freely',
      'Delete logs daily to save space',
    ],
    a: 'A',
    wc: 'Storing logs on remote/centralized servers (limiting local tampering) and periodically hashing them to verify integrity are sound log-protection practices.',
    ww: {
      B: 'Local-only logs can be altered or destroyed by an attacker on that host.',
      C: 'Freely editable logs lose integrity.',
      D: 'Deleting logs daily can violate retention policy and destroy evidence.',
    },
    er: 'Tests remote storage + hashing for log integrity.',
  },
  {
    t: 'Log Reviews', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Log Reviews',
    q: 'The PRIMARY purpose of reviewing system logs is to:',
    o: [
      'Track system events and provide an audit trail for detecting/investigating issues',
      'Increase network bandwidth',
      'Encrypt data at rest automatically',
      'Provide backup power to servers',
    ],
    a: 'A',
    wc: 'Logs record system events and form audit trails that support detection, investigation, and accountability.',
    ww: {
      B: 'Logs do not increase bandwidth.',
      C: 'Logging is not data-at-rest encryption.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Recall of the audit-trail purpose of logs.',
  },
  {
    t: 'Penetration Testing', s: 'Exploitation phase', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing Phases',
    q: 'In the exploitation phase, testers attempt to:',
    o: [
      'Bypass security controls (manually or with tools like Metasploit) to compromise the target',
      'Gather only public OSINT data',
      'Write the final executive summary',
      'Synchronize all server clocks',
    ],
    a: 'A',
    wc: 'The exploitation phase actively bypasses security controls—using manual techniques or tools such as Metasploit—to compromise the target while minimizing indicators of compromise.',
    ww: {
      B: 'Gathering public OSINT is the discovery phase.',
      C: 'The executive summary belongs to reporting.',
      D: 'Clock synchronization is a log-review/operations concern.',
    },
    er: 'Maps active compromise to the exploitation phase.',
  },
  {
    t: 'Breach and Attack Simulation', s: 'BAS vs pen test', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Breach and Attack Simulation (BAS)',
    q: 'Compared to a periodic manual penetration test, a key advantage of BAS is that it:',
    o: [
      'Can run continuously/automatically to repeatedly validate control effectiveness',
      'Requires no security controls to be present',
      'Eliminates the need to ever patch systems',
      'Provides legal authorization automatically',
    ],
    a: 'A',
    wc: 'BAS automates simulated attacks so control effectiveness can be validated continuously, complementing point-in-time manual pen tests.',
    ww: {
      B: 'BAS validates existing controls; it does not remove the need for them.',
      C: 'Patching is still required regardless of BAS.',
      D: 'Authorization still comes from rules of engagement, not BAS itself.',
    },
    er: 'Tests the continuous/automated advantage of BAS.',
  },
  {
    t: 'Penetration Testing', s: 'Authorization importance', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Rules of Engagement',
    q: 'Why is documented authorization (in the rules of engagement) essential before testing?',
    o: [
      'It provides legal cover so testers are not committing unauthorized access',
      'It makes the test run faster',
      'It encrypts the network automatically',
      'It guarantees no vulnerabilities will be found',
    ],
    a: 'A',
    wc: 'Without documented authorization, the same actions a pen tester performs would be illegal unauthorized access; the rules of engagement provide the necessary legal cover.',
    ww: {
      B: 'Authorization is about legality, not speed.',
      C: 'It does not encrypt the network.',
      D: 'It does not affect whether vulnerabilities exist.',
    },
    er: 'Tests the legal-authorization purpose of rules of engagement.',
  },
  {
    t: 'Testing Teams', s: 'Red vs blue distinction', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Testing Teams',
    q: 'Which TWO statements about testing teams are correct? (Select TWO.)',
    o: [
      'The red team emulates real-world attackers',
      'The blue team focuses on detection and defense',
      'The red team approves the corporate budget',
      'The blue team writes the marketing plan',
    ],
    a: ['A', 'B'],
    wc: 'The red team emulates attackers and the blue team handles detection/defense; together (purple) they improve posture.',
    ww: {
      C: 'Budget approval is a management function, not a red-team task.',
      D: 'Marketing plans are unrelated to the blue team.',
    },
    er: 'Reinforces red (attack) and blue (defend) roles.',
  },
  {
    t: 'Penetration Testing', s: 'Tools', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Popular Tools/Distributions for Penetration Testing',
    q: 'Which TWO are Linux distributions commonly used for penetration testing? (Select TWO.)',
    o: ['Kali Linux', 'Parrot OS', 'Microsoft Excel', 'Adobe Photoshop'],
    a: ['A', 'B'],
    wc: 'Kali Linux and Parrot OS (along with BlackArch and BackBox) are distributions bundling penetration-testing tools.',
    ww: {
      C: 'Excel is a spreadsheet application.',
      D: 'Photoshop is image-editing software.',
    },
    er: 'Identifies pen-testing distributions.',
  },
  {
    t: 'Log Reviews', s: 'Periodic assessment', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Log Protection and Security Best Practices',
    q: 'Conducting periodic log assessments helps an organization to:',
    o: [
      'Meet policy/compliance requirements and detect issues that automated alerts may miss',
      'Increase the CPU clock speed',
      'Replace the disaster recovery plan',
      'Assign IP addresses to hosts',
    ],
    a: 'A',
    wc: 'Periodic log reviews verify compliance with policy and can surface anomalies/trends that real-time alerts alone might not catch.',
    ww: {
      B: 'Log review does not change CPU speed.',
      C: 'Log review does not replace DR planning.',
      D: 'IP assignment is DHCP\'s function.',
    },
    er: 'Tests the compliance/detection value of periodic log review.',
  },
  {
    t: 'Penetration Testing', s: 'Pen test value', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Penetration Testing',
    q: 'A board asks why a clean vulnerability scan is not sufficient and why a penetration test was also commissioned. The BEST justification is that a pen test:',
    o: [
      'Demonstrates whether identified weaknesses are actually exploitable and what real impact they have',
      'Is cheaper and faster than a scan in every case',
      'Removes the need to ever scan again',
      'Guarantees the network can never be breached',
    ],
    a: 'A',
    wc: 'A scan finds potential weaknesses; a pen test validates which are truly exploitable and demonstrates real business impact, informing prioritization.',
    ww: {
      B: 'Pen tests are usually more involved/costly than scans, not cheaper in every case.',
      C: 'Scanning remains a regular, complementary practice.',
      D: 'No test guarantees an unbreachable network.',
    },
    er: 'Tests articulating the exploit-validation value of pen testing.',
  },
];
