// Domain 6 — Part 2: Vulnerability assessment, information sources, SCAP,
// scan types (credentialed vs not), discovery scans, port status, packet scans.
module.exports = [
  {
    t: 'Vulnerability Assessment', s: 'Purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Vulnerability Assessments',
    q: 'The PRIMARY purpose of a vulnerability assessment is to:',
    o: [
      'Identify and categorize weaknesses so they can be prioritized and remediated',
      'Exploit weaknesses to gain full control of systems',
      'Permanently eliminate all risk',
      'Encrypt all data on the network',
    ],
    a: 'A',
    wc: 'A vulnerability assessment identifies and categorizes weaknesses (often by severity) to reduce risk exposure—it does not exploit them (that is penetration testing).',
    ww: {
      B: 'Exploiting weaknesses is penetration testing, not a vulnerability assessment.',
      C: 'No assessment eliminates all risk.',
      D: 'Assessment finds weaknesses; it does not perform encryption.',
    },
    er: 'Distinguishes vulnerability assessment (find/categorize) from pen testing (exploit).',
  },
  {
    t: 'Vulnerability Assessment', s: 'Assessment vs pen test', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Vulnerability Assessments',
    q: 'Management wants to know which weaknesses exist on its servers but does NOT want testers to actually break in or disrupt operations. Which activity fits BEST?',
    o: [
      'A vulnerability assessment/scan',
      'A full-scope penetration test with exploitation',
      'A full interruption DR test',
      'A breach and attack simulation against production',
    ],
    a: 'A',
    wc: 'A vulnerability assessment/scan identifies and reports weaknesses without exploiting them, matching the requirement to avoid intrusion/disruption.',
    ww: {
      B: 'A penetration test actively exploits weaknesses, which management excluded.',
      C: 'A full interruption test disrupts production—out of scope here.',
      D: 'BAS exercises attack techniques, which may be more intrusive than wanted.',
    },
    er: 'Maps non-intrusive weakness identification to a vulnerability assessment.',
  },
  {
    t: 'Vulnerability Sources', s: 'CVE/NVD', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Sources for Vulnerability Information',
    q: 'The MITRE CVE list and the National Vulnerability Database (NVD) primarily provide:',
    o: [
      'Standardized identifiers and details for publicly known vulnerabilities',
      'A backup power supply for scanners',
      'Encryption keys for production systems',
      'Physical access badges for the data center',
    ],
    a: 'A',
    wc: 'CVE provides unique identifiers for publicly known vulnerabilities, and the NVD enriches them with details/scoring—both are key vulnerability information sources.',
    ww: {
      B: 'Backup power is a UPS/generator function.',
      C: 'CVE/NVD do not provide encryption keys.',
      D: 'Badges are physical access controls.',
    },
    er: 'Maps known-vulnerability identifiers to CVE/NVD.',
  },
  {
    t: 'SCAP', s: 'Purpose', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Security Content Automation Protocol (SCAP)',
    q: 'The Security Content Automation Protocol (SCAP), created by NIST, primarily exists to:',
    o: [
      'Standardize how vulnerability and configuration information is expressed and reported',
      'Provide backup power to scanners',
      'Replace the need for any vulnerability scanning',
      'Encrypt wireless traffic',
    ],
    a: 'A',
    wc: 'SCAP standardizes the format/exchange of security content (vulnerabilities, configuration checks, scoring) so tools interoperate and reporting is consistent.',
    ww: {
      B: 'Backup power is unrelated to SCAP.',
      C: 'SCAP standardizes scanning content; it does not replace scanning.',
      D: 'Wireless encryption is WPA2/WPA3, not SCAP.',
    },
    er: 'Tests the standardization purpose of SCAP.',
  },
  {
    t: 'SCAP', s: 'CVSS', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > SCAP Identification Schemes',
    q: 'Within SCAP, the Common Vulnerability Scoring System (CVSS) is used to:',
    o: [
      'Assign a severity score to a vulnerability to help prioritize remediation',
      'Uniquely name a hardware/software platform',
      'List the open ports on a host',
      'Encrypt the scan results',
    ],
    a: 'A',
    wc: 'CVSS provides a numeric severity score (e.g., 0–10) for vulnerabilities, helping teams prioritize which to fix first.',
    ww: {
      B: 'Naming a platform is the role of CPE (Common Platform Enumeration).',
      C: 'Listing open ports is a function of a port scan, not CVSS.',
      D: 'CVSS scores severity; it does not encrypt results.',
    },
    er: 'Maps vulnerability severity scoring to CVSS.',
  },
  {
    t: 'SCAP', s: 'CPE', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > SCAP Identification Schemes',
    q: 'Common Platform Enumeration (CPE) within SCAP is used to:',
    o: [
      'Provide standardized names for hardware, operating systems, and applications',
      'Score the severity of a vulnerability',
      'Define interactive checklist questions',
      'Map a network\'s physical cabling',
    ],
    a: 'A',
    wc: 'CPE is a standardized naming scheme for platforms (hardware, OS, applications), enabling consistent identification across tools.',
    ww: {
      B: 'Severity scoring is CVSS.',
      C: 'Interactive checklist questions are OCIL.',
      D: 'CPE does not map physical cabling.',
    },
    er: 'Maps platform naming to CPE.',
  },
  {
    t: 'SCAP', s: 'Components', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Key SCAP Components',
    q: 'Which TWO of the following are SCAP components? (Select TWO.)',
    o: ['XCCDF', 'OVAL', 'WPA3', 'SYN flood'],
    a: ['A', 'B'],
    wc: 'XCCDF (configuration checklists) and OVAL (vulnerability/assessment language) are SCAP components, along with OCIL, CPE, CVE, and CVSS.',
    ww: {
      C: 'WPA3 is a wireless encryption protocol.',
      D: 'A SYN flood is a DoS attack technique.',
    },
    er: 'Identifies SCAP components.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Credentialed vs non-credentialed', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Types of Scans',
    q: 'A team needs to verify exact patch levels and detailed configurations on servers. Which scan type provides this deeper insight, and what does it require?',
    o: [
      'A credentialed (authenticated) scan, which requires privileged login access',
      'A non-credentialed scan, which needs no access at all',
      'A discovery scan, which only finds live hosts',
      'A SYN scan, which only checks port state',
    ],
    a: 'A',
    wc: 'A credentialed/authenticated scan logs in with privileged access to reveal patch levels and detailed configurations—deeper than a non-credentialed scan.',
    ww: {
      B: 'A non-credentialed scan only checks general settings/communications with limited depth.',
      C: 'A discovery scan finds active hosts, not detailed patch levels.',
      D: 'A SYN scan determines port status, not configuration/patch detail.',
    },
    er: 'Maps deep patch/config insight to credentialed scans.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Non-credentialed scan', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Scans',
    q: 'A non-credentialed vulnerability scan is characterized by:',
    o: [
      'Checking general settings/communications with read-only access and limited depth',
      'Logging in as root to read every configuration file',
      'Always taking longer than a credentialed scan',
      'Requiring physical access to each server',
    ],
    a: 'A',
    wc: 'A non-credentialed scan inspects externally visible settings/communications with read-only access—faster but shallower than a credentialed scan.',
    ww: {
      B: 'Root login for deep config reading describes a credentialed scan.',
      C: 'Non-credentialed scans are typically faster, not slower.',
      D: 'Scans are network-based; they do not require physical access.',
    },
    er: 'Tests the read-only, limited-depth nature of non-credentialed scans.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Discovery scan', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Discovery Scan',
    q: 'A discovery scan is primarily used to:',
    o: [
      'Detect active hosts across an IP range/subnet to maintain an inventory',
      'Exploit a vulnerability to gain shell access',
      'Score vulnerabilities with CVSS',
      'Encrypt host communications',
    ],
    a: 'A',
    wc: 'A discovery scan targets an IP address/range/subnet to find live hosts, useful for maintaining an accurate host inventory.',
    ww: {
      B: 'Exploiting for shell access is penetration testing.',
      C: 'CVSS scoring is a separate severity step.',
      D: 'Discovery scans identify hosts; they do not encrypt communications.',
    },
    er: 'Maps host inventory discovery to the discovery scan.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Port status', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Port Status Results in Discovery Scans',
    q: 'In scan results, a port reported as "filtered" generally means:',
    o: [
      'A firewall or filter is blocking the scanner from determining the port\'s true state',
      'The port is definitely open and accepting connections',
      'The port is physically disconnected',
      'The host does not exist',
    ],
    a: 'A',
    wc: 'A filtered (unknown/filtered) result indicates a firewall/filter is preventing the scanner from confirming whether the port is open or closed.',
    ww: {
      B: 'An open port would be reported as "open," not filtered.',
      C: 'Filtering is a logical block, not a physical disconnection.',
      D: 'A non-existent host would not return port results at all.',
    },
    er: 'Tests interpretation of a filtered port result.',
  },
  {
    t: 'Packet Scans', s: 'XMAS scan', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Packet Scans in Vulnerability Scanning',
    q: 'An XMAS scan sends packets with which characteristic to probe a target\'s response?',
    o: [
      'Multiple TCP flags set (e.g., FIN, PSH, URG) "lighting up" the packet',
      'A completed three-way handshake on every port',
      'Only the SYN flag set',
      'No flags and an empty payload only',
    ],
    a: 'A',
    wc: 'An XMAS scan sets several TCP flags (commonly FIN, PSH, URG) at once—"lit up like a Christmas tree"—to elicit responses that reveal port state while sometimes evading basic logging.',
    ww: {
      B: 'A completed handshake on every port describes a TCP Connect scan.',
      C: 'Only the SYN flag set describes a SYN scan.',
      D: 'A no-flags packet describes a NULL scan, not XMAS.',
    },
    er: 'Identifies the multi-flag XMAS scan.',
  },
  {
    t: 'Packet Scans', s: 'SYN scan', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Packet Scans in Vulnerability Scanning',
    q: 'A SYN (half-open) scan is often preferred over a full TCP Connect scan because it:',
    o: [
      'Does not complete the three-way handshake, making it stealthier and faster',
      'Always completes the full handshake and logs every connection',
      'Requires privileged credentials on the target',
      'Encrypts the scan traffic end to end',
    ],
    a: 'A',
    wc: 'A SYN scan sends SYN and interprets the response without completing the handshake (sending RST instead of ACK), making it faster and less likely to be fully logged than a TCP Connect scan.',
    ww: {
      B: 'Completing the handshake/logging describes a TCP Connect scan.',
      C: 'A SYN scan does not require target credentials.',
      D: 'A SYN scan does not encrypt its traffic.',
    },
    er: 'Tests why SYN (half-open) scans are stealthier than TCP Connect scans.',
  },
  {
    t: 'Packet Scans', s: 'TCP Connect scan', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Packet Scans in Vulnerability Scanning',
    q: 'A TCP Connect scan differs from a SYN scan in that it:',
    o: [
      'Completes the full three-way handshake, which is more easily logged',
      'Never receives any response from the target',
      'Can only scan UDP services',
      'Requires the XMAS flag combination',
    ],
    a: 'A',
    wc: 'A TCP Connect scan fully establishes the connection (completes the handshake), which is reliable but more likely to be logged than a half-open SYN scan.',
    ww: {
      B: 'It does receive handshake responses; that is how it confirms open ports.',
      C: 'TCP Connect scans target TCP services, not only UDP.',
      D: 'XMAS is a different scan technique.',
    },
    er: 'Distinguishes the full-handshake TCP Connect scan from SYN.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Best practices', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Best Practices for Vulnerability Scanning',
    q: 'A vulnerability scanning best practice is to:',
    o: [
      'Keep scanners updated with the latest signatures/plugins and schedule scans appropriately',
      'Run scans once at install and never again',
      'Disable scanning during business hours permanently',
      'Use an outdated scanner to avoid false positives',
    ],
    a: 'A',
    wc: 'Scanners must be kept updated (new signatures/plugins) and scans planned/scheduled (e.g., incremental scanning) to remain effective against current threats.',
    ww: {
      B: 'One-time scanning misses newly disclosed vulnerabilities.',
      C: 'Scans should be scheduled thoughtfully, not permanently disabled.',
      D: 'Outdated scanners miss new vulnerabilities; updates are essential.',
    },
    er: 'Tests vulnerability-scanning best practices.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Signature-based', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Vulnerability Scanning Process',
    q: 'A signature-based vulnerability scanner detects issues by:',
    o: [
      'Comparing system characteristics against a database of known vulnerability signatures',
      'Randomly guessing passwords until one works',
      'Encrypting files to test resilience',
      'Physically inspecting cabling',
    ],
    a: 'A',
    wc: 'Signature-based scanners match observed system attributes against a database of known vulnerability signatures—so the signature database must stay current.',
    ww: {
      B: 'Password guessing is a brute-force attack, not signature scanning.',
      C: 'Encrypting files is not how scanners detect vulnerabilities.',
      D: 'Cabling inspection is a physical activity, not a scan.',
    },
    er: 'Tests how signature-based scanning works.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Scan scope risk', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Best Practices for Vulnerability Scanning',
    q: 'A vulnerability scan against a fragile legacy system causes it to crash. Which practice would BEST reduce this risk in the future?',
    o: [
      'Plan/schedule scans and test scan intensity in a non-production environment first',
      'Always run the most aggressive scan settings on production',
      'Stop scanning the environment entirely',
      'Remove all logging so crashes are not recorded',
    ],
    a: 'A',
    wc: 'Careful planning/scheduling and validating scan intensity against test/non-production systems reduces the chance of crashing fragile production hosts.',
    ww: {
      B: 'Aggressive settings on production increase crash risk.',
      C: 'Stopping all scanning leaves the environment unassessed.',
      D: 'Removing logging hides problems and harms accountability.',
    },
    er: 'Tests safe scanning practices for fragile systems.',
  },
  {
    t: 'Vulnerability Assessment', s: 'Vulnerability management process', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Vulnerability Assessments',
    q: 'After a scan identifies vulnerabilities, the NEXT logical step in a vulnerability management process is to:',
    o: [
      'Prioritize the findings (e.g., by severity) and remediate or mitigate them',
      'Immediately ignore all findings',
      'Delete the scanner',
      'Publish all findings publicly with full exploit details',
    ],
    a: 'A',
    wc: 'Vulnerability management continues by prioritizing findings (often by severity/CVSS) and remediating or mitigating them, then re-scanning to verify.',
    ww: {
      B: 'Ignoring findings leaves the organization exposed.',
      C: 'Deleting the scanner removes a needed capability.',
      D: 'Publicly releasing exploit details before remediation is reckless and unethical.',
    },
    er: 'Tests the prioritize-and-remediate step of vulnerability management.',
  },
  {
    t: 'Packet Scans', s: 'UDP scan', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Packet Scans in Vulnerability Scanning',
    q: 'UDP scans are often slower and less reliable than TCP scans because UDP:',
    o: [
      'Is connectionless, so the absence of a reply is ambiguous (open or filtered)',
      'Always completes a three-way handshake',
      'Encrypts every packet by default',
      'Cannot be scanned at all',
    ],
    a: 'A',
    wc: 'UDP is connectionless—no handshake—so a lack of response is ambiguous (open|filtered), making UDP scans slower and harder to interpret.',
    ww: {
      B: 'UDP has no handshake (that is TCP).',
      C: 'UDP does not encrypt by default.',
      D: 'UDP can be scanned, just less reliably.',
    },
    er: 'Explains why UDP scanning is ambiguous/slower.',
  },
  {
    t: 'SCAP', s: 'OVAL', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Key SCAP Components',
    q: 'Within SCAP, OVAL (Open Vulnerability and Assessment Language) is primarily used to:',
    o: [
      'Express system states/tests to assess for vulnerabilities and configuration issues',
      'Score the severity of a vulnerability numerically',
      'Provide a standardized platform name',
      'Carry voice traffic over IP',
    ],
    a: 'A',
    wc: 'OVAL provides a standardized language to describe system states and tests used to assess machines for vulnerabilities and configuration issues.',
    ww: {
      B: 'Numeric severity scoring is CVSS.',
      C: 'Standardized platform naming is CPE.',
      D: 'Voice over IP is VoIP, unrelated to OVAL.',
    },
    er: 'Maps assessment-state description to OVAL.',
  },
  {
    t: 'Vulnerability Sources', s: 'US-CERT/vendor', d: 'easy', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Sources for Vulnerability Information',
    q: 'Which TWO are valid sources of vulnerability information? (Select TWO.)',
    o: ['Vendor security advisories', 'The MITRE CVE database', 'The office cafeteria menu', 'The company holiday calendar'],
    a: ['A', 'B'],
    wc: 'Vendor security advisories and the MITRE CVE database (plus the NVD and US-CERT) are key sources of vulnerability information.',
    ww: {
      C: 'A cafeteria menu is irrelevant to vulnerabilities.',
      D: 'A holiday calendar is unrelated.',
    },
    er: 'Identifies valid vulnerability-information sources.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Incremental scanning', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Best Practices for Vulnerability Scanning',
    q: 'Incremental scanning is a best practice that helps by:',
    o: [
      'Breaking large scans into manageable segments to reduce load and improve coverage over time',
      'Scanning the entire enterprise in one pass during peak hours',
      'Never updating the scanner',
      'Scanning only printers and nothing else',
    ],
    a: 'A',
    wc: 'Incremental scanning divides scanning into smaller segments, reducing impact and making thorough coverage more manageable.',
    ww: {
      B: 'A single massive peak-hours scan risks disruption.',
      C: 'Scanners must be updated regularly.',
      D: 'Limiting scans to printers would miss most systems.',
    },
    er: 'Tests the purpose of incremental scanning.',
  },
  {
    t: 'Vulnerability Scanning', s: 'Open port result', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Port Status Results in Discovery Scans',
    q: 'A scan result of "open" for a port indicates that:',
    o: [
      'A service is listening and accepting connections on that port',
      'The port is blocked by a firewall',
      'The host is powered off',
      'The cable is unplugged',
    ],
    a: 'A',
    wc: 'An "open" port means a service is actively listening/accepting connections, which may represent an attack surface to evaluate.',
    ww: {
      B: 'A firewall-blocked port would show as filtered.',
      C: 'A powered-off host would not return open ports.',
      D: 'An unplugged cable is a physical-layer issue, not an "open" result.',
    },
    er: 'Tests interpretation of an open-port result.',
  },
  {
    t: 'SCAP', s: 'OCIL', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Key SCAP Components',
    q: 'OCIL (Open Checklist Interactive Language) within SCAP is used for:',
    o: [
      'Expressing checks that require human interaction/questionnaire responses',
      'Numerically scoring vulnerability severity',
      'Naming platforms uniquely',
      'Routing packets between subnets',
    ],
    a: 'A',
    wc: 'OCIL standardizes interactive checks (e.g., questionnaire-style items requiring human input) within SCAP content.',
    ww: {
      B: 'Severity scoring is CVSS.',
      C: 'Platform naming is CPE.',
      D: 'Packet routing is a network function.',
    },
    er: 'Maps interactive checklist checks to OCIL.',
  },
  {
    t: 'Vulnerability Scanning', s: 'ACK scan', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > Types of Packet Scans in Vulnerability Scanning',
    q: 'An ACK scan is most useful for:',
    o: [
      'Determining whether a firewall is stateful and how it filters (mapping rule sets)',
      'Completing a full three-way handshake to log connections',
      'Encrypting traffic to the target',
      'Assigning IP addresses to hosts',
    ],
    a: 'A',
    wc: 'An ACK scan sends ACK packets to probe firewall behavior—helping determine whether a firewall is stateful and how ports are filtered—rather than simply finding open services.',
    ww: {
      B: 'Completing the handshake describes a TCP Connect scan.',
      C: 'An ACK scan does not encrypt traffic.',
      D: 'IP assignment is DHCP\'s function.',
    },
    er: 'Tests the firewall-mapping use of ACK scans.',
  },
  {
    t: 'Vulnerability Assessment', s: 'Assessment cadence', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Conduct Security Testing > Best Practices for Vulnerability Scanning',
    q: 'Which TWO practices improve the value of an ongoing vulnerability scanning program? (Select TWO.)',
    o: ['Regularly updating scanner signatures', 'Scheduling scans to balance coverage and impact', 'Disabling authentication so scans run faster', 'Ignoring all medium/low findings forever'],
    a: ['A', 'B'],
    wc: 'Keeping signatures current and scheduling scans to balance coverage with operational impact strengthen a scanning program.',
    ww: {
      C: 'Disabling authentication reduces depth and harms security; credentialed scans are valuable.',
      D: 'Permanently ignoring lower-severity findings lets risk accumulate.',
    },
    er: 'Identifies sound vulnerability-scanning practices.',
  },
  {
    t: 'SCAP', s: 'Tool interoperability', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Conduct Security Testing > SCAP Identification Schemes',
    q: 'A key benefit of using SCAP-compatible tools is that they:',
    o: [
      'Can exchange and consume standardized security content consistently',
      'Eliminate the need for any patching',
      'Guarantee zero false positives',
      'Provide physical security for the data center',
    ],
    a: 'A',
    wc: 'SCAP compatibility lets tools share standardized content (CVE, CPE, CVSS, OVAL, etc.), improving consistency and interoperability across the security toolchain.',
    ww: {
      B: 'SCAP supports identifying issues; patching is still required.',
      C: 'No tool guarantees zero false positives.',
      D: 'SCAP is about content standards, not physical security.',
    },
    er: 'Tests the interoperability benefit of SCAP.',
  },
  {
    t: 'Vulnerability Assessment', s: 'Severity prioritization', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Conduct Security Testing > Vulnerability Assessments',
    q: 'A scan returns hundreds of findings. With limited remediation capacity, which approach is BEST?',
    o: [
      'Prioritize remediation by severity and exposure (e.g., critical, internet-facing first)',
      'Fix findings in alphabetical order by hostname',
      'Patch only the lowest-severity issues first',
      'Do nothing until every finding can be fixed at once',
    ],
    a: 'A',
    wc: 'With limited capacity, prioritize by severity (e.g., CVSS) and exposure—remediating critical, internet-facing vulnerabilities first to reduce the greatest risk.',
    ww: {
      B: 'Alphabetical order ignores risk.',
      C: 'Fixing low-severity first leaves critical risks open.',
      D: 'Waiting to fix everything at once leaves critical risks unaddressed indefinitely.',
    },
    er: 'Tests risk-based remediation prioritization.',
  },
];
