// Domain 6 — Part 1: Assessment vs test vs audit, audit types, KPIs/KRIs,
// measurement standards, data collection (account mgmt, training, triple
// constraint), DR/BC data, DR test types, backup types.
module.exports = [
  {
    t: 'Assessment Strategy', s: 'Test vs assessment vs audit', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Security Test and Assessment Overview',
    q: 'Which statement BEST distinguishes a security audit from a security test?',
    o: [
      'An audit focuses on verifying compliance with governance/regulations and reporting on posture; a test exercises a control to see if it works',
      'A test always checks compliance while an audit attacks the system',
      'An audit and a test are identical activities',
      'A test is performed only by external regulators',
    ],
    a: 'A',
    wc: 'A security audit evaluates compliance with governance, regulations, and overall security posture (reporting status and risk impact); a test exercises specific controls to verify they function.',
    ww: {
      B: 'This reverses the roles—audits emphasize compliance verification.',
      C: 'Audits and tests serve different purposes.',
      D: 'Tests can be performed internally or by hired testers, not only regulators.',
    },
    er: 'Distinguishes compliance-focused audits from control-exercising tests.',
  },
  {
    t: 'Security Audits', s: 'Internal audit', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Types of Security Audits',
    q: 'An internal security audit is characterized by being:',
    o: [
      'Performed by internal personnel and reported to senior management',
      'Performed by an outside firm and reported to regulators only',
      'Always more objective than an external audit',
      'Prohibited before an external audit',
    ],
    a: 'A',
    wc: 'Internal audits are conducted by internal staff and reported to senior management, often as a self-audit before an external audit.',
    ww: {
      B: 'That describes an external/third-party audit.',
      C: 'Internal audits are generally LESS objective than independent external audits.',
      D: 'Internal self-audits are commonly performed before external audits.',
    },
    er: 'Recall of the internal audit definition.',
  },
  {
    t: 'Security Audits', s: 'External vs third-party', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Security Test and Assessment > Types of Security Audits',
    q: 'A business partner hires an outside firm to audit a vendor and have the results reported back to the partner (not the vendor) for an acquisition decision. This is BEST described as a:',
    o: ['Third-party audit', 'Internal audit', 'Self-assessment', 'Penetration test'],
    a: 'A',
    wc: 'A third-party audit is performed by an outside team on behalf of another organization, with results reported to that organization—common for compliance or acquisition due diligence.',
    ww: {
      B: 'Internal audits are run by the audited org\'s own staff and report to its management.',
      C: 'A self-assessment is performed by the org on itself.',
      D: 'A penetration test simulates attacks, not a compliance audit reported to a third party.',
    },
    er: 'Maps an outside-org-directed audit to a third-party audit.',
  },
  {
    t: 'Security Audits', s: 'External audit value', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Types of Security Audits',
    q: 'The PRIMARY value of an external audit (conducted by an outside specialist firm) is that it:',
    o: [
      'Provides an unbiased, independent perspective',
      'Is always cheaper than an internal audit',
      'Requires no scope definition',
      'Eliminates the need for any internal controls',
    ],
    a: 'A',
    wc: 'External audits provide an independent, unbiased perspective, reporting to executive officers.',
    ww: {
      B: 'External audits are often more costly, not cheaper.',
      C: 'Scope must still be defined for any audit.',
      D: 'Audits assess controls; they do not remove the need for them.',
    },
    er: 'Tests the independence value of external audits.',
  },
  {
    t: 'Performance Indicators', s: 'KRI', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Key Risk Indicators (KRIs)',
    q: 'A Key Risk Indicator (KRI) differs from a Key Performance Indicator (KPI) in that a KRI:',
    o: [
      'Measures potential failure or ineffectiveness in security controls (forward-looking risk)',
      'Measures only past financial profit',
      'Is identical to a KPI in every way',
      'Can only be expressed as a color code',
    ],
    a: 'A',
    wc: 'A KRI measures the potential for failure/ineffectiveness of controls—signaling rising risk—whereas a KPI measures performance against objectives.',
    ww: {
      B: 'KRIs concern security-control risk, not just financial profit.',
      C: 'KRIs and KPIs measure different things (risk vs performance).',
      D: 'KRIs are not limited to color codes.',
    },
    er: 'Distinguishes KRIs (risk) from KPIs (performance).',
  },
  {
    t: 'Performance Indicators', s: 'KPI', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Performance and Risk Indicators',
    q: 'A Key Performance Indicator (KPI) in security assessment is BEST used to:',
    o: [
      'Measure how well security activities are meeting defined objectives/targets',
      'Predict the exact date of the next breach',
      'Replace all logging and monitoring',
      'Define the office floor plan',
    ],
    a: 'A',
    wc: 'KPIs measure performance against goals/targets (e.g., percentage of systems patched on time), helping gauge program effectiveness.',
    ww: {
      B: 'KPIs measure performance, not predict exact breach dates.',
      C: 'KPIs complement, not replace, monitoring.',
      D: 'Floor plans are unrelated to KPIs.',
    },
    er: 'Tests the performance-measurement role of KPIs.',
  },
  {
    t: 'Measurement Standards', s: 'NIST 800-55 / ISO 27004', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Measurement Standards and Guides',
    q: 'Which pair of standards provides guidance on security measurement and metrics?',
    o: ['NIST SP 800-55 and ISO 27004', 'NIST SP 800-88 and ISO 11889', 'PCI DSS and HIPAA', 'WPA2 and WPA3'],
    a: 'A',
    wc: 'NIST SP 800-55 and ISO 27004 both address security measurement, metrics, and evaluation.',
    ww: {
      B: 'NIST SP 800-88 is media sanitization; ISO 11889 is TPM.',
      C: 'PCI DSS/HIPAA are compliance regulations, not measurement guides.',
      D: 'WPA2/WPA3 are wireless encryption protocols.',
    },
    er: 'Maps security metrics guidance to NIST 800-55/ISO 27004.',
  },
  {
    t: 'Data Collection', s: 'Triple constraint', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Security Test and Assessment > Collecting Security Data',
    q: 'A team must collect assessment data but has limited time and budget. The guide frames this trade-off using the triple constraint of:',
    o: [
      'Scope, time, and cost (which together affect data quality)',
      'People, process, and technology',
      'Confidentiality, integrity, and availability',
      'Red, blue, and purple teams',
    ],
    a: 'A',
    wc: 'The triple constraint of scope, time, and cost governs the quality of collected assessment data—expanding one usually pressures the others.',
    ww: {
      B: 'People/process/technology is a different model, not the triple constraint here.',
      C: 'CIA is the security triad, not the project triple constraint.',
      D: 'Red/blue/purple are testing teams, not constraints.',
    },
    er: 'Maps the scope/time/cost trade-off to the triple constraint.',
  },
  {
    t: 'Data Collection', s: 'Account management data', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Account Management Data',
    q: 'Reviewing account management data during an assessment primarily helps verify that:',
    o: [
      'Account creation, modification, and removal follow policy (e.g., no orphaned or excessive accounts)',
      'The data center temperature is correct',
      'The wireless encryption is WPA3',
      'The office has enough parking',
    ],
    a: 'A',
    wc: 'Account management data (identities and authenticators across the account lifecycle) lets assessors verify proper creation, modification, and auditing of accounts—catching orphaned or over-privileged accounts.',
    ww: {
      B: 'Temperature is an environmental control concern.',
      C: 'Wireless encryption is a network control, not account data.',
      D: 'Parking is unrelated to account management.',
    },
    er: 'Connects account management data to lifecycle verification.',
  },
  {
    t: 'Data Collection', s: 'Management approval', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Collecting Security Data',
    q: 'Before conducting security assessment data collection, the team should FIRST obtain:',
    o: [
      'Management approval and support for the assessment',
      'A new set of office furniture',
      'Permission from external attackers',
      'A larger UPS battery',
    ],
    a: 'A',
    wc: 'Assessments require management approval and support to authorize scope, access, and resources.',
    ww: {
      B: 'Furniture is irrelevant to assessment authorization.',
      C: 'Attackers do not authorize assessments.',
      D: 'A UPS is a power device, not assessment authorization.',
    },
    er: 'Tests the need for management authorization of assessments.',
  },
  // ---- DR tests ----
  {
    t: 'DR Testing', s: 'Test types order', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'Order the disaster recovery test types from LEAST disruptive/intensive to MOST disruptive. (Provide the option labels in order.)',
    o: ['Checklist (read-through) test', 'Structured walkthrough (tabletop)', 'Simulation test', 'Parallel test', 'Full interruption test'],
    a: 'A,B,C,D,E',
    wc: 'DR tests escalate from a checklist review, to a tabletop walkthrough, to a simulation, to a parallel test (no impact to live ops), to a full interruption test (production is impacted).',
    ww: {},
    er: 'Tests the order of DR test intensity.',
  },
  {
    t: 'DR Testing', s: 'Parallel test', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'A company wants to validate that its recovery site can run production workloads WITHOUT taking the live production environment offline. Which DR test fits BEST?',
    o: [
      'Parallel test',
      'Full interruption test',
      'Checklist (read-through) test',
      'Structured walkthrough (tabletop)',
    ],
    a: 'A',
    wc: 'A parallel test runs recovery procedures/site in parallel without impacting live operations—validating recovery capability with low risk.',
    ww: {
      B: 'A full interruption test deliberately impacts production, which the requirement forbids.',
      C: 'A checklist test only reviews documents, not actual recovery operations.',
      D: 'A tabletop exercise discusses the plan but does not run the recovery site.',
    },
    er: 'Maps no-impact recovery validation to a parallel test.',
  },
  {
    t: 'DR Testing', s: 'Full interruption test', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'Which DR test is the MOST thorough but also the RISKIEST, because production operations are actually moved to the backup site?',
    o: ['Full interruption test', 'Parallel test', 'Simulation test', 'Checklist test'],
    a: 'A',
    wc: 'A full interruption test moves production to the backup site, impacting live operations—most realistic and thorough but highest risk.',
    ww: {
      B: 'A parallel test does not impact live operations.',
      C: 'A simulation walks through a scenario without full production cutover.',
      D: 'A checklist test only reviews documentation.',
    },
    er: 'Maps highest-risk production cutover to the full interruption test.',
  },
  {
    t: 'DR Testing', s: 'Tabletop exercise', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'A structured walkthrough (tabletop) DR test consists of:',
    o: [
      'Team members reviewing the DR plan together in a meeting to identify issues',
      'Actually failing over production to a cloud site',
      'Sending invalid data to an application to find bugs',
      'Scanning the network for open ports',
    ],
    a: 'A',
    wc: 'A structured walkthrough/tabletop exercise gathers the team to review the DR plan and identify gaps—discussion-based, no live failover.',
    ww: {
      B: 'Failing over production is a full interruption test.',
      C: 'Sending invalid data is fuzz testing.',
      D: 'Port scanning is a vulnerability-scanning activity.',
    },
    er: 'Recall of the tabletop/structured walkthrough test.',
  },
  // ---- Backups ----
  {
    t: 'Backups', s: 'Differential backup', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Backup Types and Testing Requirements',
    q: 'A differential backup copies:',
    o: [
      'All data modified since the last FULL backup',
      'Only data modified since the last full OR incremental backup',
      'The entire system every time',
      'Nothing; it only verifies existing backups',
    ],
    a: 'A',
    wc: 'A differential backup copies everything changed since the last full backup (so differentials grow until the next full backup).',
    ww: {
      B: 'Copying changes since the last full OR incremental describes an incremental backup.',
      C: 'Backing up everything each time describes a full backup.',
      D: 'A differential backup copies changed data; it is not merely a verification.',
    },
    er: 'Distinguishes differential (since last full) from incremental.',
  },
  {
    t: 'Backups', s: 'Incremental backup', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Security Test and Assessment > Backup Types and Testing Requirements',
    q: 'An organization runs a full backup on Sunday and incremental backups each weeknight. To FULLY restore data after a Thursday failure, which sets are needed?',
    o: [
      'The Sunday full backup plus every incremental from Monday through Thursday',
      'Only Thursday\'s incremental backup',
      'Only the Sunday full backup',
      'Any single incremental backup',
    ],
    a: 'A',
    wc: 'Incrementals capture only changes since the last full or incremental, so a full restore needs the full backup plus the complete chain of incrementals up to the failure.',
    ww: {
      B: 'A single incremental lacks all prior changes since the full backup.',
      C: 'The full backup alone misses changes made during the week.',
      D: 'One incremental is insufficient; the entire chain is required.',
    },
    er: 'Tests incremental restore requiring full + full incremental chain.',
  },
  {
    t: 'Backups', s: 'Full backup', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Backup Types and Testing Requirements',
    q: 'A full backup is:',
    o: [
      'A complete copy of all system and user data',
      'A copy of only the files changed since yesterday',
      'A read-through review of the backup plan',
      'A scan for open network ports',
    ],
    a: 'A',
    wc: 'A full backup captures a complete copy of all objects and user data, enabling a complete restore from one set.',
    ww: {
      B: 'Copying only recent changes describes incremental/differential backups.',
      C: 'A read-through review is a checklist DR test.',
      D: 'Port scanning is a vulnerability-assessment activity.',
    },
    er: 'Recall of the full backup definition.',
  },
  {
    t: 'Backups', s: 'Backup verification', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Backup Data Testing and Verification',
    q: 'During a security assessment, the MOST important thing to verify about backups is that they:',
    o: [
      'Can actually be restored, and are retained/encrypted/archived per policy',
      'Are stored on the same server as production data',
      'Are never tested to avoid wear',
      'Use the brightest-colored tapes',
    ],
    a: 'A',
    wc: 'Backups must be tested for successful restoration and verified for retention, encryption, and proper archiving—an untested backup is unreliable.',
    ww: {
      B: 'Storing backups with production defeats their disaster-recovery purpose.',
      C: 'Backups must be tested; untested backups may fail when needed.',
      D: 'Tape color is irrelevant to backup integrity.',
    },
    er: 'Emphasizes restore-testing and proper backup handling.',
  },
  {
    t: 'Data Collection', s: 'Training verification', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Verifying Training and Awareness',
    q: 'Collecting security training and awareness data during an assessment helps the organization:',
    o: [
      'Track compliance with training requirements and identify gaps for emerging risks',
      'Eliminate the need for any technical controls',
      'Guarantee no employee will ever click a phishing link',
      'Replace the disaster recovery plan',
    ],
    a: 'A',
    wc: 'Training/awareness data verifies who has completed required training, tracks compliance, and reveals gaps relative to emerging risks.',
    ww: {
      B: 'Training complements, not replaces, technical controls.',
      C: 'Training reduces but cannot guarantee zero risky behavior.',
      D: 'Training data does not replace DR planning.',
    },
    er: 'Connects training data to compliance tracking and gap analysis.',
  },
  {
    t: 'DR Testing', s: 'Checklist test', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'A checklist (read-through) DR test involves:',
    o: [
      'Distributing the DR checklist to team members to review and provide feedback',
      'Cutting over production to the backup site',
      'Exploiting vulnerabilities with Metasploit',
      'Encrypting all backup tapes',
    ],
    a: 'A',
    wc: 'A checklist/read-through test distributes the DR plan/checklist for review and feedback—the least disruptive DR test.',
    ww: {
      B: 'Production cutover is a full interruption test.',
      C: 'Exploitation with Metasploit is a penetration-testing activity.',
      D: 'Encrypting tapes is a backup-handling control, not a DR test type.',
    },
    er: 'Recall of the checklist DR test.',
  },
  {
    t: 'Data Collection', s: 'Sources of data', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 6 > Security Test and Assessment > Sources of Measurement Data',
    q: 'Which TWO are valid sources of measurement data for a security assessment? (Select TWO.)',
    o: [
      'Risk assessment/analysis results',
      'Vulnerability assessment outcomes categorized by severity',
      'The CEO\'s favorite color',
      'The cafeteria menu',
    ],
    a: ['A', 'B'],
    wc: 'Risk assessment results and severity-categorized vulnerability outcomes (plus incident/recovery timelines) are valid measurement-data sources.',
    ww: {
      C: 'Personal color preference is not assessment data.',
      D: 'The cafeteria menu is irrelevant.',
    },
    er: 'Identifies legitimate measurement-data sources.',
  },
  {
    t: 'Security Audits', s: 'Audit report content', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Security Audit',
    q: 'A security audit report typically includes:',
    o: [
      'Compliance status and the perceived risk impact',
      'Only the source code of every application',
      'A list of employee salaries',
      'The office Wi-Fi password',
    ],
    a: 'A',
    wc: 'Audit reports communicate compliance status against governance/regulations and the perceived risk impact of findings.',
    ww: {
      B: 'Audits report on controls/compliance, not full source code.',
      C: 'Salaries are not audit-report content.',
      D: 'Publishing the Wi-Fi password would be a security risk, not audit content.',
    },
    er: 'Tests typical audit-report content.',
  },
  {
    t: 'Assessment Strategy', s: 'Define scope', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Security Test and Assessment Strategy',
    q: 'A critical FIRST step when building a security test and assessment strategy is to:',
    o: [
      'Define the scope of what will be assessed',
      'Immediately exploit production systems',
      'Delete all existing logs',
      'Disable monitoring to reduce noise',
    ],
    a: 'A',
    wc: 'Defining the scope establishes what systems, controls, and objectives the assessment covers, guiding all subsequent activities.',
    ww: {
      B: 'Exploiting production without scope/authorization is reckless and unauthorized.',
      C: 'Deleting logs destroys evidence and accountability.',
      D: 'Disabling monitoring reduces visibility during assessment.',
    },
    er: 'Tests scoping as a foundational assessment step.',
  },
  {
    t: 'DR Testing', s: 'Simulation test', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 6 > Security Test and Assessment > Disaster Recovery Test Types and Considerations',
    q: 'A simulation DR test is BEST described as:',
    o: [
      'A structured walkthrough applied to a specific disaster scenario, evaluating results and corrective actions',
      'A complete production cutover to the cloud',
      'A static analysis of application source code',
      'A scan of all open TCP ports',
    ],
    a: 'A',
    wc: 'A simulation test applies a structured walkthrough to a specific scenario (e.g., natural or man-made disaster), then evaluates results and corrective actions—without full production impact.',
    ww: {
      B: 'Full production cutover is a full interruption test.',
      C: 'Static source-code analysis is SAST, not a DR test.',
      D: 'Port scanning is a vulnerability-assessment activity.',
    },
    er: 'Recall of the simulation DR test.',
  },
  {
    t: 'Data Collection', s: 'Account lifecycle audit', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 6 > Security Test and Assessment > Account Management Lifecycle',
    q: 'During an assessment, an auditor finds several active accounts belonging to employees who left months ago. This finding MOST directly indicates a weakness in:',
    o: [
      'The account deprovisioning/auditing part of the account management lifecycle',
      'The data center cooling system',
      'The wireless encryption protocol',
      'The fire suppression system',
    ],
    a: 'A',
    wc: 'Lingering accounts for departed staff indicate failures in account auditing/deprovisioning within the account management lifecycle—an access risk.',
    ww: {
      B: 'Cooling is an environmental control, unrelated to orphaned accounts.',
      C: 'Wireless encryption does not govern account removal.',
      D: 'Fire suppression is a physical safety control.',
    },
    er: 'Maps orphaned accounts to account-lifecycle/deprovisioning weakness.',
  },
];
