// Domain 5 — Part 4: Access control models (DAC/MAC/RBAC/ABAC/rule-based/
// risk-based), authorization mechanisms, accountability, session management,
// and logical access concepts.
module.exports = [
  // ---- Access control models ----
  {
    t: 'Access Control Models', s: 'DAC', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Discretionary Access Control (DAC)',
    q: 'In Discretionary Access Control (DAC), access decisions are based on:',
    o: [
      'The object OWNER granting permissions to subjects, typically via an ACL',
      'Security labels and clearances enforced by a central authority',
      'A calculated real-time risk score',
      'Predefined firewall port/protocol rules',
    ],
    a: 'A',
    wc: 'In DAC, the object owner determines who may access the object, usually through an Access Control List (ACL); it is flexible but offers weaker, identity-based control.',
    ww: {
      B: 'Labels/clearances enforced centrally describe MAC.',
      C: 'A real-time risk score describes risk-based access control.',
      D: 'Port/protocol rules describe rule-based access control.',
    },
    er: 'Maps owner-set, ACL-based access to DAC.',
  },
  {
    t: 'Access Control Models', s: 'MAC', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Mandatory Access Control (MAC)',
    q: 'Mandatory Access Control (MAC) enforces access using:',
    o: [
      'Security labels on subjects and objects compared against the subject\'s clearance',
      'The discretion of the individual data owner',
      'Group/role membership only',
      'A list of allowed TCP ports',
    ],
    a: 'A',
    wc: 'MAC is non-discretionary: access is determined by comparing security labels/classifications on objects against the subject\'s clearance, common in military/highly sensitive environments.',
    ww: {
      B: 'Owner discretion describes DAC.',
      C: 'Role/group membership describes RBAC.',
      D: 'Allowed ports describe rule-based access control.',
    },
    er: 'Maps label/clearance enforcement to MAC.',
  },
  {
    t: 'Access Control Models', s: 'RBAC', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Role-Based Access Control (RBAC)',
    q: 'Role-Based Access Control (RBAC) grants access based on:',
    o: [
      'A subject\'s assigned role or group, helping reduce privilege creep',
      'Security labels and clearances',
      'The object owner\'s personal discretion',
      'A real-time geolocation risk score',
    ],
    a: 'A',
    wc: 'RBAC assigns permissions to roles/groups and users inherit them via role membership, streamlining administration and reducing privilege creep—useful for high-turnover environments.',
    ww: {
      B: 'Labels/clearances describe MAC.',
      C: 'Owner discretion describes DAC.',
      D: 'A geolocation risk score describes risk-based access control.',
    },
    er: 'Maps role/group-based access to RBAC.',
  },
  {
    t: 'Access Control Models', s: 'ABAC', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Attribute-Based Access Control (ABAC)',
    q: 'Attribute-Based Access Control (ABAC) makes decisions based on:',
    o: [
      'Multiple attributes of the subject, object, action, and environment',
      'Only the object owner\'s preference',
      'Only the subject\'s single role',
      'Only the destination port number',
    ],
    a: 'A',
    wc: 'ABAC (also called policy-based access control) evaluates combinations of subject, object, action, and environmental attributes (e.g., clearance, department, time, IP), enabling fine-grained policies often via XACML.',
    ww: {
      B: 'Owner-only preference describes DAC.',
      C: 'A single role describes RBAC, which is coarser than ABAC.',
      D: 'Port-only decisions describe rule-based access control.',
    },
    er: 'Maps multi-attribute, fine-grained decisions to ABAC.',
  },
  {
    t: 'Access Control Models', s: 'Rule-based', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Rule-Based Access Control',
    q: 'Rule-based access control, as used in devices like firewalls, grants or denies access based on:',
    o: [
      'Predefined rules such as port number and protocol',
      'The subject\'s biometric template',
      'The object owner\'s discretion',
      'A user\'s job title alone',
    ],
    a: 'A',
    wc: 'Rule-based access control applies predefined rules/restrictions (e.g., allow HTTP on port 80) regardless of user identity, common in firewalls and IPS.',
    ww: {
      B: 'Biometric templates relate to authentication, not rule-based ACLs.',
      C: 'Owner discretion describes DAC.',
      D: 'Job-title/role-based access is RBAC.',
    },
    er: 'Maps predefined port/protocol rules to rule-based access control.',
  },
  {
    t: 'Access Control Models', s: 'Risk-based (RAdAC)', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Risk-Based Access Control',
    q: 'A user logs in from an unrecognized IP on an untrusted network, so the system requires additional authentication factors before granting access. Which access control model is this?',
    o: [
      'Risk-based (risk-adaptive) access control',
      'Discretionary access control',
      'Mandatory access control',
      'Rule-based access control',
    ],
    a: 'A',
    wc: 'Risk-based (RAdAC) access control dynamically adjusts requirements based on a calculated risk level (device, location, sensitivity), e.g., demanding MFA for higher-risk logins.',
    ww: {
      B: 'DAC relies on owner-set permissions, not dynamic risk.',
      C: 'MAC uses static labels/clearances.',
      D: 'Rule-based uses fixed rules, not adaptive risk scoring.',
    },
    er: 'Maps adaptive, risk-driven authentication to risk-based access control.',
  },
  {
    t: 'Access Control Models', s: 'Model selection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Mandatory Access Control (MAC)',
    q: 'A defense agency must enforce that data classified "Top Secret" is only accessible to subjects with Top Secret clearance, with no owner discretion allowed. Which model is MOST appropriate?',
    o: [
      'Mandatory Access Control (MAC)',
      'Discretionary Access Control (DAC)',
      'Role-Based Access Control (RBAC)',
      'Rule-Based Access Control',
    ],
    a: 'A',
    wc: 'MAC enforces non-discretionary access using labels/clearances—ideal for classified environments where owners cannot override the policy.',
    ww: {
      B: 'DAC allows owner discretion, which the requirement forbids.',
      C: 'RBAC groups by role but does not enforce clearance/label dominance like MAC.',
      D: 'Rule-based controls (e.g., port rules) do not enforce classification clearance.',
    },
    er: 'Maps clearance-enforced, non-discretionary classification to MAC.',
  },
  {
    t: 'Access Control Models', s: 'RBAC turnover', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Role-Based Access Control (RBAC)',
    q: 'A call center with very high staff turnover wants to simplify granting and revoking access as employees join and leave. Which access control model BEST fits?',
    o: [
      'RBAC — assign access to roles, then add/remove users from roles',
      'DAC — let each employee set their own permissions',
      'MAC — assign clearances and labels to every file',
      'Risk-based — recompute risk on every keystroke',
    ],
    a: 'A',
    wc: 'RBAC streamlines administration in high-turnover environments: access is tied to roles, so onboarding/offboarding is just role assignment/removal.',
    ww: {
      B: 'DAC self-set permissions would be chaotic and inconsistent at scale.',
      C: 'MAC labeling every file is heavy and aimed at classified data, not call-center turnover.',
      D: 'Per-keystroke risk scoring is unnecessary overhead for this need.',
    },
    er: 'Maps high-turnover administration efficiency to RBAC.',
  },
  {
    t: 'Access Control Models', s: 'Model-to-basis mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 5 > Access and Authorization > Access Control Models',
    p: ['DAC', 'MAC', 'RBAC', 'ABAC'],
    q: 'Match each access control model (1-4) to the basis for its access decisions (A-D).',
    o: [
      'Security labels/clearances set by a central authority',
      'Owner discretion via ACLs (identity-based)',
      'Multiple attributes (subject, object, action, environment)',
      'Role or group membership',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'DAC → owner discretion/ACLs (B); MAC → labels/clearances (A); RBAC → role/group membership (D); ABAC → multiple attributes (C).',
    ww: {},
    er: 'Tests mapping of access control models to their decision basis.',
  },
  {
    t: 'Access Control Models', s: 'DAC weakness', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Discretionary Access Control (DAC)',
    q: 'A noted security weakness of DAC compared to MAC is that DAC:',
    o: [
      'Relies on individual owners\' discretion, making consistent, fine-grained control harder to guarantee',
      'Cannot use access control lists at all',
      'Always requires a security clearance',
      'Is only usable on wireless networks',
    ],
    a: 'A',
    wc: 'Because DAC delegates access decisions to object owners, enforcement can be inconsistent and harder to control centrally—weaker than label-driven MAC for sensitive data.',
    ww: {
      B: 'DAC specifically uses ACLs.',
      C: 'Clearances are a MAC concept, not required by DAC.',
      D: 'DAC is not limited to wireless networks.',
    },
    er: 'Tests the discretion-driven weakness of DAC.',
  },
  {
    t: 'Access Control Models', s: 'Non-discretionary', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Non-Discretionary Access Control',
    q: 'In non-discretionary access control, access rights are determined by:',
    o: [
      'A central authority or policy, not the individual object owner',
      'Each user for their own files',
      'The destination MAC address only',
      'The current temperature of the server room',
    ],
    a: 'A',
    wc: 'Non-discretionary models (e.g., MAC, RBAC) have a central authority/policy set access rights, rather than leaving them to object owners (DAC).',
    ww: {
      B: 'Per-user discretion is DAC, which is discretionary.',
      C: 'MAC-address-only decisions are a Layer 2 filter, not this concept.',
      D: 'Room temperature is an environmental control.',
    },
    er: 'Tests the central-authority basis of non-discretionary control.',
  },
  {
    t: 'Access Control Models', s: 'ABAC attributes', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Access and Authorization > Attribute-Based Access Control (ABAC)',
    q: 'Which TWO are categories of attributes that ABAC can evaluate? (Select TWO.)',
    o: ['Subject attributes (e.g., clearance, department)', 'Environmental attributes (e.g., time, IP address)', 'The font used in the document', 'The color of the user\'s desk'],
    a: ['A', 'B'],
    wc: 'ABAC evaluates subject, object, action, and environmental attributes; clearance/department (subject) and time/IP (environmental) are valid examples.',
    ww: {
      C: 'Document font is not an access-control attribute.',
      D: 'Desk color is irrelevant to access decisions.',
    },
    er: 'Identifies legitimate ABAC attribute categories.',
  },
  // ---- Authorization mechanisms ----
  {
    t: 'Authorization', s: 'Implicit deny', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'The principle of "implicit deny" means that:',
    o: [
      'Access is denied by default unless it is explicitly granted',
      'Access is allowed by default unless explicitly denied',
      'All users get administrator access',
      'Logging is turned off by default',
    ],
    a: 'A',
    wc: 'Implicit deny ("permit by exception, deny by default") denies any access not explicitly allowed, a secure default.',
    ww: {
      B: 'Allow-by-default is the opposite (and insecure) approach.',
      C: 'Implicit deny restricts, not grants, broad access.',
      D: 'Implicit deny concerns access, not logging configuration.',
    },
    er: 'Recall of the deny-by-default principle.',
  },
  {
    t: 'Authorization', s: 'Permissions/rights/privileges', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'In the guide\'s authorization terminology, "privileges" are best defined as:',
    o: [
      'The combination of a subject\'s permissions and rights',
      'Only the subject\'s ability to access an object',
      'Only the subject\'s authority to perform specific actions',
      'A list of all denied users',
    ],
    a: 'A',
    wc: 'Privileges are the combination of permissions (ability to access an object) and rights (authority to perform actions).',
    ww: {
      B: 'Ability to access an object alone is a permission.',
      C: 'Authority to perform actions alone is a right.',
      D: 'A deny list is not the definition of privileges.',
    },
    er: 'Distinguishes privileges from permissions and rights.',
  },
  {
    t: 'Authorization', s: 'Access control matrix vs capability table', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'How does a capability table differ from an access control matrix?',
    o: [
      'A capability table is subject-focused (lists what a subject can access), while an ACL/matrix is object-focused',
      'A capability table is object-focused and a matrix is subject-focused',
      'They are identical in every way',
      'A capability table is a physical security barrier',
    ],
    a: 'A',
    wc: 'A capability table lists a subject\'s capabilities (subject-focused); an access control list/matrix is organized by object (object-focused). They are complementary views.',
    ww: {
      B: 'This reverses the focus of each.',
      C: 'They present different (subject vs object) views.',
      D: 'A capability table is a logical construct, not a physical barrier.',
    },
    er: 'Tests subject-focused (capability) vs object-focused (matrix/ACL).',
  },
  {
    t: 'Authorization', s: 'Content vs context-dependent', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Content-Dependent vs. Context-Dependent Controls',
    q: 'A database hides specific salary columns from users not in HR based on the data being viewed. This is an example of which control?',
    o: [
      'Content-dependent control (based on the type/content of the object)',
      'Context-dependent control (based on the sequence/situation of actions)',
      'Rule-based firewall control',
      'Physical access control',
    ],
    a: 'A',
    wc: 'Content-dependent controls restrict access based on the actual content/type of the object (e.g., specific sensitive columns), independent of the request sequence.',
    ww: {
      B: 'Context-dependent controls depend on the situation/sequence of actions, not the data content itself.',
      C: 'A firewall rule filters network traffic, not database column content.',
      D: 'Physical access control governs facility entry, not data columns.',
    },
    er: 'Distinguishes content-dependent from context-dependent controls.',
  },
  {
    t: 'Authorization', s: 'Constrained interface', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'A constrained interface restricts access by:',
    o: [
      'Limiting the actions/options available based on the subject\'s privilege level',
      'Encrypting the network connection',
      'Assigning IP addresses to users',
      'Physically locking the server rack',
    ],
    a: 'A',
    wc: 'A constrained interface only exposes the functions/options a subject is privileged to use, implementing least privilege at the interface.',
    ww: {
      B: 'Connection encryption is a transport control, not interface constraint.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'Locking a rack is a physical control.',
    },
    er: 'Maps privilege-limited interfaces to constrained interfaces.',
  },
  {
    t: 'Authorization', s: 'Separation of duties', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Authorization Principles',
    q: 'Separation of duties as an authorization principle is designed to:',
    o: [
      'Divide critical tasks among multiple people to prevent any one person having excessive control',
      'Give one administrator complete control for efficiency',
      'Allow users to approve their own requests',
      'Remove the need for least privilege',
    ],
    a: 'A',
    wc: 'Separation of duties splits sensitive tasks so no single individual can complete a critical process alone, reducing fraud and error.',
    ww: {
      B: 'Concentrating control in one person defeats separation of duties.',
      C: 'Self-approval undermines the control.',
      D: 'SoD complements, not replaces, least privilege.',
    },
    er: 'Recall of separation of duties.',
  },
  {
    t: 'Authorization', s: 'Least privilege', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Authorization Principles',
    q: 'Least privilege in authorization means providing subjects with:',
    o: [
      'Only the access rights necessary to perform their role',
      'The maximum access in case it is needed later',
      'Administrator rights by default',
      'Access to all data in the organization',
    ],
    a: 'A',
    wc: 'Least privilege grants only the access necessary for a subject\'s duties, limiting the impact of compromise or misuse.',
    ww: {
      B: 'Granting extra "just in case" access violates least privilege.',
      C: 'Default admin rights are excessive.',
      D: 'All-data access ignores need-to-know and least privilege.',
    },
    er: 'Recall of least privilege.',
  },
  {
    t: 'Authorization', s: 'Need to know', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Authorization Principles',
    q: 'A user has the technical permission to open a shared folder but should not see one specific file unrelated to their duties. Restricting that file enforces:',
    o: ['Need to know', 'Implicit allow', 'Mandatory vacation', 'Open design'],
    a: 'A',
    wc: 'Need to know restricts access to specific information to only those who require it for their duties, even where broader permissions exist.',
    ww: {
      B: '"Implicit allow" is insecure and not the principle here.',
      C: 'Mandatory vacation is a fraud-detection control.',
      D: 'Open design is a secure-design principle, not access scoping.',
    },
    er: 'Distinguishes need-to-know from least privilege.',
  },
  {
    t: 'Authorization', s: 'Authorization principles', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Access and Authorization > Authorization Principles',
    q: 'Which TWO are authorization principles emphasized in the guide? (Select TWO.)',
    o: ['Separation of duties', 'Least privilege', 'Security through obscurity', 'Implicit allow'],
    a: ['A', 'B'],
    wc: 'Separation of duties and least privilege (with need-to-know) are core authorization principles.',
    ww: {
      C: 'Security through obscurity is discouraged, not an authorization principle.',
      D: '"Implicit allow" is insecure; the secure default is implicit deny.',
    },
    er: 'Identifies sound authorization principles.',
  },
  // ---- Accountability ----
  {
    t: 'Accountability', s: 'Definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Accountability',
    q: 'Accountability in access management ensures that:',
    o: [
      'Subjects can be held responsible for their actions, supporting non-repudiation',
      'All data is encrypted at rest',
      'Networks never experience downtime',
      'Passwords are stored in plaintext',
    ],
    a: 'A',
    wc: 'Accountability tracks and verifies subjects\' actions so they can be held responsible, supporting non-repudiation.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Accountability does not guarantee uptime.',
      D: 'Plaintext password storage is an insecure practice, not accountability.',
    },
    er: 'Recall of accountability and its link to non-repudiation.',
  },
  {
    t: 'Accountability', s: 'Implementation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Implementing Accountability',
    q: 'Which mechanism is MOST fundamental to implementing accountability?',
    o: [
      'System logging/auditing of subject actions',
      'Disabling all user accounts',
      'Removing the identity provider',
      'Turning off encryption',
    ],
    a: 'A',
    wc: 'Logging and auditing of actions are fundamental to accountability—recording who did what, when, to support investigation and non-repudiation.',
    ww: {
      B: 'Disabling accounts prevents work, not enables accountability.',
      C: 'Removing the identity provider would undermine authentication and tracking.',
      D: 'Disabling encryption is unrelated and insecure.',
    },
    er: 'Maps accountability to logging/auditing.',
  },
  {
    t: 'Accountability', s: 'Log protection', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Implementing Accountability',
    q: 'An attacker who gains admin access tries to delete the audit logs to hide their actions. Which control BEST preserves accountability?',
    o: [
      'Protecting logs from tampering (e.g., write-once/remote log storage with restricted access)',
      'Storing logs on the same account the admin controls',
      'Disabling logging during maintenance windows',
      'Allowing all users to edit logs',
    ],
    a: 'A',
    wc: 'Protecting logs from tampering—e.g., forwarding to a secured/append-only remote log store with strict access—preserves accountability even if an endpoint is compromised.',
    ww: {
      B: 'Storing logs where the admin can alter them defeats accountability.',
      C: 'Disabling logging creates blind spots attackers exploit.',
      D: 'Allowing anyone to edit logs destroys their integrity.',
    },
    er: 'Tests protecting log integrity to preserve accountability.',
  },
  {
    t: 'Accountability', s: 'Non-repudiation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Key Benefits',
    q: 'Accountability supports non-repudiation by:',
    o: [
      'Linking actions to authenticated subjects so they cannot credibly deny performing them',
      'Encrypting the corporate WAN',
      'Assigning dynamic IP addresses',
      'Suppressing fires in the data center',
    ],
    a: 'A',
    wc: 'By tying logged actions to authenticated identities, accountability prevents subjects from denying actions they performed (non-repudiation).',
    ww: {
      B: 'WAN encryption is unrelated to non-repudiation linkage.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Connects accountability to non-repudiation.',
  },
  // ---- Session management ----
  {
    t: 'Session Management', s: 'Session timeout', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Session Management',
    q: 'A session timeout improves security by:',
    o: [
      'Automatically ending an inactive session and requiring re-authentication',
      'Permanently disabling the user account',
      'Encrypting the user\'s files',
      'Assigning a new IP address',
    ],
    a: 'A',
    wc: 'Session timeouts end inactive sessions after a set period, reducing the risk of an unattended, still-authenticated session being hijacked.',
    ww: {
      B: 'A timeout ends a session; it does not disable the account.',
      C: 'Timeouts do not encrypt files.',
      D: 'Timeouts do not assign IP addresses.',
    },
    er: 'Recall of session timeout purpose.',
  },
  {
    t: 'Session Management', s: 'Session ID', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Session Management',
    q: 'A session ID is used to:',
    o: [
      'Bind a user\'s authenticated credentials to an active session',
      'Encrypt the hard drive',
      'Provide backup power',
      'Resolve domain names',
    ],
    a: 'A',
    wc: 'A session ID ties the user\'s credentials/state to an active session, and must be protected (e.g., against hijacking/fixation).',
    ww: {
      B: 'Disk encryption is a separate control.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Name resolution is DNS.',
    },
    er: 'Recall of the session ID purpose.',
  },
  {
    t: 'Session Management', s: 'Session hijacking defense', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Session Management',
    q: 'To reduce the risk of session hijacking on a web application, which combination is MOST effective?',
    o: [
      'Use unpredictable session IDs over TLS and enforce idle/absolute session timeouts',
      'Embed the user password in every URL',
      'Reuse the same session ID for all users',
      'Disable HTTPS to improve speed',
    ],
    a: 'A',
    wc: 'Strong, random session IDs transmitted over TLS, combined with idle/absolute timeouts, significantly reduce hijacking/fixation risk.',
    ww: {
      B: 'Putting passwords in URLs exposes them in logs/history.',
      C: 'Reusing one session ID for all users is catastrophic.',
      D: 'Disabling HTTPS exposes session tokens to interception.',
    },
    er: 'Tests layered defenses against session hijacking.',
  },
  // ---- Logical access concepts ----
  {
    t: 'Logical Access', s: 'Subject vs object', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Subjects and Objects in Logical Access',
    q: 'In access control terminology, a "subject" is:',
    o: [
      'An active entity (user, program, or process) that requests access to an object',
      'A passive resource being accessed',
      'A fire suppression system',
      'A backup generator',
    ],
    a: 'A',
    wc: 'A subject is the active entity (user, program, script, service) that acts on an object (the passive resource being accessed).',
    ww: {
      B: 'A passive resource being accessed is the object, not the subject.',
      C: 'Fire suppression is a physical control.',
      D: 'A generator provides backup power.',
    },
    er: 'Distinguishes subject (active) from object (passive).',
  },
  {
    t: 'Logical Access', s: 'Roles interchange', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Subjects and Objects in Logical Access',
    q: 'A web server requests data from a database, then returns it to a user\'s browser. Regarding the database transaction, the web server is acting as the ____.',
    o: [
      'Subject (it is the active entity requesting the object/data)',
      'Object (it is the passive resource)',
      'Reference monitor',
      'Identity provider',
    ],
    a: 'A',
    wc: 'Subject/object roles are relative: when the web server requests data from the database, the server is the active subject and the database is the object. Roles interchange based on the access.',
    ww: {
      B: 'In this transaction the database (not the web server) is the passive object.',
      C: 'A reference monitor mediates access; it is not the requesting server here.',
      D: 'An identity provider issues identity assertions, unrelated to this DB request.',
    },
    er: 'Tests that subject/object roles interchange by context.',
  },
  {
    t: 'Logical Access', s: 'Logical access goals', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Goals in Controlling Access',
    q: 'The goals of controlling logical access align directly with which security model?',
    o: [
      'The CIA triad (confidentiality, integrity, availability)',
      'The fire triangle (oxygen, heat, fuel)',
      'The OSI model layers',
      'The TCP three-way handshake',
    ],
    a: 'A',
    wc: 'Logical access control aims to prevent unauthorized disclosure (confidentiality), maintain authorized-only changes (integrity), and ensure availability for authorized subjects—the CIA triad.',
    ww: {
      B: 'The fire triangle is a physical-safety concept.',
      C: 'The OSI model describes networking layers.',
      D: 'The TCP handshake establishes a connection.',
    },
    er: 'Maps logical-access goals to the CIA triad.',
  },
  {
    t: 'Access Control Models', s: 'DAC ACL', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Discretionary Access Control (DAC)',
    q: 'DAC commonly tracks which subjects may access an object using a(n):',
    o: ['Access Control List (ACL)', 'Fire suppression plan', 'Subnet mask', 'UPS battery'],
    a: 'A',
    wc: 'DAC uses Access Control Lists (ACLs) to record which subjects have which permissions on an object.',
    ww: {
      B: 'A fire suppression plan is a physical-safety document.',
      C: 'A subnet mask defines network ranges.',
      D: 'A UPS battery provides backup power.',
    },
    er: 'Maps DAC permission tracking to ACLs.',
  },
  {
    t: 'Access Control Models', s: 'MAC environments', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Mandatory Access Control (MAC)',
    q: 'MAC is most commonly used in environments handling:',
    o: [
      'Highly sensitive data such as national security, PII, or PHI',
      'Public marketing brochures only',
      'Anonymous guest Wi-Fi',
      'Disposable test data with no value',
    ],
    a: 'A',
    wc: 'MAC\'s rigid label/clearance enforcement suits highly sensitive environments (military/government, regulated PII/PHI).',
    ww: {
      B: 'Public brochures need little access control.',
      C: 'Guest Wi-Fi does not require MAC labeling.',
      D: 'Disposable test data does not warrant MAC overhead.',
    },
    er: 'Maps MAC to highly sensitive environments.',
  },
  {
    t: 'Authorization', s: 'Object-focused control', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'An access control list (ACL) attached to a file is an example of which type of access view?',
    o: ['Object-focused (lists which subjects can access the object)', 'Subject-focused (lists a subject\'s capabilities)', 'Risk-based scoring', 'Biometric enrollment'],
    a: 'A',
    wc: 'An ACL is organized by the object, listing which subjects have which permissions on it (object-focused); a capability table is subject-focused.',
    ww: {
      B: 'A subject-focused list is a capability table, not an ACL.',
      C: 'Risk-based scoring is a dynamic model, not an ACL view.',
      D: 'Biometric enrollment is an authentication process.',
    },
    er: 'Maps ACLs to the object-focused view.',
  },
  {
    t: 'Accountability', s: 'Audit value', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Key Benefits',
    q: 'Besides assigning responsibility, robust accountability/auditing can also:',
    o: [
      'Reveal design vulnerabilities that allow unauthorized actions',
      'Replace the need for authentication',
      'Encrypt all stored data automatically',
      'Eliminate the need for backups',
    ],
    a: 'A',
    wc: 'Reviewing accountability data can expose gaps/vulnerabilities in system design that permit unauthorized actions, informing improvements.',
    ww: {
      B: 'Auditing complements, not replaces, authentication.',
      C: 'Auditing does not encrypt data.',
      D: 'Backups remain necessary for availability.',
    },
    er: 'Tests the design-insight benefit of accountability.',
  },
  {
    t: 'Access Control Models', s: 'Privilege creep', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Access and Authorization > Role-Based Access Control (RBAC)',
    q: 'A long-tenured employee has accumulated access from every past role (privilege creep). Which TWO practices BEST prevent this? (Select TWO.)',
    o: [
      'Periodic access reviews/recertification',
      'Role-based access tied to current duties, removing old access on transfer',
      'Disabling all audit logging',
      'Granting permanent administrator rights to all staff',
    ],
    a: ['A', 'B'],
    wc: 'Periodic access reviews and RBAC tied to current roles (removing old access at transfer) prevent the accumulation of unneeded access (privilege creep).',
    ww: {
      C: 'Disabling logging removes visibility and worsens security.',
      D: 'Permanent admin rights for all is excessive standing privilege, the opposite of the goal.',
    },
    er: 'Identifies practices that prevent privilege creep.',
  },
  {
    t: 'Authorization', s: 'Rights definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'In authorization terms, a "right" refers to a subject\'s:',
    o: [
      'Authority to conduct specific actions (e.g., shut down a system)',
      'Physical office location',
      'Choice of web browser',
      'Network bandwidth allocation',
    ],
    a: 'A',
    wc: 'A right is the authority to perform specific actions; permissions concern access to objects, and privileges combine the two.',
    ww: {
      B: 'Office location is not an authorization right.',
      C: 'Browser choice is irrelevant to authorization rights.',
      D: 'Bandwidth allocation is a network resource matter.',
    },
    er: 'Recall of "rights" in authorization.',
  },
  {
    t: 'Access Control Models', s: 'Rule-based use', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Rule-Based Access Control',
    q: 'Rule-based access control is MOST commonly seen in which type of device?',
    o: ['Firewalls and intrusion prevention systems', 'Biometric fingerprint readers', 'Backup generators', 'HVAC units'],
    a: 'A',
    wc: 'Rule-based access control (allow/deny by predefined rules like port/protocol) is characteristic of firewalls and IPS.',
    ww: {
      B: 'Fingerprint readers perform biometric authentication.',
      C: 'Generators provide backup power.',
      D: 'HVAC units manage environment, not access rules.',
    },
    er: 'Maps rule-based control to firewalls/IPS.',
  },
  {
    t: 'Authorization', s: 'Deny by default scenario', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'A new application is configured so that any access not explicitly permitted is blocked. A user with no assigned permissions tries to open a record and is denied. This reflects which principle?',
    o: ['Implicit deny (deny by default)', 'Implicit allow', 'Mandatory vacation', 'Privilege creep'],
    a: 'A',
    wc: 'Blocking anything not explicitly permitted is implicit deny ("permit by exception, deny by default")—a secure default.',
    ww: {
      B: 'Implicit allow would have granted the access.',
      C: 'Mandatory vacation is a fraud-detection control.',
      D: 'Privilege creep is accumulation of excess access, not a default-deny outcome.',
    },
    er: 'Maps default-blocking behavior to implicit deny.',
  },
  {
    t: 'Access Control Models', s: 'ABAC vs RBAC', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Attribute-Based Access Control (ABAC)',
    q: 'Compared to RBAC, ABAC provides FINER-grained control primarily because it can:',
    o: [
      'Factor in many attributes (e.g., time, location, device) beyond a single role',
      'Only ever consider the user\'s role',
      'Ignore the object\'s sensitivity',
      'Eliminate the need for any policy',
    ],
    a: 'A',
    wc: 'ABAC evaluates multiple attributes (subject, object, action, environment), enabling more granular, context-aware decisions than role-only RBAC.',
    ww: {
      B: 'Considering only a role describes RBAC, which is coarser.',
      C: 'ABAC can use object sensitivity as an attribute.',
      D: 'ABAC is policy-driven; it does not remove the need for policy.',
    },
    er: 'Tests why ABAC is finer-grained than RBAC.',
  },
  {
    t: 'Accountability', s: 'Accountability example', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Accountability',
    q: 'Which activity BEST demonstrates accountability in action?',
    o: [
      'Logs that record which user accessed and deleted a sensitive file',
      'A faster internet connection for the office',
      'A brighter parking-lot light',
      'A larger UPS battery',
    ],
    a: 'A',
    wc: 'Recording who accessed/modified/deleted sensitive data is accountability in action—enabling investigation and non-repudiation.',
    ww: {
      B: 'Bandwidth is unrelated to accountability.',
      C: 'Lighting is a physical/CPTED control.',
      D: 'A UPS supports availability, not action attribution.',
    },
    er: 'Identifies a concrete accountability example.',
  },
  {
    t: 'Session Management', s: 'Re-authentication', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Session Management',
    q: 'After a session times out due to inactivity, the user must:',
    o: [
      'Re-authenticate to start a new session',
      'Wait for the network to reboot',
      'Reinstall the operating system',
      'Change their MAC address',
    ],
    a: 'A',
    wc: 'A timed-out session requires re-authentication before a new session is established, limiting unauthorized use of an abandoned session.',
    ww: {
      B: 'The network does not need to reboot for re-authentication.',
      C: 'No OS reinstall is required.',
      D: 'MAC address changes are unrelated to session re-authentication.',
    },
    er: 'Tests the re-authentication requirement after timeout.',
  },
  {
    t: 'Access Control Models', s: 'Model overview', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Control Models',
    q: 'The overall purpose of any access control model is to govern:',
    o: [
      'How a subject is permitted to interact with an object',
      'The color scheme of the user interface',
      'The brand of network cabling used',
      'The office seating arrangement',
    ],
    a: 'A',
    wc: 'Access control models define how subjects (users, devices, processes) are authorized to interact with objects (files, services, functions).',
    ww: {
      B: 'UI color is a cosmetic choice.',
      C: 'Cabling brand is a procurement detail.',
      D: 'Seating arrangement is unrelated to logical access control.',
    },
    er: 'Recall of the purpose of access control models.',
  },
  {
    t: 'Authorization', s: 'Privilege definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Access Authorization',
    q: 'A "permission," in authorization terms, refers to a subject\'s:',
    o: [
      'Ability to access an object',
      'Authority to perform any action anywhere',
      'Physical clearance badge',
      'Biometric template',
    ],
    a: 'A',
    wc: 'A permission is the ability to access an object; combined with rights (authority to act), they form privileges.',
    ww: {
      B: 'Authority to perform actions is a "right," not a permission.',
      C: 'A clearance badge is a physical credential, not the logical permission concept.',
      D: 'A biometric template is authentication data, not a permission.',
    },
    er: 'Recall of "permission" in authorization.',
  },
  {
    t: 'Access Control Models', s: 'Risk-based factors', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Access and Authorization > Risk-Based Access Control',
    q: 'Which TWO contextual factors might a risk-based access control system evaluate? (Select TWO.)',
    o: ['Device type/trust', 'Geolocation of the request', 'The user\'s favorite food', 'The office wall color'],
    a: ['A', 'B'],
    wc: 'Risk-based access control uses contextual data such as device trust and geolocation (plus network attributes and object sensitivity) to calculate risk.',
    ww: {
      C: 'Personal food preferences are irrelevant to access risk.',
      D: 'Wall color is irrelevant to access decisions.',
    },
    er: 'Identifies legitimate risk-based contextual factors.',
  },
  {
    t: 'Logical Access', s: 'Access definition', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Controlling Logical Access',
    q: 'Logical access control manages a subject\'s ability to:',
    o: [
      'Open, modify, execute, or delete data and resources',
      'Physically enter the building lobby',
      'Adjust the thermostat in the lobby',
      'Park in the company garage',
    ],
    a: 'A',
    wc: 'Logical access control governs privileges to open, modify, execute, or delete data/resources, protecting confidentiality, integrity, and availability.',
    ww: {
      B: 'Physical entry is a physical access control.',
      C: 'Thermostat control is an environmental matter.',
      D: 'Parking is a physical/facility concern.',
    },
    er: 'Distinguishes logical from physical access control.',
  },
  {
    t: 'Authorization', s: 'SoD example', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 5 > Access and Authorization > Authorization Principles',
    q: 'A finance process is designed so the person who creates a vendor payment cannot also approve it. This control is:',
    o: ['Separation of duties', 'Single sign-on', 'Implicit allow', 'Session timeout'],
    a: 'A',
    wc: 'Requiring different people to create and approve a payment is separation of duties, preventing one individual from completing a sensitive transaction alone.',
    ww: {
      B: 'SSO is an authentication convenience, not a duty split.',
      C: 'Implicit allow is an insecure default, unrelated here.',
      D: 'A session timeout ends inactive sessions; it is not duty separation.',
    },
    er: 'Maps create-vs-approve separation to separation of duties.',
  },
  {
    t: 'Access Control Models', s: 'Identity-based', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Discretionary Access Control (DAC)',
    q: 'DAC is often described as "identity-based" access control because access depends on:',
    o: [
      'The identity of the individual subject and the owner\'s granted permissions',
      'The classification label of the data only',
      'The current network risk score',
      'The firewall rule set',
    ],
    a: 'A',
    wc: 'DAC ties access to the subject\'s identity and the owner-granted permissions (via ACLs), hence "identity-based."',
    ww: {
      B: 'Classification-label enforcement describes MAC.',
      C: 'Network risk scoring describes risk-based access control.',
      D: 'Firewall rule sets describe rule-based access control.',
    },
    er: 'Maps identity-based access to DAC.',
  },
  {
    t: 'Accountability', s: 'Strong access controls', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Access and Authorization > Implementing Accountability',
    q: 'To support accountability, access to logs and sensitive files should be governed by:',
    o: [
      'Strong authentication and least-privilege access controls',
      'Anonymous, unrestricted access',
      'A single shared account for convenience',
      'No authentication during business hours',
    ],
    a: 'A',
    wc: 'Strong authentication and least privilege over logs/sensitive files protect their integrity and ensure actions are attributable—supporting accountability.',
    ww: {
      B: 'Anonymous access destroys attribution.',
      C: 'Shared accounts eliminate individual accountability.',
      D: 'Removing authentication breaks accountability.',
    },
    er: 'Connects strong access controls to accountability.',
  },
];
