// Domain 5 — Part 2: Authentication factors (Type 1/2/3, SFA/2FA/MFA,
// context-based), biometrics (physiological/behavioral, FRR/FAR/CER),
// directory services (LDAP), and AAA (RADIUS/TACACS+/Diameter).
module.exports = [
  // ---- Authentication factors ----
  {
    t: 'Authentication Factors', s: 'Type 1 (know)', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Factor Types',
    q: 'A password is an example of which authentication factor type?',
    o: ['Type 1 — Something you know', 'Type 2 — Something you have', 'Type 3 — Something you are', 'Type 4 — Somewhere you are'],
    a: 'A',
    wc: 'A password is knowledge-based (Type 1 — something you know).',
    ww: {
      B: 'Type 2 is a possession such as a token or smart card.',
      C: 'Type 3 is a biometric trait.',
      D: 'Location is a contextual factor, not a primary Type.',
    },
    er: 'Recall of Type 1 (knowledge) factors.',
  },
  {
    t: 'Authentication Factors', s: 'Type 2 (have)', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Factor Types',
    q: 'A hardware token or smart card represents which authentication factor type?',
    o: ['Type 2 — Something you have', 'Type 1 — Something you know', 'Type 3 — Something you are', 'A context-based factor'],
    a: 'A',
    wc: 'A token or smart card is a possession-based factor (Type 2 — something you have).',
    ww: {
      B: 'Type 1 is knowledge (e.g., a password/PIN).',
      C: 'Type 3 is a biometric.',
      D: 'Context-based factors (e.g., location) are not Type 2.',
    },
    er: 'Recall of Type 2 (possession) factors.',
  },
  {
    t: 'Authentication Factors', s: 'Type 3 (are)', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Factor Types',
    q: 'A fingerprint scan is which authentication factor type?',
    o: ['Type 3 — Something you are', 'Type 1 — Something you know', 'Type 2 — Something you have', 'Something you do'],
    a: 'A',
    wc: 'A fingerprint is a biometric trait (Type 3 — something you are).',
    ww: {
      B: 'Type 1 is knowledge-based.',
      C: 'Type 2 is possession-based.',
      D: '"Something you do" (e.g., keystroke dynamics) is a behavioral/contextual factor, not the physiological Type 3 fingerprint.',
    },
    er: 'Recall of Type 3 (biometric) factors.',
  },
  {
    t: 'Authentication Factors', s: 'MFA definition', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Types of Authentication Factors',
    q: 'For authentication to qualify as TRUE multi-factor authentication (MFA), the factors used must:',
    o: [
      'Come from two or more DIFFERENT factor types (e.g., something you know + something you have)',
      'All be passwords of different lengths',
      'All be biometrics from the same finger',
      'Be entered on the same screen',
    ],
    a: 'A',
    wc: 'MFA requires factors from different categories (knowledge, possession, inherence); combining two of the same type (e.g., two passwords) is not true MFA.',
    ww: {
      B: 'Two passwords are both Type 1—still single-factor in nature.',
      C: 'Two biometrics are both Type 3, not multi-factor.',
      D: 'Where factors are entered is irrelevant to whether they are different types.',
    },
    er: 'Tests that MFA needs distinct factor types.',
  },
  {
    t: 'Authentication Factors', s: '2FA scenario', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Process Examples',
    q: 'A login requires a password AND a one-time code from a hardware token. How many DISTINCT factor types are in use, and what is this called?',
    o: [
      'Two types (know + have) — two-factor authentication',
      'One type — single-factor authentication',
      'Three types — multi-factor authentication',
      'Zero types — anonymous access',
    ],
    a: 'A',
    wc: 'A password (Type 1, know) plus a token code (Type 2, have) uses two different factor types—two-factor authentication.',
    ww: {
      B: 'Two different types is not single-factor.',
      C: 'Only two types are used, not three.',
      D: 'Authentication is occurring, so it is not anonymous.',
    },
    er: 'Tests counting distinct factor types for 2FA.',
  },
  {
    t: 'Authentication Factors', s: 'Factor-type mapping', d: 'medium', qt: 'matching',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Factor Types',
    p: ['Something you know', 'Something you have', 'Something you are', 'Somewhere you are'],
    q: 'Match each authentication factor category (1-4) to an example (A-D).',
    o: [
      'A smart card or hardware token',
      'A password or PIN',
      'A login restricted to a trusted geographic location',
      'A fingerprint or iris scan',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'Know → password/PIN (B); Have → smart card/token (A); Are → fingerprint/iris (D); Somewhere you are → geographic/location-based (C).',
    ww: {},
    er: 'Tests mapping of factor categories to examples.',
  },
  {
    t: 'Authentication Factors', s: 'Context-based', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Context-Based Authentication',
    q: 'Evaluating a login\'s geographic location and the time of day as part of the access decision is an example of:',
    o: ['Context-based authentication', 'Single-factor knowledge authentication', 'Static packet filtering', 'Key escrow'],
    a: 'A',
    wc: 'Context-based authentication factors in attributes like location ("somewhere you are"), time, and behavior to strengthen or adapt access decisions.',
    ww: {
      B: 'Knowledge-only authentication ignores contextual signals.',
      C: 'Static packet filtering is a firewall technique.',
      D: 'Key escrow is a key-management control.',
    },
    er: 'Maps location/time signals to context-based authentication.',
  },
  {
    t: 'Authentication Factors', s: 'MFA strength', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Key Exam Tips',
    q: 'A bank wants to strengthen logins against stolen passwords. Which change provides the GREATEST improvement to authentication assurance?',
    o: [
      'Add a second factor of a different type (e.g., a possession-based token or biometric)',
      'Require a longer password only',
      'Ask the same security question twice',
      'Display the password as the user types it',
    ],
    a: 'A',
    wc: 'Adding a different factor type (possession or inherence) means a stolen password alone is insufficient—materially raising assurance versus knowledge-only changes.',
    ww: {
      B: 'A longer password is still a single knowledge factor that can be phished/stolen.',
      C: 'Repeating a knowledge question adds no new factor type.',
      D: 'Revealing the typed password weakens, not strengthens, security.',
    },
    er: 'Tests that adding a distinct factor type best mitigates stolen-password risk.',
  },
  // ---- Biometrics ----
  {
    t: 'Biometrics', s: 'Physiological vs behavioral', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Behavioral Attributes',
    q: 'Which of the following is a BEHAVIORAL biometric rather than a physiological one?',
    o: ['Keystroke dynamics', 'Fingerprint', 'Iris pattern', 'Retina pattern'],
    a: 'A',
    wc: 'Keystroke dynamics (how a person types) is a behavioral biometric; fingerprints, iris, and retina are physiological traits.',
    ww: {
      B: 'A fingerprint is a physiological trait.',
      C: 'Iris pattern is physiological.',
      D: 'Retina pattern is physiological.',
    },
    er: 'Distinguishes behavioral from physiological biometrics.',
  },
  {
    t: 'Biometrics', s: 'FRR (Type 1 error)', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Biometric System Errors',
    q: 'In a biometric system, the False Rejection Rate (FRR), also called a Type 1 error, occurs when the system:',
    o: [
      'Incorrectly REJECTS a legitimate, authorized user',
      'Incorrectly ACCEPTS an unauthorized impostor',
      'Crashes during enrollment',
      'Stores templates in plaintext',
    ],
    a: 'A',
    wc: 'FRR (Type 1 error) is a false rejection—an authorized user is wrongly denied; it harms usability/availability.',
    ww: {
      B: 'Falsely accepting an impostor is the False Acceptance Rate (FAR, Type 2 error).',
      C: 'A crash is a reliability failure, not FRR.',
      D: 'Plaintext template storage is a protection issue, not FRR.',
    },
    er: 'Maps false rejection of legitimate users to FRR (Type 1).',
  },
  {
    t: 'Biometrics', s: 'FAR (Type 2 error)', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Biometric System Errors',
    q: 'Which biometric error is generally the MOST dangerous from a security standpoint?',
    o: [
      'False Acceptance Rate (FAR / Type 2) — accepting an impostor',
      'False Rejection Rate (FRR / Type 1) — rejecting a valid user',
      'Crossover Error Rate (CER)',
      'Enrollment time',
    ],
    a: 'A',
    wc: 'A false acceptance (FAR, Type 2) admits an unauthorized impostor, which is the more serious security failure; FRR mainly hurts usability.',
    ww: {
      B: 'FRR denies legitimate users—an inconvenience, not a breach.',
      C: 'CER is a tuning metric (where FRR=FAR), not itself an error event.',
      D: 'Enrollment time is a usability metric, not a security error.',
    },
    er: 'Tests that FAR (Type 2) is the security-critical biometric error.',
  },
  {
    t: 'Biometrics', s: 'CER/EER', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Crossover Error Rate (CER)',
    q: 'The Crossover Error Rate (CER), also called the Equal Error Rate (EER), is:',
    o: [
      'The point where the False Rejection Rate equals the False Acceptance Rate; a lower CER indicates a more accurate system',
      'The maximum number of users a system can enroll',
      'The time required to scan a fingerprint',
      'The encryption strength of stored templates',
    ],
    a: 'A',
    wc: 'CER/EER is the rate at which FRR equals FAR; a lower CER means the biometric system is more accurate overall and is used to compare/tune systems.',
    ww: {
      B: 'CER is an accuracy metric, not an enrollment capacity.',
      C: 'Scan time is a usability metric, not CER.',
      D: 'Template encryption is a protection measure, not CER.',
    },
    er: 'Tests the CER/EER definition and that lower is better.',
  },
  {
    t: 'Biometrics', s: 'Tuning trade-off', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Crossover Error Rate (CER)',
    q: 'A high-security facility tunes its biometric scanner to be more strict. What is the LIKELY trade-off?',
    o: [
      'FAR decreases (fewer impostors accepted) but FRR increases (more legitimate users rejected)',
      'Both FAR and FRR drop to zero automatically',
      'FAR increases and FRR decreases',
      'The CER is no longer relevant after tuning',
    ],
    a: 'A',
    wc: 'Tightening the threshold reduces false acceptances (lower FAR) at the cost of more false rejections (higher FRR)—the inherent biometric trade-off.',
    ww: {
      B: 'No tuning eliminates both error types simultaneously.',
      C: 'Stricter settings lower FAR, not raise it.',
      D: 'CER remains a useful comparison metric regardless of tuning.',
    },
    er: 'Tests the FAR/FRR trade-off when adjusting sensitivity.',
  },
  {
    t: 'Biometrics', s: 'Behavioral biometrics', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Authentication Mechanisms > Behavioral Attributes',
    q: 'Which TWO of the following are behavioral biometrics? (Select TWO.)',
    o: ['Signature dynamics', 'Voice pattern recognition', 'Iris scan', 'Fingerprint'],
    a: ['A', 'B'],
    wc: 'Signature dynamics and voice pattern recognition are behavioral biometrics; iris and fingerprint are physiological.',
    ww: {
      C: 'An iris scan is a physiological biometric.',
      D: 'A fingerprint is a physiological biometric.',
    },
    er: 'Identifies behavioral biometrics.',
  },
  // ---- Directory services / LDAP ----
  {
    t: 'Directory Services', s: 'LDAP purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > LDAP (Lightweight Directory Access Protocol)',
    q: 'LDAP (Lightweight Directory Access Protocol) is primarily used to:',
    o: [
      'Query and manage directory services that store identity/account information',
      'Encrypt files on a laptop',
      'Suppress fires in a server room',
      'Provide backup power during outages',
    ],
    a: 'A',
    wc: 'LDAP is used to access and manage directory services (e.g., Active Directory), which store users, groups, and other identity data.',
    ww: {
      B: 'File encryption is unrelated to LDAP.',
      C: 'Fire suppression is a physical control.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Recall of LDAP\'s directory-access purpose.',
  },
  {
    t: 'Directory Services', s: 'LDAP DN components', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > LDAP (Lightweight Directory Access Protocol)',
    q: 'In an LDAP Distinguished Name (DN), what does the "OU" component represent?',
    o: ['Organizational Unit', 'Object Username', 'Outbound URL', 'Open Utility'],
    a: 'A',
    wc: 'In an LDAP DN, OU = Organizational Unit (a container/subdivision), alongside CN (Common Name) and DC (Domain Component).',
    ww: {
      B: '"Object Username" is not an LDAP DN component.',
      C: '"Outbound URL" is not an LDAP DN component.',
      D: '"Open Utility" is not an LDAP DN component.',
    },
    er: 'Recall of the OU component in an LDAP DN.',
  },
  {
    t: 'Directory Services', s: 'LDAP DN components', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > LDAP (Lightweight Directory Access Protocol)',
    q: 'In an LDAP Distinguished Name, the "CN" component typically identifies the:',
    o: ['Common Name (e.g., a specific user or object)', 'Country Number', 'Cipher Name', 'Cache Node'],
    a: 'A',
    wc: 'CN = Common Name, which identifies a specific entry such as a user or object within the directory.',
    ww: {
      B: '"Country Number" is not an LDAP DN component.',
      C: '"Cipher Name" is unrelated to LDAP DNs.',
      D: '"Cache Node" is not an LDAP DN component.',
    },
    er: 'Recall of the CN component in an LDAP DN.',
  },
  // ---- AAA ----
  {
    t: 'AAA', s: 'AAA framework', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > AAA (Authentication, Authorization, and Accounting)',
    q: 'The "AAA" framework in access management stands for:',
    o: [
      'Authentication, Authorization, and Accounting',
      'Availability, Assurance, and Auditing',
      'Access, Allocation, and Accountability',
      'Authentication, Availability, and Anonymity',
    ],
    a: 'A',
    wc: 'AAA stands for Authentication (who you are), Authorization (what you can do), and Accounting (recording what you did).',
    ww: {
      B: 'These are not the AAA components.',
      C: 'These are not the AAA components.',
      D: 'These are not the AAA components.',
    },
    er: 'Recall of the AAA acronym.',
  },
  {
    t: 'AAA', s: 'RADIUS vs TACACS+', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > AAA (Authentication, Authorization, and Accounting)',
    q: 'A notable difference between TACACS+ and RADIUS is that TACACS+:',
    o: [
      'Encrypts the entire payload and separates authentication, authorization, and accounting',
      'Sends all data in cleartext with no encryption',
      'Cannot be used for network device administration',
      'Is identical to RADIUS in every respect',
    ],
    a: 'A',
    wc: 'TACACS+ encrypts the full payload and treats authentication, authorization, and accounting as separate functions; RADIUS encrypts only the password and combines authentication/authorization.',
    ww: {
      B: 'TACACS+ encrypts the entire payload, not nothing.',
      C: 'TACACS+ is commonly used for administering network devices.',
      D: 'They differ in encryption scope and AAA separation.',
    },
    er: 'Distinguishes TACACS+ (full encryption, separated AAA) from RADIUS.',
  },
  {
    t: 'AAA', s: 'Diameter', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > AAA (Authentication, Authorization, and Accounting)',
    q: 'Diameter is best described as:',
    o: [
      'A successor AAA protocol designed to improve upon RADIUS',
      'A physical security barrier around a facility',
      'A biometric scanner type',
      'A fire suppression agent',
    ],
    a: 'A',
    wc: 'Diameter is an AAA protocol developed as an evolution/successor to RADIUS with enhanced capabilities.',
    ww: {
      B: 'Physical barriers are facility controls.',
      C: 'Diameter is not a biometric scanner.',
      D: 'It is not a fire suppression agent.',
    },
    er: 'Recall of Diameter as a RADIUS successor.',
  },
  {
    t: 'AAA', s: 'Accounting', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > AAA (Authentication, Authorization, and Accounting)',
    q: 'The "Accounting" component of AAA is most directly associated with which security goal?',
    o: ['Accountability (recording and auditing user actions)', 'Confidentiality of data at rest', 'Physical perimeter defense', 'Load balancing'],
    a: 'A',
    wc: 'Accounting records user activities (e.g., session start/stop, commands), supporting accountability and auditing.',
    ww: {
      B: 'Data-at-rest confidentiality is a separate control.',
      C: 'Perimeter defense is a physical control.',
      D: 'Load balancing is a performance/availability technique.',
    },
    er: 'Maps AAA accounting to accountability/auditing.',
  },
  {
    t: 'Authentication Factors', s: 'SFA risk', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Types of Authentication Factors',
    q: 'Single-factor authentication (SFA) using only a password is considered weak primarily because:',
    o: [
      'A single stolen or guessed credential grants full access',
      'It requires too many devices to log in',
      'It always locks out legitimate users',
      'It cannot be used on modern systems',
    ],
    a: 'A',
    wc: 'With SFA, compromising the single factor (e.g., a phished password) is enough to gain access; MFA mitigates this.',
    ww: {
      B: 'SFA requires fewer, not more, devices.',
      C: 'SFA does not inherently lock out legitimate users.',
      D: 'SFA is still widely (if unwisely) used on modern systems.',
    },
    er: 'Tests the single-point-of-compromise weakness of SFA.',
  },
  {
    t: 'Biometrics', s: 'Physiological biometrics', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Biometric Authentication',
    q: 'Which of the following is a PHYSIOLOGICAL biometric?',
    o: ['Retina scan', 'Keystroke dynamics', 'Signature dynamics', 'Mouse-movement pattern'],
    a: 'A',
    wc: 'A retina scan measures a physical (physiological) characteristic; the others are behavioral biometrics.',
    ww: {
      B: 'Keystroke dynamics is behavioral.',
      C: 'Signature dynamics is behavioral.',
      D: 'Mouse-movement patterns are behavioral.',
    },
    er: 'Distinguishes physiological from behavioral biometrics.',
  },
  {
    t: 'Directory Services', s: 'LDAP DN concept', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > LDAP (Lightweight Directory Access Protocol)',
    q: 'In LDAP, a Distinguished Name (DN) serves to:',
    o: [
      'Uniquely identify an entry\'s full path within the directory hierarchy',
      'Encrypt the directory database',
      'Assign IP addresses to directory clients',
      'Provide backup power to the directory server',
    ],
    a: 'A',
    wc: 'A DN uniquely identifies a directory entry by specifying its complete hierarchical path (e.g., CN=user,OU=Sales,DC=example,DC=com).',
    ww: {
      B: 'A DN names an entry; it does not encrypt the database.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Tests the unique-path purpose of an LDAP DN.',
  },
  {
    t: 'Authentication Factors', s: 'Something you do', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Context-Based Authentication',
    q: 'Analyzing the unique rhythm and timing of how a user types their password reflects which contextual/behavioral factor?',
    o: ['Something you do (keystroke dynamics)', 'Something you have', 'Somewhere you are', 'Something you know'],
    a: 'A',
    wc: 'Keystroke dynamics is a "something you do" behavioral factor based on how the user performs an action.',
    ww: {
      B: '"Something you have" is a possession factor.',
      C: '"Somewhere you are" is a location factor.',
      D: '"Something you know" is the password content itself, not the typing rhythm.',
    },
    er: 'Maps typing rhythm to "something you do".',
  },
  {
    t: 'Authentication Factors', s: 'Factor combinations', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Authentication Mechanisms > Types of Authentication Factors',
    q: 'Which TWO combinations qualify as TRUE multi-factor authentication? (Select TWO.)',
    o: [
      'Password + hardware token code',
      'Fingerprint + smart card',
      'Password + PIN',
      'Two different fingerprints',
    ],
    a: ['A', 'B'],
    wc: 'Password (know) + token (have) and fingerprint (are) + smart card (have) each combine different factor types—true MFA.',
    ww: {
      C: 'Password + PIN are both knowledge factors (Type 1)—not MFA.',
      D: 'Two fingerprints are both Type 3—not MFA.',
    },
    er: 'Identifies genuine multi-factor combinations.',
  },
  {
    t: 'Directory Services', s: 'Directory protocols', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Authentication Systems',
    q: 'Directory services (such as those queried by LDAP) primarily provide:',
    o: [
      'A centralized store of identity and resource information for authentication/authorization',
      'A method to physically destroy hard drives',
      'A backup generator control panel',
      'A fire detection sensor array',
    ],
    a: 'A',
    wc: 'Directory services centrally store identities, groups, and resource information, supporting authentication and authorization decisions.',
    ww: {
      B: 'Drive destruction is a sanitization activity.',
      C: 'Generator control is a power-management function.',
      D: 'Fire detection is a physical safety control.',
    },
    er: 'Tests the centralized identity-store role of directory services.',
  },
  {
    t: 'AAA', s: 'RADIUS use', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Key Terms to Know',
    q: 'RADIUS is commonly used to provide centralized AAA for:',
    o: [
      'Remote/network access (e.g., VPN, Wi-Fi 802.1X) authentication',
      'Encrypting data at rest on servers',
      'Suppressing fires in data centers',
      'Translating private IPs to public IPs',
    ],
    a: 'A',
    wc: 'RADIUS centralizes authentication/authorization/accounting for remote and network access such as VPN and 802.1X Wi-Fi.',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'Fire suppression is a physical control.',
      D: 'IP translation is NAT.',
    },
    er: 'Maps centralized network-access AAA to RADIUS.',
  },
];
