// Domain 5 — Part 1: Identity proofing (resolution/validation/verification),
// assurance levels, CSP, provisioning/deprovisioning lifecycle, federated &
// delegated identity (SAML/SPML/XACML, IdP/SP).
module.exports = [
  // ---- Identity proofing ----
  {
    t: 'Identity Proofing', s: 'Proofing steps', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Identity Proofing Process',
    q: 'The identity proofing process consists of which three core steps?',
    o: ['Resolution, validation, and verification', 'Encrypt, hash, and sign', 'Detect, respond, and recover', 'Plan, do, check'],
    a: 'A',
    wc: 'Identity proofing consists of resolution (uniquely identifying the applicant), validation (confirming the evidence is genuine), and verification (confirming the evidence belongs to the applicant).',
    ww: {
      B: 'Encrypt/hash/sign are cryptographic operations, not proofing steps.',
      C: 'Detect/respond/recover are incident/CSF functions.',
      D: 'Plan/do/check is the Deming cycle.',
    },
    er: 'Recall of the three identity-proofing steps.',
  },
  {
    t: 'Identity Proofing', s: 'Proofing sequence', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 5 > Identity Management Introduction > Proofing Process Steps',
    q: 'Order the identity proofing process steps as described in the guide. (Provide the option labels in order.)',
    o: ['Applicant request', 'Resolution', 'Validation', 'Verification', 'Enrollment'],
    a: 'A,B,C,D,E',
    wc: 'The flow runs from the applicant request, to resolution, validation, verification, and finally enrollment (creating the credential).',
    ww: {},
    er: 'Tests the ordered identity-proofing steps.',
  },
  {
    t: 'Identity Proofing', s: 'Resolution', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Proofing Process Steps',
    q: 'In identity proofing, the "resolution" step specifically aims to:',
    o: [
      'Uniquely distinguish the applicant from all other individuals',
      'Encrypt the applicant\'s biometric template',
      'Grant the applicant access to all systems',
      'Revoke the applicant\'s prior credentials',
    ],
    a: 'A',
    wc: 'Resolution uniquely identifies/distinguishes the applicant as a single, specific person before evidence is validated and verified.',
    ww: {
      B: 'Encrypting a biometric template is a storage/protection step, not resolution.',
      C: 'Granting access is authorization, which follows enrollment.',
      D: 'Revoking credentials is part of deprovisioning, not proofing resolution.',
    },
    er: 'Tests the meaning of the resolution step.',
  },
  {
    t: 'Identity Proofing', s: 'Verification', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Proofing Process Steps',
    q: 'During proofing, the "verification" step confirms that:',
    o: [
      'The validated identity evidence actually belongs to the applicant presenting it',
      'The applicant has paid for the service',
      'The network connection is encrypted',
      'The password meets complexity requirements',
    ],
    a: 'A',
    wc: 'Verification confirms that the (already validated) identity evidence genuinely relates to the applicant—linking the person to the evidence.',
    ww: {
      B: 'Payment is unrelated to identity verification.',
      C: 'Connection encryption is a transport concern, not proofing verification.',
      D: 'Password complexity is a credential policy, not identity verification.',
    },
    er: 'Distinguishes verification (binds evidence to applicant) from validation (evidence authenticity).',
  },
  {
    t: 'Assurance Levels', s: 'IAL/AAL', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Assurance Levels',
    q: 'In identity management, increasing assurance levels (Level 1 to Level 3) generally indicate:',
    o: [
      'Progressively stronger confidence/rigor in the identity proofing and authentication',
      'Progressively weaker security requirements',
      'The number of users in the system',
      'The physical size of the data center',
    ],
    a: 'A',
    wc: 'Higher assurance levels require more rigorous proofing and stronger authentication, providing greater confidence in the claimed identity.',
    ww: {
      B: 'Higher levels are stronger, not weaker.',
      C: 'Assurance levels measure confidence, not user counts.',
      D: 'They are unrelated to data center size.',
    },
    er: 'Tests that higher assurance = greater rigor/confidence.',
  },
  {
    t: 'Identity Management', s: 'Credential Service Provider', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Establishing Identity',
    q: 'A Credential Service Provider (CSP) is responsible for:',
    o: [
      'Issuing and managing credentials for subscribers after enrollment',
      'Physically guarding the data center entrance',
      'Suppressing fires in server rooms',
      'Routing packets between autonomous systems',
    ],
    a: 'A',
    wc: 'A CSP registers identities and issues/manages credentials for subscribers as part of the identity lifecycle.',
    ww: {
      B: 'Physical guarding is a facility security function.',
      C: 'Fire suppression is a physical control.',
      D: 'Inter-AS routing is a BGP/router function.',
    },
    er: 'Recall of the CSP role.',
  },
  // ---- Provisioning lifecycle ----
  {
    t: 'Provisioning Lifecycle', s: 'Lifecycle steps', d: 'medium', qt: 'sequence_ordering',
    sec: 'Domain 5 > Identity Management Introduction > Identity and Access Lifecycle',
    q: 'Order the identity and access provisioning lifecycle steps as described in the guide. (Provide the option labels in order.)',
    o: ['Provisioning', 'Review', 'Revocation'],
    a: 'A,B,C',
    wc: 'The lifecycle runs from provisioning (granting access), to periodic review (re-certifying access), to revocation (removing access when no longer needed).',
    ww: {},
    er: 'Tests the provisioning lifecycle order.',
  },
  {
    t: 'Provisioning Lifecycle', s: 'Deprovisioning', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Identity Management Introduction > Deprovisioning',
    q: 'An employee resigns. From an access-management standpoint, what is the MOST time-critical deprovisioning action?',
    o: [
      'Promptly revoke the departing employee\'s access to systems and data',
      'Schedule their next access review for next quarter',
      'Archive their desk furniture',
      'Add them to additional security groups for record-keeping',
    ],
    a: 'A',
    wc: 'Access should be revoked quickly on departure to minimize the window for misuse of lingering credentials.',
    ww: {
      B: 'A future review does nothing to close the immediate access window.',
      C: 'Furniture handling is not an access concern.',
      D: 'Adding groups expands access—the opposite of deprovisioning.',
    },
    er: 'Prioritizes prompt access revocation in deprovisioning.',
  },
  {
    t: 'Provisioning Lifecycle', s: 'Access review', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Lifecycle Steps',
    q: 'Periodic access reviews (recertification) during the identity lifecycle primarily help to:',
    o: [
      'Detect and remove excessive or no-longer-needed access (privilege creep)',
      'Increase the number of administrators',
      'Encrypt all network traffic',
      'Replace the need for authentication',
    ],
    a: 'A',
    wc: 'Regular access reviews identify accumulated/unnecessary access and adjust it, countering privilege creep and unauthorized use.',
    ww: {
      B: 'Reviews right-size access; they do not add administrators.',
      C: 'Traffic encryption is unrelated to access review.',
      D: 'Reviews complement, not replace, authentication.',
    },
    er: 'Ties access reviews to controlling privilege creep.',
  },
  {
    t: 'Provisioning Lifecycle', s: 'Automation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Key Considerations',
    q: 'Automating the provisioning and deprovisioning process primarily improves security by:',
    o: [
      'Ensuring access is granted and removed consistently and promptly, reducing human error',
      'Eliminating the need for any access policy',
      'Allowing users to grant themselves any access',
      'Guaranteeing no account is ever disabled',
    ],
    a: 'A',
    wc: 'Automation makes provisioning/deprovisioning consistent and timely, reducing the manual errors and delays that leave dangling access.',
    ww: {
      B: 'Automation enforces policy; it does not remove the need for one.',
      C: 'Self-granting access violates least privilege and separation of duties.',
      D: 'Automation should ensure accounts ARE disabled when appropriate.',
    },
    er: 'Connects automation to consistent, timely access changes.',
  },
  // ---- Federated identity ----
  {
    t: 'Federated Identity', s: 'FIM concept', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Federated Identity Management',
    q: 'Federated Identity Management (FIM) primarily enables:',
    o: [
      'Users to access multiple organizations\' systems using a single, shared identity across trust domains',
      'Encryption of all data at rest',
      'Automatic patching of operating systems',
      'Physical access control to buildings',
    ],
    a: 'A',
    wc: 'FIM lets a user\'s identity be trusted across organizational boundaries, so one identity can access resources in multiple trust domains (e.g., via SAML).',
    ww: {
      B: 'Data-at-rest encryption is a separate control.',
      C: 'OS patching is unrelated to federation.',
      D: 'Physical access control is a facility function.',
    },
    er: 'Tests the cross-domain shared-identity purpose of FIM.',
  },
  {
    t: 'Federated Identity', s: 'SAML', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Security Assertion Markup Language (SAML)',
    q: 'Security Assertion Markup Language (SAML) is built on XML and is primarily used to:',
    o: [
      'Exchange authentication and authorization assertions between an identity provider and a service provider',
      'Assign IP addresses to clients',
      'Encrypt files on a hard drive',
      'Suppress electrical fires',
    ],
    a: 'A',
    wc: 'SAML uses XML (and SOAP) to exchange authentication/authorization assertions between an identity provider (IdP) and service provider (SP), enabling web SSO/federation.',
    ww: {
      B: 'IP assignment is DHCP\'s function.',
      C: 'File encryption is unrelated to SAML.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Maps cross-domain assertion exchange to SAML.',
  },
  {
    t: 'Federated Identity', s: 'IdP vs SP', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Identity Management Introduction > Operational Flow of SAML',
    q: 'In a SAML web-SSO flow, a user tries to access a partner web application. The application redirects to a trusted party that authenticates the user and asserts their identity. The application is the ____ and the authenticating party is the ____.',
    o: [
      'Service Provider (SP); Identity Provider (IdP)',
      'Identity Provider (IdP); Service Provider (SP)',
      'Resource Owner; Resource Server',
      'KDC; TGS',
    ],
    a: 'A',
    wc: 'The application consuming the assertion is the Service Provider (SP); the party that authenticates the user and issues the assertion is the Identity Provider (IdP).',
    ww: {
      B: 'This reverses the roles—the app is the SP, the authenticator is the IdP.',
      C: 'Resource Owner/Server are OAuth roles, not SAML SP/IdP.',
      D: 'KDC/TGS are Kerberos components, not SAML roles.',
    },
    er: 'Tests SAML SP vs IdP roles in an SSO flow.',
  },
  {
    t: 'Federated Identity', s: 'SPML', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Service Provisioning Markup Language (SPML)',
    q: 'Service Provisioning Markup Language (SPML) is used primarily to:',
    o: [
      'Exchange user, resource, and service provisioning information between organizations/systems',
      'Authenticate users with biometrics',
      'Encrypt email messages',
      'Route packets between subnets',
    ],
    a: 'A',
    wc: 'SPML is an XML-based standard for exchanging provisioning information (creating/managing accounts and resources) across systems.',
    ww: {
      B: 'Biometric authentication is unrelated to SPML.',
      C: 'Email encryption uses S/MIME/PGP, not SPML.',
      D: 'Packet routing is a network-layer function.',
    },
    er: 'Maps cross-system provisioning to SPML.',
  },
  {
    t: 'Federated Identity', s: 'XACML', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Extensible Access Control Markup Language (XACML)',
    q: 'Extensible Access Control Markup Language (XACML) is primarily used to:',
    o: [
      'Define and evaluate attribute-based access control policies',
      'Carry voice over IP networks',
      'Provide a backup power source',
      'Resolve domain names to IP addresses',
    ],
    a: 'A',
    wc: 'XACML is a standard for expressing and evaluating access control policies, commonly underpinning attribute-based access control (ABAC/PBAC).',
    ww: {
      B: 'Voice over IP is VoIP, unrelated to XACML.',
      C: 'Backup power is a UPS/generator function.',
      D: 'Name resolution is DNS.',
    },
    er: 'Maps access-policy definition to XACML.',
  },
  {
    t: 'Federated Identity', s: 'Standards purpose', d: 'hard', qt: 'matching',
    sec: 'Domain 5 > Identity Management Introduction > Federated Identity Management',
    p: ['SAML', 'SPML', 'XACML', 'OAuth'],
    q: 'Match each identity/access standard (1-4) to its primary purpose (A-D).',
    o: [
      'Exchanging account/resource provisioning information',
      'Exchanging authentication/authorization assertions for SSO',
      'Delegated authorization using access tokens',
      'Defining attribute-based access control policies',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'SAML → authn/authz assertions/SSO (B); SPML → provisioning exchange (A); XACML → access-policy definition (D); OAuth → token-based delegated authorization (C).',
    ww: {},
    er: 'Tests mapping of identity standards to their purposes.',
  },
  {
    t: 'Federated Identity', s: 'Delegated identity', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Delegated Identity Management',
    q: 'A key BENEFIT of delegated identity management is that it:',
    o: [
      'Allows identity/access administration to be distributed to appropriate parties while maintaining central policy',
      'Eliminates the need for any authentication',
      'Forces every user to share one password',
      'Removes all logging of access',
    ],
    a: 'A',
    wc: 'Delegated identity management distributes administrative responsibility (e.g., to departments or partners) while central governance/policy is maintained, improving scalability.',
    ww: {
      B: 'Delegation does not remove authentication.',
      C: 'Shared passwords destroy accountability and are not delegation.',
      D: 'Logging remains essential; delegation does not remove it.',
    },
    er: 'Tests the distributed-administration benefit of delegation.',
  },
  {
    t: 'Identity Management', s: 'Centralized vs decentralized', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Identity Management Introduction > Identity Management',
    q: 'A multinational company wants consistent access policy and a single point of administration for identities across all regions. Which access-control administration approach BEST fits?',
    o: [
      'Centralized access control',
      'Fully decentralized control with no coordination',
      'No access control at all',
      'Per-user self-administration of all rights',
    ],
    a: 'A',
    wc: 'Centralized access control provides a single administration point and consistent policy enforcement across the organization, ideal for uniform governance.',
    ww: {
      B: 'Fully decentralized control yields inconsistent policy and weaker governance for this goal.',
      C: 'No access control is never acceptable.',
      D: 'Self-administration of rights violates least privilege and separation of duties.',
    },
    er: 'Maps a need for consistent, single-point administration to centralized access control.',
  },
  {
    t: 'Identity Management', s: 'Core IAM functions', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Identity Management',
    q: 'Which sequence correctly orders the core IAM concepts for a subject interacting with a system?',
    o: [
      'Identification, authentication, authorization, accountability',
      'Authorization, identification, accountability, authentication',
      'Accountability, authorization, authentication, identification',
      'Authentication, accountability, identification, authorization',
    ],
    a: 'A',
    wc: 'A subject is first identified, then authenticated (proves the identity), then authorized (granted access), with accountability (auditing) tracking actions throughout.',
    ww: {
      B: 'Authorization cannot precede identification/authentication.',
      C: 'This reverses the logical order.',
      D: 'Identification must come before authentication.',
    },
    er: 'Tests the identification→authentication→authorization→accountability order.',
  },
  {
    t: 'Identity Proofing', s: 'Validation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Proofing Process Steps',
    q: 'The "validation" step of identity proofing confirms that:',
    o: [
      'The submitted identity evidence is authentic and accurate',
      'The applicant has logged out of all sessions',
      'The data center temperature is within range',
      'The firewall rules are correctly ordered',
    ],
    a: 'A',
    wc: 'Validation confirms the identity evidence itself is genuine/accurate (e.g., a real, unexpired ID document), before verification links it to the applicant.',
    ww: {
      B: 'Logging out sessions is unrelated to proofing validation.',
      C: 'Temperature is an environmental control concern.',
      D: 'Firewall ordering is a network control, not proofing.',
    },
    er: 'Distinguishes validation (evidence authenticity) from verification.',
  },
  {
    t: 'Provisioning Lifecycle', s: 'Joiner-mover-leaver', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Identity Management Introduction > Identity and Access Lifecycle',
    q: 'An employee transfers from Finance to Marketing. From an access-management standpoint, the BEST practice during this "mover" event is to:',
    o: [
      'Grant the new role\'s access and remove the old role\'s access that is no longer needed',
      'Keep all Finance access and simply add Marketing access',
      'Disable the account permanently',
      'Grant administrator rights for convenience',
    ],
    a: 'A',
    wc: 'On role change, access should be re-baselined to the new role—adding what is needed and removing now-unneeded access—to avoid privilege creep.',
    ww: {
      B: 'Retaining old access while adding new access causes privilege creep.',
      C: 'A transferring employee still needs an active account for the new role.',
      D: 'Granting admin rights violates least privilege.',
    },
    er: 'Tests proper handling of a mover/role-change event.',
  },
  {
    t: 'Federated Identity', s: 'SAML components', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Identity Management Introduction > SAML Assertions, Protocols, and Bindings',
    q: 'Which TWO of the following are core building blocks of SAML? (Select TWO.)',
    o: ['Assertions', 'Bindings', 'Rainbow tables', 'Fire classes'],
    a: ['A', 'B'],
    wc: 'SAML is structured around assertions (statements about a subject), protocols, and bindings (how messages are transported).',
    ww: {
      C: 'Rainbow tables are a cryptanalytic attack artifact.',
      D: 'Fire classes are a physical-security concept.',
    },
    er: 'Identifies SAML building blocks.',
  },
  {
    t: 'Identity Management', s: 'Distributed access control', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Identity Management Introduction > Identity Management',
    q: 'A drawback of a decentralized/distributed access control approach is that it:',
    o: [
      'Can lead to inconsistent policy enforcement across the organization',
      'Always provides a single point of administration',
      'Eliminates the need for any identity store',
      'Guarantees uniform configuration everywhere',
    ],
    a: 'A',
    wc: 'Decentralized control distributes administration closer to resources but risks inconsistent policy and configuration across the organization.',
    ww: {
      B: 'A single administration point is a feature of centralized, not decentralized, control.',
      C: 'An identity store is still required.',
      D: 'Decentralization tends to produce variation, not guaranteed uniformity.',
    },
    er: 'Tests the consistency drawback of decentralized access control.',
  },
];
