// Domain 5 — Part 3: Single Sign-On, Kerberos, OAuth/OIDC/OpenID/SAML for SSO,
// credential management systems, and Just-In-Time access / PAM.
module.exports = [
  // ---- SSO ----
  {
    t: 'Single Sign-On', s: 'SSO concept', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Single Sign On',
    q: 'Single Sign-On (SSO) primarily allows a user to:',
    o: [
      'Authenticate once and gain access to multiple systems without re-entering credentials',
      'Use a different password for every application',
      'Avoid authenticating at all',
      'Encrypt all of their files automatically',
    ],
    a: 'A',
    wc: 'SSO lets a user authenticate a single time and then access multiple connected systems without repeatedly entering credentials.',
    ww: {
      B: 'Separate passwords per app is the opposite of SSO.',
      C: 'SSO still requires authentication—just once.',
      D: 'File encryption is unrelated to SSO.',
    },
    er: 'Recall of the SSO single-authentication benefit.',
  },
  {
    t: 'Single Sign-On', s: 'SSO drawback', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Single Sign On',
    q: 'A company implements SSO across all internal applications. What is the PRIMARY security drawback the team must mitigate?',
    o: [
      'If the single credential is compromised, the attacker can reach all connected systems',
      'Users must remember dozens of separate passwords',
      'Applications can no longer be accessed at all',
      'It makes auditing user activity impossible',
    ],
    a: 'A',
    wc: 'SSO concentrates risk: a compromised single credential unlocks every connected system, so it must be paired with strong authentication (e.g., MFA) and monitoring.',
    ww: {
      B: 'SSO reduces the number of passwords—it does not increase them.',
      C: 'SSO enables, not prevents, application access.',
      D: 'SSO does not make auditing impossible; centralized logging is still possible.',
    },
    er: 'Tests the single-point-of-compromise drawback of SSO.',
  },
  {
    t: 'Single Sign-On', s: 'SSO mitigation', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Single Sign On',
    q: 'Which control BEST mitigates the concentrated risk of SSO?',
    o: [
      'Requiring multi-factor authentication for the SSO login',
      'Disabling logging on the identity provider',
      'Using one shared SSO account for the whole team',
      'Removing session timeouts entirely',
    ],
    a: 'A',
    wc: 'Because SSO concentrates access behind one login, protecting that login with MFA substantially reduces the impact of a stolen password.',
    ww: {
      B: 'Disabling logging removes the visibility needed to detect abuse.',
      C: 'A shared account destroys accountability and worsens risk.',
      D: 'Removing timeouts leaves sessions open to hijacking.',
    },
    er: 'Maps SSO risk mitigation to MFA.',
  },
  // ---- Kerberos ----
  {
    t: 'Kerberos', s: 'KDC components', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos',
    q: 'The Kerberos Key Distribution Center (KDC) is composed of which two services?',
    o: [
      'Authentication Server (AS) and Ticket Granting Service (TGS)',
      'Identity Provider and Service Provider',
      'Resource Owner and Resource Server',
      'Policy Engine and Policy Enforcement Point',
    ],
    a: 'A',
    wc: 'The KDC contains the Authentication Server (AS), which issues TGTs, and the Ticket Granting Service (TGS), which issues service tickets.',
    ww: {
      B: 'IdP/SP are SAML federation roles.',
      C: 'Resource Owner/Server are OAuth roles.',
      D: 'PE/PEP are Zero Trust components.',
    },
    er: 'Recall of the KDC = AS + TGS.',
  },
  {
    t: 'Kerberos', s: 'Operation flow', d: 'hard', qt: 'sequence_ordering',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos Operation Flow',
    q: 'Order the steps of the Kerberos authentication flow. (Provide the option labels in order.)',
    o: [
      'Client authenticates to the Authentication Server (AS)',
      'AS issues a Ticket Granting Ticket (TGT)',
      'Client presents the TGT to the Ticket Granting Service (TGS)',
      'TGS issues a Service Ticket',
      'Client uses the Service Ticket to access the service',
    ],
    a: 'A,B,C,D,E',
    wc: 'The client authenticates to the AS, receives a TGT, presents the TGT to the TGS, receives a Service Ticket, and uses it to access the target service.',
    ww: {},
    er: 'Tests the ordered Kerberos ticket flow.',
  },
  {
    t: 'Kerberos', s: 'TGT', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Tickets',
    q: 'In Kerberos, a Ticket Granting Ticket (TGT) is used by the client to:',
    o: [
      'Request service tickets from the Ticket Granting Service without re-entering the password',
      'Directly decrypt the target server\'s files',
      'Assign IP addresses to clients',
      'Permanently disable the KDC',
    ],
    a: 'A',
    wc: 'After authenticating, the client holds a TGT that it presents to the TGS to obtain service tickets, enabling SSO without re-authenticating each time.',
    ww: {
      B: 'A TGT does not decrypt server files directly.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'A TGT does not disable the KDC.',
    },
    er: 'Tests the TGT\'s role in obtaining service tickets.',
  },
  {
    t: 'Kerberos', s: 'KDC single point of failure', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos Operation Flow',
    q: 'In a Kerberos deployment, the KDC becomes unavailable. What is the MOST direct consequence, and what design lesson does it illustrate?',
    o: [
      'Authentication fails (Kerberos fails secure); the KDC is a single point of failure that needs redundancy',
      'All users automatically gain administrator rights',
      'Existing files are permanently deleted',
      'Passwords are exposed in cleartext to all users',
    ],
    a: 'A',
    wc: 'If the KDC is down/compromised, Kerberos fails secure (access is denied), making the KDC a critical single point of failure that should be made redundant and time-synchronized.',
    ww: {
      B: 'KDC failure denies access; it does not grant admin rights.',
      C: 'KDC failure does not delete files.',
      D: 'KDC failure does not expose passwords in cleartext.',
    },
    er: 'Tests the KDC single-point-of-failure and fail-secure behavior.',
  },
  {
    t: 'Kerberos', s: 'Time synchronization', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos Operation Flow',
    q: 'Why must all systems in a Kerberos realm keep their clocks synchronized?',
    o: [
      'Kerberos tickets are time-stamped; significant clock skew causes valid tickets to be rejected',
      'Synchronization increases network bandwidth',
      'It is required to assign MAC addresses',
      'It encrypts the directory database',
    ],
    a: 'A',
    wc: 'Kerberos uses time-stamped tickets (and tolerates only small skew) to resist replay; if clocks drift too far, authentication fails.',
    ww: {
      B: 'Time sync does not increase bandwidth.',
      C: 'MAC assignment is hardware-based, not time-driven.',
      D: 'Time sync does not encrypt databases.',
    },
    er: 'Tests the time-synchronization dependency of Kerberos.',
  },
  {
    t: 'Kerberos', s: 'Kerberoasting', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos Operation Flow',
    q: 'A Kerberoasting attack works by:',
    o: [
      'Requesting service tickets and cracking their hashes offline to recover service-account passwords',
      'Flooding the network with ICMP echo replies',
      'Physically stealing a smart card',
      'Sending unsolicited Bluetooth messages',
    ],
    a: 'A',
    wc: 'Kerberoasting requests service tickets (encrypted with the service account\'s key) and cracks the hashes offline to recover the service account\'s password.',
    ww: {
      B: 'ICMP echo flooding is a Smurf/DoS attack.',
      C: 'Stealing a smart card is a possession-factor theft, not Kerberoasting.',
      D: 'Unsolicited Bluetooth messages are bluejacking.',
    },
    er: 'Maps offline service-ticket cracking to Kerberoasting.',
  },
  {
    t: 'Kerberos', s: 'Component mapping', d: 'hard', qt: 'matching',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos',
    p: ['Authentication Server (AS)', 'Ticket Granting Service (TGS)', 'Ticket Granting Ticket (TGT)', 'Service Ticket'],
    q: 'Match each Kerberos element (1-4) to its role (A-D).',
    o: [
      'Issues service tickets when presented a valid TGT',
      'Verifies initial credentials and issues a TGT',
      'Presented to a target service to gain access',
      'Proves the client authenticated, used to request service tickets',
    ],
    a: '1-B,2-A,3-D,4-C',
    wc: 'AS → verifies credentials/issues TGT (B); TGS → issues service tickets (A); TGT → proves authentication, requests service tickets (D); Service Ticket → presented to the target service (C).',
    ww: {},
    er: 'Tests mapping of Kerberos components to their roles.',
  },
  // ---- OAuth / OIDC / OpenID ----
  {
    t: 'Federation Protocols', s: 'OAuth vs OIDC', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > OAuth and OIDC',
    q: 'Which statement correctly distinguishes OAuth 2.0 from OpenID Connect (OIDC)?',
    o: [
      'OAuth 2.0 is for delegated authorization; OIDC adds an identity (authentication) layer on top of OAuth 2.0',
      'OAuth 2.0 is for authentication; OIDC is only for encryption',
      'They are unrelated and never used together',
      'OIDC is older than OAuth and replaced it',
    ],
    a: 'A',
    wc: 'OAuth 2.0 handles delegated authorization (granting access via tokens); OIDC builds an authentication/identity layer on top of OAuth 2.0 (using REST/JSON, JWTs).',
    ww: {
      B: 'OAuth is authorization-focused; OIDC adds authentication, not encryption only.',
      C: 'OIDC is built directly on OAuth 2.0—they are closely related.',
      D: 'OIDC came after and extends OAuth 2.0; it did not replace it.',
    },
    er: 'Tests the authorization (OAuth) vs authentication (OIDC) distinction.',
  },
  {
    t: 'Federation Protocols', s: 'OAuth purpose', d: 'medium', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > OAuth and OIDC',
    q: 'A user lets a photo-printing app access their cloud photos WITHOUT sharing their cloud password, by granting a scoped access token. Which standard enables this delegated access?',
    o: ['OAuth 2.0', 'WEP', 'Kerberoasting', 'CPTED'],
    a: 'A',
    wc: 'OAuth 2.0 enables delegated authorization: the app receives a scoped access token to act on the user\'s behalf without seeing the user\'s password.',
    ww: {
      B: 'WEP is a wireless encryption protocol.',
      C: 'Kerberoasting is an attack technique.',
      D: 'CPTED is a physical site-design strategy.',
    },
    er: 'Maps password-less delegated access to OAuth 2.0.',
  },
  {
    t: 'Federation Protocols', s: 'OpenID', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > OpenID',
    q: 'OpenID allows users to:',
    o: [
      'Access multiple websites using a single set of credentials managed by a third-party provider',
      'Encrypt files on their local disk',
      'Physically enter a secured facility',
      'Route packets between autonomous systems',
    ],
    a: 'A',
    wc: 'OpenID lets a third-party provider manage authentication credentials so users can sign in to many sites with one identity.',
    ww: {
      B: 'File encryption is unrelated to OpenID.',
      C: 'Physical entry is a facility control.',
      D: 'Packet routing is a network function.',
    },
    er: 'Recall of OpenID\'s single-credential multi-site authentication.',
  },
  {
    t: 'Federation Protocols', s: 'OAuth components', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > OAuth Workflow',
    q: 'In the OAuth framework, the application requesting access to protected resources on the user\'s behalf is the:',
    o: ['Client', 'Resource Owner', 'Resource Server', 'Authorization Server'],
    a: 'A',
    wc: 'The OAuth client is the application requesting access; the resource owner is the user, the resource server hosts the data, and the authorization server issues tokens.',
    ww: {
      B: 'The resource owner is the user who owns the data and grants access.',
      C: 'The resource server hosts the protected resources.',
      D: 'The authorization server issues access tokens.',
    },
    er: 'Distinguishes the OAuth client from other roles.',
  },
  {
    t: 'Federation Protocols', s: 'SSO via SAML', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Security Assertion Markup Language (SAML)',
    q: 'In enterprise web SSO, SAML is commonly used to:',
    o: [
      'Pass authentication/authorization assertions from an identity provider to web applications',
      'Encrypt files at rest on endpoints',
      'Suppress fires in server rooms',
      'Provide backup power during outages',
    ],
    a: 'A',
    wc: 'SAML conveys authentication/authorization assertions from the IdP to service providers (web apps), enabling federated web SSO.',
    ww: {
      B: 'File encryption is a separate control.',
      C: 'Fire suppression is a physical control.',
      D: 'Backup power is a UPS/generator function.',
    },
    er: 'Maps web SSO assertions to SAML.',
  },
  {
    t: 'Federation Protocols', s: 'JWT/OIDC', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > OpenID Connect',
    q: 'OpenID Connect commonly conveys identity claims using which token format?',
    o: ['JSON Web Token (JWT)', 'A magnetic stripe', 'An LDAP DN', 'A SYN-ACK packet'],
    a: 'A',
    wc: 'OIDC uses REST/JSON and conveys identity information in JSON Web Tokens (JWTs).',
    ww: {
      B: 'A magnetic stripe is a physical card medium, not a token format.',
      C: 'An LDAP DN names a directory entry, not an OIDC token.',
      D: 'A SYN-ACK is a TCP handshake message.',
    },
    er: 'Maps OIDC identity claims to JWT.',
  },
  // ---- CMS ----
  {
    t: 'Credential Management', s: 'CMS purpose', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Credential Management Systems',
    q: 'A credential management system (password manager) primarily helps users by:',
    o: [
      'Securely storing and retrieving credentials so users can use strong, unique passwords',
      'Encrypting the entire corporate WAN',
      'Assigning IP addresses to devices',
      'Physically guarding the data center',
    ],
    a: 'A',
    wc: 'A CMS securely stores credentials (often in an encrypted vault), enabling strong, unique passwords without users having to memorize them all.',
    ww: {
      B: 'A CMS does not encrypt the WAN.',
      C: 'IP assignment is DHCP\'s function.',
      D: 'Physical guarding is a facility control.',
    },
    er: 'Recall of the CMS password-vault purpose.',
  },
  {
    t: 'Credential Management', s: 'Credential vault', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Attributes Stored in Credential Management Systems',
    q: 'A "credential vault" within a CMS is best described as:',
    o: [
      'A secured, encrypted store that holds credentials and secrets',
      'A backup generator enclosure',
      'A physical safe for paper documents only',
      'A network switch port',
    ],
    a: 'A',
    wc: 'A credential vault is the secured, encrypted repository where a CMS stores credentials/secrets, protecting them from unauthorized access.',
    ww: {
      B: 'A generator enclosure is a power-equipment housing.',
      C: 'A credential vault is digital, not a paper safe.',
      D: 'A switch port is a network connection, not a secret store.',
    },
    er: 'Recall of the credential vault concept.',
  },
  {
    t: 'Credential Management', s: 'CMS risk', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > Credential Management Systems',
    q: 'An organization adopts a centralized credential vault. What is the KEY risk that must be tightly controlled?',
    o: [
      'The vault becomes a high-value single target; its master access must be strongly protected',
      'Users can no longer use any passwords',
      'It eliminates the need to ever rotate credentials',
      'It prevents administrators from auditing access',
    ],
    a: 'A',
    wc: 'A centralized vault concentrates many secrets, making it a high-value target; access to it must be strongly protected (e.g., MFA, strict access controls, monitoring).',
    ww: {
      B: 'The vault enables, not prevents, password use.',
      C: 'Credential rotation is still needed.',
      D: 'A vault supports auditing rather than preventing it.',
    },
    er: 'Tests the concentrated-target risk of a credential vault.',
  },
  // ---- JIT / PAM ----
  {
    t: 'Privileged Access', s: 'JIT access', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Just-In-Time Access',
    q: 'Just-In-Time (JIT) access reduces standing privilege by:',
    o: [
      'Granting elevated access only for the time it is needed, then automatically revoking it',
      'Giving every user permanent administrator rights',
      'Disabling all access reviews',
      'Sharing one admin account among the team',
    ],
    a: 'A',
    wc: 'JIT access provisions elevated rights only when needed and for a limited window (often via ephemeral accounts/temporary elevation), shrinking the attack surface of standing privilege.',
    ww: {
      B: 'Permanent admin rights are exactly what JIT avoids.',
      C: 'JIT complements, not eliminates, access reviews.',
      D: 'Shared admin accounts destroy accountability.',
    },
    er: 'Tests the time-bounded elevation concept of JIT access.',
  },
  {
    t: 'Privileged Access', s: 'Ephemeral accounts', d: 'hard', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Components of JIT Access',
    q: 'An "ephemeral account" used in JIT access is one that:',
    o: [
      'Exists only temporarily for a specific task and is removed afterward',
      'Has permanent domain administrator rights',
      'Can never be audited',
      'Is shared by all employees indefinitely',
    ],
    a: 'A',
    wc: 'Ephemeral accounts are created for a specific, short-lived purpose and removed when no longer needed, limiting standing privileged access.',
    ww: {
      B: 'Permanent admin rights contradict the ephemeral concept.',
      C: 'Ephemeral accounts can and should be audited.',
      D: 'They are single-purpose and temporary, not shared indefinitely.',
    },
    er: 'Recall of ephemeral accounts in JIT.',
  },
  {
    t: 'Privileged Access', s: 'PAM', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Privileged Access Management (PAM)',
    q: 'Privileged Access Management (PAM) focuses primarily on:',
    o: [
      'Controlling, monitoring, and securing the use of accounts with elevated privileges',
      'Assigning IP addresses to endpoints',
      'Encrypting wireless traffic',
      'Suppressing fires in data centers',
    ],
    a: 'A',
    wc: 'PAM secures, controls, and monitors privileged/administrative accounts, which are high-value targets, often combined with JIT elevation and session recording.',
    ww: {
      B: 'IP assignment is DHCP\'s function.',
      C: 'Wireless encryption is WPA2/WPA3.',
      D: 'Fire suppression is a physical control.',
    },
    er: 'Tests the privileged-account focus of PAM.',
  },
  {
    t: 'Privileged Access', s: 'PAM scenario', d: 'hard', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Authentication Mechanisms > Implementation and Best Practices',
    q: 'A security team wants admins to have NO standing privileged access. Which TWO practices BEST help achieve zero standing privilege with accountability? (Select TWO.)',
    o: [
      'Just-In-Time elevation granted only on request for a limited time',
      'PAM with privileged session monitoring/recording',
      'Giving every admin a permanent domain-admin account',
      'Sharing a single root password among the team',
    ],
    a: ['A', 'B'],
    wc: 'JIT elevation removes standing privilege by granting time-bound access on request, and PAM with session monitoring provides control and accountability.',
    ww: {
      C: 'Permanent domain-admin accounts are exactly the standing privilege to eliminate.',
      D: 'A shared root password destroys accountability and is a severe risk.',
    },
    er: 'Identifies practices for zero standing privilege with accountability.',
  },
  {
    t: 'Privileged Access', s: 'Temporary elevation', d: 'medium', qt: 'multiple_correct_answers',
    sec: 'Domain 5 > Authentication Mechanisms > Components of JIT Access',
    q: 'Which TWO practices align with Just-In-Time privileged access? (Select TWO.)',
    o: ['Time-bound temporary elevation of privileges', 'Automatic revocation after the task completes', 'Permanent standing admin rights for all', 'Sharing privileged credentials broadly'],
    a: ['A', 'B'],
    wc: 'JIT access grants temporary, time-bound elevation and revokes it automatically when the task is done.',
    ww: {
      C: 'Permanent standing rights are the opposite of JIT.',
      D: 'Sharing privileged credentials undermines accountability and least privilege.',
    },
    er: 'Identifies JIT-aligned practices.',
  },
  {
    t: 'Single Sign-On', s: 'SSO technologies', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Common SSO Technologies',
    q: 'Which of the following is a common technology used to implement SSO?',
    o: ['Kerberos', 'Degaussing', 'CPTED', 'Wet-pipe sprinklers'],
    a: 'A',
    wc: 'Kerberos is a common SSO technology (along with SAML and OIDC); it issues tickets so users authenticate once.',
    ww: {
      B: 'Degaussing destroys magnetic media.',
      C: 'CPTED is a physical site-design strategy.',
      D: 'Wet-pipe sprinklers are fire suppression.',
    },
    er: 'Identifies Kerberos as an SSO technology.',
  },
  {
    t: 'Federation Protocols', s: 'SAML vs OAuth use', d: 'hard', qt: 'scenario_based',
    sec: 'Domain 5 > Authentication Mechanisms > OAuth and OIDC',
    q: 'An enterprise needs employees to SSO into internal SaaS web apps with assertions of who they are. A separate consumer app needs to let users authorize limited access to their data via tokens. Which pairing of standards fits BEST?',
    o: [
      'SAML for enterprise web SSO; OAuth 2.0 for delegated authorization',
      'OAuth 2.0 for enterprise SSO; WEP for delegated authorization',
      'Kerberoasting for SSO; CPTED for authorization',
      'RADIUS for SSO; degaussing for authorization',
    ],
    a: 'A',
    wc: 'SAML is well-suited to enterprise web SSO (identity assertions), while OAuth 2.0 is designed for delegated authorization via access tokens.',
    ww: {
      B: 'WEP is a wireless cipher, not an authorization framework.',
      C: 'Kerberoasting is an attack and CPTED is physical design.',
      D: 'RADIUS is network AAA and degaussing destroys media—neither fits.',
    },
    er: 'Maps enterprise SSO to SAML and delegated authorization to OAuth.',
  },
  {
    t: 'Kerberos', s: 'Mutual authentication', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Kerberos',
    q: 'A security strength of Kerberos is that it:',
    o: [
      'Provides mutual authentication and avoids sending passwords across the network',
      'Transmits passwords in cleartext for speed',
      'Eliminates the need for any time source',
      'Stores all credentials on every client',
    ],
    a: 'A',
    wc: 'Kerberos supports mutual authentication and uses tickets/keys so user passwords are not transmitted across the network in the clear.',
    ww: {
      B: 'Kerberos specifically avoids sending cleartext passwords.',
      C: 'Kerberos depends on synchronized time.',
      D: 'Credentials are managed by the KDC, not stored on every client.',
    },
    er: 'Tests the no-cleartext-password and mutual-auth strengths of Kerberos.',
  },
  {
    t: 'Credential Management', s: 'CMS best practice', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Credential Management Systems',
    q: 'Which is a sound security practice when deploying a credential management system?',
    o: [
      'Protect the vault with strong authentication (e.g., MFA) and restrict/monitor access',
      'Store the master password on a public web page',
      'Disable encryption to speed up retrieval',
      'Allow anonymous access to the vault',
    ],
    a: 'A',
    wc: 'The vault holds many secrets, so it must be protected with strong authentication, least-privilege access, encryption, and monitoring.',
    ww: {
      B: 'Publishing the master password defeats the vault entirely.',
      C: 'Disabling encryption exposes all stored secrets.',
      D: 'Anonymous access would expose every stored credential.',
    },
    er: 'Identifies sound CMS protection practices.',
  },
  {
    t: 'Federation Protocols', s: 'OAuth token', d: 'medium', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > OAuth and OIDC',
    q: 'OAuth 2.0 authorizes a client to access resources by issuing it a(n):',
    o: ['Access token with a defined scope', 'Kerberos service ticket', 'LDAP distinguished name', 'WPA2 pre-shared key'],
    a: 'A',
    wc: 'OAuth issues scoped access tokens that the client presents to the resource server to access only the permitted resources.',
    ww: {
      B: 'Service tickets belong to Kerberos, not OAuth.',
      C: 'An LDAP DN names a directory entry.',
      D: 'A WPA2 PSK is a wireless key.',
    },
    er: 'Maps OAuth scoped access to access tokens.',
  },
  {
    t: 'Single Sign-On', s: 'SSO expense', d: 'easy', qt: 'single_best_answer',
    sec: 'Domain 5 > Authentication Mechanisms > Single Sign On',
    q: 'Besides the security risk, which is a noted practical DRAWBACK of implementing SSO?',
    o: [
      'Integration complexity and expense across many applications',
      'Users must memorize more passwords',
      'It cannot be combined with MFA',
      'It removes the need for an identity provider',
    ],
    a: 'A',
    wc: 'SSO can be costly and complex to integrate across diverse applications, which is a practical drawback noted in the guide.',
    ww: {
      B: 'SSO reduces the number of passwords.',
      C: 'SSO can and should be combined with MFA.',
      D: 'SSO relies on an identity provider, not removes it.',
    },
    er: 'Tests the integration cost/complexity drawback of SSO.',
  },
];
